import type { RMApplication, RMCommunication, RMCustomer, RMEscalation, RMFranchise, RMLead, RMMaterial, RMTicket, RMTraining, RMUser } from './types'

export const currentRM:RMUser={id:'RM-008',employeeId:'TROTH-EMP-0142',name:'Rohan Mehta',designation:'Relationship Manager',department:'Franchise Distribution',branch:'Ahmedabad',region:'West Region',reportingManager:'Ananya Kapoor',joiningDate:'14 June 2022',status:'Active',mobile:'+91 98250 44182',alternateMobile:'',email:'rohan.mehta@trothone.in',address:'Prahlad Nagar',city:'Ahmedabad',state:'Gujarat',pinCode:'380015',allocatedFranchiseIds:['FR-0101','FR-0105','FR-0109','FR-0113']}
export const rmFranchises:RMFranchise[]=[
 {id:'FR-0101',name:'Troth Finserve',principal:'Neha Patel',city:'Ahmedabad',mobile:'+91 98250 11482',email:'neha@trothfinserve.in',status:'Active',customers:64,business:12400000,lastActivity:'Today, 11:42 AM',documents:[{name:'Franchise Agreement',status:'Valid'},{name:'IRDAI Empanelment',status:'Valid'},{name:'GST Certificate',status:'Verified'}],team:[{name:'Neha Patel',role:'Principal',mobile:'+91 98250 11482',email:'neha@trothfinserve.in',status:'Active'},{name:'Rahul Shah',role:'Sales Executive',mobile:'+91 98251 45621',email:'rahul@trothfinserve.in',status:'Active'}]},
 {id:'FR-0105',name:'Shreeji Finance',principal:'Kunal Trivedi',city:'Vadodara',mobile:'+91 98980 22018',email:'kunal@shreejifin.in',status:'Active',customers:48,business:9100000,lastActivity:'Today, 9:18 AM',documents:[{name:'Franchise Agreement',status:'Valid'},{name:'Lending Empanelment',status:'Renewal due'}],team:[{name:'Kunal Trivedi',role:'Principal',mobile:'+91 98980 22018',email:'kunal@shreejifin.in',status:'Active'}]},
 {id:'FR-0109',name:'Prosperity Point',principal:'Aditi Vora',city:'Surat',mobile:'+91 97261 55004',email:'aditi@prosperitypoint.in',status:'Active',customers:72,business:15800000,lastActivity:'Yesterday, 5:30 PM',documents:[{name:'Franchise Agreement',status:'Valid'},{name:'AMFI Certificate',status:'Valid'}],team:[{name:'Aditi Vora',role:'Principal',mobile:'+91 97261 55004',email:'aditi@prosperitypoint.in',status:'Active'},{name:'Dev Joshi',role:'Relationship Executive',mobile:'+91 97262 88104',email:'dev@prosperitypoint.in',status:'Active'}]},
 {id:'FR-0113',name:'Capital Bridge',principal:'Mehul Desai',city:'Rajkot',mobile:'+91 99090 41173',email:'mehul@capitalbridge.in',status:'Onboarding',customers:19,business:2850000,lastActivity:'02 Sep, 3:05 PM',documents:[{name:'Franchise Agreement',status:'Pending signature'},{name:'KYC',status:'Verified'}],team:[{name:'Mehul Desai',role:'Principal',mobile:'+91 99090 41173',email:'mehul@capitalbridge.in',status:'Active'}]},
 {id:'FR-9999',name:'Outside Allocation Demo',principal:'Restricted User',city:'Mumbai',mobile:'-',email:'restricted@example.in',status:'Active',customers:999,business:99999999,lastActivity:'Today',documents:[],team:[]}
]
const people=['Aarav Shah','Meera Iyer','Kabir Desai','Riya Mehta','Dev Khanna','Ishita Rao','Vihaan Joshi','Anaya Kapoor','Nirav Vora','Sara Gandhi','Ishaan Dave','Diya Bhatt']
const products=['Mutual Fund','Loans','Insurance','Loan Protector','Demat','Advisory'] as const
export const rmCustomers:RMCustomer[]=Array.from({length:20},(_,i)=>({id:`TC-${1048+i}`,franchiseId:currentRM.allocatedFranchiseIds[i%4],name:people[i%people.length],mobile:`+91 98${24000000+i*731}`,email:`${people[i%people.length].toLowerCase().replace(' ','.')}@example.in`,kyc:i%7===0?'Pending':i%11===0?'Expired':'Verified',products:[products[i%products.length]],value:420000+i*285000,lastActivity:`${String(2+i%7).padStart(2,'0')} Sep 2026`,status:i%11===0?'Review due':'Active'}))
const leadStages=['New','Contacted','Qualified','Quote Raised','Won','Lost'] as const
const leadSources=['Referral','Campaign','Manual Lead','Inquiry Inbox','Website','Other']
const leadOwners=['Rahul Shah','Kunal Trivedi','Dev Joshi','Mehul Desai']
const leadStageAges=[1,3,6,2,0,4,8,2]
const leadDate=(daysAgo:number,hour=10)=>new Date(Date.UTC(2026,8,11-daysAgo,hour,30)).toISOString()
const shortDate=(value:string)=>new Date(value).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric',timeZone:'Asia/Kolkata'})
export const rmLeads:RMLead[]=Array.from({length:16},(_,i)=>{
 const stage=leadStages[i%leadStages.length],owner=leadOwners[i%leadOwners.length],age=leadStageAges[i%leadStageAges.length],createdAt=leadDate(13+i%9,9),stageIndex=stage==='Lost'?Math.min(1+i%4,3):leadStages.indexOf(stage),terminal=stage==='Won'||stage==='Lost',lastActivityAt=leadDate(terminal?age:Math.max(age,i%5),terminal?17:11),source=leadSources[i%leadSources.length]
 const path=(['New','Contacted','Qualified','Quote Raised'] as const).slice(0,stageIndex+1)
 const stageProgress:RMLead['stageProgress']=path.map((item,index)=>{const enteredAt=index===stageIndex?leadDate(age,10):leadDate(age+(stageIndex-index)*2,10),completedAt=index<stageIndex||terminal?leadDate(age+Math.max(0,stageIndex-index-1)*2,16):undefined;return {stage:item,enteredAt,completedAt,handledBy:owner,activity:item==='New'?'Lead reviewed and assigned':item==='Contacted'?'Customer contact logged':item==='Qualified'?'Requirement and eligibility recorded':'Quote or proposal shared',notes:index===stageIndex&&!terminal?`Current franchise update for ${products[i%products.length]}`:undefined}})
 if(terminal)stageProgress.push({stage,enteredAt:leadDate(age,17),handledBy:owner,activity:stage==='Won'?'Lead converted to customer application':'Lead closed by franchise',notes:stage==='Lost'?'Customer did not proceed at this time':undefined})
 const nextFollowUpAt=!['Won','Lost'].includes(stage)?leadDate(i%4===0?2:-1,14):undefined
 const currentStageDetail=stageProgress.find(item=>item.stage===stage)
 if(currentStageDetail&&nextFollowUpAt)currentStageDetail.nextFollowUpAt=nextFollowUpAt
 const activities=[...stageProgress].reverse().map((item,index)=>({id:`LA-${i}-${index}`,occurredAt:item.enteredAt,action:item.activity||`Moved to ${item.stage}`,stage:item.stage,user:item.handledBy,notes:item.notes}))
 if(source==='Inquiry Inbox')activities.push({id:`LA-${i}-inquiry`,occurredAt:createdAt,action:'Inquiry converted to lead',stage:'New',user:'Franchise CRM',notes:'Created from the Inquiry Inbox'})
 else activities.push({id:`LA-${i}-created`,occurredAt:createdAt,action:'Lead created',stage:'New',user:owner,notes:`Source: ${source}`})
 return {id:`TL-${2201-i}`,franchiseId:currentRM.allocatedFranchiseIds[i%4],customer:people[(i+4)%people.length],mobile:`+91 98${25141008+i*397}`,email:`${people[(i+4)%people.length].toLowerCase().replace(' ','.')}@example.in`,product:products[i%products.length],source,owner,stage,value:85000+i*175000,created:shortDate(createdAt),createdAt,updated:shortDate(lastActivityAt),lastActivityAt,nextFollowUpAt,nextFollowUpNote:nextFollowUpAt?'Franchise to reconnect with the prospect':undefined,age,attentionReason:i===6?'Required action pending':undefined,stageProgress,timeline:activities.map(item=>item.action),activities}
})
export const rmApplications:RMApplication[]=Array.from({length:18},(_,i)=>({id:`TAPP-${260184-i}`,franchiseId:currentRM.allocatedFranchiseIds[i%4],customer:people[i%people.length],product:products[i%products.length],type:['New Business','Renewal','Top-up'][i%3],stage:['Initial Review','KYC Verification','Provider Review','Approval','Fulfilment'][i%5],status:['In Review','Pending','Pending','Approved','Completed'][i%5] as RMApplication['status'],pendingWith:['Head Office','Franchise','Provider','Customer'][i%4] as RMApplication['pendingWith'],pendingSince:`${1+i%7} Sep 2026`,owner:['Priya Nair','Harsh Vyas','Provider Desk','Franchise Team'][i%4],submitted:`${18+i%11} Aug 2026`,updated:`${1+i%7} Sep 2026`,age:[1,3,7,2,5,9][i%6],queryDays:i%4===1?3:0,documents:[{name:'PAN',status:'Verified'},{name:'Application Form',status:i%4===1?'Pending':'Received'}],timeline:['Application submitted','Documents reviewed',`Moved to ${['Initial Review','KYC Verification','Provider Review','Approval','Fulfilment'][i%5]}`]}))
export const seedEscalations:RMEscalation[]=[{id:'ISS-1042',applicationId:'TAPP-260182',type:'Processing Delay',subject:'Provider review pending beyond SLA',description:'Please confirm current provider status.',assignedTo:'Head Office Operations',priority:'High',status:'In Progress',raisedBy:'Rohan Mehta',raisedByRole:'Relationship Manager',raisedAt:'05 Sep 2026, 10:30 AM',updatedAt:'05 Sep 2026, 02:15 PM',comments:[{id:'CMT-1042-1',author:'HO Operations',role:'Head Office Operations',createdAt:'05 Sep 2026, 02:15 PM',text:'Provider desk has been contacted. We are awaiting confirmation.'}],activity:[{id:'ACT-1042-1',createdAt:'05 Sep 2026, 10:30 AM',text:'Issue raised by Rohan Mehta'},{id:'ACT-1042-2',createdAt:'05 Sep 2026, 10:30 AM',text:'Assigned to Head Office Operations'},{id:'ACT-1042-3',createdAt:'05 Sep 2026, 02:15 PM',text:'Status changed to In Progress'}]}]
export const rmTickets:RMTicket[]=Array.from({length:10},(_,i)=>({id:`TKT-${4218-i}`,franchiseId:currentRM.allocatedFranchiseIds[i%4],category:['Operational Query','Portal Issue','Customer Escalation'][i%3],subject:['Policy endorsement clarification','Document preview not loading','Loan sanction update delayed','Payout reconciliation query'][i%4],related:i%2===0?`TAPP-${260184-i}`:undefined,desk:i%3===1?'HO IT':'HO Operations',status:['Open','In Progress','Waiting','Resolved'][i%4] as RMTicket['status'],priority:i%5===0?'High':'Normal',created:`${25+i%6} Aug 2026`,updated:`${1+i%6} Sep 2026`,age:[1,4,7,2,6][i%5],messages:['Ticket raised by franchise',...(i%2?['HO desk acknowledged']:[])]}))
export const seedCommunications:RMCommunication[]=[{id:'COM-81',title:'September protection campaign',type:'Announcement',message:'Campaign assets and talking points are now available.',franchiseIds:[...currentRM.allocatedFranchiseIds],created:'02 Sep 2026'}]
export const seedMaterials:RMMaterial[]=[{id:'MAT-81',title:'Family Health Plan — One Pager',type:'PDF',product:'Insurance',franchiseIds:[...currentRM.allocatedFranchiseIds],uploaded:'02 Sep 2026'},{id:'MAT-79',title:'SIP Goal Builder Carousel',type:'Social Media Post',product:'Mutual Fund',franchiseIds:['FR-0101','FR-0109'],uploaded:'30 Aug 2026'}]
export const seedTraining:RMTraining[]=[{id:'LRN-41',title:'Health Insurance Sales SOP',category:'Product',product:'Insurance',type:'Video',franchiseIds:[...currentRM.allocatedFranchiseIds],completion:{'FR-0101':100,'FR-0105':65,'FR-0109':80,'FR-0113':0},uploaded:'01 Sep 2026',status:'Published'},{id:'LRN-39',title:'Handling Loan Documents',category:'Process',product:'Loans',type:'Process Guide',franchiseIds:['FR-0101','FR-0105'],completion:{'FR-0101':75,'FR-0105':30},uploaded:'28 Aug 2026',status:'Published'}]
