import type { RMApplication, RMCommunication, RMCustomer, RMEscalation, RMFranchise, RMLead, RMMaterial, RMTicket, RMTraining, RMUser } from './types'

export const currentRM:RMUser={id:'RM-008',employeeId:'TROTH-EMP-0142',name:'Rohan Mehta',designation:'Relationship Manager',department:'Franchise Distribution',branch:'Ahmedabad',region:'West Region',reportingManager:'Ananya Kapoor',joiningDate:'14 June 2022',status:'Active',mobile:'+91 98250 44182',alternateMobile:'',email:'rohan.mehta@trothone.in',address:'Prahlad Nagar',city:'Ahmedabad',state:'Gujarat',pinCode:'380015',allocatedFranchiseIds:['FR-0101','FR-0105','FR-0109','FR-0113']}
export const rmFranchises:RMFranchise[]=[
 {id:'FR-0101',name:'Troth Finserve',principal:'Neha Patel',city:'Ahmedabad',mobile:'+91 98250 11482',email:'neha@trothfinserve.in',status:'Active',customers:64,business:12400000,lastActivity:'Today, 11:42 AM',documents:[{name:'Franchise Agreement',status:'Valid'},{name:'IRDAI Empanelment',status:'Valid'},{name:'GST Certificate',status:'Verified'}],team:[{name:'Neha Patel',role:'Principal',mobile:'+91 98250 11482',email:'neha@trothfinserve.in',status:'Active'},{name:'Rahul Shah',role:'Sales Executive',mobile:'+91 98251 45621',email:'rahul@trothfinserve.in',status:'Active'}]},
 {id:'FR-0105',name:'Shreeji Finance',principal:'Kunal Trivedi',city:'Vadodara',mobile:'+91 98980 22018',email:'kunal@shreejifin.in',status:'Active',customers:48,business:9100000,lastActivity:'Today, 9:18 AM',documents:[{name:'Franchise Agreement',status:'Valid'},{name:'Lending Empanelment',status:'Renewal due'}],team:[{name:'Kunal Trivedi',role:'Principal',mobile:'+91 98980 22018',email:'kunal@shreejifin.in',status:'Active'}]},
 {id:'FR-0109',name:'Prosperity Point',principal:'Aditi Vora',city:'Surat',mobile:'+91 97261 55004',email:'aditi@prosperitypoint.in',status:'Active',customers:72,business:15800000,lastActivity:'Yesterday, 5:30 PM',documents:[{name:'Franchise Agreement',status:'Valid'},{name:'AMFI Certificate',status:'Valid'}],team:[{name:'Aditi Vora',role:'Principal',mobile:'+91 97261 55004',email:'aditi@prosperitypoint.in',status:'Active'},{name:'Dev Joshi',role:'Relationship Executive',mobile:'+91 97262 88104',email:'dev@prosperitypoint.in',status:'Active'}]},
 {id:'FR-0113',name:'Capital Bridge',principal:'Mehul Desai',city:'Rajkot',mobile:'+91 99090 41173',email:'mehul@capitalbridge.in',status:'Onboarding',customers:19,business:2850000,lastActivity:'02 Sep, 3:05 PM',documents:[{name:'Franchise Agreement',status:'Pending signature'},{name:'KYC',status:'Verified'}],team:[{name:'Mehul Desai',role:'Principal',mobile:'+91 99090 41173',email:'mehul@capitalbridge.in',status:'Active'}]},
 {id:'FR-9999',name:'Outside Allocation Demo',principal:'Restricted User',city:'Mumbai',mobile:'-',email:'restricted@example.in',status:'Active',customers:999,business:99999999,lastActivity:'Today',documents:[],team:[]}
]
const people=['Aarav Shah','Meera Iyer','Kabir Desai','Riya Mehta','Dev Khanna','Ishita Rao','Vihaan Joshi','Anaya Kapoor','Nirav Vora','Sara Gandhi','Ishaan Dave','Diya Bhatt']
const products=['Mutual Fund','Loans','Insurance','Loan Protector','Demat','Advisory'] as const
export const rmCustomers:RMCustomer[]=Array.from({length:20},(_,i)=>({id:`TC-${1048+i}`,franchiseId:currentRM.allocatedFranchiseIds[i%4],name:people[i%people.length],mobile:`+91 98${24000000+i*731}`,email:`${people[i%people.length].toLowerCase().replace(' ','.')}@example.in`,kyc:i%7===0?'Pending':i%11===0?'Expired':'Verified',products:[products[i%products.length]],value:420000+i*285000,lastActivity:`${String(2+i%7).padStart(2,'0')} Sep 2026`,status:i%11===0?'Review due':'Active'}))
export const rmLeads:RMLead[]=Array.from({length:16},(_,i)=>({id:`TL-${2201-i}`,franchiseId:currentRM.allocatedFranchiseIds[i%4],customer:people[(i+4)%people.length],product:products[i%products.length],source:['Referral','Campaign','Walk-in','HO Assigned'][i%4],owner:['Rahul Shah','Kunal Trivedi','Dev Joshi','Mehul Desai'][i%4],stage:['New','Contacted','Qualified','Proposal Shared','Won'][i%5],value:85000+i*175000,created:`${20+i%10} Aug 2026`,updated:`${1+i%6} Sep 2026`,age:1+i%8,timeline:['Lead created','First contact completed',...(i%3===0?['Proposal shared']:[])]}))
export const rmApplications:RMApplication[]=Array.from({length:18},(_,i)=>({id:`TAPP-${260184-i}`,franchiseId:currentRM.allocatedFranchiseIds[i%4],customer:people[i%people.length],product:products[i%products.length],type:['New Business','Renewal','Top-up'][i%3],stage:['Initial Review','KYC Verification','Provider Review','Approval','Fulfilment'][i%5],pendingWith:['Head Office','Franchise','Provider','Customer'][i%4] as RMApplication['pendingWith'],owner:['Priya Nair','Harsh Vyas','Provider Desk','Franchise Team'][i%4],submitted:`${18+i%11} Aug 2026`,updated:`${1+i%7} Sep 2026`,age:[1,3,7,2,5,9][i%6],queryDays:i%4===1?3:0,documents:[{name:'PAN',status:'Verified'},{name:'Application Form',status:i%4===1?'Pending':'Received'}],timeline:['Application submitted','Documents reviewed',`Moved to ${['Initial Review','KYC Verification','Provider Review','Approval','Fulfilment'][i%5]}`]}))
export const seedEscalations:RMEscalation[]=[{id:'ISS-1042',applicationId:'TAPP-260182',type:'Processing Delay',subject:'Provider review pending beyond SLA',description:'Please confirm current provider status.',assignedTo:'Head Office Operations',priority:'High',status:'In Progress',raisedAt:'05 Sep 2026',comments:['Escalated by Rohan Mehta','HO Operations acknowledged']}]
export const rmTickets:RMTicket[]=Array.from({length:10},(_,i)=>({id:`TKT-${4218-i}`,franchiseId:currentRM.allocatedFranchiseIds[i%4],category:['Operational Query','Portal Issue','Customer Escalation'][i%3],subject:['Policy endorsement clarification','Document preview not loading','Loan sanction update delayed','Payout reconciliation query'][i%4],related:i%2===0?`TAPP-${260184-i}`:undefined,desk:i%3===1?'HO IT':'HO Operations',status:['Open','In Progress','Waiting','Resolved'][i%4] as RMTicket['status'],priority:i%5===0?'High':'Normal',created:`${25+i%6} Aug 2026`,updated:`${1+i%6} Sep 2026`,age:[1,4,7,2,6][i%5],messages:['Ticket raised by franchise',...(i%2?['HO desk acknowledged']:[])]}))
export const seedCommunications:RMCommunication[]=[{id:'COM-81',title:'September protection campaign',type:'Announcement',message:'Campaign assets and talking points are now available.',franchiseIds:[...currentRM.allocatedFranchiseIds],created:'02 Sep 2026'}]
export const seedMaterials:RMMaterial[]=[{id:'MAT-81',title:'Family Health Plan — One Pager',type:'PDF',product:'Insurance',franchiseIds:[...currentRM.allocatedFranchiseIds],uploaded:'02 Sep 2026'},{id:'MAT-79',title:'SIP Goal Builder Carousel',type:'Social Media Post',product:'Mutual Fund',franchiseIds:['FR-0101','FR-0109'],uploaded:'30 Aug 2026'}]
export const seedTraining:RMTraining[]=[{id:'LRN-41',title:'Health Insurance Sales SOP',category:'Product',product:'Insurance',type:'Video',franchiseIds:[...currentRM.allocatedFranchiseIds],completion:{'FR-0101':100,'FR-0105':65,'FR-0109':80,'FR-0113':0},uploaded:'01 Sep 2026',status:'Published'},{id:'LRN-39',title:'Handling Loan Documents',category:'Process',product:'Loans',type:'Process Guide',franchiseIds:['FR-0101','FR-0105'],completion:{'FR-0101':75,'FR-0105':30},uploaded:'28 Aug 2026',status:'Published'}]
