import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { CalendarClock, Check, ChevronRight, MessageSquareText, PhoneCall, Search, ShieldCheck, StickyNote, X } from 'lucide-react'
import { rmInquiryService } from './inquiryService'
import { rmRepository } from './service'
import type { RMInquiry, RMInquiryAction } from './types'

interface Props {franchiseContext:string;globalSearch:string;onToast:(message:string)=>void}
type ActionMode='Comment Added'|'Call Logged'|'Follow-Up Logged'|'Internal Note Added'
type SupportAction=Exclude<RMInquiryAction,'Inquiry Opened'|'Status Changed'>
const displayDate=(value:string)=>new Date(value).toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})
const age=(value:string)=>Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/86400000))
const franchiseName=(id?:string)=>id?rmRepository.franchises().find(item=>item.id===id)?.name||'Direct RM assignment':'Direct RM assignment'
function Chip({children,tone='neutral'}:{children:ReactNode;tone?:string}){return <span className={`rm-chip ${tone}`}>{children}</span>}

export function RMInquiryInbox({franchiseContext,globalSearch,onToast}:Props){
 const [items,setItems]=useState(rmInquiryService.list)
 const [search,setSearch]=useState(globalSearch)
 const [status,setStatus]=useState('all')
 const [selected,setSelected]=useState<string>()
 useEffect(()=>setSearch(globalSearch),[globalSearch])
 const rows=items.filter(item=>(franchiseContext==='all'||item.franchiseId===franchiseContext)&&(status==='all'||item.status===status)&&`${item.id} ${item.customerName} ${item.mobile} ${item.subject} ${item.details} ${item.productService||''} ${franchiseName(item.franchiseId)}`.toLowerCase().includes(search.trim().toLowerCase()))
 const inquiry=items.find(item=>item.id===selected)
 const refresh=(next:RMInquiry)=>setItems(current=>current.map(item=>item.id===next.id?next:item))
 const open=(id:string)=>{try{const next=rmInquiryService.recordOpen(id);refresh(next);setSelected(id)}catch(error){onToast(error instanceof Error?error.message:'Unable to open inquiry')}}
 const action=(id:string,type:SupportAction,remarks:string,followUpAt?:string)=>{try{const next=rmInquiryService.addAction(id,type,remarks,followUpAt);refresh(next);onToast(`${type} on ${id}`)}catch(error){onToast(error instanceof Error?error.message:'Unable to update inquiry')}}
 const close=(id:string,remarks:string)=>{try{const next=rmInquiryService.close(id,remarks);refresh(next);onToast(`${id} marked resolved and closed`)}catch(error){onToast(error instanceof Error?error.message:'Unable to close inquiry')}}
 return <>
  <div className="rm-inquiry-filters"><label><Search/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search inquiry, customer, mobile, subject..."/></label><select value={status} onChange={event=>setStatus(event.target.value)}><option value="all">All statuses</option><option>Open</option><option>Converted to Lead</option><option>Converted to Case</option><option>Closed</option></select><button onClick={()=>{setSearch(globalSearch);setStatus('all')}}>Reset</button></div>
  <section className="rm-panel rm-inquiry-list"><div className="rm-panel-head"><div><b>{rows.length} inquir{rows.length===1?'y':'ies'}</b><small>Allocated franchises and inquiries assigned directly to you</small></div></div><div className="rm-table-wrap"><table><thead><tr><th>Inquiry ID</th><th>Customer</th><th>Mobile</th><th>Franchise</th><th>Assigned RM</th><th>Inquiry Type</th><th>Product / Service</th><th>Subject / Details</th><th>Received</th><th>Status</th><th>Age</th><th>Action</th></tr></thead><tbody>{rows.map(item=><tr key={item.id}><td><b>{item.id}</b><small>{item.source}</small></td><td><b>{item.customerName}</b><small>{item.customerId||'Prospect'}</small></td><td>{item.mobile}<small>{item.email||'Email not provided'}</small></td><td>{franchiseName(item.franchiseId)}<small>{item.franchiseId||'Direct'}</small></td><td>{item.assignedRMName||rmRepository.currentRM.name}<small>{item.assignedRMId?'Direct assignment':'Via franchise mapping'}</small></td><td>{item.inquiryType}</td><td>{item.productService||'Not specified'}</td><td><b>{item.subject}</b><small>{item.details}</small></td><td>{displayDate(item.receivedAt)}</td><td><Chip tone={item.status==='Closed'?'green':item.status==='Open'?'amber':'blue'}>{item.status}</Chip></td><td><b>{age(item.receivedAt)} days</b></td><td><button className="rm-open-case" onClick={()=>open(item.id)}>Open <ChevronRight/></button></td></tr>)}</tbody></table>{!rows.length&&<div className="rm-empty"><Search/><b>No matching inquiries</b><span>Only allocated-franchise and directly assigned inquiries are visible here.</span></div>}</div></section>
  {inquiry&&<InquiryDrawer inquiry={inquiry} close={()=>setSelected(undefined)} addAction={action} closeInquiry={close}/>} 
 </>
}

function InquiryDrawer({inquiry,close,addAction,closeInquiry}:{inquiry:RMInquiry;close:()=>void;addAction:(id:string,type:SupportAction,remarks:string,followUpAt?:string)=>void;closeInquiry:(id:string,remarks:string)=>void}){
 const [mode,setMode]=useState<ActionMode>(),[closing,setClosing]=useState(false)
 return <><button className="rm-drawer-scrim" onClick={close} aria-label="Close inquiry detail"/><aside className="rm-drawer wide rm-inquiry-drawer"><header><div><b>{inquiry.id} · {inquiry.customerName}</b><small>{inquiry.subject}</small></div><button onClick={close} aria-label="Close"><X/></button></header><div className="rm-drawer-body"><div className="rm-lead-readonly"><ShieldCheck/><span><b>RM Customer Assistance</b>Support and follow-up actions are recorded without changing Franchisee sales or HO processing records.</span><Chip tone={inquiry.status==='Closed'?'green':'amber'}>{inquiry.status}</Chip></div><section className="rm-lead-detail-section"><div className="rm-lead-section-head"><div><h3>Inquiry Details</h3><p>Customer, source and assignment information</p></div></div><div className="rm-detail-grid">{([['Customer',inquiry.customerName],['Mobile',inquiry.mobile],['Email',inquiry.email||'Not provided'],['Customer reference',inquiry.customerId||'Prospect'],['Franchise',franchiseName(inquiry.franchiseId)],['Franchise ID',inquiry.franchiseId||'Direct to RM'],['Inquiry source',inquiry.source],['Inquiry type',inquiry.inquiryType],['Product / service',inquiry.productService||'Not specified'],['Received',displayDate(inquiry.receivedAt)],['Assigned RM',inquiry.assignedRMName||rmRepository.currentRM.name],['Current status',inquiry.status]] as [string,string][]).map(([label,value])=><div key={label}><small>{label}</small><b>{value}</b></div>)}</div><div className="rm-inquiry-message"><small>INQUIRY DESCRIPTION</small><p>{inquiry.details}</p></div></section>
   {inquiry.status==='Open'&&<section className="rm-inquiry-actions"><div className="rm-lead-section-head"><div><h3>Assist Customer</h3><p>Record a permitted RM support action</p></div></div><div><button onClick={()=>setMode('Comment Added')}><MessageSquareText/> Add Comment</button><button onClick={()=>setMode('Call Logged')}><PhoneCall/> Log Call</button><button onClick={()=>setMode('Follow-Up Logged')}><CalendarClock/> Log Follow-Up</button><button onClick={()=>setMode('Internal Note Added')}><StickyNote/> Internal Note</button><button onClick={()=>addAction(inquiry.id,'Marked Assisted','RM assistance provided; inquiry remains in the normal workflow.')}><Check/> Mark Assisted</button><button className="resolve" onClick={()=>setClosing(true)}><ShieldCheck/> Resolve & Close</button></div></section>}
   {mode&&<ActionForm mode={mode} cancel={()=>setMode(undefined)} submit={(remarks,followUpAt)=>{addAction(inquiry.id,mode,remarks,followUpAt);setMode(undefined)}}/>}
   {closing&&<CloseForm cancel={()=>setClosing(false)} submit={remarks=>{closeInquiry(inquiry.id,remarks);setClosing(false)}}/>}
   <section className="rm-lead-history rm-inquiry-history"><div className="rm-lead-section-head"><div><h3>Inquiry Activity History</h3><p>RM and Franchise support activity</p></div></div>{inquiry.activities.length?inquiry.activities.map(item=><article key={item.id}><i/><div><header><b>{item.action}</b><Chip tone={item.role==='Relationship Manager'?'blue':'neutral'}>{item.role}</Chip></header><p>{item.remarks}</p><small>{displayDate(item.createdAt)} · {item.user}{item.followUpAt?` · Follow-up ${displayDate(item.followUpAt)}`:''}</small></div></article>):<p className="rm-muted">No activity recorded yet.</p>}</section>
  </div></aside></>
}

function ActionForm({mode,cancel,submit}:{mode:ActionMode;cancel:()=>void;submit:(remarks:string,followUpAt?:string)=>void}){const [remarks,setRemarks]=useState(''),[followUpAt,setFollowUpAt]=useState(''),[error,setError]=useState('');const save=(event:FormEvent)=>{event.preventDefault();if(remarks.trim().length<3){setError('Add a short remark for the activity history.');return}if(mode==='Follow-Up Logged'&&!followUpAt){setError('Select a follow-up date and time.');return}submit(remarks.trim(),followUpAt||undefined)};return <form className="rm-inquiry-action-form" onSubmit={save}><h3>{mode}</h3>{mode==='Follow-Up Logged'&&<label>Follow-up date and time<input type="datetime-local" value={followUpAt} onChange={event=>setFollowUpAt(event.target.value)} required/></label>}<label>Remarks<textarea value={remarks} onChange={event=>setRemarks(event.target.value)} placeholder="Record the customer assistance or outcome..."/></label>{error&&<p>{error}</p>}<footer><button type="button" onClick={cancel}>Cancel</button><button className="rm-primary">Save Activity</button></footer></form>}
function CloseForm({cancel,submit}:{cancel:()=>void;submit:(remarks:string)=>void}){const [remarks,setRemarks]=useState('');return <form className="rm-inquiry-action-form close" onSubmit={event=>{event.preventDefault();if(remarks.trim())submit(remarks.trim())}}><h3>Resolve and close inquiry</h3><label>Resolution note<textarea value={remarks} onChange={event=>setRemarks(event.target.value)} placeholder="Confirm how the customer was assisted..." required/></label><footer><button type="button" onClick={cancel}>Cancel</button><button className="rm-primary"><Check/> Confirm Resolution</button></footer></form>}
