import type { Application } from '../types'

export type ChatActionType='product-details'|'buy'|'inquiry'|'view-application'|'upload'|'support'|'callback'
export interface ChatAction { label:string; type:ChatActionType; target?:string }
export interface ChatReply { text:string; bullets?:string[]; actions?:ChatAction[]; caution?:string }
export const suggestedQuestions=['Explain Health Insurance','What documents are required for a Home Loan?','What is SIP?','How does Loan Protector work?','Where is my application?','How do I renew my policy?','Explain my pending document requirement']

export async function sendMessage(question:string,context:{applications:Application[]}):Promise<ChatReply>{
  const q=question.toLowerCase().trim()
  await new Promise(resolve=>setTimeout(resolve,450))
  if(q.includes('home loan')&&q.includes('document'))return {text:'Typical documents for a Home Loan include:',bullets:['PAN and KYC','Address proof','Income documents','Recent bank statements','Employment or business proof','Property documents'],actions:[{label:'View Home Loan',type:'product-details',target:'home-loan'},{label:'Start Application',type:'buy',target:'home-loan'},{label:'Submit Inquiry',type:'inquiry',target:'home-loan'},{label:'Talk to Support',type:'support'}],caution:'Actual requirements may vary by lender and applicant profile.'}
  if(q.includes('sip'))return {text:'A SIP lets you invest a fixed amount in a mutual fund at regular intervals. It can support disciplined, long-term investing and averages purchase costs across market levels.',bullets:['Choose an amount and frequency','Invest automatically each month','Track units and portfolio value','Increase or pause based on scheme rules'],actions:[{label:'Use SIP Calculator',type:'product-details',target:'calculator'},{label:'Explore Mutual Funds',type:'product-details',target:'equity-mutual-fund'},{label:'Start Investment',type:'buy',target:'equity-mutual-fund'}],caution:'Mutual fund returns are market-linked and are not guaranteed.'}
  if(q.includes('loan protector'))return {text:'Loan Protector is insurance designed to help cover an outstanding eligible loan if a specified insured event occurs, subject to policy terms.',bullets:['Can complement a Home Loan, Business Loan or LAP','Cover can be aligned with outstanding liability','Helps reduce financial pressure on the borrower’s family'],actions:[{label:'Product Details',type:'product-details',target:'loan-protector'},{label:'Buy Now',type:'buy',target:'loan-protector'},{label:'Submit Inquiry',type:'inquiry',target:'loan-protector'}],caution:'Coverage and claim eligibility depend on insurer underwriting, exclusions and policy terms.'}
  if(q.includes('health insurance')||q.includes('health cover'))return {text:'Health Insurance can help cover eligible hospitalization and medical expenses for you or your family.',bullets:['Individual and family floater options','Cashless treatment within insurer networks','Pre and post-hospitalization benefits depending on plan'],actions:[{label:'Product Details',type:'product-details',target:'health-insurance'},{label:'Buy Now',type:'buy',target:'health-insurance'},{label:'Submit Inquiry',type:'inquiry',target:'health-insurance'}],caution:'Coverage, waiting periods and claims depend on the selected plan and policy terms.'}
  if((q.includes('where')||q.includes('status')||q.includes('track')||q.includes('show'))&&q.includes('application')){const app=context.applications.find(a=>a.product==='Loans')||context.applications[0];return app?{text:`Your ${app.productName} application is currently at ${app.stage}.`,bullets:[`Application: ${app.id}`,`Status: ${app.status}`,`Pending from you: ${app.pendingAction}`],actions:[{label:'View Application',type:'view-application',target:app.id},{label:'Upload Document',type:'upload'},{label:'Talk to Support',type:'support'}]}:{text:'I could not find an active application in the prototype account.',actions:[{label:'Raise Support Request',type:'support'}]}}
  if(q.includes('pending')&&q.includes('document')){const app=context.applications.find(a=>a.pendingAction!=='None');return {text:app?`The pending requirement for ${app.id} is: ${app.pendingAction}. Upload a clear, current copy to help the review continue.`:'I cannot see a pending document requirement right now.',actions:app?[{label:'View Application',type:'view-application',target:app.id},{label:'Upload Document',type:'upload'},{label:'Talk to Support',type:'support'}]:[{label:'Raise Support Request',type:'support'}]}}
  if(q.includes('pending')&&q.includes('application')){const app=context.applications.find(a=>a.pendingAction!=='None');return {text:app?`Your application is pending because the next requirement is: ${app.pendingAction}.`:'I cannot see a pending application requirement right now.',actions:app?[{label:'View Application',type:'view-application',target:app.id},{label:'Talk to Support',type:'support'}]:[{label:'Raise Support Request',type:'support'}]}}
  if(q.includes('application stage'))return {text:'Troth One applications generally move through these stages:',bullets:['New','In Progress','Action Required, if something is needed','Approved','Completed'],actions:[{label:'View My Applications',type:'view-application',target:context.applications[0]?.id},{label:'Talk to Support',type:'support'}]}
  if(q.includes('renew'))return {text:'You can request a renewal from My Products. Your upcoming Health Insurance renewal is shown for 21 Sep 2026.',bullets:['Review existing policy details','Confirm any profile changes','Request renewal support before expiry'],actions:[{label:'View My Products',type:'product-details',target:'my-products'},{label:'Request Callback',type:'callback'},{label:'Talk to Support',type:'support'}],caution:'Renewal premium and coverage remain subject to insurer terms.'}
  if(q.includes('kyc'))return {text:'KYC helps verify your identity before eligible financial products or transactions can be processed.',bullets:['PAN','Address or identity proof','Photograph or signature where required','Bank proof for relevant products'],actions:[{label:'View Documents & Profile',type:'upload'},{label:'Talk to Support',type:'support'}]}
  if(q.includes('expected return'))return {text:'Expected return is an assumption used to illustrate how an investment might grow. It is not a promised or guaranteed return.',bullets:['Use a reasonable long-term assumption','Compare more than one scenario','Actual returns can be higher or lower'],actions:[{label:'Open Calculator',type:'product-details',target:'calculator'},{label:'Talk to Support',type:'support'}],caution:'Investment returns are market-linked and may vary significantly.'}
  if(q.includes('emi')&&q.includes('calculated'))return {text:'EMI is calculated using the loan amount, monthly interest rate and number of monthly repayments. A higher rate or shorter tenure generally increases the EMI.',actions:[{label:'Use EMI Calculator',type:'product-details',target:'calculator'},{label:'Explore Home Loan',type:'product-details',target:'home-loan'},{label:'Submit Inquiry',type:'inquiry',target:'home-loan'}],caution:'The final EMI depends on lender-approved terms and applicable charges.'}
  if(q.includes('sip period'))return {text:'A suitable SIP period depends on your goal and risk profile. Longer periods may provide more time for compounding, but market returns are not guaranteed.',actions:[{label:'Use SIP Calculator',type:'product-details',target:'calculator'},{label:'Explore Mutual Funds',type:'product-details',target:'equity-mutual-fund'},{label:'Talk to Support',type:'support'}]}
  if(q.includes('pan')&&q.includes('required'))return {text:'PAN is commonly used for identity and tax-related verification across financial products and investments.',actions:[{label:'View Documents & Profile',type:'upload'},{label:'Talk to Support',type:'support'}]}
  if(q.includes('document')&&(q.includes('need')||q.includes('upload'))){const app=context.applications.find(a=>a.pendingAction!=='None');return {text:app?`For your current application, the requested item is: ${app.pendingAction}.`:'Document requirements depend on the selected product and provider.',bullets:['Upload a clear and complete copy','Use a current document','Check that names and details match your profile'],actions:[{label:'View Documents & Profile',type:'upload'},{label:'Talk to Support',type:'support'}]}}
  if(q.includes('which calculator'))return {text:'Choose a calculator based on what you want to plan: investments and goals, loan repayments or eligibility, or insurance protection needs.',actions:[{label:'Open Calculator',type:'product-details',target:'calculator'},{label:'Request Advisor Call',type:'callback'}],caution:'Calculator results are illustrative estimates, not financial advice or product approval.'}
  if(q.includes('what needs my attention')){const app=context.applications.find(a=>a.pendingAction!=='None');return {text:app?`Your current priority is ${app.pendingAction} for application ${app.id}.`:'There are no visible pending actions in the prototype account.',actions:app?[{label:'View Application',type:'view-application',target:app.id},{label:'Upload Document',type:'upload'}]:[{label:'Go to Support',type:'support'}]}}
  return {text:"I don't have enough information to answer that accurately. You can raise a support request and the Troth team can assist you.",actions:[{label:'Raise Support Request',type:'support'},{label:'Request Callback',type:'callback'}]}
}
