import { ArrowRight, CheckCircle2, ChevronDown, Search, X } from 'lucide-react'
import type { ReactNode } from 'react'

export const money=(value:number)=>value>=10000000?`₹${(value/10000000).toFixed(2)} Cr`:value>=100000?`₹${(value/100000).toFixed(2)} L`:`₹${value.toLocaleString('en-IN')}`

export function PageHeader({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description:string;actions?:ReactNode}){
  return <div className="tf-page-head"><div>{eyebrow&&<span>{eyebrow}</span>}<h1>{title}</h1><p>{description}</p></div>{actions&&<div className="tf-head-actions">{actions}</div>}</div>
}
export function StatusBadge({children,tone}:{children:ReactNode;tone?:'green'|'amber'|'red'|'blue'|'gray'}){return <span className={`tf-badge ${tone||toneFor(String(children))}`}>{children}</span>}
export const toneFor=(value:string):'green'|'amber'|'red'|'blue'|'gray'=>/completed|approved|issued|paid|verified|active|passed|won|resolved/i.test(value)?'green':/query|pending|waiting|progress|review|draft|new/i.test(value)?'amber':/rejected|lost|expired|urgent|missing|disabled/i.test(value)?'red':/submitted|qualified|contacted/i.test(value)?'blue':'gray'
export function Metric({label,value,meta,icon,onClick,tone='blue'}:{label:string;value:string|number;meta:string;icon?:ReactNode;onClick?:()=>void;tone?:string}){return <button className={`tf-metric ${tone}`} onClick={onClick} disabled={!onClick}>{icon&&<i>{icon}</i>}<span>{label}</span><strong>{value}</strong><small>{meta}</small>{onClick&&<ArrowRight/>}</button>}
export function Panel({title,subtitle,action,children,className=''}:{title:string;subtitle?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={`tf-panel ${className}`}><header><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</header>{children}</section>}
export function Filters({search,onSearch,children}:{search?:string;onSearch?:(v:string)=>void;children?:ReactNode}){return <div className="tf-filters">{onSearch&&<label className="tf-search"><Search/><input value={search} onChange={e=>onSearch(e.target.value)} placeholder="Search records..."/>{search&&<button onClick={()=>onSearch('')}><X/></button>}</label>}{children}</div>}
export function FilterSelect({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]}){return <label className="tf-select"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(option=><option key={option}>{option}</option>)}</select><ChevronDown/></label>}
export function DataTable({headers,children,empty}:{headers:string[];children:ReactNode;empty?:boolean}){return <div className="tf-table-wrap"><table className="tf-table"><thead><tr>{headers.map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{empty?<tr><td colSpan={headers.length}><EmptyState title="No matching records" detail="Try changing the active filters."/></td></tr>:children}</tbody></table></div>}
export function Timeline({items}:{items:{id:string;title:string;detail:string;time:string;actor:string}[]}){return <div className="tf-timeline">{items.map(item=><div key={item.id}><i/><section><b>{item.title}</b><p>{item.detail}</p><small>{item.time} · {item.actor}</small></section></div>)}</div>}
export function Documents({items}:{items:{name:string;status:string}[]}){return <div className="tf-documents">{items.map(item=><div key={item.name}><span className="tf-doc-icon">DOC</span><b>{item.name}</b><StatusBadge>{item.status}</StatusBadge><button className="tf-text-btn">View</button></div>)}</div>}
export function EmptyState({title,detail}:{title:string;detail:string}){return <div className="tf-empty"><CheckCircle2/><b>{title}</b><span>{detail}</span></div>}
export function Modal({title,subtitle,onClose,children}:{title:string;subtitle?:string;onClose:()=>void;children:ReactNode}){return <div className="tf-modal-wrap"><button className="tf-modal-scrim" onClick={onClose} aria-label="Close"/><section className="tf-modal"><header><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className="tf-icon-btn" onClick={onClose}><X/></button></header>{children}</section></div>}
export function Progress({value,label}:{value:number;label?:string}){return <div className="tf-progress"><div><i style={{width:`${Math.min(value,100)}%`}}/></div>{label&&<small>{label}</small>}</div>}
