import { useState, type ChangeEvent, type ReactNode } from 'react'
import { ArrowLeft, BriefcaseBusiness, Building2, CircleAlert, FileText, MapPin, ShieldCheck, Upload, UsersRound } from 'lucide-react'
import { PageHeader, StatusBadge } from './FranchiseeUI'
import type { LegalEntityType, SubFranchiseeDocument, SubFranchiseeDocumentType, SubFranchiseeDraft } from '../subFranchiseeTypes'

const entityTypes:LegalEntityType[]=['Proprietorship','Partnership','LLP','Private Limited','Individual']
const documentTypes:SubFranchiseeDocumentType[]=['PAN Card','Identity Proof','GST Certificate','Business Registration','Cancelled Cheque','Photograph / Logo','Signed Agreement']
const blank=(products:string[]):SubFranchiseeDraft=>({firmName:'',contactPerson:'',mobile:'',email:'',businessType:'Financial Services',legalEntityType:'Proprietorship',pan:'',gstin:'',registrationNumber:'',yearsInBusiness:0,addressLine:'',area:'',city:'Ahmedabad',district:'Ahmedabad',state:'Gujarat',pinCode:'',territory:'Ahmedabad',products:products.slice(0,1),effectiveDate:new Date().toISOString().slice(0,10),documents:[]})
const date=(value:string)=>new Date(`${value}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})

interface ParentFranchise { id:string; name:string; code:string; territory:string }

export function SubFranchiseeCreatePage({products,parent,onBack,onSave}:{products:string[];parent:ParentFranchise;onBack:()=>void;onSave:(draft:SubFranchiseeDraft)=>void}){
  const [draft,setDraft]=useState<SubFranchiseeDraft>(()=>blank(products)),[error,setError]=useState('')
  const set=<K extends keyof SubFranchiseeDraft>(key:K,value:SubFranchiseeDraft[K])=>setDraft(current=>({...current,[key]:value}))
  const submit=()=>{if(!draft.firmName.trim()||!draft.contactPerson.trim())return setError('Firm name and contact person are required.');if(!/^\+?[0-9 ]{10,16}$/.test(draft.mobile))return setError('Enter a valid 10-digit mobile number.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(draft.email))return setError('Enter a valid email address.');if(!/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(draft.pan))return setError('PAN must use the format ABCDE1234F.');if(!/^\d{6}$/.test(draft.pinCode))return setError('PIN code must contain 6 digits.');setError('');onSave(draft)}
  const addFiles=(event:ChangeEvent<HTMLInputElement>)=>{const files=[...(event.target.files||[])];const docs:SubFranchiseeDocument[]=files.map((file,index)=>({id:`DOC-${Date.now()}-${index}`,type:documentTypes[Math.min(draft.documents.length+index,documentTypes.length-1)],fileName:file.name,size:file.size,uploadedAt:new Date().toISOString().slice(0,10),status:'Uploaded'}));set('documents',[...draft.documents,...docs]);event.target.value=''}
  return <div className="franchisee-sub-franchisees sf-form-page"><button className="sf-back" onClick={onBack}><ArrowLeft/> Back to Sub-Franchisees</button><div className="sf-breadcrumb">Admin Dashboard <span>/</span> Franchisees <span>/</span> {parent.name} <span>/</span> <b>Add Sub-Franchisee</b></div><PageHeader eyebrow="PARTNER NETWORK" title="Add Sub-Franchisee" description="The new account will remain pending until KYC and Head Office approval are complete."/>
    <section className="sf-parent"><ShieldCheck/><div><span>Parent Franchise</span><b>{parent.name}</b><small>{parent.code} · {parent.territory}</small></div><em>READ ONLY</em></section>
    <form className="sf-form" onSubmit={event=>{event.preventDefault();submit()}}><FormSection icon={<UsersRound/>} title="Basic Details" copy="Primary identity and communication details."><div className="sf-fields"><Field label="Sub-Franchisee / Firm Name" required><input value={draft.firmName} onChange={e=>set('firmName',e.target.value)} placeholder="Registered or trading name"/></Field><Field label="Contact Person Name" required><input value={draft.contactPerson} onChange={e=>set('contactPerson',e.target.value)} placeholder="Full name"/></Field><Field label="Mobile Number" required><input value={draft.mobile} onChange={e=>set('mobile',e.target.value)} placeholder="+91 98765 43210"/></Field><Field label="Email Address" required><input type="email" value={draft.email} onChange={e=>set('email',e.target.value)} placeholder="name@company.in"/></Field><Field label="Business Type"><input value={draft.businessType} onChange={e=>set('businessType',e.target.value)}/></Field></div></FormSection>
      <FormSection icon={<BriefcaseBusiness/>} title="Business Details" copy="Legal and statutory information used for verification."><div className="sf-fields"><Field label="Legal Entity Type" required><select value={draft.legalEntityType} onChange={e=>set('legalEntityType',e.target.value as LegalEntityType)}>{entityTypes.map(value=><option key={value}>{value}</option>)}</select></Field><Field label="PAN" required><input maxLength={10} value={draft.pan} onChange={e=>set('pan',e.target.value.toUpperCase().replace(/\s/g,''))} placeholder="ABCDE1234F"/></Field><Field label="GSTIN"><input maxLength={15} value={draft.gstin} onChange={e=>set('gstin',e.target.value.toUpperCase())}/></Field><Field label="Registration Number"><input value={draft.registrationNumber} onChange={e=>set('registrationNumber',e.target.value)}/></Field><Field label="Years in Business"><input type="number" min="0" max="99" value={draft.yearsInBusiness} onChange={e=>set('yearsInBusiness',Number(e.target.value))}/></Field></div></FormSection>
      <FormSection icon={<MapPin/>} title="Address Details" copy="Registered office and operating territory."><div className="sf-fields"><Field label="Address Line" required wide><input value={draft.addressLine} onChange={e=>set('addressLine',e.target.value)}/></Field><Field label="Area"><input value={draft.area} onChange={e=>set('area',e.target.value)}/></Field><Field label="City" required><input value={draft.city} onChange={e=>set('city',e.target.value)}/></Field><Field label="District"><input value={draft.district} onChange={e=>set('district',e.target.value)}/></Field><Field label="State" required><input value={draft.state} onChange={e=>set('state',e.target.value)}/></Field><Field label="PIN Code" required><input maxLength={6} inputMode="numeric" value={draft.pinCode} onChange={e=>set('pinCode',e.target.value.replace(/\D/g,''))}/></Field><Field label="Territory"><input value={draft.territory} onChange={e=>set('territory',e.target.value)}/></Field></div></FormSection>
      <FormSection icon={<FileText/>} title="KYC & Documents" copy="Upload document metadata for Head Office verification."><label className="sf-upload"><Upload/><b>Choose documents to upload</b><span>PDF, JPG or PNG · maximum 10 MB each</span><input type="file" multiple accept=".pdf,.jpg,.jpeg,.png" onChange={addFiles}/></label>{draft.documents.length>0&&<div className="sf-document-list">{draft.documents.map((document,index)=><article key={document.id}><FileText/><div><input value={document.fileName} readOnly/><small>{(document.size/1024).toFixed(0)} KB · Uploaded {date(document.uploadedAt)}</small></div><select value={document.type} onChange={e=>set('documents',draft.documents.map((item,itemIndex)=>itemIndex===index?{...item,type:e.target.value as SubFranchiseeDocumentType}:item))}>{documentTypes.map(type=><option key={type}>{type}</option>)}</select><StatusBadge>{document.status}</StatusBadge><button type="button" onClick={()=>set('documents',draft.documents.filter(item=>item.id!==document.id))}>Remove</button></article>)}</div>}</FormSection>
      <FormSection icon={<Building2/>} title="Commercial, Product & Access" copy="Products are limited to those enabled for the selected franchise; payout controls remain with Head Office."><div className="sf-access"><div><span>Role</span><b>Sub-Franchisee</b><small>Assigned automatically</small></div><div><span>Approval</span><b>Head Office Review</b><small>Login sent only after approval</small></div><div><span>Commission / Payout</span><b>Derived from HO controls</b><small>Not editable here</small></div></div><Field label="Product Access"><div className="sf-products">{products.map(product=><label key={product}><input type="checkbox" checked={draft.products.includes(product)} onChange={()=>set('products',draft.products.includes(product)?draft.products.filter(value=>value!==product):[...draft.products,product])}/><span>{product}</span></label>)}</div></Field><div className="sf-fields"><Field label="Effective Date"><input type="date" value={draft.effectiveDate} onChange={e=>set('effectiveDate',e.target.value)}/></Field></div></FormSection>
      {error&&<div className="sf-error"><CircleAlert/>{error}</div>}<footer><button type="button" className="tf-secondary" onClick={onBack}>Cancel</button><button className="tf-primary"><ShieldCheck/> Submit for Approval</button></footer></form>
  </div>
}

function FormSection({icon,title,copy,children}:{icon:ReactNode;title:string;copy:string;children:ReactNode}){return <section className="sf-form-section"><header><span>{icon}</span><div><h2>{title}</h2><p>{copy}</p></div></header><div className="sf-section-body">{children}</div></section>}
function Field({label,required,wide,children}:{label:string;required?:boolean;wide?:boolean;children:ReactNode}){return <label className={`sf-field ${wide?'wide':''}`}>{label}{required&&<sup>*</sup>}{children}</label>}
