export type CustomerType = 'Individual'|'Business'
export type ReminderType = 'Insurance Renewal'|'Premium Due'|'Loan EMI'|'Loan Maturity'|'Rate Review'|'Document Expiry'|'Investment Maturity'|'SIP Reminder'|'Financial Review'
export type ReminderChannel = 'WhatsApp'|'SMS'|'Email'|'In-App'

export interface CustomerBasicDetails { customerType:CustomerType; profilePhoto?:FileMetadata; title?:string; firstName?:string; middleName?:string; lastName?:string; dateOfBirth?:string; gender?:string; maritalStatus?:string; nationality:string; customerSince:string; businessName?:string; entityType?:string; incorporationDate?:string; industry?:string; businessActivity?:string; gstin?:string; pan?:string; website?:string; primaryContact?:string; designation?:string }
export interface AddressDetails { line1:string; line2?:string; landmark?:string; city:string; state:string; pinCode:string; country:string }
export interface CustomerContactDetails { primaryMobile:string; alternateMobile?:string; email:string; alternateEmail?:string; preferredCommunication:string[]; preferredLanguage:string; currentAddress:AddressDetails; permanentSame:boolean; permanentAddress?:AddressDetails }
export interface FamilyMember { id:string; name:string; relationship:string; dateOfBirth?:string; gender?:string; occupation?:string; dependent:boolean; mobile?:string }
export interface NomineeDetails { name?:string; relationship?:string; dateOfBirth?:string; mobile?:string }
export interface CustomerProfileDetails { occupation?:string; employerName?:string; designation?:string; yearsInEmployment?:string; family:FamilyMember[]; nominee:NomineeDetails }
export interface CustomerFinancialProfile { annualIncomeRange?:string; monthlyIncome?:number; monthlyExpenses?:number; monthlyEmi?:number; assets?:number; liabilities?:number; netWorth?:number; primaryBank?:string; accountType?:string }
export interface CustomerKycProfile { status:'Not Started'|'Pending'|'Partially Complete'|'Complete'; panNumber?:string; aadhaarAvailable:boolean; aadhaarNumber?:string; passportNumber?:string; drivingLicence?:string; voterId?:string; gstin?:string; cin?:string }
export interface FileMetadata { fileName:string; fileSize:number; fileType:string; uploadedAt:string; url?:string }
export interface CustomerDocument { id:string; documentType:string; documentNumber?:string; issueDate?:string; expiryDate?:string; file?:FileMetadata; remarks?:string; status:'Uploaded'|'Pending'|'Expired'|'Verified'; reminderEnabled?:boolean; reminderOffsets?:number[]; relatedEntityId?:string }
export interface ExistingInsurancePolicy { id:string; category:string; insurer:string; planName?:string; policyNumber:string; policyHolder?:string; insuredMembers?:string; sumInsured?:number; premiumAmount?:number; premiumFrequency?:string; startDate?:string; renewalDate:string; premiumDueDate?:string; agentName?:string; status:string; purchasedThrough?:string; document?:FileMetadata; renewalReminderEnabled:boolean; premiumReminderEnabled:boolean; reminderOffsets:number[]; remarks?:string }
export interface ExistingLoan { id:string; loanType:string; lender:string; accountNumber?:string; originalAmount?:number; outstandingAmount?:number; interestRate?:number; interestType?:string; emiAmount?:number; emiDueDay?:number; startDate?:string; tenureMonths?:number; remainingTenure?:number; maturityDate?:string; status:string; primaryBorrower?:string; coBorrower?:string; arrangedThrough?:string; documents:CustomerDocument[]; emiReminderEnabled:boolean; maturityReminderEnabled:boolean; rateReviewReminderEnabled:boolean; balanceTransferInterest?:string; topUpInterest?:string; remarks?:string }
export interface ExistingInvestment { id:string; investmentType:string; provider?:string; productName?:string; referenceNumber?:string; currentValue?:number; investmentAmount?:number; sipAmount?:number; startDate?:string; maturityDate?:string; frequency?:string; status?:string; maturityReminderEnabled:boolean; sipReminderEnabled:boolean; reviewReminderEnabled:boolean; remarks?:string }
export interface CustomerReminder { id:string; customerId:string; type:ReminderType; title:string; relatedEntityId?:string; relatedEntityType?:'policy'|'loan'|'document'|'investment'; dueDate:string; reminderOffsets:number[]; channels:ReminderChannel[]; enabled:boolean; status:'Upcoming'|'Due'|'Completed'|'Disabled' }
export interface CustomerPreferences { interests:string[]; primaryGoal?:string; targetYear?:string; targetAmount?:number; riskPreference:string; source:string; referredBy?:string; relationshipManager?:string; category:string; tags:string[]; preferredContactMethod:string; preferredContactTime?:string; communicationConsent:string[]; marketingConsent:boolean; followUpConsent:boolean; reminderTypes:string[]; reminderChannels:ReminderChannel[]; notes?:string }
export interface FranchiseeCustomerProfile { id:string; customerType:CustomerType; basic:CustomerBasicDetails; contact:CustomerContactDetails; profile:CustomerProfileDetails; financial:CustomerFinancialProfile; kyc:CustomerKycProfile; documents:CustomerDocument[]; policies:ExistingInsurancePolicy[]; loans:ExistingLoan[]; investments:ExistingInvestment[]; reminders:CustomerReminder[]; noExistingPolicies:boolean; noExistingLoans:boolean; noExistingInvestments:boolean; preferences:CustomerPreferences; profileCompleteness:number; createdAt:string; updatedAt?:string }
export type CustomerOnboardingDraft = Omit<FranchiseeCustomerProfile,'id'|'reminders'|'profileCompleteness'|'createdAt'|'updatedAt'>
