import type { FranchiseeStore, TimelineEvent } from './types'

const event=(id:string,title:string,detail:string,time:string,actor:string):TimelineEvent=>({id,title,detail,time,actor})

export const franchiseeWorkspaceSeed:FranchiseeStore={
  dashboardSummary:{totalNetWorth:20000000,totalRevenue:825000,totalCustomers:425,currentMonthRevenue:120000},
  customers:[
    {id:'TC-1048',name:'Aarav Shah',mobile:'+91 98240 11482',email:'aarav.shah@example.in',city:'Ahmedabad',kyc:'Verified',relationshipValue:4850000,performance:12.4,products:['Mutual Fund','Health Insurance','Demat'],lastActivity:'02 Sep 2026',tags:['HNI','Cross-sell'],documents:[{name:'PAN',status:'Verified'},{name:'Aadhaar',status:'Verified'},{name:'Bank proof',status:'Received'}],timeline:[event('e1','Portfolio review completed','Quarterly allocation reviewed with customer.','02 Sep, 3:20 PM','Nisha Patel')]},
    {id:'TC-1052',name:'Meera Iyer',mobile:'+91 98980 22716',email:'meera.iyer@example.in',city:'Vadodara',kyc:'Pending',relationshipValue:1725000,performance:8.7,products:['Home Loan','Loan Protector'],lastActivity:'01 Sep 2026',tags:['Loan'],documents:[{name:'PAN',status:'Verified'},{name:'Address proof',status:'Pending',requested:true},{name:'Income proof',status:'Received'}],timeline:[event('e2','Document requested','Updated address proof requested.','01 Sep, 11:05 AM','System')]},
    {id:'TC-1061',name:'Kabir Desai',mobile:'+91 97261 55004',email:'kabir.desai@example.in',city:'Surat',kyc:'Verified',relationshipValue:860000,performance:6.1,products:['Motor Insurance'],lastActivity:'29 Aug 2026',tags:['Renewal'],documents:[{name:'PAN',status:'Verified'},{name:'RC copy',status:'Verified'}],timeline:[event('e3','Renewal call logged','Customer asked for zero-depreciation options.','29 Aug, 5:10 PM','Rahul Shah')]},
    {id:'TC-1067',name:'Riya Mehta',mobile:'+91 99090 41973',email:'riya.mehta@example.in',city:'Rajkot',kyc:'Expired',relationshipValue:2340000,performance:10.3,products:['PMS'],lastActivity:'27 Aug 2026',tags:['Review due'],documents:[{name:'PAN',status:'Verified'},{name:'KYC declaration',status:'Missing',requested:true}],timeline:[event('e4','KYC renewal due','Declaration expired and needs refresh.','27 Aug, 9:30 AM','Compliance')]}
  ],
  inquiries:[],
  leads:[
    {id:'TL-2201',name:'Dev Khanna',mobile:'+91 98251 41008',email:'dev.khanna@example.in',source:'HO-assigned',owner:'Nisha Patel',product:'Health Insurance',expectedValue:85000,stage:'New',nextAction:'Today, 4:30 PM',notes:['Interested in family floater'],timeline:[event('l1','Lead assigned by HO','SLA: first contact within four hours.','Today, 10:15 AM','HO Inside Sales')]},
    {id:'TL-2194',name:'Ishita Rao',mobile:'+91 97125 01842',email:'ishita.rao@example.in',source:'Referral',owner:'Rahul Shah',product:'PMS',expectedValue:5500000,stage:'Qualified',nextAction:'04 Sep, 11:00 AM',notes:['Risk profile completed'],timeline:[event('l2','Lead qualified','Minimum investment and strategy discussed.','Yesterday','Rahul Shah')]},
    {id:'TL-2187',name:'Vihaan Joshi',mobile:'+91 99041 22754',email:'vihaan.joshi@example.in',source:'Self-sourced',owner:'Nisha Patel',product:'Business Loan',expectedValue:2500000,stage:'Quote Raised',nextAction:'05 Sep, 2:00 PM',notes:['Comparing two lenders'],timeline:[event('l3','Indicative quote shared','Two lender options emailed.','31 Aug','Nisha Patel')]},
    {id:'TL-2168',name:'Anaya Kapoor',mobile:'+91 98250 78112',email:'anaya.kapoor@example.in',source:'Campaign',owner:'Rahul Shah',product:'Mutual Fund',expectedValue:600000,stage:'Contacted',nextAction:'06 Sep, 10:00 AM',notes:['Prefers monthly SIP'],timeline:[event('l4','Introductory call logged','Requested goal-planning illustration.','30 Aug','Rahul Shah')]}
  ],
  cases:[
    {id:'TAPP-260184',customerId:'TC-1052',customer:'Meera Iyer',product:'Home Loan',amount:4200000,status:'Query Raised',assignedTeam:'HO Operations — Lending',updated:'Today, 12:40 PM',query:'Latest three-month salary account statement is required.',documents:[{name:'PAN',status:'Verified'},{name:'Income proof',status:'Received'},{name:'Bank statement',status:'Missing',requested:true}],timeline:[event('a1','HO query raised','Upload the latest salary account statement.','Today, 12:40 PM','HO Operations'),event('a2','Application submitted','Case entered HO Operations queue.','01 Sep, 4:15 PM','Nisha Patel')]},
    {id:'TAPP-260179',customerId:'TC-1048',customer:'Aarav Shah',product:'PMS',amount:5000000,status:'Under Review',assignedTeam:'HO Operations — Wealth',updated:'Today, 10:20 AM',documents:[{name:'PAN',status:'Verified'},{name:'Risk profile',status:'Verified'},{name:'Bank proof',status:'Received'}],timeline:[event('a3','Review started','Suitability and documents under review.','Today, 10:20 AM','HO Operations'),event('a4','Application submitted','Case entered the Wealth queue.','31 Aug, 1:05 PM','Rahul Shah')]},
    {id:'TAPP-260162',customerId:'TC-1061',customer:'Kabir Desai',product:'Motor Insurance',amount:24600,status:'Approved / Issued',assignedTeam:'HO Operations — Insurance',updated:'01 Sep, 6:10 PM',documents:[{name:'RC copy',status:'Verified'},{name:'Previous policy',status:'Verified'}],timeline:[event('a5','Policy issued','Policy document is available to download.','01 Sep, 6:10 PM','HO Operations')]},
    {id:'TAPP-260151',customerId:'TC-1067',customer:'Riya Mehta',product:'AIF',amount:10000000,status:'Draft',assignedTeam:'Franchise',updated:'29 Aug, 2:00 PM',documents:[{name:'PAN',status:'Verified'},{name:'Accreditation declaration',status:'Pending'}],timeline:[event('a6','Draft saved','Application has not been sent to HO.','29 Aug, 2:00 PM','Nisha Patel')]}
  ],
  tickets:[
    {id:'TKT-4218',category:'Operational Query',subject:'Clarification on policy endorsement',status:'In Progress',priority:'Normal',assignedDesk:'HO Operations',created:'01 Sep 2026',sla:'6h 18m remaining',lastResponse:'Today, 11:20 AM',messages:[event('t1','HO Operations replied','Endorsement request is with the insurer.','Today, 11:20 AM','HO Operations')]},
    {id:'TKT-4202',category:'Technical / Portal Issue',subject:'Document preview not loading',status:'Waiting for Me',priority:'Urgent',assignedDesk:'HO IT',created:'30 Aug 2026',sla:'2h 42m remaining',lastResponse:'Yesterday, 5:45 PM',messages:[event('t2','Information requested','Please attach a screenshot and browser version.','Yesterday, 5:45 PM','HO IT')]},
    {id:'TKT-4176',category:'Customer Escalation',subject:'Delayed loan sanction update',status:'Resolved',priority:'Urgent',assignedDesk:'HO Operations',created:'27 Aug 2026',sla:'Resolved in 7h',lastResponse:'29 Aug, 4:10 PM',messages:[event('t3','Resolution shared','Lender sanction letter was delivered.','29 Aug, 4:10 PM','HO Operations')]}
  ],
  products:[
    ['health','Health Insurance','Insurance','Family and individual medical protection.','Adults and dependent family members','18% of net brokerage',true],['term','Term Insurance','Insurance','Long-term life protection.','Eligible adults subject to underwriting','22% of net brokerage',true],['motor','Motor Insurance','Insurance','Own-damage and third-party protection.','Registered vehicle owners','15% of net brokerage',false],['home-loan','Home Loan','Loans','Purchase, construction and balance transfer.','Income and credit assessment','0.35% of disbursal',false],['business-loan','Business Loan','Loans','Working capital and growth finance.','Operating business with acceptable vintage','0.75% of disbursal',false],['personal-loan','Personal Loan','Loans','Unsecured personal finance.','Salaried or self-employed applicants','1.00% of disbursal',false],['lap','Loan Against Property','Loans','Secured finance against property.','Eligible property and income','0.50% of disbursal',false],['loan-protector','Loan Protector','Loan Protector','Protection linked to outstanding loan.','Borrower with an eligible active loan','20% of net brokerage',true],['mf','Mutual Fund','Investment & Wealth','SIP and lumpsum wealth solutions.','Valid PAN, KYC and bank account','Trail as per scheme',true],['demat','Shares / Demat','Investment & Wealth','Digital market account and holdings.','PAN, KYC and bank account','₹450 activation + trail',true],['pms','PMS','Investment & Wealth','Professionally managed portfolios.','Minimum ₹50 lakh and risk profiling','1.10% of net fees',true],['aif','AIF','Investment & Wealth','Selected alternative strategies.','Minimum commitment per regulation','1.25% of net fees',true],['bonds','Bonds & FD','Investment & Wealth','Income-oriented fixed instruments.','Completed KYC','0.45% of mobilised value',false],['ipo','IPO','Investment & Wealth','Primary market investment access.','Active demat and UPI/bank mandate','₹250 per activation',false],['nps','NPS','Investment & Wealth','Retirement-focused market-linked saving.','Indian citizen with KYC','As per PFRDA slab',true],['gold','Digital Gold','Investment & Wealth','Small-ticket gold accumulation.','Completed KYC','0.40% of purchase',false],['research','Research Advisory','Investment & Wealth','Structured research and insights.','Risk acknowledgement','30% of subscription',true],['fd','Corporate FD','Investment & Wealth','Fixed-tenure corporate deposits.','PAN, KYC and bank account','0.60% of deposit',false]
  ].map(([id,name,category,description,eligibility,commission,certification])=>({id:id as string,name:name as string,category:category as FranchiseeStore['products'][number]['category'],description:description as string,eligibility:eligibility as string,commission:commission as string,certification:certification as boolean,enabled:true,documents:['PAN / KYC','Bank proof','Product-specific declaration'],faqs:['Who is eligible?','What documents are required?','How is payout calculated?']})),
  mappings:[],
  notifications:[
    {id:'TN-1',title:'HO query raised on TAPP-260184',detail:'Latest salary account statement is required.',type:'Query',read:false,time:'18 min ago'},
    {id:'TN-2',title:'Payout credited',detail:'August trail payout of ₹1.84 lakh has been credited.',type:'Payout',read:false,time:'2 hr ago'},
    {id:'TN-3',title:'Application moved to review',detail:'PMS case TAPP-260179 is under review.',type:'Application',read:true,time:'Today, 10:20 AM'},
    {id:'TN-4',title:'Support response received',detail:'HO IT replied on ticket TKT-4202.',type:'Support',read:false,time:'Yesterday'},
    {id:'TN-5',title:'Document expires in 12 days',detail:'Riya Mehta’s KYC declaration needs renewal.',type:'Document',read:true,time:'27 Aug'}
  ],
  circulars:[{id:'CIR-094',title:'Revised insurance solicitation checklist',category:'Compliance',date:'02 Sep 2026',required:true,acknowledged:false},{id:'CIR-091',title:'NPS product launch and enablement',category:'Product launch',date:'30 Aug 2026',required:false,acknowledged:true},{id:'CIR-087',title:'September festive campaign toolkit',category:'Marketing',date:'27 Aug 2026',required:false,acknowledged:true}],
  marketing:[{id:'MA-81',title:'Family Health Plan — One Pager',product:'Health Insurance',category:'Brochure',format:'PDF',campaign:'Protection Month'},{id:'MA-79',title:'SIP Goal Builder Carousel',product:'Mutual Fund',category:'Social creative',format:'PNG',campaign:'Wealth Week'},{id:'MA-76',title:'Home Loan Rate Comparison',product:'Home Loan',category:'Co-branded template',format:'PPTX',campaign:'Home Festival'},{id:'MA-72',title:'Loan Protector Customer Script',product:'Loan Protector',category:'Sales aid',format:'PDF',campaign:'Always-on'}],
  learning:[{id:'L-41',title:'PMS Suitability & Positioning',product:'PMS',type:'Video',duration:'24 min',completed:true},{id:'L-39',title:'Health Insurance Sales SOP',product:'Health Insurance',type:'SOP',duration:'12 min',completed:false},{id:'L-36',title:'Handling Home Loan Documents',product:'Home Loan',type:'Process guide',duration:'18 min',completed:false},{id:'L-31',title:'Mutual Fund Discovery Script',product:'Mutual Fund',type:'Sales script',duration:'8 min',completed:true}],
  certifications:[{productId:'health',product:'Health Insurance',required:true,status:'In progress',score:72},{productId:'mf',product:'Mutual Fund',required:true,status:'Passed',score:88},{productId:'pms',product:'PMS',required:true,status:'Passed',score:92},{productId:'loan-protector',product:'Loan Protector',required:true,status:'Not started'}],
  revenue:[{id:'BR-891',date:'02 Sep 2026',customer:'Aarav Shah',product:'PMS',business:5000000,earning:64000,status:'Approved',owner:'Rahul Shah'},{id:'BR-886',date:'01 Sep 2026',customer:'Kabir Desai',product:'Motor Insurance',business:24600,earning:2952,status:'Paid',owner:'Nisha Patel'},{id:'BR-878',date:'29 Aug 2026',customer:'Meera Iyer',product:'Home Loan',business:4200000,earning:14700,status:'Pending',owner:'Nisha Patel'},{id:'BR-865',date:'26 Aug 2026',customer:'Aarav Shah',product:'Mutual Fund',business:750000,earning:8750,status:'Paid',owner:'Rahul Shah'},{id:'BR-849',date:'18 Aug 2026',customer:'Riya Mehta',product:'AIF',business:10000000,earning:118000,status:'Approved',owner:'Nisha Patel'}]
}

franchiseeWorkspaceSeed.mappings=franchiseeWorkspaceSeed.products.map(product=>({productId:product.id,enabled:product.id!=='nps',certified:!product.certification||['mf','pms'].includes(product.id),empanelment:product.id==='nps'?'Pending':'Active',prerequisite:product.certification?'Product certification required':'None'}))
