export type EmployeeStatus='Active'|'On Leave'|'Inactive'|'Exited'
export type EmployeeDocumentStatus='Uploaded'|'Pending'|'Verified'|'Expired'

export interface EmployeeFileMetadata { fileName:string; fileSize:number; fileType:string; uploadedAt:string }
export interface EmployeeAddress { line1:string; line2?:string; city:string; state:string; pinCode:string; country:string }
export interface EmployeeEmergencyContact { name:string; relationship:string; mobile:string }
export interface EmployeeDocument { id:string; documentType:string; documentNumber?:string; issueDate?:string; expiryDate?:string; file?:EmployeeFileMetadata; status:EmployeeDocumentStatus; remarks?:string }
export interface EmployeeActivity { id:string; title:string; detail:string; timestamp:string }
export interface FranchiseeEmployee {
  id:string; franchiseeId:string; subFranchiseeId?:string; employeeId:string; photo?:EmployeeFileMetadata; title?:string; firstName:string; middleName?:string; lastName:string
  mobile:string; alternateMobile?:string; email:string; personalEmail?:string; dateOfBirth?:string; gender?:string; maritalStatus?:string; bloodGroup?:string
  designation:string; department:string; role:string; employmentType:string; joiningDate:string; probationEndDate?:string; workLocation?:string; status:EmployeeStatus
  reportingManagerId?:string; assignedProducts:string[]; assignedCustomerIds:string[]; address:EmployeeAddress; permanentSame:boolean; permanentAddress?:EmployeeAddress
  emergencyContact:EmployeeEmergencyContact; pan?:string; aadhaarAvailable:boolean; aadhaarNumber?:string; drivingLicence?:string; passport?:string
  documents:EmployeeDocument[]; notes?:string; platformAccess:false; activity:EmployeeActivity[]; createdAt:string; updatedAt?:string
}
export type EmployeeDraft=Omit<FranchiseeEmployee,'id'|'activity'|'createdAt'|'updatedAt'|'platformAccess'>

export const currentFranchiseeId='FR-GJ-0418'
export const employeeDepartments=['Sales','Insurance','Loans','Wealth','Operations','Customer Service','Back Office','Accounts','Marketing','Management','Other']
export const employeeRoles=['Sales Executive','Insurance Advisor','Loan Advisor','Relationship Executive','Operations Executive','Customer Service','Branch Coordinator','Manager','Other']
export const employeeProductOptions=['Health Insurance','Life Insurance','Motor Insurance','General Insurance','Loan Protector','Home Loan','Personal Loan','Business Loan','Loan Against Property','Mutual Funds','Wealth Management','Other']
export const employeeDocumentTypes=['PAN Card','Aadhaar Card','Passport','Driving Licence','Address Proof','Photograph','Resume','Appointment Letter','Education Certificate','Experience Letter','Training Certificate','Insurance Certification','Loan/Finance Certification','Other']

const seed:FranchiseeEmployee[]=[
  {id:'FE-1',franchiseeId:currentFranchiseeId,employeeId:'EMP-1001',title:'Ms',firstName:'Nisha',lastName:'Patel',mobile:'+91 98250 11042',email:'nisha.patel@example.in',dateOfBirth:'1990-04-18',gender:'Female',designation:'Franchise Principal',department:'Management',role:'Manager',employmentType:'Full Time',joiningDate:'2023-04-01',workLocation:'Ahmedabad Main Branch',status:'Active',assignedProducts:['Health Insurance','Home Loan','Mutual Funds','Wealth Management'],assignedCustomerIds:['TC-1048','TC-1052'],address:{line1:'Satellite Road',city:'Ahmedabad',state:'Gujarat',pinCode:'380015',country:'India'},permanentSame:true,emergencyContact:{name:'Harsh Patel',relationship:'Spouse',mobile:'+91 98790 33210'},pan:'ABCDE1234F',aadhaarAvailable:true,documents:[{id:'ED-1',documentType:'PAN Card',file:{fileName:'nisha-pan.pdf',fileSize:248000,fileType:'application/pdf',uploadedAt:'2026-04-01'},status:'Verified'},{id:'ED-2',documentType:'Insurance Certification',file:{fileName:'insurance-certification.pdf',fileSize:412000,fileType:'application/pdf',uploadedAt:'2026-04-02'},issueDate:'2025-06-15',expiryDate:'2028-06-14',status:'Verified'}],platformAccess:false,activity:[{id:'EA-1',title:'Product assignments updated',detail:'Wealth Management added to operational assignments.',timestamp:'02 Sep 2026, 03:20 PM'},{id:'EA-2',title:'Employee profile created',detail:'Employee master record created for the franchise.',timestamp:'01 Apr 2023, 10:00 AM'}],createdAt:'2023-04-01T10:00:00.000Z'},
  {id:'FE-2',franchiseeId:currentFranchiseeId,employeeId:'EMP-1002',title:'Mr',firstName:'Rahul',lastName:'Shah',mobile:'+91 98980 22541',email:'rahul.shah@example.in',designation:'Relationship Executive',department:'Sales',role:'Relationship Executive',employmentType:'Full Time',joiningDate:'2024-02-12',probationEndDate:'2024-08-12',workLocation:'Ahmedabad Main Branch',status:'Active',reportingManagerId:'FE-1',assignedProducts:['Motor Insurance','Home Loan','Business Loan','Loan Protector'],assignedCustomerIds:['TC-1061','TC-1067'],address:{line1:'Navrangpura',city:'Ahmedabad',state:'Gujarat',pinCode:'380009',country:'India'},permanentSame:true,emergencyContact:{name:'Rina Shah',relationship:'Mother',mobile:'+91 98240 99231'},aadhaarAvailable:false,documents:[{id:'ED-3',documentType:'Resume',file:{fileName:'rahul-shah-resume.pdf',fileSize:188000,fileType:'application/pdf',uploadedAt:'2024-02-10'},status:'Uploaded'},{id:'ED-4',documentType:'Appointment Letter',status:'Verified'}],platformAccess:false,activity:[{id:'EA-3',title:'Customer assigned',detail:'Kabir Desai and Riya Mehta assigned.',timestamp:'27 Aug 2026, 11:15 AM'},{id:'EA-4',title:'Employee profile created',detail:'Employee master record created for the franchise.',timestamp:'12 Feb 2024, 09:30 AM'}],createdAt:'2024-02-12T09:30:00.000Z'},
  {id:'FE-3',franchiseeId:currentFranchiseeId,employeeId:'EMP-1003',title:'Ms',firstName:'Aditi',lastName:'Rao',mobile:'+91 97261 44882',email:'aditi.rao@example.in',designation:'Service Coordinator',department:'Customer Service',role:'Customer Service',employmentType:'Full Time',joiningDate:'2026-09-02',workLocation:'Ahmedabad Main Branch',status:'On Leave',reportingManagerId:'FE-1',assignedProducts:['Health Insurance','General Insurance'],assignedCustomerIds:[],address:{line1:'Bodakdev',city:'Ahmedabad',state:'Gujarat',pinCode:'380054',country:'India'},permanentSame:true,emergencyContact:{name:'Mohan Rao',relationship:'Father',mobile:'+91 99090 88224'},aadhaarAvailable:false,documents:[{id:'ED-5',documentType:'Address Proof',status:'Pending'}],platformAccess:false,activity:[{id:'EA-5',title:'Status changed',detail:'Employee marked On Leave.',timestamp:'05 Sep 2026, 09:10 AM'},{id:'EA-6',title:'Employee profile created',detail:'Employee master record created for the franchise.',timestamp:'02 Sep 2026, 10:30 AM'}],createdAt:'2026-09-02T10:30:00.000Z'}
]

const storageKey='troth-franchisee-employees'
const read=():FranchiseeEmployee[]=>{try{const value=localStorage.getItem(storageKey);return value?JSON.parse(value) as FranchiseeEmployee[]:seed}catch{return seed}}
const write=(employees:FranchiseeEmployee[])=>{try{localStorage.setItem(storageKey,JSON.stringify(employees))}catch{/* Keep in-memory state usable. */}}
const event=(title:string,detail:string):EmployeeActivity=>({id:crypto.randomUUID(),title,detail,timestamp:new Date().toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})})

export const franchiseeEmployeeRepository={
  load:(franchiseeId=currentFranchiseeId)=>read().filter(employee=>employee.franchiseeId===franchiseeId),
  nextEmployeeId:()=>`EMP-${String(Math.max(1000,...read().map(employee=>Number(employee.employeeId.replace(/\D/g,''))||1000))+1)}`,
  saveNew:(draft:EmployeeDraft):FranchiseeEmployee=>{const employee:FranchiseeEmployee={...draft,id:crypto.randomUUID(),platformAccess:false,activity:[event('Employee created','Employee master record created. No platform login was enabled.')],createdAt:new Date().toISOString()};const rows=[employee,...read()];write(rows);return employee},
  update:(employee:FranchiseeEmployee,draft:EmployeeDraft):FranchiseeEmployee=>{const assignmentsChanged=employee.assignedProducts.join('|')!==draft.assignedProducts.join('|')||employee.assignedCustomerIds.join('|')!==draft.assignedCustomerIds.join('|'),statusChanged=employee.status!==draft.status;const activity=[...(statusChanged?[event('Status changed',`Status changed from ${employee.status} to ${draft.status}.`)]:[]),...(assignmentsChanged?[event('Assignments updated','Product or customer assignments were updated.')]:[]),event('Profile updated','Employee master details were updated.'),...employee.activity];const updated={...employee,...draft,updatedAt:new Date().toISOString(),activity};write(read().map(row=>row.id===employee.id?updated:row));return updated},
  changeStatus:(employee:FranchiseeEmployee,status:EmployeeStatus):FranchiseeEmployee=>{const updated={...employee,status,updatedAt:new Date().toISOString(),activity:[event('Status changed',`Status changed from ${employee.status} to ${status}.`),...employee.activity]};write(read().map(row=>row.id===employee.id?updated:row));return updated}
}
