import { useEffect, useState } from 'react'
import { DashboardPage } from './pages/DashboardPage'
import { CustomersPage } from './pages/CustomersPage'
import { CRMPage } from './pages/CRMPage'
import { ApplicationsPage } from './pages/ApplicationsPage'
import { ProductsPage } from './pages/ProductsPage'
import { SupportPage } from './pages/SupportPage'
import { ProfilePage } from './pages/ProfilePage'
import { NotificationsPage } from './pages/NotificationsPage'
import { MarketingPage } from './pages/MarketingPage'
import { TrainingPage } from './pages/TrainingPage'
import { BusinessRevenuePage } from './pages/BusinessRevenuePage'
import { EmployeesPage } from './pages/EmployeesPage'
import { CommissionPayoutPage } from './pages/CommissionPayoutPage'
import { RenewalsPage } from './pages/RenewalsPage'
import { SubFranchiseesPage } from './pages/SubFranchiseesPage'
import { Customer360Page } from './pages/Customer360Page'
import { CustomerOnboardingWizard } from './components/CustomerOnboardingWizard'
import { AgentsPage } from './pages/AgentsPage'
import { franchiseeWorkspaceService } from './services/franchiseeWorkspaceService'
import type { FranchiseeCustomer, FranchiseeRoute } from './types'
import type { CustomerOnboardingDraft } from './customer360Types'
import { currentFranchiseeId, franchiseeEmployeeRepository } from './employees'
import './franchisee.css'

const validRoutes:FranchiseeRoute[]=['dashboard','customers','employees','sub-franchisees','agents','crm','applications','renewals','products','support','profile','notifications','marketing','training','business-revenue','commission-payout']
export function FranchiseeApp({page,onNavigate}:{page:string;onNavigate:(page:string)=>void}){
  const customer360Id=page.match(/^customers\/([^/]+)\/360$/)?.[1]
  const subFranchiseeId=page.match(/^sub-franchisees\/([^/]+)$/)?.[1]
  const creatingEmployee=page==='employees/new'
  const creatingCustomer=page==='customers/new'
  const creatingAgent=page==='agents/new'
  const route=(creatingEmployee?'employees':creatingAgent?'agents':validRoutes.includes(page as FranchiseeRoute)?page:'dashboard') as FranchiseeRoute
  const [store,setStore]=useState(franchiseeWorkspaceService.load),[toast,setToast]=useState('')
  const crmOwners=franchiseeEmployeeRepository.load(currentFranchiseeId).filter(employee=>employee.status==='Active').map(employee=>[employee.firstName,employee.middleName,employee.lastName].filter(Boolean).join(' '))
  const [applicationPrefill,setApplicationPrefill]=useState<{customerId?:string;product?:string}>(),[supportPrefill,setSupportPrefill]=useState<{category?:string;subject?:string}>(),[customerFocus,setCustomerFocus]=useState<string>()
  useEffect(()=>{if(!toast)return;const timer=window.setTimeout(()=>setToast(''),3200);return()=>window.clearTimeout(timer)},[toast])
  const navigate=(next:FranchiseeRoute)=>{onNavigate(next);window.scrollTo(0,0)}
  const applyFor=(customer?:FranchiseeCustomer,product?:string)=>{setApplicationPrefill({customerId:customer?.id,product});navigate('applications')}
  const content=customer360Id?<Customer360Page customerId={decodeURIComponent(customer360Id)} store={store} onBack={()=>navigate('customers')} onApply={customer=>applyFor(customer)} onSupport={customer=>{setSupportPrefill({category:'Customer Escalation',subject:`Service request — ${customer.name}`});navigate('support')}} onViewCases={()=>navigate('applications')} onEdit={(customer,draft)=>{const updated=franchiseeWorkspaceService.updateCustomerProfile(customer,draft);setStore(current=>({...current,customers:current.customers.map(item=>item.id===customer.id?updated:item)}));setToast('Customer profile updated successfully')}}/>:creatingCustomer?<CustomerOnboardingWizard presentation="page" initial={franchiseeWorkspaceService.loadCustomerDraft()} onClose={()=>navigate('customers')} onSaveDraft={input=>{franchiseeWorkspaceService.saveCustomerDraft(input);setToast('Customer onboarding draft saved locally')}} onCreate={input=>{const customer=franchiseeWorkspaceService.createCustomerProfile(input);setStore(current=>({...current,customers:[customer,...current.customers],dashboardSummary:{...current.dashboardSummary,totalCustomers:current.dashboardSummary.totalCustomers+1}}));setToast(`${customer.name} created with a complete Customer 360 profile`);navigate('customers')}}/>:subFranchiseeId?<SubFranchiseesPage availableProducts={store.products.filter(product=>product.enabled).map(product=>product.name)} products={store.products} customers={store.customers} cases={store.cases} subFranchiseeId={decodeURIComponent(subFranchiseeId)} onOpenDetail={id=>onNavigate(`sub-franchisees/${encodeURIComponent(id)}`)} onBack={()=>navigate('sub-franchisees')} onOpenCustomer={customerId=>{setCustomerFocus(customerId);navigate('customers')}} onToast={setToast}/>:({
    dashboard:<DashboardPage store={store} onNavigate={navigate} onToast={setToast}/>,
    customers:<CustomersPage customers={store.customers} focusCustomerId={customerFocus} onFocusHandled={()=>setCustomerFocus(undefined)} onOpen360={customerId=>onNavigate(`customers/${encodeURIComponent(customerId)}/360`)} onAddCustomer={()=>onNavigate('customers/new')} onApply={c=>applyFor(c)} onSupport={c=>{setSupportPrefill({category:'Customer Escalation',subject:`Service request — ${c.name}`});navigate('support')}} onToast={setToast}/>,
    employees:<EmployeesPage creating={creatingEmployee} customers={store.customers} cases={store.cases} products={store.products.filter(product=>product.enabled).map(product=>product.name)} onCreateEmployee={()=>onNavigate('employees/new')} onExitCreate={()=>navigate('employees')} onOpenCustomer={customerId=>{setCustomerFocus(customerId);navigate('customers')}} onToast={setToast}/>,
    'sub-franchisees':<SubFranchiseesPage availableProducts={store.products.filter(product=>product.enabled).map(product=>product.name)} products={store.products} customers={store.customers} cases={store.cases} onOpenDetail={id=>onNavigate(`sub-franchisees/${encodeURIComponent(id)}`)} onBack={()=>navigate('sub-franchisees')} onOpenCustomer={customerId=>{setCustomerFocus(customerId);navigate('customers')}} onToast={setToast}/>,
    agents:<AgentsPage products={store.products} customers={store.customers} cases={store.cases} creating={creatingAgent} onCreateAgent={()=>onNavigate('agents/new')} onExitCreate={()=>navigate('agents')} onOpenCustomer={customerId=>{setCustomerFocus(customerId);navigate('customers')}} onToast={setToast}/>,
    crm:<CRMPage inquiries={store.inquiries} leads={store.leads} products={store.products} customers={store.customers} owners={crmOwners} onAddInquiry={item=>setStore(s=>({...s,inquiries:[item,...s.inquiries]}))} onUpdateInquiry={(id,patch)=>setStore(s=>({...s,inquiries:s.inquiries.map(item=>item.id===id?{...item,...patch}:item)}))} onAddLead={lead=>setStore(s=>({...s,leads:[lead,...s.leads]}))} onUpdateLead={(id,patch)=>setStore(s=>({...s,leads:s.leads.map(item=>item.id===id?{...item,...patch}:item)}))} onInquiryToLead={(inquiry,lead)=>{if(inquiry.status!=='Open'){setToast('This inquiry has already been classified');return}setStore(s=>({...s,leads:[lead,...s.leads],inquiries:s.inquiries.map(item=>item.id===inquiry.id?{...item,status:'Converted to Lead',linkedLeadId:lead.id,timeline:[{id:crypto.randomUUID(),title:'Converted to lead',detail:`Lead ${lead.id} created at New stage.`,time:'Just now',actor:'Franchise'},...item.timeline]}:item)}));setToast(`${inquiry.id} converted to ${lead.id}`)}} onInquiryToCase={inquiry=>{if(inquiry.status!=='Open'){setToast('This inquiry has already been classified');return}const customer=store.customers.find(item=>item.id===inquiry.customerId||item.mobile===inquiry.mobile||Boolean(inquiry.email&&item.email===inquiry.email)),created=franchiseeWorkspaceService.createCase(customer,inquiry.productInterest||'Service Request',0,'Submitted'),application={...created,sourceInquiryId:inquiry.id,timeline:[{id:crypto.randomUUID(),title:'Created from inquiry',detail:`Source inquiry ${inquiry.id}: ${inquiry.subject}`,time:'Just now',actor:'Franchise'},...created.timeline]};setStore(s=>({...s,cases:[application,...s.cases],inquiries:s.inquiries.map(item=>item.id===inquiry.id?{...item,status:'Converted to Case',linkedCaseId:application.id,timeline:[{id:crypto.randomUUID(),title:'Converted to case',detail:`Application ${application.id} created.`,time:'Just now',actor:'Franchise'},...item.timeline]}:item)}));setToast(`${inquiry.id} converted to ${application.id}`);navigate('applications')}} onConvert={lead=>{if(lead.convertedApplicationId){setToast(`Application ${lead.convertedApplicationId} already exists`);navigate('applications');return}const existing=store.customers.find(item=>item.id===lead.customerId||item.mobile===lead.mobile||Boolean(lead.email&&item.email===lead.email)),converted=franchiseeWorkspaceService.convertLead(lead,existing);setStore(s=>({...s,leads:s.leads.map(item=>item.id===lead.id?converted.lead:item),customers:converted.customerCreated?[converted.customer,...s.customers]:s.customers,dashboardSummary:converted.customerCreated?{...s.dashboardSummary,totalCustomers:s.dashboardSummary.totalCustomers+1}:s.dashboardSummary,cases:[converted.application,...s.cases],inquiries:s.inquiries.map(item=>item.id===lead.inquiryId?{...item,linkedCaseId:converted.application.id}:item)}));setToast(`Lead won; ${converted.application.id} submitted to HO Operations`);navigate('applications')}} onToast={setToast}/>,
    applications:<ApplicationsPage cases={store.cases} customers={store.customers} products={store.products} prefill={applicationPrefill} onClearPrefill={()=>setApplicationPrefill(undefined)} onCreate={(customer,product,amount,status)=>{const item=franchiseeWorkspaceService.createCase(customer,product,amount,status);setStore(s=>({...s,cases:[item,...s.cases]}));setApplicationPrefill(undefined);setToast(status==='Draft'?`${item.id} saved as draft`:`${item.id} submitted — waiting for HO Operations`)}} onResolve={(item,response)=>{setStore(s=>({...s,cases:s.cases.map(c=>c.id===item.id?{...c,status:'Query Resolved',query:undefined,assignedTeam:'HO Operations',updated:'Just now',timeline:[{id:crypto.randomUUID(),title:'Franchise response submitted',detail:response,time:'Just now',actor:'Franchise → HO Operations'},...c.timeline]}:c)}));setToast(`${item.id} cleared from Pending Actions and returned to HO`)}} onToast={setToast}/>,
    renewals:<RenewalsPage customers={store.customers} cases={store.cases} onViewCustomer={customerId=>{setCustomerFocus(customerId);navigate('customers')}} onStartRenewal={renewal=>{const customer=store.customers.find(item=>item.id===renewal.customerId);if(!customer){setToast('Customer record is unavailable');return ''}const item=franchiseeWorkspaceService.createRenewalCase(customer,renewal);setStore(current=>({...current,cases:[item,...current.cases]}));setToast('Renewal case created successfully.');return item.id}} onViewCase={()=>navigate('applications')}/>,
    products:<ProductsPage products={store.products} mappings={store.mappings} onApply={p=>applyFor(undefined,p.name)} onToast={setToast}/>,
    support:<SupportPage tickets={store.tickets} prefill={supportPrefill} onClearPrefill={()=>setSupportPrefill(undefined)} onCreate={(category,subject,description,assigned)=>{const ticket=franchiseeWorkspaceService.createTicket(category,subject,description,assigned);setStore(s=>({...s,tickets:[ticket,...s.tickets]}));setToast(`${ticket.id} routed to ${assigned}`)}} onUpdate={(id,patch)=>setStore(s=>({...s,tickets:s.tickets.map(t=>t.id===id?{...t,...patch}:t)}))} onToast={setToast}/>,
    profile:<ProfilePage products={store.products} mappings={store.mappings} onToast={setToast}/>,
    notifications:<NotificationsPage notifications={store.notifications} circulars={store.circulars} onRead={id=>setStore(s=>({...s,notifications:s.notifications.map(n=>n.id===id?{...n,read:true}:n)}))} onReadAll={()=>{setStore(s=>({...s,notifications:s.notifications.map(n=>({...n,read:true}))}));setToast('All notifications marked read')}} onAcknowledge={id=>{setStore(s=>({...s,circulars:s.circulars.map(c=>c.id===id?{...c,acknowledged:true}:c)}));setToast('Circular acknowledgement logged against compliance record')}} onToast={setToast}/>,
    marketing:<MarketingPage assets={store.marketing} onRequest={(campaign,description)=>{const ticket=franchiseeWorkspaceService.createTicket('Marketing Material Request',campaign,description,'HO Marketing');setStore(s=>({...s,tickets:[ticket,...s.tickets]}));setToast(`${ticket.id} routed to HO Marketing and is trackable in Support`)}} onToast={setToast}/>,
    training:<TrainingPage learning={store.learning} certifications={store.certifications} onPass={productId=>{setStore(s=>({...s,certifications:s.certifications.map(c=>c.productId===productId?{...c,status:'Passed',score:86}:c),mappings:s.mappings.map(m=>m.productId===productId?{...m,certified:true,enabled:true,empanelment:'Active'}:m)}));setToast('Assessment passed — Product Mapping and empanelment updated')}} onToast={setToast}/>,
    'business-revenue':<BusinessRevenuePage availableProducts={store.products.filter(product=>product.enabled).map(product=>product.name)} availableCustomers={store.customers.map(customer=>customer.name)} onOpenCustomer={()=>navigate('customers')} onToast={setToast}/>,
    'commission-payout':<CommissionPayoutPage products={store.products} tickets={store.tickets} onQuery={()=>{setSupportPrefill({category:'Payout Query',subject:'Commission / payout clarification'});navigate('support')}} onToast={setToast}/>
  }[route])
  return <div className="tf-shell tf-embedded"><section className="tf-main"><main>{content}</main></section>{toast&&<div className="tf-toast" role="status"><span>✓</span>{toast}</div>}</div>
}
