import type { CustomerOnboardingDraft } from '../franchisee/customer360Types'
import type { FranchiseeAgent } from '../franchisee/agentOnboarding'
import type { BusinessSource } from './types'

export type RecordStatus='Active'|'Inactive'|'Onboarding'
export interface TestAdminFranchise {id:string;code:string;name:string;legalName:string;contactPerson:string;mobile:string;email:string;address:string;city:string;state:string;pincode:string;activationDate:string;rmId:string;rmName:string;products:string[];status:RecordStatus;complianceStatus:'Pending'|'Verified';entityType?:string;pan?:string;gstin?:string;registrationNumber?:string;territory?:string;accountHolder?:string;bankName?:string;accountNumberLast4?:string;ifsc?:string;loginEmail?:string;documents?:string[];createdAt:string;updatedAt:string}
export interface TestAdminSubFranchise {id:string;code:string;parentFranchiseId:string;name:string;contactPerson:string;mobile:string;email:string;address:string;city:string;state:string;products:string[];status:RecordStatus;assignedOwner:string;onboardingNotes:string;legalEntityType?:string;pan?:string;gstin?:string;pincode?:string;territory?:string;effectiveDate?:string;kycStatus?:'Pending'|'Verified';documents?:string[];createdAt:string;updatedAt:string}
export interface TestAdminCustomer {id:string;name:string;mobile:string;email:string;dateOfBirth:string;pan:string;kycStatus:'Not Started'|'Pending'|'Complete';address:string;city:string;state:string;pincode:string;relationshipType:'Individual'|'Business';businessSource:Exclude<BusinessSource,'All'>;franchiseId?:string;subFranchiseId?:string;hoPospId?:string;primaryOwner:string;rmId?:string;profileDraft?:CustomerOnboardingDraft;createdAt:string;updatedAt:string}
export interface TestAdminHOEmployee {id:string;employeeId:string;name:string;mobile:string;email:string;department:string;designation:string;reportingManagerId:string;role:string;desk:string;joiningDate:string;businessLines:string[];status:'Active'|'Inactive'|'Onboarding';ownership:'Head Office';createdAt:string;updatedAt:string}
export type TestAdminHOAgent=FranchiseeAgent
interface TestAdminWorkspace {franchises:TestAdminFranchise[];subFranchises:TestAdminSubFranchise[];customers:TestAdminCustomer[];hoEmployees:TestAdminHOEmployee[];hoAgents:TestAdminHOAgent[]}

const KEY='troth-test-admin-workspace-v1'
const empty:TestAdminWorkspace={franchises:[],subFranchises:[],customers:[],hoEmployees:[],hoAgents:[]}
// Temporary browser persistence for the prototype. Replace this adapter with authenticated APIs when available.
const read=():TestAdminWorkspace=>{try{const value=localStorage.getItem(KEY);return value?{...empty,...JSON.parse(value) as TestAdminWorkspace}:structuredClone(empty)}catch{return structuredClone(empty)}}
const write=(value:TestAdminWorkspace)=>{try{localStorage.setItem(KEY,JSON.stringify(value))}catch(error){throw new Error(error instanceof Error?error.message:'Browser storage is unavailable.')}}
const stamp=()=>new Date().toISOString()
const code=(prefix:string,rows:{code?:string;employeeId?:string}[])=>`${prefix}-${String(Math.max(1000,...rows.map(row=>Number((row.code||row.employeeId||'').replace(/\D/g,''))||1000))+1)}`
const unique=(rows:{id:string}[],id:string)=>rows.findIndex(row=>row.id===id)

export const testAdminWorkspaceRepository={
 load:read,
 nextFranchiseCode:()=>code('FR',read().franchises),
 nextSubFranchiseCode:()=>code('SF',read().subFranchises),
 nextCustomerId:()=>code('CUS',read().customers.map(row=>({...row,code:row.id}))),
 nextEmployeeId:()=>code('HOE',read().hoEmployees),
 nextHOAgentCode:()=>code('HOP',read().hoAgents.map(row=>({...row,code:row.agentCode}))),
 saveFranchise:(draft:Omit<TestAdminFranchise,'id'|'createdAt'|'updatedAt'>,id?:string)=>{const store=read(),now=stamp(),index=id?unique(store.franchises,id):-1;const row:TestAdminFranchise=index>=0?{...store.franchises[index],...draft,updatedAt:now}:{...draft,id:crypto.randomUUID(),createdAt:now,updatedAt:now};store.franchises=index>=0?store.franchises.map(item=>item.id===id?row:item):[row,...store.franchises];write(store);return row},
 saveSubFranchise:(draft:Omit<TestAdminSubFranchise,'id'|'createdAt'|'updatedAt'>,id?:string)=>{if(!draft.parentFranchiseId)throw new Error('Parent Franchise is required.');const store=read();if(!store.franchises.some(row=>row.id===draft.parentFranchiseId)&&!draft.parentFranchiseId.startsWith('BASE:'))throw new Error('Select a valid Parent Franchise.');const now=stamp(),index=id?unique(store.subFranchises,id):-1;const row:TestAdminSubFranchise=index>=0?{...store.subFranchises[index],...draft,updatedAt:now}:{...draft,id:crypto.randomUUID(),createdAt:now,updatedAt:now};store.subFranchises=index>=0?store.subFranchises.map(item=>item.id===id?row:item):[row,...store.subFranchises];write(store);return row},
 saveCustomer:(draft:Omit<TestAdminCustomer,'id'|'createdAt'|'updatedAt'>,id?:string)=>{const store=read(),duplicate=store.customers.find(row=>row.id!==id&&(row.mobile===draft.mobile||row.email.toLowerCase()===draft.email.toLowerCase()));if(duplicate)throw new Error(`A customer with this mobile or email already exists (${duplicate.id}).`);if(draft.businessSource==='Franchise'&&!draft.franchiseId)throw new Error('Franchise ownership is required.');if(draft.businessSource==='Sub-Franchise'&&(!draft.franchiseId||!draft.subFranchiseId))throw new Error('Parent Franchise and Sub-Franchise are required.');if(draft.businessSource==='HO POSP'&&!draft.hoPospId)throw new Error('Select an HO POSP owner.');const now=stamp(),index=id?unique(store.customers,id):-1;const row:TestAdminCustomer=index>=0?{...store.customers[index],...draft,updatedAt:now}:{...draft,id:testAdminWorkspaceRepository.nextCustomerId(),createdAt:now,updatedAt:now};store.customers=index>=0?store.customers.map(item=>item.id===id?row:item):[row,...store.customers];write(store);return row},
 saveHOEmployee:(draft:Omit<TestAdminHOEmployee,'id'|'ownership'|'createdAt'|'updatedAt'>,id?:string)=>{const store=read(),duplicate=store.hoEmployees.find(row=>row.id!==id&&(row.employeeId===draft.employeeId||row.email.toLowerCase()===draft.email.toLowerCase()));if(duplicate)throw new Error(`An HO employee with this ID or email already exists (${duplicate.employeeId}).`);const now=stamp(),index=id?unique(store.hoEmployees,id):-1;const row:TestAdminHOEmployee=index>=0?{...store.hoEmployees[index],...draft,ownership:'Head Office',updatedAt:now}:{...draft,id:crypto.randomUUID(),ownership:'Head Office',createdAt:now,updatedAt:now};store.hoEmployees=index>=0?store.hoEmployees.map(item=>item.id===id?row:item):[row,...store.hoEmployees];write(store);return row},
 saveHOAgent:(draft:Omit<TestAdminHOAgent,'id'|'franchiseeId'|'activity'|'createdAt'|'updatedAt'>,id?:string)=>{const store=read(),duplicate=store.hoAgents.find(row=>row.id!==id&&(row.agentCode===draft.agentCode||row.email.toLowerCase()===draft.email.toLowerCase()));if(duplicate)throw new Error(`An HO POSP / Agent with this code or email already exists (${duplicate.agentCode}).`);const now=stamp(),index=id?unique(store.hoAgents,id):-1;const previous=index>=0?store.hoAgents[index]:undefined;const row:TestAdminHOAgent=previous?{...previous,...draft,updatedAt:now,activity:[{id:crypto.randomUUID(),title:'Profile updated',detail:'HO POSP / Agent onboarding details were updated.',time:new Date().toLocaleString('en-IN'),actor:'Master Admin'},...previous.activity]}:{...draft,id:crypto.randomUUID(),franchiseeId:'HO-TROTH-001',activity:[{id:crypto.randomUUID(),title:'HO onboarding started',detail:`${draft.assignments.length} business line(s) assigned. Eligibility is controlled by mandatory requirements.`,time:new Date().toLocaleString('en-IN'),actor:'Master Admin'}],createdAt:now,updatedAt:now};store.hoAgents=previous?store.hoAgents.map(item=>item.id===id?row:item):[row,...store.hoAgents];write(store);return row},
 updateHOAgentRequirement:(agentId:string,lineId:string,requirementId:string,status:'Completed'|'Pending HO Verification'|'Verified')=>{const store=read(),now=stamp();let result:TestAdminHOAgent|undefined;store.hoAgents=store.hoAgents.map(agent=>{if(agent.id!==agentId)return agent;const title=status==='Verified'?'Requirement verified':status==='Completed'?'Requirement completed':'Requirement submitted';result={...agent,assignments:agent.assignments.map(line=>line.businessLineId===lineId?{...line,requirements:line.requirements.map(requirement=>requirement.id===requirementId?{...requirement,status,...(status==='Verified'?{verifiedBy:'Master Admin / Compliance',verifiedAt:now}:{})}:requirement)}:line),activity:[{id:crypto.randomUUID(),title,detail:`Onboarding requirement status changed to ${status}.`,time:new Date().toLocaleString('en-IN'),actor:'Master Admin'},...agent.activity],updatedAt:now};return result});write(store);return result}
}
