import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, CalendarClock, CheckCircle2, FileText, Mail, MessageSquare, Pencil, Plus, Upload, UserPlus, X } from 'lucide-react'
import type { Application } from '../types'
import type { CustomerKycStatus, CustomerRelationshipStatus, FranchiseeCustomer } from '../types/franchisee'
import { formatINR } from '../data/mockData'
import { PageHeader, SearchBox, Select, StatCard, StatusBadge } from '../components/UI'

interface Props {
  customers:FranchiseeCustomer[]
  apps:Application[]
  onAdd:(customer:FranchiseeCustomer)=>void
  onUpdate:(id:string,patch:Partial<FranchiseeCustomer>)=>void
  onNavigate:(page:string)=>void
  onToast:(message:string)=>void
}

export function FranchiseeCustomers({customers,apps,onAdd,onUpdate,onNavigate,onToast}:Props){
  const [search,setSearch]=useState('')
  const [status,setStatus]=useState('All')
  const [kyc,setKyc]=useState('All')
  const [selectedId,setSelectedId]=useState<string|null>(null)
  const [addOpen,setAddOpen]=useState(false)
  const selected=customers.find(customer=>customer.id===selectedId)||null
  useEffect(()=>{if(sessionStorage.getItem('troth-franchisee-action')==='add-customer'){sessionStorage.removeItem('troth-franchisee-action');setAddOpen(true)}},[])
  const rows=useMemo(()=>customers.filter(customer=>(status==='All'||customer.relationshipStatus===status)&&(kyc==='All'||customer.kycStatus===kyc)&&`${customer.name} ${customer.id} ${customer.mobile} ${customer.email}`.toLowerCase().includes(search.toLowerCase())),[customers,status,kyc,search])
  const createCustomer=(data:Record<string,string>)=>{
    const id=`CU-${1100+customers.length+1}`
    onAdd({id,name:data.name,mobile:data.mobile,email:data.email,city:data.city,source:data.source,relationshipStatus:'Prospect',kycStatus:'Pending',products:[],applicationIds:[],businessValue:0,assignedTo:'Neha Sharma',lastContact:'Just now',nextFollowUp:data.followUp||'Not scheduled',notes:[],activities:[{title:'Customer profile created',date:'03 Sep 2026 • Just now'}],documents:[{name:'PAN card',status:'Missing'},{name:'Aadhaar card',status:'Missing'},{name:'Cancelled cheque',status:'Missing'}],serviceHistory:[]})
    setAddOpen(false);onToast(`${data.name} added successfully`)
  }
  return <div className="page franchisee-customers-page">
    <PageHeader eyebrow="CUSTOMERS" title="Customers" description="Manage customer relationships, portfolios, activities and next actions." actions={<button className="primary-btn" onClick={()=>setAddOpen(true)}><UserPlus/> Add customer</button>}/>
    <section className="mini-stats"><StatCard label="Total Customers" value={customers.length} meta="Franchisee relationships"/><StatCard label="Active" value={customers.filter(customer=>customer.relationshipStatus==='Active').length} meta="Currently engaged" tone="green"/><StatCard label="KYC Pending" value={customers.filter(customer=>customer.kycStatus==='Pending').length} meta="Needs completion" tone="amber"/><StatCard label="Portfolio Value" value={formatINR(customers.reduce((sum,customer)=>sum+customer.businessValue,0),true)} meta="Recorded customer business" tone="blue"/></section>
    <section className="table-panel"><div className="table-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search customer, ID, mobile or email"/><div className="toolbar-filters"><Select value={status} onChange={setStatus}><option>All</option><option>Active</option><option>Prospect</option><option>Dormant</option></Select><Select value={kyc} onChange={setKyc}><option>All</option><option>Verified</option><option>Pending</option><option>Expired</option></Select></div></div><div className="result-count"><b>{rows.length} customers</b><span>Visible to Troth Finserve</span></div>
      <div className="data-table-wrap"><table className="data-table franchisee-customer-table"><thead><tr><th>Customer</th><th>Contact</th><th>Products</th><th>Applications</th><th>Business Value</th><th>KYC</th><th>Relationship</th><th>Next Follow-up</th><th/></tr></thead><tbody>{rows.map(customer=><tr key={customer.id} onClick={()=>setSelectedId(customer.id)}><td data-label="Customer"><b className="link-text">{customer.name}</b><small>{customer.id} • {customer.city}</small></td><td data-label="Contact"><b>{customer.mobile}</b><small>{customer.email}</small></td><td data-label="Products"><b>{customer.products.length}</b><small>{customer.products.slice(0,2).join(', ')||'No active products'}</small></td><td data-label="Applications"><b>{customer.applicationIds.length}</b><small>{customer.applicationIds[0]||'No applications'}</small></td><td data-label="Business"><b>{formatINR(customer.businessValue)}</b></td><td data-label="KYC"><StatusBadge status={customer.kycStatus}/></td><td data-label="Relationship"><StatusBadge status={customer.relationshipStatus}/></td><td data-label="Follow-up"><span>{customer.nextFollowUp}</span></td><td><ArrowRight/></td></tr>)}</tbody></table></div>
      {!rows.length&&<div className="empty-state"><UserPlus/><h3>No customers found</h3><p>Try changing the search or filters.</p><button onClick={()=>{setSearch('');setStatus('All');setKyc('All')}}>Clear filters</button></div>}
    </section>
    {selected&&<CustomerDrawer customer={selected} apps={apps.filter(app=>selected.applicationIds.includes(app.id)||app.customer===selected.name)} onClose={()=>setSelectedId(null)} onUpdate={patch=>onUpdate(selected.id,patch)} onNavigate={onNavigate} onToast={onToast}/>} 
    {addOpen&&<CustomerForm onClose={()=>setAddOpen(false)} onSubmit={createCustomer}/>} 
  </div>
}

function CustomerDrawer({customer,apps,onClose,onUpdate,onNavigate,onToast}:{customer:FranchiseeCustomer;apps:Application[];onClose:()=>void;onUpdate:(patch:Partial<FranchiseeCustomer>)=>void;onNavigate:(page:string)=>void;onToast:(message:string)=>void}){
  const [tab,setTab]=useState('Overview');const [editing,setEditing]=useState(false);const [note,setNote]=useState('');const [followUp,setFollowUp]=useState(customer.nextFollowUp)
  const tabs=['Overview','Contact Details','Products','Applications','Documents','Activities','Notes','Follow-ups','Service History']
  const saveNote=()=>{if(!note.trim())return;onUpdate({notes:[{id:`N-${Date.now()}`,text:note.trim(),date:'03 Sep 2026 • Just now'},...customer.notes]});setNote('');onToast('Customer note added')}
  return <><button className="drawer-scrim" onClick={onClose}/><aside className="detail-drawer franchisee-customer-drawer"><div className="drawer-header"><div><span className="eyebrow">{customer.id}</span><h2>{customer.name}</h2><p>{customer.city} • Managed by {customer.assignedTo}</p></div><button className="icon-button" onClick={onClose}><X/></button></div><div className="drawer-summary"><StatusBadge status={customer.relationshipStatus}/><StatusBadge status={customer.kycStatus}/><span>Last contact <b>{customer.lastContact}</b></span></div><div className="drawer-tabs">{tabs.map(item=><button className={tab===item?'active':''} onClick={()=>setTab(item)} key={item}>{item}</button>)}</div><div className="drawer-body">
    {tab==='Overview'&&<><section className="drawer-stat-grid"><StatCard label="Products" value={customer.products.length} meta="Active holdings"/><StatCard label="Applications" value={apps.length} meta="Current and historical" tone="blue"/><StatCard label="Business Value" value={formatINR(customer.businessValue,true)} meta="Recorded business" tone="green"/><StatCard label="Open Services" value={customer.serviceHistory.filter(item=>item.status!=='Completed').length} meta="Support requests" tone="amber"/></section><section className="detail-section"><h3>Relationship overview</h3><div className="detail-grid"><div><span>Customer source</span><b>{customer.source}</b></div><div><span>Assigned owner</span><b>{customer.assignedTo}</b></div><div><span>Last contact</span><b>{customer.lastContact}</b></div><div><span>Next follow-up</span><b>{customer.nextFollowUp}</b></div></div></section></>}
    {tab==='Contact Details'&&<section className="detail-section"><div className="section-inline-heading"><h3>Permitted contact details</h3><button onClick={()=>setEditing(value=>!value)}><Pencil/> {editing?'Cancel':'Edit'}</button></div>{editing?<form onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);onUpdate({mobile:String(data.get('mobile')),email:String(data.get('email')),city:String(data.get('city'))});setEditing(false);onToast('Customer contact details updated')}}><label>Mobile<input name="mobile" defaultValue={customer.mobile} required/></label><label>Email<input name="email" type="email" defaultValue={customer.email} required/></label><label>City<input name="city" defaultValue={customer.city} required/></label><button className="primary-btn">Save permitted changes</button></form>:<div className="detail-grid"><div><span>Mobile</span><b>{customer.mobile}</b></div><div><span>Email</span><b>{customer.email}</b></div><div><span>City</span><b>{customer.city}</b></div><div><span>Franchisee</span><b>Troth Finserve</b></div></div>}</section>}
    {tab==='Products'&&<section className="detail-section"><h3>Product portfolio</h3><div className="customer-drawer-list">{customer.products.length?customer.products.map(product=><div key={product}><span><CheckCircle2/></span><div><b>{product}</b><small>Active customer relationship</small></div><button onClick={()=>onToast(`${product} details opened`)}>View</button></div>):<p>No active products are recorded for this customer.</p>}</div></section>}
    {tab==='Applications'&&<section className="detail-section"><h3>Applications</h3><div className="customer-drawer-list">{apps.length?apps.map(app=><button key={app.id} onClick={()=>{sessionStorage.setItem('troth-open-app',app.id);onNavigate('applications')}}><span><FileText/></span><div><b>{app.productName}</b><small>{app.id} • {app.stage}</small></div><StatusBadge status={app.status}/></button>):<p>No applications are currently linked.</p>}</div><button className="primary-btn drawer-primary-action" onClick={()=>{sessionStorage.setItem('troth-franchisee-action','new-application');onNavigate('applications')}}><Plus/> Create application</button></section>}
    {tab==='Documents'&&<section className="detail-section"><h3>Customer documents</h3><div className="document-list">{customer.documents.map(document=><div key={document.name}><span className={`doc-icon ${document.status.toLowerCase()}`}><Upload/></span><div><b>{document.name}</b><small>Customer KYC document</small></div><StatusBadge status={document.status}/><button onClick={()=>onToast(`${document.name} upload opened`)}>Manage</button></div>)}</div></section>}
    {tab==='Activities'&&<section className="detail-section"><h3>Activity history</h3><div className="timeline">{customer.activities.map(activity=><div key={activity.title+activity.date}><i/><p><b>{activity.title}</b><span>{activity.date}</span></p></div>)}</div></section>}
    {tab==='Notes'&&<section className="detail-section"><h3>Relationship notes</h3><div className="note-box"><textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Add a customer note..."/><button onClick={saveNote}>Add note</button></div><div className="customer-notes">{customer.notes.map(item=><article key={item.id}><MessageSquare/><div><p>{item.text}</p><small>{item.date}</small></div></article>)}</div></section>}
    {tab==='Follow-ups'&&<section className="detail-section"><h3>Schedule follow-up</h3><label className="drawer-field">Next follow-up<input type="text" value={followUp} onChange={event=>setFollowUp(event.target.value)}/></label><button className="primary-btn" onClick={()=>{onUpdate({nextFollowUp:followUp});onToast('Follow-up scheduled')}}><CalendarClock/> Save follow-up</button></section>}
    {tab==='Service History'&&<section className="detail-section"><h3>Service history</h3><div className="customer-drawer-list">{customer.serviceHistory.length?customer.serviceHistory.map(item=><div key={item.id}><span><MessageSquare/></span><div><b>{item.subject}</b><small>{item.id} • {item.date}</small></div><StatusBadge status={item.status}/></div>):<p>No service requests are recorded.</p>}</div></section>}
  </div><div className="drawer-actions"><button className="secondary-btn" onClick={()=>onToast(`Email composer opened for ${customer.name}`)}><Mail/> Communicate</button><button className="primary-btn" onClick={()=>{sessionStorage.setItem('troth-franchisee-action','new-application');onNavigate('applications')}}><Plus/> Start application</button></div></aside></>
}

function CustomerForm({onClose,onSubmit}:{onClose:()=>void;onSubmit:(data:Record<string,string>)=>void}){return <div className="modal-wrap"><button className="modal-scrim" onClick={onClose}/><form className="modal franchisee-customer-form" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);onSubmit(Object.fromEntries([...data.entries()].map(([key,value])=>[key,String(value)])))}}><div className="modal-heading"><div className="modal-icon"><UserPlus/></div><div><span className="eyebrow">NEW RELATIONSHIP</span><h2>Add customer</h2></div><button type="button" className="icon-button" onClick={onClose}><X/></button></div><label>Customer name<input name="name" required placeholder="Full name"/></label><div className="form-row"><label>Mobile<input name="mobile" required placeholder="+91"/></label><label>Email<input name="email" type="email" required placeholder="name@example.in"/></label></div><div className="form-row"><label>City<input name="city" required defaultValue="Ahmedabad"/></label><label>Source<select name="source"><option>Referral</option><option>Walk-in</option><option>Digital Campaign</option><option>Social Media</option><option>Other</option></select></label></div><label>First follow-up<input name="followUp" placeholder="e.g. 05 Sep 2026 • 11:00 AM"/></label><div className="form-actions"><button type="button" className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn">Add customer</button></div></form></div>}

