import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, CalendarClock, CheckCircle2, Kanban, List, MessageSquare, Plus, UserCheck, UserPlus, X } from 'lucide-react'
import type { FranchiseeCustomer, FranchiseeLead, LeadStage } from '../types/franchisee'
import { leadStages } from '../data/franchiseeData'
import { formatINR } from '../data/mockData'
import { PageHeader, SearchBox, Select, StatCard, StatusBadge } from '../components/UI'

interface Props {
  leads:FranchiseeLead[]
  onAdd:(lead:FranchiseeLead)=>void
  onUpdate:(id:string,patch:Partial<FranchiseeLead>)=>void
  onConvert:(lead:FranchiseeLead)=>void
  onNavigate:(page:string)=>void
  onToast:(message:string)=>void
}

export function FranchiseeCRM({leads,onAdd,onUpdate,onConvert,onNavigate,onToast}:Props){
  const [search,setSearch]=useState('');const [stage,setStage]=useState('All');const [owner,setOwner]=useState('All');const [view,setView]=useState<'pipeline'|'list'>('pipeline');const [selectedId,setSelectedId]=useState<string|null>(null);const [addOpen,setAddOpen]=useState(false)
  const selected=leads.find(lead=>lead.id===selectedId)||null
  useEffect(()=>{const action=sessionStorage.getItem('troth-franchisee-action');if(action==='add-lead'){sessionStorage.removeItem('troth-franchisee-action');setAddOpen(true)}const requested=sessionStorage.getItem('troth-crm-stage');if(requested){setStage(requested);sessionStorage.removeItem('troth-crm-stage')}},[])
  const visible=useMemo(()=>leads.filter(lead=>(stage==='All'||lead.stage===stage)&&(owner==='All'||lead.owner===owner)&&`${lead.name} ${lead.id} ${lead.interest} ${lead.mobile}`.toLowerCase().includes(search.toLowerCase())),[leads,stage,owner,search])
  const active=leads.filter(lead=>!['Converted','Lost / Closed'].includes(lead.stage));const converted=leads.filter(lead=>lead.stage==='Converted').length;const hot=active.filter(lead=>lead.temperature==='Hot').length;const due=active.filter(lead=>lead.nextFollowUp.startsWith('03 Sep')).length
  const createLead=(data:Record<string,string>)=>{onAdd({id:`LD-${2100+leads.length+1}`,name:data.name,mobile:data.mobile,email:data.email,city:data.city,source:data.source,interest:data.interest,estimatedValue:Number(data.value)||0,stage:'New Lead',kycStatus:'Not Started',owner:data.owner,temperature:data.temperature as FranchiseeLead['temperature'],nextFollowUp:data.followUp||'Not scheduled',lastActivity:'Lead created'});setAddOpen(false);onToast(`${data.name} added to the pipeline`)}
  return <div className="page franchisee-crm-page"><PageHeader eyebrow="CRM / SALES PIPELINE" title="Leads & Opportunities" description="Manage opportunities from first contact through KYC, application and conversion." actions={<button className="primary-btn" onClick={()=>setAddOpen(true)}><UserPlus/> Add lead</button>}/>
    <section className="mini-stats"><StatCard label="Active Leads" value={active.length} meta="Open opportunities"/><StatCard label="Hot Opportunities" value={hot} meta="Priority prospects" tone="red"/><StatCard label="Follow-ups Due" value={due} meta="Due today" tone="amber"/><StatCard label="Converted" value={converted} meta="Current sample pipeline" tone="green"/></section>
    <section className="crm-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search lead, ID, product or mobile"/><div><Select value={stage} onChange={setStage}><option>All</option>{leadStages.map(item=><option key={item}>{item}</option>)}</Select><Select value={owner} onChange={setOwner}><option>All</option><option>Neha Sharma</option><option>Amit Patel</option></Select><span className="view-switch"><button className={view==='pipeline'?'active':''} onClick={()=>setView('pipeline')}><Kanban/> Pipeline</button><button className={view==='list'?'active':''} onClick={()=>setView('list')}><List/> List</button></span></div></section>
    {view==='pipeline'?<PipelineBoard leads={visible} onSelect={setSelectedId}/>:<LeadTable leads={visible} onSelect={setSelectedId}/>} 
    {!visible.length&&<div className="panel empty-state"><UserPlus/><h3>No leads found</h3><p>Try changing the search or pipeline filters.</p><button onClick={()=>{setSearch('');setStage('All');setOwner('All')}}>Clear filters</button></div>}
    {selected&&<LeadDrawer lead={selected} onClose={()=>setSelectedId(null)} onUpdate={patch=>onUpdate(selected.id,patch)} onConvert={()=>{onConvert(selected);setSelectedId(null)}} onNavigate={onNavigate} onToast={onToast}/>} 
    {addOpen&&<LeadForm onClose={()=>setAddOpen(false)} onSubmit={createLead}/>} 
  </div>
}

const boardStages:LeadStage[]=['New Lead','Contacted','Qualified','Requirement Identified','KYC Pending','KYC Completed','Application Initiated','Application Submitted','Converted']
function PipelineBoard({leads,onSelect}:{leads:FranchiseeLead[];onSelect:(id:string)=>void}){return <section className="crm-pipeline-board">{boardStages.map(stage=><div className="pipeline-column" key={stage}><header><span>{stage}</span><b>{leads.filter(lead=>lead.stage===stage).length}</b></header><div>{leads.filter(lead=>lead.stage===stage).map(lead=><button key={lead.id} onClick={()=>onSelect(lead.id)}><div><b>{lead.name}</b><i className={`temperature-${lead.temperature.toLowerCase()}`}>{lead.temperature}</i></div><p>{lead.interest}</p><strong>{formatINR(lead.estimatedValue)}</strong><small><CalendarClock/> {lead.nextFollowUp}</small><span>{lead.owner}</span></button>)}</div></div>)}</section>}

function LeadTable({leads,onSelect}:{leads:FranchiseeLead[];onSelect:(id:string)=>void}){return <section className="table-panel"><div className="result-count"><b>{leads.length} leads</b></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Lead</th><th>Contact</th><th>Interest</th><th>Value</th><th>Stage</th><th>KYC</th><th>Owner</th><th>Next Follow-up</th><th/></tr></thead><tbody>{leads.map(lead=><tr key={lead.id} onClick={()=>onSelect(lead.id)}><td><b className="link-text">{lead.name}</b><small>{lead.id} • {lead.source}</small></td><td><b>{lead.mobile}</b><small>{lead.email}</small></td><td>{lead.interest}</td><td><b>{formatINR(lead.estimatedValue)}</b></td><td><StatusBadge status={lead.stage}/></td><td><StatusBadge status={lead.kycStatus}/></td><td>{lead.owner}</td><td>{lead.nextFollowUp}</td><td><ArrowRight/></td></tr>)}</tbody></table></div></section>}

function LeadDrawer({lead,onClose,onUpdate,onConvert,onNavigate,onToast}:{lead:FranchiseeLead;onClose:()=>void;onUpdate:(patch:Partial<FranchiseeLead>)=>void;onConvert:()=>void;onNavigate:(page:string)=>void;onToast:(message:string)=>void}){
  const [activity,setActivity]=useState('');const [followUp,setFollowUp]=useState(lead.nextFollowUp)
  const updateStage=(value:string)=>{onUpdate({stage:value as LeadStage,lastActivity:`Moved to ${value}`});onToast(`Lead moved to ${value}`)}
  return <><button className="drawer-scrim" onClick={onClose}/><aside className="detail-drawer crm-lead-drawer"><div className="drawer-header"><div><span className="eyebrow">{lead.id}</span><h2>{lead.name}</h2><p>{lead.interest} • {lead.source}</p></div><button className="icon-button" onClick={onClose}><X/></button></div><div className="drawer-summary"><StatusBadge status={lead.stage}/><span>Owner <b>{lead.owner}</b></span><span>Opportunity <b>{formatINR(lead.estimatedValue)}</b></span></div><div className="drawer-body"><section className="detail-section"><h3>Lead information</h3><div className="detail-grid"><div><span>Mobile</span><b>{lead.mobile}</b></div><div><span>Email</span><b>{lead.email}</b></div><div><span>City</span><b>{lead.city}</b></div><div><span>Temperature</span><b>{lead.temperature}</b></div><div><span>KYC status</span><StatusBadge status={lead.kycStatus}/></div><div><span>Last activity</span><b>{lead.lastActivity}</b></div></div></section><section className="detail-section"><h3>Update pipeline</h3><div className="crm-update-grid"><label>Pipeline stage<select value={lead.stage} onChange={event=>updateStage(event.target.value)}>{leadStages.map(stage=><option key={stage}>{stage}</option>)}</select></label><label>KYC status<select value={lead.kycStatus} onChange={event=>{onUpdate({kycStatus:event.target.value as FranchiseeLead['kycStatus']});onToast('KYC status updated')}}><option>Not Started</option><option>Pending</option><option>Completed</option></select></label><label>Assigned owner<select value={lead.owner} onChange={event=>onUpdate({owner:event.target.value})}><option>Neha Sharma</option><option>Amit Patel</option></select></label><label>Next follow-up<input value={followUp} onChange={event=>setFollowUp(event.target.value)}/></label></div><button className="secondary-btn" onClick={()=>{onUpdate({nextFollowUp:followUp});onToast('Follow-up scheduled')}}><CalendarClock/> Save follow-up</button></section><section className="detail-section"><h3>Add activity</h3><div className="note-box"><textarea value={activity} onChange={event=>setActivity(event.target.value)} placeholder="Record a call, meeting or customer update..."/><button onClick={()=>{if(!activity.trim())return;onUpdate({lastActivity:activity.trim()});setActivity('');onToast('CRM activity added')}}>Add activity</button></div></section></div><div className="drawer-actions"><button className="secondary-btn" onClick={()=>onToast(`Message composer opened for ${lead.name}`)}><MessageSquare/> Communicate</button>{lead.stage!=='Converted'&&<button className="secondary-btn" onClick={onConvert}><UserCheck/> Convert customer</button>}<button className="primary-btn" onClick={()=>{onUpdate({stage:'Application Initiated'});sessionStorage.setItem('troth-franchisee-action','new-application');onNavigate('applications')}}><Plus/> Initiate application</button></div></aside></>
}

function LeadForm({onClose,onSubmit}:{onClose:()=>void;onSubmit:(data:Record<string,string>)=>void}){return <div className="modal-wrap"><button className="modal-scrim" onClick={onClose}/><form className="modal franchisee-lead-form" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);onSubmit(Object.fromEntries([...data.entries()].map(([key,value])=>[key,String(value)])))}}><div className="modal-heading"><div className="modal-icon"><UserPlus/></div><div><span className="eyebrow">NEW OPPORTUNITY</span><h2>Add lead</h2></div><button type="button" className="icon-button" onClick={onClose}><X/></button></div><label>Lead name<input name="name" required placeholder="Full name"/></label><div className="form-row"><label>Mobile<input name="mobile" required placeholder="+91"/></label><label>Email<input name="email" type="email" required placeholder="name@example.in"/></label></div><div className="form-row"><label>City<input name="city" defaultValue="Ahmedabad" required/></label><label>Source<select name="source"><option>Referral</option><option>Walk-in</option><option>Website</option><option>Digital Campaign</option><option>Social Media</option></select></label></div><div className="form-row"><label>Product interest<select name="interest"><option>Health Insurance</option><option>Home Loan</option><option>Business Loan</option><option>Loan Protector</option><option>Mutual Fund</option><option>Demat Account</option></select></label><label>Estimated value<input name="value" type="number" min="0" placeholder="₹ 0"/></label></div><div className="form-row"><label>Owner<select name="owner"><option>Neha Sharma</option><option>Amit Patel</option></select></label><label>Priority<select name="temperature"><option>Warm</option><option>Hot</option><option>Cold</option></select></label></div><label>First follow-up<input name="followUp" placeholder="e.g. 05 Sep 2026 • 11:00 AM"/></label><div className="form-actions"><button type="button" className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn">Add lead</button></div></form></div>}

