import { franchiseeWorkspaceSeed } from '../data'
import type { FranchiseeCase, FranchiseeCommissionSlab, FranchiseeCustomer, FranchiseeLead, FranchiseeProduct, FranchiseeStore, FranchiseeTicket } from '../types'
import type { CustomerOnboardingDraft, CustomerReminder, FranchiseeCustomerProfile, ReminderChannel } from '../customer360Types'
import type { FranchiseeRenewal } from '../renewalsData'
import { crmStageService } from './crmStageService'

const clone=<T,>(value:T):T=>structuredClone(value)
const customerKey='troth-franchisee-customers'
const commissionSlabKey='troth-franchisee-commission-slabs-v1'
export const customerDraftKey='troth-franchisee-customer-drafts'
const safeRead=<T,>(key:string,fallback:T):T=>{try{const value=localStorage.getItem(key);return value?JSON.parse(value) as T:fallback}catch{return fallback}}
const safeWrite=(key:string,value:unknown)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{/* Storage may be unavailable. */}}
const customerName=(draft:CustomerOnboardingDraft)=>draft.customerType==='Business'?draft.basic.businessName?.trim()||'Business Customer':[draft.basic.firstName,draft.basic.middleName,draft.basic.lastName].filter(Boolean).join(' ')
const reminder=(customerId:string,type:CustomerReminder['type'],title:string,dueDate:string,offsets:number[],channels:ReminderChannel[],entityType:CustomerReminder['relatedEntityType'],entityId:string):CustomerReminder=>({id:crypto.randomUUID(),customerId,type,title,dueDate,reminderOffsets:offsets,channels,relatedEntityType:entityType,relatedEntityId:entityId,enabled:true,status:new Date(`${dueDate}T23:59:59`)<new Date()?'Due':'Upcoming'})
const buildReminders=(customerId:string,draft:CustomerOnboardingDraft)=>{const channels=draft.preferences.reminderChannels.length?draft.preferences.reminderChannels:['In-App' as const];const rows:CustomerReminder[]=[];draft.documents.forEach(doc=>{if(doc.expiryDate&&doc.reminderEnabled)rows.push(reminder(customerId,'Document Expiry',`${doc.documentType} expiry`,doc.expiryDate,doc.reminderOffsets||[30],channels,'document',doc.id))});draft.policies.forEach(policy=>{if(policy.renewalDate&&policy.renewalReminderEnabled)rows.push(reminder(customerId,'Insurance Renewal',`${policy.insurer} ${policy.category}`,policy.renewalDate,policy.reminderOffsets,channels,'policy',policy.id));if(policy.premiumDueDate&&policy.premiumReminderEnabled)rows.push(reminder(customerId,'Premium Due',`${policy.insurer} premium`,policy.premiumDueDate,[7,1],channels,'policy',policy.id))});draft.loans.forEach(loan=>{if(loan.emiDueDay&&loan.emiReminderEnabled){const next=new Date();next.setMonth(next.getMonth()+(next.getDate()>loan.emiDueDay?1:0),loan.emiDueDay);rows.push(reminder(customerId,'Loan EMI',`${loan.lender} ${loan.loanType} EMI`,next.toISOString().slice(0,10),[3,1,0],channels,'loan',loan.id))}if(loan.maturityDate&&loan.maturityReminderEnabled)rows.push(reminder(customerId,'Loan Maturity',`${loan.lender} ${loan.loanType} maturity`,loan.maturityDate,[90,60,30],channels,'loan',loan.id));if(loan.rateReviewReminderEnabled){const due=new Date();due.setMonth(due.getMonth()+6);rows.push(reminder(customerId,'Rate Review',`${loan.lender} rate review`,due.toISOString().slice(0,10),[30],channels,'loan',loan.id))}});draft.investments.forEach(item=>{if(item.maturityDate&&item.maturityReminderEnabled)rows.push(reminder(customerId,'Investment Maturity',`${item.provider||''} ${item.productName||item.investmentType}`.trim(),item.maturityDate,[30,7],channels,'investment',item.id));if(item.sipReminderEnabled){const due=new Date();due.setMonth(due.getMonth()+1,1);rows.push(reminder(customerId,'SIP Reminder',`${item.productName||item.investmentType} SIP`,due.toISOString().slice(0,10),[3,1],channels,'investment',item.id))}});return rows}
const commissionSlabSeed=(products:FranchiseeProduct[]):FranchiseeCommissionSlab[]=>products.map((product,index)=>{const numeric=Number(product.commission.match(/[\d.]+/)?.[0]||0),fixed=/₹/.test(product.commission);return{id:`FSL-${String(index+1).padStart(3,'0')}`,name:`${product.name} ${/trail/i.test(product.commission)?'Trail':'Standard'}`,vertical:product.category,product:product.name,transactionType:/trail|renewal/i.test(product.commission)?'Renewal':'New Business',calculationType:fixed?'Fixed Amount':'Percentage',rate:numeric,franchiseSharePercent:100,hoSharePercent:0,agentSharePercent:0,effectiveFrom:'2026-04-01',effectiveTo:'2027-03-31',status:'Active',updatedAt:'01 Apr 2026',updatedBy:'Franchise Principal',remarks:product.commission}})

export const franchiseeWorkspaceService={
  load:():FranchiseeStore=>{const seed=clone(franchiseeWorkspaceSeed);const saved=safeRead<FranchiseeCustomer[]>(customerKey,[]);return {...seed,customers:[...saved,...seed.customers],dashboardSummary:{...seed.dashboardSummary,totalCustomers:seed.dashboardSummary.totalCustomers+saved.length}}},
  createCustomer:(input:Pick<FranchiseeCustomer,'name'|'mobile'|'email'|'city'>):FranchiseeCustomer=>({id:`CUST-${1070+Math.floor(Math.random()*20)}`,...input,kyc:'Pending',relationshipValue:0,performance:0,products:[],lastActivity:'Just now',tags:['New'],documents:[{name:'PAN',status:'Missing',requested:true},{name:'Aadhaar',status:'Missing',requested:true}],timeline:[{id:crypto.randomUUID(),title:'Customer profile created',detail:'KYC documents are pending. No HO case has been created.',time:'Just now',actor:'Franchise'}]}),
  createCustomerProfile:(draft:CustomerOnboardingDraft):FranchiseeCustomer=>{const customerId=`CUST-${Date.now().toString().slice(-7)}`;const profile:FranchiseeCustomerProfile={...draft,id:customerId,reminders:buildReminders(customerId,draft),profileCompleteness:0,createdAt:new Date().toISOString()};const basicComplete=draft.customerType==='Individual'?Boolean(draft.basic.firstName&&draft.basic.lastName&&draft.basic.dateOfBirth):Boolean(draft.basic.businessName&&draft.basic.entityType&&draft.basic.primaryContact);const address=draft.contact.currentAddress;const productsAccounted=(draft.noExistingPolicies||draft.policies.length>0)&&(draft.noExistingLoans||draft.loans.length>0)&&(draft.noExistingInvestments||draft.investments.length>0);profile.profileCompleteness=(basicComplete?20:0)+(draft.contact.primaryMobile&&draft.contact.email&&address.line1&&address.city&&address.state&&address.pinCode?15:0)+(draft.customerType==='Business'||draft.profile.occupation||draft.profile.family.length||draft.profile.nominee.name?10:0)+(draft.kyc.status!=='Not Started'||draft.kyc.panNumber?15:0)+(draft.documents.length?10:0)+(productsAccounted?15:0)+(draft.preferences.interests.length||draft.preferences.primaryGoal?10:0)+(draft.preferences.communicationConsent.length||draft.preferences.reminderTypes.length?5:0);const products=[...draft.policies.map(p=>p.category),...draft.loans.map(l=>l.loanType),...draft.investments.map(i=>i.investmentType)].filter(Boolean);const customer:FranchiseeCustomer={id:customerId,name:customerName(draft),mobile:draft.contact.primaryMobile,email:draft.contact.email,city:address.city,kyc:draft.kyc.status==='Complete'?'Verified':'Pending',relationshipValue:draft.financial.netWorth||draft.investments.reduce((sum,item)=>sum+(item.currentValue||0),0),performance:0,products:[...new Set(products)],lastActivity:'Just now',tags:['New',...draft.preferences.tags],documents:draft.documents.map(doc=>({name:doc.documentType,status:doc.status==='Verified'?'Verified':doc.status==='Uploaded'?'Received':'Pending'})),timeline:[{id:crypto.randomUUID(),title:'Customer 360 profile created',detail:`${profile.profileCompleteness}% complete · ${profile.reminders.length} reminder configurations captured.`,time:'Just now',actor:'Franchise'}],profile360:profile};const saved=safeRead<FranchiseeCustomer[]>(customerKey,[]);safeWrite(customerKey,[customer,...saved]);localStorage.removeItem(customerDraftKey);return customer},
  loadCustomerDraft:()=>safeRead<CustomerOnboardingDraft|undefined>(customerDraftKey,undefined),
  saveCustomerDraft:(draft:CustomerOnboardingDraft)=>safeWrite(customerDraftKey,draft),
  loadCommissionSlabs:(products:FranchiseeProduct[])=>safeRead<FranchiseeCommissionSlab[]>(commissionSlabKey,commissionSlabSeed(products)),
  saveCommissionSlabs:(slabs:FranchiseeCommissionSlab[])=>safeWrite(commissionSlabKey,slabs),
  createCase:(customer:FranchiseeCustomer|undefined,product:string,amount:number,status:FranchiseeCase['status']='Submitted'):FranchiseeCase=>({id:`APP-${Date.now().toString().slice(-6)}`,customerId:customer?.id||'',customer:customer?.name||'Customer to be selected',product,amount,status,assignedTeam:status==='Draft'?'Franchise':'HO Operations',updated:'Just now',documents:[{name:'PAN / KYC',status:customer?.kyc==='Verified'?'Verified':'Pending'},{name:'Bank proof',status:'Pending'},{name:'Product form',status:'Received'}],timeline:[{id:crypto.randomUUID(),title:status==='Draft'?'Draft saved':'Application submitted',detail:status==='Draft'?'Not yet sent to Head Office.':'Waiting for HO Operations review.',time:'Just now',actor:'Franchise'}]}),
  createTicket:(category:string,subject:string,description:string,assignedDesk:string):FranchiseeTicket=>({id:`TKT-${4300+Math.floor(Math.random()*100)}`,category,subject,status:'New',priority:'Normal',assignedDesk,created:'03 Sep 2026',sla:'SLA starts after HO acknowledgement',lastResponse:'Awaiting first response',messages:[{id:crypto.randomUUID(),title:'Request routed',detail:description,time:'Just now',actor:`Franchise → ${assignedDesk}`}]}),
  createRenewalCase:(customer:FranchiseeCustomer,renewal:FranchiseeRenewal):FranchiseeCase=>({id:`REN-APP-${Date.now().toString().slice(-6)}`,customerId:customer.id,customer:customer.name,product:renewal.product,amount:renewal.currentPremium,status:'Submitted',assignedTeam:'HO Operations',updated:'Just now',transactionType:'Renewal',originalReference:renewal.policyNumber,documents:[{name:'Existing policy copy',status:'Received'},{name:'Customer PAN / KYC',status:customer.kyc==='Verified'?'Verified':'Pending'},{name:'Renewal declaration',status:'Pending'}],timeline:[{id:crypto.randomUUID(),title:'Renewal case created',detail:`Renewal linked to ${renewal.policyNumber} and submitted to Head Office Operations.`,time:'Just now',actor:'Franchise → HO Operations'}]}),
  convertLead:(lead:FranchiseeLead,existingCustomer?:FranchiseeCustomer):{lead:FranchiseeLead;customer:FranchiseeCustomer;application:FranchiseeCase;customerCreated:boolean}=>{
    if(lead.stage!=='Quote Raised'||!crmStageService.hasValidQuote(lead))throw new Error('A lead can be converted only from Quote Raised after valid quote or proposal details are recorded.')
    const customer=existingCustomer||franchiseeWorkspaceService.createCustomer({name:lead.name,mobile:lead.mobile,email:lead.email,city:'Ahmedabad'})
    const application={...franchiseeWorkspaceService.createCase(customer,lead.product,lead.expectedValue,'Submitted'),sourceLeadId:lead.id,sourceInquiryId:lead.inquiryId}
    const changedAt=new Date().toISOString()
    const conversionEvent={id:crypto.randomUUID(),title:'Lead converted and marked Won',detail:`Application ${application.id} created and sent to HO Operations.`,time:'Just now',actor:'Franchise'}

    return {lead:{...lead,stage:'Won',customerId:customer.id,convertedApplicationId:application.id,updatedAt:changedAt,stageHistory:[{id:crypto.randomUUID(),from:lead.stage,to:'Won',changedAt,changedBy:'Franchise',reason:'Converted to customer application',relatedActivityId:conversionEvent.id},...(lead.stageHistory||[])],timeline:[conversionEvent,...lead.timeline]},customer,application,customerCreated:!existingCustomer}
  }
}
