import type { SubFranchisee, SubFranchiseeDraft, SubFranchiseeStatus } from '../subFranchiseeTypes'

const STORAGE_KEY='troth-sub-franchisees-v1'
export const authenticatedFranchisee={id:'FR-0418',name:'Troth Meridian Financial Services',code:'FR-GJ-0418',territory:'Ahmedabad, Gujarat',headOfficeId:'HO-TROTH-001'} as const

const seed:SubFranchisee[]=[
  {id:'SF-1001',parentFranchiseeId:'FR-0418',headOfficeId:'HO-TROTH-001',code:'SF-GJ-0101',firmName:'Aarohi Financial Services',contactPerson:'Riya Shah',mobile:'+91 98765 41120',email:'riya@aarohifin.in',businessType:'Financial Services',legalEntityType:'Proprietorship',pan:'AVKPS2481D',gstin:'24AVKPS2481D1Z8',registrationNumber:'UDYAM-GJ-01-0081245',yearsInBusiness:5,addressLine:'312, Shivalik Plaza',area:'Satellite',city:'Ahmedabad',district:'Ahmedabad',state:'Gujarat',pinCode:'380015',territory:'Ahmedabad West',dateAdded:'2026-08-18',kycStatus:'Verified',status:'Active',products:['Insurance','Loans','Mutual Fund'],effectiveDate:'2026-09-01',documents:[{id:'D-1',type:'PAN Card',fileName:'aarohi-pan.pdf',size:248321,uploadedAt:'2026-08-18',status:'Verified'},{id:'D-2',type:'Cancelled Cheque',fileName:'aarohi-cheque.pdf',size:320110,uploadedAt:'2026-08-18',status:'Verified'}],invitationStatus:'Accepted',lastInvitationAt:'2026-08-22',businessGenerated:1840000},
  {id:'SF-1002',parentFranchiseeId:'FR-0418',headOfficeId:'HO-TROTH-001',code:'SF-GJ-0102',firmName:'Nivesh Mitra',contactPerson:'Parth Desai',mobile:'+91 98250 77891',email:'parth@niveshmitra.in',businessType:'Advisory',legalEntityType:'Partnership',pan:'AAEFN8842L',gstin:'24AAEFN8842L1Z4',registrationNumber:'REG-AHD-55219',yearsInBusiness:3,addressLine:'8, Commerce House',area:'Navrangpura',city:'Ahmedabad',district:'Ahmedabad',state:'Gujarat',pinCode:'380009',territory:'Ahmedabad Central',dateAdded:'2026-08-29',kycStatus:'KYC Pending',status:'Pending Approval',products:['Insurance','Loans'],effectiveDate:'2026-09-15',documents:[{id:'D-3',type:'PAN Card',fileName:'nivesh-pan.pdf',size:198220,uploadedAt:'2026-08-29',status:'Uploaded'}],invitationStatus:'Sent',lastInvitationAt:'2026-08-29',businessGenerated:0},
  {id:'SF-1003',parentFranchiseeId:'FR-0418',headOfficeId:'HO-TROTH-001',code:'SF-GJ-0103',firmName:'Blueleaf Wealth Desk',contactPerson:'Mehul Trivedi',mobile:'+91 98980 22440',email:'mehul@blueleaf.in',businessType:'Wealth Distribution',legalEntityType:'LLP',pan:'AATFB9021R',gstin:'24AATFB9021R1ZM',registrationNumber:'AAV-7142',yearsInBusiness:7,addressLine:'1104, Westgate',area:'SG Highway',city:'Ahmedabad',district:'Ahmedabad',state:'Gujarat',pinCode:'380054',territory:'Ahmedabad North',dateAdded:'2026-06-11',kycStatus:'Verified',status:'Inactive',products:['Mutual Fund','Insurance'],effectiveDate:'2026-06-20',documents:[],invitationStatus:'Accepted',businessGenerated:725000},
  {id:'SF-1004',parentFranchiseeId:'FR-0418',headOfficeId:'HO-TROTH-001',code:'SF-GJ-0104',firmName:'Shreeji Risk Advisors',contactPerson:'Kavita Patel',mobile:'+91 99090 56112',email:'kavita@shreejirisk.in',businessType:'Insurance Distribution',legalEntityType:'Private Limited',pan:'ABHCS6112K',gstin:'24ABHCS6112K1Z2',registrationNumber:'U66000GJ2025PTC112345',yearsInBusiness:2,addressLine:'45, Riverfront Road',area:'Paldi',city:'Ahmedabad',district:'Ahmedabad',state:'Gujarat',pinCode:'380007',territory:'Ahmedabad South',dateAdded:'2026-09-04',kycStatus:'KYC Pending',status:'Pending Approval',products:['Insurance'],effectiveDate:'2026-09-20',documents:[],invitationStatus:'Not Sent',businessGenerated:0},
]
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null') as SubFranchisee[]||seed}catch{return seed}}
const write=(rows:SubFranchisee[])=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(rows))}catch{/* prototype fallback */}}
const owned=(row:SubFranchisee)=>row.parentFranchiseeId===authenticatedFranchisee.id

export const subFranchiseeService={
  list:()=>read().filter(owned),
  create:(draft:SubFranchiseeDraft,owner:Pick<SubFranchisee,'parentFranchiseeId'|'headOfficeId'>={parentFranchiseeId:authenticatedFranchisee.id,headOfficeId:authenticatedFranchisee.headOfficeId})=>{const rows=read();const next=rows.length+101;const row:SubFranchisee={...draft,id:`SF-${Date.now()}`,parentFranchiseeId:owner.parentFranchiseeId,headOfficeId:owner.headOfficeId,code:`SF-GJ-${String(next).padStart(4,'0')}`,dateAdded:new Date().toISOString().slice(0,10),kycStatus:'KYC Pending',status:'Pending Approval',invitationStatus:'Not Sent',businessGenerated:0};write([row,...rows]);return row},
  update:(id:string,draft:SubFranchiseeDraft)=>{const rows=read();const target=rows.find(row=>row.id===id);if(!target||!owned(target))throw new Error('You do not have access to this Sub-Franchisee.');const updated={...target,...draft,parentFranchiseeId:target.parentFranchiseeId,headOfficeId:target.headOfficeId,id:target.id,code:target.code} as SubFranchisee;write(rows.map(row=>row.id===id?updated:row));return updated},
  setStatus:(id:string,status:SubFranchiseeStatus)=>{const rows=read();const target=rows.find(row=>row.id===id);if(!target||!owned(target))throw new Error('You do not have access to this Sub-Franchisee.');if(target.status==='Pending Approval'||target.status==='Rejected')throw new Error('Head Office approval is required for this status.');write(rows.map(row=>row.id===id?{...row,status}:row))},
  resendInvitation:(id:string)=>{const rows=read();const target=rows.find(row=>row.id===id);if(!target||!owned(target))throw new Error('You do not have access to this Sub-Franchisee.');write(rows.map(row=>row.id===id?{...row,invitationStatus:'Sent' as const,lastInvitationAt:new Date().toISOString().slice(0,10)}:row))}
}
