import { useState } from 'react'
import type { LucideIcon } from 'lucide-react'
import { BellRing, BookOpenText, BriefcaseBusiness, Check, ChevronLeft, ChevronRight, Database, Download, FileCog, FileText, History, ListTree, Plus, RotateCcw, Settings2, ShieldCheck, SlidersHorizontal, Upload, Workflow, X } from 'lucide-react'
import { PageHeader, SearchBox, Select, StatCard } from '../components/UI'
import {
  administrationProducts, initialAuditEntries, initialBusinessSettings, initialDocumentRules, initialMasterValues, initialNotificationRules, initialSlaRules, initialSystemSettings, initialTemplates, initialWorkflowRules, masterGroups, templateCategories, templateChannels,
  type AdminConfigStatus, type AuditEntry, type BusinessSettings, type CommunicationTemplate, type DocumentRule, type MasterDataValue, type NotificationRule, type SlaRule, type SystemSettings,
} from '../data/adminAdministrationData'

interface Props { onToast:(message:string)=>void }
type AdminSection='Master Data'|'Workflow & SLA'|'Templates'|'Notifications'|'Business Settings'|'Document Rules'|'System Settings'|'Audit Trail'|'Data Management'
const sections:{id:AdminSection;description:string;action:string;icon:LucideIcon}[]=[
  {id:'Master Data',description:'Manage regions, statuses, sources, categories and shared reference values.',action:'Manage',icon:ListTree},{id:'Workflow & SLA',description:'Configure ageing, SLA thresholds, escalation and workflow rules.',action:'Configure',icon:Workflow},{id:'Templates',description:'Manage reusable communication and notification templates.',action:'Manage',icon:BookOpenText},{id:'Notifications',description:'Configure system events, recipients and notification channels.',action:'Configure',icon:BellRing},{id:'Business Settings',description:'Manage financial year, targets and reporting defaults.',action:'Configure',icon:BriefcaseBusiness},{id:'Document Rules',description:'Define product-specific document requirements and stages.',action:'Manage',icon:FileCog},{id:'System Settings',description:'Manage platform preferences and naming conventions.',action:'Configure',icon:Settings2},{id:'Audit Trail',description:'Review administrative and configuration changes only.',action:'View History',icon:History},{id:'Data Management',description:'Access prototype import, export and local reset tools.',action:'Manage',icon:Database},
]

export function AdminAdministration({onToast}:Props){
  const [section,setSection]=useState<AdminSection|null>(null)
  const [masters,setMasters]=useState<MasterDataValue[]>(initialMasterValues)
  const [slaRules,setSlaRules]=useState<SlaRule[]>(initialSlaRules)
  const [workflowRules,setWorkflowRules]=useState(initialWorkflowRules)
  const [templates,setTemplates]=useState<CommunicationTemplate[]>(initialTemplates)
  const [notifications,setNotifications]=useState<NotificationRule[]>(initialNotificationRules)
  const [business,setBusiness]=useState<BusinessSettings>(initialBusinessSettings)
  const [documents,setDocuments]=useState<DocumentRule[]>(initialDocumentRules)
  const [system,setSystem]=useState<SystemSettings>(initialSystemSettings)
  const [audit,setAudit]=useState<AuditEntry[]>(initialAuditEntries)
  const [resetOpen,setResetOpen]=useState(false)
  const auditChange=(module:string,action:string,item:string,previousValue:string,newValue:string)=>setAudit(current=>[{id:`AUD-${Date.now()}`,timestamp:'Just now',adminUser:'Aarav Shukla',module,action,item,previousValue,newValue},...current])
  const resetLocal=()=>{setMasters(initialMasterValues);setSlaRules(initialSlaRules);setWorkflowRules(initialWorkflowRules);setTemplates(initialTemplates);setNotifications(initialNotificationRules);setBusiness(initialBusinessSettings);setDocuments(initialDocumentRules);setSystem(initialSystemSettings);setAudit(initialAuditEntries);setResetOpen(false);onToast('Local Administration prototype changes reset')}
  const content=section==='Master Data'?<MasterData values={masters} setValues={setMasters} onAudit={auditChange} onToast={onToast}/>:section==='Workflow & SLA'?<WorkflowSla rules={slaRules} setRules={setSlaRules} workflows={workflowRules} setWorkflows={setWorkflowRules} onAudit={auditChange} onToast={onToast}/>:section==='Templates'?<Templates values={templates} setValues={setTemplates} onAudit={auditChange} onToast={onToast}/>:section==='Notifications'?<Notifications rules={notifications} setRules={setNotifications} onAudit={auditChange} onToast={onToast}/>:section==='Business Settings'?<BusinessSettingsSection value={business} onSave={value=>{setBusiness(value);auditChange('Business Settings','Updated','Business defaults','Previous local settings','Saved local settings');onToast('Business settings saved locally')}}/>:section==='Document Rules'?<DocumentRules rules={documents} setRules={setDocuments} onAudit={auditChange} onToast={onToast}/>:section==='System Settings'?<SystemSettingsSection value={system} onSave={value=>{setSystem(value);auditChange('System Settings','Updated','Platform preferences','Previous local settings','Saved local settings');onToast('System settings saved locally')}}/>:section==='Audit Trail'?<AuditTrail entries={audit}/>:section==='Data Management'?<DataManagement onToast={onToast} onReset={()=>setResetOpen(true)}/>:null
  return <div className="page admin-administration"><PageHeader eyebrow="PLATFORM GOVERNANCE" title="Administration" description="Configure platform rules, master data, workflows, templates and system settings." actions={section?<button className="secondary-btn" onClick={()=>setSection(null)}><ChevronLeft/> Administration Overview</button>:<button className="secondary-btn" onClick={()=>setSection('Audit Trail')}><History/> View Audit Trail</button>}/>
    {!section?<AdministrationOverview masters={masters} slaRules={slaRules} templates={templates} notifications={notifications} onOpen={setSection}/>:<><nav className="admin-section-tabs" aria-label="Administration sections">{sections.map(item=><button key={item.id} className={section===item.id?'active':''} onClick={()=>setSection(item.id)}>{item.id}</button>)}</nav><div className="administration-section-head"><span>{sectionIcon(section)}</span><div><small>ADMINISTRATION</small><h2>{section}</h2><p>{sections.find(item=>item.id===section)?.description}</p></div></div>{content}</>}
    {resetOpen&&<ConfirmReset onClose={()=>setResetOpen(false)} onConfirm={resetLocal}/>}</div>
}

function AdministrationOverview({masters,slaRules,templates,notifications,onOpen}:{masters:MasterDataValue[];slaRules:SlaRule[];templates:CommunicationTemplate[];notifications:NotificationRule[];onOpen:(section:AdminSection)=>void}){return <><section className="administration-summary"><StatCard label="Master Lists" value={masterGroups.length} meta={`${masters.filter(item=>item.status==='Active').length} active values`} tone="navy" icon={<ListTree/>}/><StatCard label="Active SLA Rules" value={slaRules.filter(item=>item.status==='Active').length} meta={`${slaRules.length} configured products`} tone="green" icon={<Workflow/>}/><StatCard label="Templates" value={templates.length} meta={`${templates.filter(item=>item.status==='Under Review').length} under review`} tone="blue" icon={<BookOpenText/>}/><StatCard label="Notification Rules" value={notifications.length} meta={`${notifications.filter(item=>item.enabled).length} enabled`} tone="violet" icon={<BellRing/>}/><StatCard label="Pending Reviews" value={slaRules.filter(item=>item.status==='Under Review').length+templates.filter(item=>item.status==='Under Review').length} meta="Configuration attention" tone="amber" icon={<ShieldCheck/>}/></section><section className="administration-card-grid">{sections.map(item=>{const Icon=item.icon;return <button key={item.id} onClick={()=>onOpen(item.id)}><span><Icon/></span><div><h3>{item.id}</h3><p>{item.description}</p><small>{sectionMeta(item.id,masters,slaRules,templates,notifications)}</small></div><b>{item.action}<ChevronRight/></b></button>})}</section></>}

function MasterData({values,setValues,onAudit,onToast}:{values:MasterDataValue[];setValues:React.Dispatch<React.SetStateAction<MasterDataValue[]>>;onAudit:(m:string,a:string,i:string,p:string,n:string)=>void;onToast:Props['onToast']}){const [selected,setSelected]=useState('Customer Sources'),[search,setSearch]=useState(''),[editing,setEditing]=useState<MasterDataValue|null|undefined>(undefined);const rows=values.filter(item=>item.group===selected&&`${item.name} ${item.code} ${item.description}`.toLowerCase().includes(search.toLowerCase()));const save=(draft:MasterDataValue)=>{if(editing){setValues(current=>current.map(item=>item.id===editing.id?{...draft,id:editing.id,group:selected,area:editing.area}:item));onAudit('Master Data','Updated',draft.name,editing.name,draft.name)}else{setValues(current=>[...current,{...draft,id:`MD-${Date.now()}`,group:selected,area:masterGroups.find(item=>item.group===selected)?.area||'Other'}]);onAudit('Master Data','Added',draft.name,'—',draft.name)}setEditing(undefined);onToast(`Master value ${editing?'updated':'added'} locally`)};return <div className="master-data-layout"><aside className="panel master-category-list">{Array.from(new Set(masterGroups.map(item=>item.area))).map(area=><section key={area}><b>{area}</b>{masterGroups.filter(item=>item.area===area).map(item=><button key={item.group} className={selected===item.group?'active':''} onClick={()=>setSelected(item.group)}><span>{item.group}</span><em>{values.filter(value=>value.group===item.group).length}</em><ChevronRight/></button>)}</section>)}</aside><section className="panel administration-table-panel"><div className="panel-head"><div><b>{selected}</b><small>Shared reference values · configuration UI only</small></div><button onClick={()=>setEditing(null)}><Plus/> Add Value</button></div><div className="administration-toolbar"><SearchBox value={search} onChange={setSearch} placeholder={`Search ${selected.toLowerCase()}`}/></div><AdminTable headers={['Value','Code','Description','Status','Sort Order','Actions']} rows={rows.map(item=>[<b>{item.name}</b>,item.code,item.description,<ConfigStatus status={item.status}/>,item.sortOrder,<div className="config-row-actions"><button onClick={()=>setEditing(item)}>Edit</button><button onClick={()=>{const status=item.status==='Active'?'Inactive':'Active';setValues(current=>current.map(value=>value.id===item.id?{...value,status}:value));onToast(`${item.name} ${status.toLowerCase()}`)}}>{item.status==='Active'?'Deactivate':'Activate'}</button></div>])}/></section>{editing!==undefined&&<MasterForm value={editing} group={selected} onClose={()=>setEditing(undefined)} onSave={save}/>}</div>}

function WorkflowSla({rules,setRules,workflows,setWorkflows,onAudit,onToast}:{rules:SlaRule[];setRules:React.Dispatch<React.SetStateAction<SlaRule[]>>;workflows:typeof initialWorkflowRules;setWorkflows:React.Dispatch<React.SetStateAction<typeof initialWorkflowRules>>;onAudit:(m:string,a:string,i:string,p:string,n:string)=>void;onToast:Props['onToast']}){const [editing,setEditing]=useState<SlaRule|null>(null);return <div className="administration-stack"><section className="panel administration-table-panel"><div className="panel-head"><div><b>SLA Configuration</b><small>Prototype thresholds are not enforced outside Administration.</small></div></div><AdminTable headers={['Product','Standard SLA','Warning','Escalation','Status','Action']} rows={rules.map(rule=>[<b>{rule.product}</b>,`${rule.standardDays} days`,`${rule.warningDays} days`,`${rule.escalationDays} days`,<ConfigStatus status={rule.status}/>,<button className="table-edit" onClick={()=>setEditing(rule)}>Edit</button>])}/></section><section className="panel workflow-rule-panel"><div className="panel-head"><div><b>Workflow Rules</b><small>Local configuration simulation only</small></div></div><div>{workflows.map(rule=><button key={rule.id} onClick={()=>{setWorkflows(current=>current.map(item=>item.id===rule.id?{...item,enabled:!item.enabled}:item));onAudit('Workflow & SLA',rule.enabled?'Disabled':'Enabled',rule.name,String(rule.enabled),String(!rule.enabled));onToast(`${rule.name} ${rule.enabled?'disabled':'enabled'} locally`)}}><span><b>{rule.name}</b><small>{rule.description}</small></span><i className={rule.enabled?'on':''}>{rule.enabled&&<Check/>}</i></button>)}</div></section>{editing&&<SlaForm value={editing} onClose={()=>setEditing(null)} onSave={draft=>{setRules(current=>current.map(item=>item.id===draft.id?draft:item));onAudit('Workflow & SLA','Updated',draft.product,`${editing.standardDays} days`,`${draft.standardDays} days`);setEditing(null);onToast(`${draft.product} SLA updated locally`)}}/>}</div>}

function Templates({values,setValues,onAudit,onToast}:{values:CommunicationTemplate[];setValues:React.Dispatch<React.SetStateAction<CommunicationTemplate[]>>;onAudit:(m:string,a:string,i:string,p:string,n:string)=>void;onToast:Props['onToast']}){const [search,setSearch]=useState(''),[category,setCategory]=useState('All Categories'),[editing,setEditing]=useState<CommunicationTemplate|null|undefined>(undefined);const rows=values.filter(item=>(category==='All Categories'||item.category===category)&&`${item.name} ${item.category} ${item.channel}`.toLowerCase().includes(search.toLowerCase()));const save=(draft:CommunicationTemplate)=>{if(editing)setValues(current=>current.map(item=>item.id===editing.id?{...draft,id:editing.id,updatedAt:'Just now'}:item));else setValues(current=>[{...draft,id:`TPL-${Date.now()}`,updatedAt:'Just now'},...current]);onAudit('Templates',editing?'Updated':'Added',draft.name,editing?.status||'—',draft.status);setEditing(undefined);onToast(`Template ${editing?'updated':'added'} locally`)};return <section className="panel administration-table-panel"><div className="panel-head"><div><b>Communication Templates</b><small>Reusable message metadata; no real delivery.</small></div><button onClick={()=>setEditing(null)}><Plus/> Add Template</button></div><div className="administration-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search templates"/><Select value={category} onChange={setCategory}>{['All Categories',...templateCategories].map(item=><option key={item}>{item}</option>)}</Select></div><AdminTable headers={['Template','Category','Channel','Status','Last Updated','Actions']} rows={rows.map(item=>[<b>{item.name}</b>,item.category,item.channel,<ConfigStatus status={item.status}/>,item.updatedAt,<button className="table-edit" onClick={()=>setEditing(item)}>Edit</button>])}/>{editing!==undefined&&<TemplateForm value={editing} onClose={()=>setEditing(undefined)} onSave={save}/>}</section>}

function Notifications({rules,setRules,onAudit,onToast}:{rules:NotificationRule[];setRules:React.Dispatch<React.SetStateAction<NotificationRule[]>>;onAudit:(m:string,a:string,i:string,p:string,n:string)=>void;onToast:Props['onToast']}){return <section className="panel administration-table-panel"><div className="panel-head"><div><b>Notification Rules</b><small>Configure event intent only; no notifications are sent.</small></div><span>{rules.filter(item=>item.enabled).length} enabled</span></div><AdminTable headers={['Event','Recipients','Channels','Enabled','Priority']} rows={rules.map(rule=>[<b>{rule.event}</b>,<ChipList values={rule.recipients}/>,<ChipList values={rule.channels}/>,<button className={`config-switch ${rule.enabled?'on':''}`} onClick={()=>{setRules(current=>current.map(item=>item.id===rule.id?{...item,enabled:!item.enabled}:item));onAudit('Notifications',rule.enabled?'Disabled':'Enabled',rule.event,String(rule.enabled),String(!rule.enabled));onToast(`${rule.event} notification ${rule.enabled?'disabled':'enabled'} locally`)}}><i>{rule.enabled&&<Check/>}</i><span>{rule.enabled?'Enabled':'Disabled'}</span></button>,<span className={`config-priority priority-${rule.priority.toLowerCase()}`}>{rule.priority}</span>])}/></section>}

function BusinessSettingsSection({value,onSave}:{value:BusinessSettings;onSave:(value:BusinessSettings)=>void}){const [draft,setDraft]=useState(value);const update=(key:keyof BusinessSettings,value:string)=>setDraft(current=>({...current,[key]:value}));return <form className="panel administration-settings-form" onSubmit={event=>{event.preventDefault();onSave(draft)}}><SectionTitle title="Business & reporting defaults" copy="These settings are not connected to reports or target enforcement."/><div className="settings-form-grid"><Field label="Financial Year" value={draft.financialYear} onChange={value=>update('financialYear',value)}/><SelectField label="Default Reporting Period" value={draft.defaultReportingPeriod} values={['Today','This Week','This Month','This Quarter']} onChange={value=>update('defaultReportingPeriod',value)}/><SelectField label="Business Currency" value={draft.currency} values={['INR']} onChange={value=>update('currency',value)}/><SelectField label="Target Cycle" value={draft.targetCycle} values={['Monthly','Quarterly','Annual']} onChange={value=>update('targetCycle',value)}/><Field label="Default Business Unit" value={draft.businessUnit} onChange={value=>update('businessUnit',value)}/><Field label="Monthly Franchisee Target" value={draft.monthlyFranchiseeTarget} onChange={value=>update('monthlyFranchiseeTarget',value)}/><Field label="Monthly Product Target" value={draft.monthlyProductTarget} onChange={value=>update('monthlyProductTarget',value)}/><Field label="RM Target" value={draft.rmTarget} onChange={value=>update('rmTarget',value)}/></div><div className="settings-save"><p><ShieldCheck/> Prototype settings remain isolated from live business calculations.</p><button className="primary-btn">Save Business Settings</button></div></form>}

function DocumentRules({rules,setRules,onAudit,onToast}:{rules:DocumentRule[];setRules:React.Dispatch<React.SetStateAction<DocumentRule[]>>;onAudit:(m:string,a:string,i:string,p:string,n:string)=>void;onToast:Props['onToast']}){const [product,setProduct]=useState('Insurance'),[editing,setEditing]=useState<DocumentRule|null|undefined>(undefined);const rows=rules.filter(item=>item.product===product);const save=(draft:DocumentRule)=>{if(editing)setRules(current=>current.map(item=>item.id===editing.id?{...draft,id:editing.id}:item));else setRules(current=>[{...draft,id:`DR-${Date.now()}`},...current]);onAudit('Document Rules',editing?'Updated':'Added',draft.document,editing?.product||'—',draft.product);setProduct(draft.product);setEditing(undefined);onToast(`Document rule ${editing?'updated':'added'} locally`)};return <section className="panel administration-table-panel"><div className="panel-head"><div><b>Document Requirements</b><small>Rules are not connected to upload validation.</small></div><button onClick={()=>setEditing(null)}><Plus/> Add Document Rule</button></div><div className="document-product-tabs">{administrationProducts.map(item=><button key={item} className={product===item?'active':''} onClick={()=>setProduct(item)}>{item}<span>{rules.filter(rule=>rule.product===item).length}</span></button>)}</div><AdminTable headers={['Document','Required','Stage','Description','Status','Action']} rows={rows.map(rule=>[<b>{rule.document}</b>,rule.required?'Required':'Optional',rule.stage,rule.description,<ConfigStatus status={rule.status}/>,<button className="table-edit" onClick={()=>setEditing(rule)}>Edit</button>])}/>{editing!==undefined&&<DocumentRuleForm value={editing} product={product} onClose={()=>setEditing(undefined)} onSave={save}/>}</section>}

function SystemSettingsSection({value,onSave}:{value:SystemSettings;onSave:(value:SystemSettings)=>void}){const [draft,setDraft]=useState(value);const update=(key:keyof SystemSettings,value:string)=>setDraft(current=>({...current,[key]:value}));return <form className="panel administration-settings-form" onSubmit={event=>{event.preventDefault();onSave(draft)}}><SectionTitle title="General preferences" copy="Platform presentation and prototype naming conventions."/><div className="settings-form-grid"><Field label="Platform Name" value={draft.platformName} onChange={value=>update('platformName',value)}/><SelectField label="Date Format" value={draft.dateFormat} values={['DD MMM YYYY','DD/MM/YYYY','YYYY-MM-DD']} onChange={value=>update('dateFormat',value)}/><SelectField label="Timezone" value={draft.timezone} values={['Asia/Kolkata','UTC']} onChange={value=>update('timezone',value)}/><SelectField label="Currency" value={draft.currency} values={['INR']} onChange={value=>update('currency',value)}/><SelectField label="Language" value={draft.language} values={['English','Hindi','Gujarati']} onChange={value=>update('language',value)}/><SelectField label="Default Page Size" value={draft.pageSize} values={['25','50','100']} onChange={value=>update('pageSize',value)}/></div><SectionTitle title="Display defaults" copy="Formatting preferences for future platform integration."/><div className="settings-form-grid"><SelectField label="Default Report Period" value={draft.reportPeriod} values={['This Week','This Month','This Quarter']} onChange={value=>update('reportPeriod',value)}/><SelectField label="Number Format" value={draft.numberFormat} values={['Indian (12,34,567)','International (1,234,567)']} onChange={value=>update('numberFormat',value)}/><Field label="Currency Format" value={draft.currencyFormat} onChange={value=>update('currencyFormat',value)}/></div><SectionTitle title="ID prefix conventions" copy="Existing record IDs are not rewritten."/><div className="settings-form-grid prefixes"><Field label="Application ID Prefix" value={draft.applicationPrefix} onChange={value=>update('applicationPrefix',value)}/><Field label="Customer ID Prefix" value={draft.customerPrefix} onChange={value=>update('customerPrefix',value)}/><Field label="Franchisee ID Prefix" value={draft.franchiseePrefix} onChange={value=>update('franchiseePrefix',value)}/><Field label="Support Ticket Prefix" value={draft.supportPrefix} onChange={value=>update('supportPrefix',value)}/></div><div className="settings-save"><p><ShieldCheck/> Saving does not alter existing IDs or shared application behavior.</p><button className="primary-btn">Save System Settings</button></div></form>}

function AuditTrail({entries}:{entries:AuditEntry[]}){
  const [search,setSearch]=useState(''),[module,setModule]=useState('All Modules'),[user,setUser]=useState('All Admins'),[date,setDate]=useState('All Dates'),[action,setAction]=useState('All Actions')
  const dates=Array.from(new Set(entries.map(item=>item.timestamp.split(',')[0])))
  const rows=entries.filter(item=>(module==='All Modules'||item.module===module)&&(user==='All Admins'||item.adminUser===user)&&(date==='All Dates'||item.timestamp.startsWith(date))&&(action==='All Actions'||item.action===action)&&`${item.item} ${item.module} ${item.adminUser}`.toLowerCase().includes(search.toLowerCase()))
  return <section className="panel administration-table-panel"><div className="panel-head"><div><b>Administration Audit Trail</b><small>Configuration changes only; business activity is excluded.</small></div><span>{rows.length} entries</span></div><div className="administration-toolbar audit-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search changed item or admin"/><Select value={module} onChange={setModule}>{['All Modules',...Array.from(new Set(entries.map(item=>item.module)))].map(item=><option key={item}>{item}</option>)}</Select><Select value={user} onChange={setUser}>{['All Admins',...Array.from(new Set(entries.map(item=>item.adminUser)))].map(item=><option key={item}>{item}</option>)}</Select><Select value={date} onChange={setDate}>{['All Dates',...dates].map(item=><option key={item}>{item}</option>)}</Select><Select value={action} onChange={setAction}>{['All Actions',...Array.from(new Set(entries.map(item=>item.action)))].map(item=><option key={item}>{item}</option>)}</Select></div><AdminTable headers={['Date & Time','Admin User','Module','Action','Changed Item','Previous Value','New Value']} rows={rows.map(item=>[item.timestamp,<b>{item.adminUser}</b>,item.module,item.action,<b>{item.item}</b>,item.previousValue,item.newValue])}/></section>
}

function DataManagement({onToast,onReset}:{onToast:Props['onToast'];onReset:()=>void}){const cards=[{title:'Export Master Data',copy:'Prepare a prototype export of shared reference values.',icon:Download,action:()=>onToast('Master data export prepared for prototype')},{title:'Import Master Data',copy:'Select a local file to simulate master data import.',icon:Upload,upload:true,action:()=>onToast('Master data import validated for prototype')},{title:'Export Configuration',copy:'Prepare workflow, template and system metadata.',icon:FileText,action:()=>onToast('Configuration export prepared for prototype')},{title:'Reset Prototype Changes',copy:'Restore Administration local state to initial fixtures.',icon:RotateCcw,danger:true,action:onReset}];return <><section className="data-management-grid">{cards.map(item=>{const Icon=item.icon;return <article className={item.danger?'danger':''} key={item.title}><span><Icon/></span><h3>{item.title}</h3><p>{item.copy}</p>{item.upload?<label className="secondary-btn"><Upload/> Select File<input type="file" accept=".csv,.json" onChange={event=>{if(event.target.files?.[0])item.action()}}/></label>:<button className={item.danger?'danger-btn':'secondary-btn'} onClick={item.action}>{item.danger?<RotateCcw/>:<Download/>}{item.title}</button>}<small>Prototype only · no external data is changed</small></article>})}</section><section className="administration-safety-note"><ShieldCheck/><p><b>Local configuration sandbox</b><span>Import, export and reset actions remain isolated to this browser session and do not modify source files or platform behavior.</span></p></section></>}

function MasterForm({value,group,onClose,onSave}:{value:MasterDataValue|null;group:string;onClose:()=>void;onSave:(value:MasterDataValue)=>void}){const [draft,setDraft]=useState<MasterDataValue>(value||{id:'',group,area:'',name:'',code:'',description:'',status:'Active',sortOrder:1});return <ConfigDrawer title={value?'Edit Master Value':'Add Master Value'} subtitle={group} onClose={onClose} onSubmit={()=>onSave(draft)}><Field label="Name *" value={draft.name} required onChange={name=>setDraft(current=>({...current,name}))}/><Field label="Code" value={draft.code} onChange={code=>setDraft(current=>({...current,code}))}/><TextArea label="Description" value={draft.description} onChange={description=>setDraft(current=>({...current,description}))}/><div className="form-row"><SelectField label="Status" value={draft.status} values={['Active','Inactive','Draft']} onChange={status=>setDraft(current=>({...current,status:status as AdminConfigStatus}))}/><Field label="Sort Order" value={String(draft.sortOrder)} type="number" onChange={value=>setDraft(current=>({...current,sortOrder:Number(value)}))}/></div></ConfigDrawer>}
function SlaForm({value,onClose,onSave}:{value:SlaRule;onClose:()=>void;onSave:(value:SlaRule)=>void}){const [draft,setDraft]=useState(value);return <ConfigDrawer title="Edit SLA Rule" subtitle={value.product} onClose={onClose} onSubmit={()=>onSave(draft)}><Field label="Product" value={draft.product} disabled onChange={()=>{}}/><div className="form-row"><Field label="Standard SLA (days)" value={String(draft.standardDays)} type="number" onChange={value=>setDraft(current=>({...current,standardDays:Number(value)}))}/><Field label="Warning (days)" value={String(draft.warningDays)} type="number" onChange={value=>setDraft(current=>({...current,warningDays:Number(value)}))}/></div><Field label="Escalation Threshold (days)" value={String(draft.escalationDays)} type="number" onChange={value=>setDraft(current=>({...current,escalationDays:Number(value)}))}/><SelectField label="Status" value={draft.status} values={['Active','Inactive','Under Review']} onChange={status=>setDraft(current=>({...current,status:status as AdminConfigStatus}))}/></ConfigDrawer>}
function TemplateForm({value,onClose,onSave}:{value:CommunicationTemplate|null;onClose:()=>void;onSave:(value:CommunicationTemplate)=>void}){const [draft,setDraft]=useState<CommunicationTemplate>(value||{id:'',name:'',category:'Welcome',channel:'Email',subject:'',body:'',status:'Draft',updatedAt:'Just now'});return <ConfigDrawer title={value?'Edit Template':'Add Template'} subtitle="Communication metadata" onClose={onClose} onSubmit={()=>onSave(draft)}><Field label="Template Name *" value={draft.name} required onChange={name=>setDraft(current=>({...current,name}))}/><div className="form-row"><SelectField label="Category" value={draft.category} values={templateCategories} onChange={category=>setDraft(current=>({...current,category}))}/><SelectField label="Channel" value={draft.channel} values={templateChannels} onChange={channel=>setDraft(current=>({...current,channel}))}/></div>{draft.channel==='Email'&&<Field label="Subject" value={draft.subject} onChange={subject=>setDraft(current=>({...current,subject}))}/>}<TextArea label="Message Body *" value={draft.body} required onChange={body=>setDraft(current=>({...current,body}))}/><div className="template-variables"><b>Available placeholders</b><span>{['{{customer_name}}','{{application_id}}','{{product_name}}','{{franchisee_name}}','{{status}}'].join(' · ')}</span></div><SelectField label="Status" value={draft.status} values={['Active','Inactive','Draft','Under Review']} onChange={status=>setDraft(current=>({...current,status:status as AdminConfigStatus}))}/></ConfigDrawer>}
function DocumentRuleForm({value,product,onClose,onSave}:{value:DocumentRule|null;product:string;onClose:()=>void;onSave:(value:DocumentRule)=>void}){const [draft,setDraft]=useState<DocumentRule>(value||{id:'',product,document:'',required:true,stage:'Application',description:'',status:'Active'});return <ConfigDrawer title={value?'Edit Document Rule':'Add Document Rule'} subtitle="Document requirement metadata" onClose={onClose} onSubmit={()=>onSave(draft)}><SelectField label="Product" value={draft.product} values={administrationProducts} onChange={product=>setDraft(current=>({...current,product}))}/><Field label="Document Type *" value={draft.document} required onChange={document=>setDraft(current=>({...current,document}))}/><div className="form-row"><SelectField label="Requirement" value={draft.required?'Required':'Optional'} values={['Required','Optional']} onChange={value=>setDraft(current=>({...current,required:value==='Required'}))}/><SelectField label="Stage" value={draft.stage} values={['Application','Verification','Approval','Disbursement']} onChange={stage=>setDraft(current=>({...current,stage}))}/></div><TextArea label="Description" value={draft.description} onChange={description=>setDraft(current=>({...current,description}))}/><SelectField label="Status" value={draft.status} values={['Active','Inactive','Draft','Under Review']} onChange={status=>setDraft(current=>({...current,status:status as AdminConfigStatus}))}/></ConfigDrawer>}

function ConfigDrawer({title,subtitle,onClose,onSubmit,children}:{title:string;subtitle:string;onClose:()=>void;onSubmit:()=>void;children:React.ReactNode}){return <><button className="drawer-scrim" onClick={onClose}/><aside className="form-drawer administration-form-drawer"><div className="drawer-header"><div><span className="eyebrow">ADMINISTRATION</span><h2>{title}</h2><p>{subtitle}</p></div><button className="icon-button" onClick={onClose}><X/></button></div><form onSubmit={event=>{event.preventDefault();onSubmit()}}>{children}<div className="form-actions"><button type="button" className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn">Save Changes</button></div></form></aside></>}
function AdminTable({headers,rows}:{headers:string[];rows:React.ReactNode[][]}){return <div className="administration-table-wrap"><table className="administration-table"><thead><tr>{headers.map(item=><th key={item}>{item}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((cell,cellIndex)=><td key={cellIndex} data-label={headers[cellIndex]}>{cell}</td>)}</tr>)}</tbody></table></div>}
function Field({label,value,onChange,type='text',required=false,disabled=false}:{label:string;value:string;onChange:(value:string)=>void;type?:string;required?:boolean;disabled?:boolean}){return <label>{label}<input type={type} value={value} required={required} disabled={disabled} onChange={event=>onChange(event.target.value)}/></label>}
function SelectField({label,value,values,onChange}:{label:string;value:string;values:readonly string[];onChange:(value:string)=>void}){return <label>{label}<select value={value} onChange={event=>onChange(event.target.value)}>{values.map(item=><option key={item}>{item}</option>)}</select></label>}
function TextArea({label,value,onChange,required=false}:{label:string;value:string;onChange:(value:string)=>void;required?:boolean}){return <label>{label}<textarea value={value} required={required} onChange={event=>onChange(event.target.value)}/></label>}
function SectionTitle({title,copy}:{title:string;copy:string}){return <div className="settings-section-title"><span><SlidersHorizontal/></span><div><h3>{title}</h3><p>{copy}</p></div></div>}
function ConfigStatus({status}:{status:AdminConfigStatus}){return <span className={`config-status config-status-${status.toLowerCase().replaceAll(' ','-')}`}><i/>{status}</span>}
function ChipList({values}:{values:string[]}){return <span className="config-chip-list">{values.slice(0,2).map(item=><i key={item}>{item}</i>)}{values.length>2&&<em>+{values.length-2}</em>}</span>}
function ConfirmReset({onClose,onConfirm}:{onClose:()=>void;onConfirm:()=>void}){return <div className="modal-wrap"><button className="modal-scrim" onClick={onClose}/><div className="modal administration-reset-modal"><span className="reset-modal-icon"><RotateCcw/></span><h2>Reset local prototype changes?</h2><p>This restores only Administration fixtures in the current session. It does not change source files or other platform modules.</p><div className="form-actions"><button className="secondary-btn" onClick={onClose}>Cancel</button><button className="danger-btn" onClick={onConfirm}>Reset Local Changes</button></div></div></div>}
function sectionIcon(section:AdminSection){const Icon=sections.find(item=>item.id===section)?.icon||Settings2;return <Icon/>}
function sectionMeta(section:AdminSection,masters:MasterDataValue[],sla:SlaRule[],templates:CommunicationTemplate[],notifications:NotificationRule[]){if(section==='Master Data')return `${masterGroups.length} lists · ${masters.length} values`;if(section==='Workflow & SLA')return `${sla.filter(item=>item.status==='Active').length} active SLA rules`;if(section==='Templates')return `${templates.length} communication templates`;if(section==='Notifications')return `${notifications.filter(item=>item.enabled).length} of ${notifications.length} enabled`;if(section==='Audit Trail')return 'Configuration history';return 'Local prototype configuration'}
