import { useMemo, useState } from 'react'
import { Activity, AlertTriangle, BarChart3, BookOpen, Building2, Check, ChevronRight, Download, Edit3, Eye, FileText, Layers3, PackageCheck, Plus, Settings2, ShieldCheck, ToggleLeft, Users, X } from 'lucide-react'
import { PageHeader, SearchBox, Select, StatCard } from '../components/UI'
import { formatINR } from '../data/mockData'
import {
  applicationMatchesAdminProduct, availabilityRoles, buildAdminPartners, buildAdminProducts, buildAdminResources, franchiseeChoices, partnerTypes, productCategories,
  type AdminDocument, type AdminPartner, type AdminProduct, type AdminProductStatus, type AdminResource, type AvailabilityRole, type FranchiseeAvailability, type PartnerStatus,
} from '../data/adminProductsPartnersData'
import type { Application } from '../types'
import type { ProductCategory } from '../data/productCatalogue'

interface Props { apps:Application[]; onNavigate:(page:string,filter?:string)=>void; onToast:(message:string)=>void }
type MainTab='Products'|'Partners'|'Performance'|'Resources'
type ProductTab='Overview'|'Configuration'|'Availability'|'Business & Applications'|'Documents'|'Activity'
type PartnerTab='Overview'|'Products'|'Contacts'|'Commercial / Relationship'|'Documents'|'Activity'
const mainTabs:MainTab[]=['Products','Partners','Performance','Resources']
const productTabs:ProductTab[]=['Overview','Configuration','Availability','Business & Applications','Documents','Activity']
const partnerTabs:PartnerTab[]=['Overview','Products','Contacts','Commercial / Relationship','Documents','Activity']
const productStatuses:AdminProductStatus[]=['Active','Inactive','Draft','Under Review','Needs Attention']
const partnerStatuses:PartnerStatus[]=['Active','Inactive','Onboarding','Under Review','Needs Attention']

export function AdminProductsPartners({apps,onNavigate,onToast}:Props){
  const [products,setProducts]=useState<AdminProduct[]>(()=>buildAdminProducts(apps))
  const [partners,setPartners]=useState<AdminPartner[]>(()=>buildAdminPartners(buildAdminProducts(apps),apps))
  const resources=useMemo(()=>buildAdminResources(products,partners),[products,partners])
  const [tab,setTab]=useState<MainTab>('Products')
  const [selectedProductId,setSelectedProductId]=useState<string|null>(null)
  const [selectedPartnerId,setSelectedPartnerId]=useState<string|null>(null)
  const [productForm,setProductForm]=useState<AdminProduct|null|undefined>(undefined)
  const [partnerForm,setPartnerForm]=useState<AdminPartner|null|undefined>(undefined)
  const [attentionOnly,setAttentionOnly]=useState(false)
  const selectedProduct=products.find(product=>product.id===selectedProductId)||null
  const selectedPartner=partners.find(partner=>partner.id===selectedPartnerId)||null
  const activePartners=partners.filter(partner=>partner.status==='Active').length
  const needAttention=products.filter(product=>product.attentionReasons.length).length+partners.filter(partner=>partner.attentionReasons.length).length
  const totalBusiness=products.reduce((sum,product)=>sum+product.businessValue,0)
  const saveProduct=(draft:ProductDraft)=>{
    const providerName=partners.find(partner=>partner.id===draft.providerId)?.name||'Partner assignment pending'
    if(productForm){setProducts(current=>current.map(product=>product.id===productForm.id?{...productFromDraft(draft,product),providerName}:product));onToast(`${draft.name} updated locally`)}
    else {const created={...productFromDraft(draft,blankProduct(products.length)),providerName};setProducts(current=>[created,...current]);setSelectedProductId(created.id);onToast(`${created.name} added to the product catalogue`)}
    setProductForm(undefined)
  }
  const savePartner=(draft:PartnerDraft)=>{
    if(partnerForm){setPartners(current=>current.map(partner=>partner.id===partnerForm.id?partnerFromDraft(draft,partner):partner));onToast(`${draft.name} updated locally`)}
    else {const created=partnerFromDraft(draft,blankPartner(partners.length));setPartners(current=>[created,...current]);setSelectedPartnerId(created.id);onToast(`${created.name} added to the partner directory`)}
    setPartnerForm(undefined)
  }
  const updateProduct=(id:string,patch:Partial<AdminProduct>)=>setProducts(current=>current.map(product=>{if(product.id!==id)return product;const next={...product,...patch};const provider=partners.find(item=>item.id===next.providerId);return {...next,attentionReasons:[...(next.status==='Under Review'||next.status==='Needs Attention'?['Product configuration is under review']:[]),...(next.franchiseeAvailability==='Selected'&&!next.selectedFranchisees.length?['No franchisees are selected']:[]),...(provider&&provider.status!=='Active'?['Provider relationship requires attention']:[])],updatedAt:'Just now',activity:[{id:`PA-${Date.now()}`,title:'Product configuration updated',detail:'Changes saved locally by Admin',timestamp:'Just now'},...product.activity]}}))
  const updatePartner=(id:string,patch:Partial<AdminPartner>)=>setPartners(current=>current.map(partner=>{if(partner.id!==id)return partner;const next={...partner,...patch};return {...next,attentionReasons:['Inactive','Onboarding','Under Review','Needs Attention'].includes(next.status)?[next.status==='Inactive'?'Provider relationship is inactive':next.status==='Onboarding'?'Partner onboarding is pending':'Commercial agreement review is due']:[],activity:[{id:`PRA-${Date.now()}`,title:'Partner profile updated',detail:'Changes saved locally by Admin',timestamp:'Just now'},...partner.activity]}}))
  const showAttention=()=>{setAttentionOnly(true);setTab(products.some(product=>product.attentionReasons.length)?'Products':'Partners')}
  return <div className="page admin-products-partners">
    <PageHeader eyebrow="CATALOGUE & ECOSYSTEM" title="Products & Partners" description="Manage product catalogue, provider relationships, availability and business performance." actions={<><button className="secondary-btn" onClick={()=>onToast('Products and partners export prepared')}><Download/> Export</button><button className="secondary-btn" onClick={()=>setPartnerForm(null)}><Plus/> Add Partner</button><button className="primary-btn" onClick={()=>setProductForm(null)}><Plus/> Add Product</button></>}/>
    <section className="product-admin-summary">
      <StatCard label="Active Products" value={products.filter(product=>product.status==='Active').length} meta="Available in the catalogue" tone="green" icon={<PackageCheck/>} onClick={()=>{setTab('Products');setAttentionOnly(false)}}/>
      <StatCard label="Active Partners" value={activePartners} meta="Provider relationships" tone="blue" icon={<Building2/>} onClick={()=>{setTab('Partners');setAttentionOnly(false)}}/>
      <StatCard label="Need Attention" value={needAttention} meta="Products and relationships" tone="amber" icon={<AlertTriangle/>} onClick={showAttention}/>
      <StatCard label="Application Volume" value={apps.length} meta="Current application dataset" tone="navy" icon={<Layers3/>}/>
      <StatCard label="Product Business" value={formatINR(totalBusiness,true)} meta="Derived from applications" tone="violet" icon={<BarChart3/>}/>
    </section>
    <nav className="product-admin-tabs" aria-label="Products and partners sections">{mainTabs.map(item=><button key={item} className={tab===item?'active':''} onClick={()=>{setTab(item);setAttentionOnly(false)}}>{item}{item==='Products'&&<span>{products.length}</span>}{item==='Partners'&&<span>{partners.length}</span>}</button>)}</nav>
    {tab==='Products'&&<ProductDirectory products={products} partners={partners} attentionOnly={attentionOnly} setAttentionOnly={setAttentionOnly} onOpen={id=>setSelectedProductId(id)} onEdit={product=>setProductForm(product)} onUpdate={updateProduct}/>} 
    {tab==='Partners'&&<PartnerDirectory partners={partners} products={products} attentionOnly={attentionOnly} setAttentionOnly={setAttentionOnly} onOpen={id=>setSelectedPartnerId(id)} onEdit={partner=>setPartnerForm(partner)} onUpdate={updatePartner}/>} 
    {tab==='Performance'&&<Performance products={products} partners={partners} onProduct={setSelectedProductId} onPartner={setSelectedPartnerId}/>} 
    {tab==='Resources'&&<Resources resources={resources} products={products} partners={partners} onToast={onToast}/>} 
    {selectedProduct&&<ProductDrawer product={selectedProduct} partner={partners.find(item=>item.id===selectedProduct.providerId)} apps={productApps(selectedProduct,apps)} onClose={()=>setSelectedProductId(null)} onEdit={()=>setProductForm(selectedProduct)} onUpdate={patch=>updateProduct(selectedProduct.id,patch)} onNavigate={onNavigate} onToast={onToast}/>} 
    {selectedPartner&&<PartnerDrawer partner={selectedPartner} products={products.filter(product=>product.providerId===selectedPartner.id)} onClose={()=>setSelectedPartnerId(null)} onEdit={()=>setPartnerForm(selectedPartner)} onProduct={id=>{setSelectedPartnerId(null);setSelectedProductId(id)}} onUpdate={patch=>updatePartner(selectedPartner.id,patch)} onToast={onToast}/>} 
    {productForm!==undefined&&<ProductForm product={productForm} partners={partners} onClose={()=>setProductForm(undefined)} onSave={saveProduct}/>} 
    {partnerForm!==undefined&&<PartnerForm partner={partnerForm} onClose={()=>setPartnerForm(undefined)} onSave={savePartner}/>} 
  </div>
}

function ProductDirectory({products,partners,attentionOnly,setAttentionOnly,onOpen,onEdit,onUpdate}:{products:AdminProduct[];partners:AdminPartner[];attentionOnly:boolean;setAttentionOnly:(value:boolean)=>void;onOpen:(id:string)=>void;onEdit:(product:AdminProduct)=>void;onUpdate:(id:string,patch:Partial<AdminProduct>)=>void}){
  const [search,setSearch]=useState(''),[category,setCategory]=useState('All Categories'),[provider,setProvider]=useState('All Partners'),[status,setStatus]=useState('All Statuses'),[availability,setAvailability]=useState('All Availability')
  const rows=useMemo(()=>products.filter(product=>{const q=search.toLowerCase();return (!q||[product.name,product.code,product.providerName,product.category,product.shortDescription].some(value=>value.toLowerCase().includes(q)))&&(category==='All Categories'||product.category===category)&&(provider==='All Partners'||product.providerId===provider)&&(status==='All Statuses'||product.status===status)&&(availability==='All Availability'||availability==='All Franchisees'&&product.franchiseeAvailability==='All'||availability==='Customer Visible'&&product.availableRoles.includes('Customer'))&&(!attentionOnly||product.attentionReasons.length)}),[products,search,category,provider,status,availability,attentionOnly])
  return <section className="panel admin-product-panel"><div className="panel-head"><div><b>Product Directory</b><small>Configure products, providers, availability and customer actions.</small></div><span>{rows.length} of {products.length} products</span></div><div className="product-admin-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search product, code, provider or description"/><div><Select value={category} onChange={setCategory}>{['All Categories',...productCategories].map(item=><option key={item}>{item}</option>)}</Select><Select value={provider} onChange={setProvider}><option>All Partners</option>{partners.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</Select><Select value={status} onChange={setStatus}>{['All Statuses',...productStatuses].map(item=><option key={item}>{item}</option>)}</Select><Select value={availability} onChange={setAvailability}>{['All Availability','All Franchisees','Customer Visible'].map(item=><option key={item}>{item}</option>)}</Select><button className={`attention-filter ${attentionOnly?'active':''}`} onClick={()=>setAttentionOnly(!attentionOnly)}><AlertTriangle/> Needs attention</button></div></div>
    <div className="product-admin-table-wrap"><table className="product-admin-table"><thead><tr><th>Product</th><th>Category</th><th>Provider / Partner</th><th>Applications</th><th>Business</th><th>Available To</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(product=><tr key={product.id} onClick={()=>onOpen(product.id)}><td data-label="Product"><span className="product-admin-icon"><PackageCheck/></span><span><b>{product.name}</b><small>{product.code}</small></span></td><td data-label="Category"><b>{product.category}</b><small>{product.productType}</small></td><td data-label="Provider"><b>{product.providerName}</b><small>{product.sellingFranchisees} selling franchisees</small></td><td data-label="Applications"><b>{product.applicationCount}</b></td><td data-label="Business"><b>{formatINR(product.businessValue,true)}</b></td><td data-label="Available To"><span className="role-summary">{product.availableRoles.slice(0,3).join(' · ')}{product.availableRoles.length>3&&` +${product.availableRoles.length-3}`}</span></td><td data-label="Status"><ProductStatus status={product.status}/>{product.attentionReasons[0]&&<small className="attention-copy">{product.attentionReasons[0]}</small>}</td><td data-label="Actions"><div className="product-row-actions"><button onClick={event=>{event.stopPropagation();onEdit(product)}}><Edit3/></button><button onClick={event=>{event.stopPropagation();onUpdate(product.id,{status:product.status==='Active'?'Inactive':'Active'})}}>{product.status==='Active'?'Deactivate':'Activate'}</button><ChevronRight/></div></td></tr>)}</tbody></table></div>{!rows.length&&<EmptySearch onClear={()=>{setSearch('');setCategory('All Categories');setProvider('All Partners');setStatus('All Statuses');setAvailability('All Availability');setAttentionOnly(false)}}/>}</section>
}

function PartnerDirectory({partners,products,attentionOnly,setAttentionOnly,onOpen,onEdit,onUpdate}:{partners:AdminPartner[];products:AdminProduct[];attentionOnly:boolean;setAttentionOnly:(value:boolean)=>void;onOpen:(id:string)=>void;onEdit:(partner:AdminPartner)=>void;onUpdate:(id:string,patch:Partial<AdminPartner>)=>void}){
  const [search,setSearch]=useState(''),[type,setType]=useState('All Types'),[status,setStatus]=useState('All Statuses'),[category,setCategory]=useState('All Categories')
  const rows=partners.filter(partner=>{const linked=products.filter(product=>product.providerId===partner.id);const q=search.toLowerCase();return (!q||[partner.name,partner.legalName,partner.primaryContact.name,partner.type].some(value=>value.toLowerCase().includes(q)))&&(type==='All Types'||partner.type===type)&&(status==='All Statuses'||partner.status===status)&&(category==='All Categories'||linked.some(product=>product.category===category))&&(!attentionOnly||partner.attentionReasons.length)})
  return <section className="panel admin-product-panel"><div className="panel-head"><div><b>Partner Directory</b><small>Manage provider relationships, contacts and linked products.</small></div><span>{rows.length} of {partners.length} partners</span></div><div className="product-admin-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search partner, contact or type"/><div><Select value={type} onChange={setType}>{['All Types',...partnerTypes].map(item=><option key={item}>{item}</option>)}</Select><Select value={status} onChange={setStatus}>{['All Statuses',...partnerStatuses].map(item=><option key={item}>{item}</option>)}</Select><Select value={category} onChange={setCategory}>{['All Categories',...productCategories].map(item=><option key={item}>{item}</option>)}</Select><button className={`attention-filter ${attentionOnly?'active':''}`} onClick={()=>setAttentionOnly(!attentionOnly)}><AlertTriangle/> Needs attention</button></div></div><div className="product-admin-table-wrap"><table className="product-admin-table partner-admin-table"><thead><tr><th>Partner</th><th>Type</th><th>Products</th><th>Applications</th><th>Business</th><th>Primary Contact</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(partner=>{const linked=products.filter(product=>product.providerId===partner.id);return <tr key={partner.id} onClick={()=>onOpen(partner.id)}><td data-label="Partner"><span className="product-admin-icon partner"><Building2/></span><span><b>{partner.name}</b><small>{partner.id} · Since {partner.since}</small></span></td><td data-label="Type"><b>{partner.type}</b></td><td data-label="Products"><b>{linked.length}</b><small>{linked.filter(product=>product.status==='Active').length} active</small></td><td data-label="Applications"><b>{partner.applicationCount}</b></td><td data-label="Business"><b>{formatINR(partner.businessValue,true)}</b></td><td data-label="Primary Contact"><b>{partner.primaryContact.name}</b><small>{partner.primaryContact.designation}</small></td><td data-label="Status"><PartnerStatusBadge status={partner.status}/>{partner.attentionReasons[0]&&<small className="attention-copy">{partner.attentionReasons[0]}</small>}</td><td data-label="Actions"><div className="product-row-actions"><button onClick={event=>{event.stopPropagation();onEdit(partner)}}><Edit3/></button><button onClick={event=>{event.stopPropagation();onUpdate(partner.id,{status:partner.status==='Active'?'Inactive':'Active'})}}>{partner.status==='Active'?'Deactivate':'Activate'}</button><ChevronRight/></div></td></tr>})}</tbody></table></div>{!rows.length&&<EmptySearch onClear={()=>{setSearch('');setType('All Types');setStatus('All Statuses');setCategory('All Categories');setAttentionOnly(false)}}/>}</section>
}

function ProductDrawer({product,partner,apps,onClose,onEdit,onUpdate,onNavigate,onToast}:{product:AdminProduct;partner?:AdminPartner;apps:Application[];onClose:()=>void;onEdit:()=>void;onUpdate:(patch:Partial<AdminProduct>)=>void;onNavigate:Props['onNavigate'];onToast:Props['onToast']}){
  const [tab,setTab]=useState<ProductTab>('Overview')
  const openApp=(id:string)=>{sessionStorage.setItem('troth-open-app',id);onNavigate('applications')}
  return <><button className="drawer-scrim" onClick={onClose}/><aside className="detail-drawer product-360-drawer"><div className="drawer-header"><div><span className="eyebrow">{product.code}</span><h2>{product.name}</h2><p>{product.category} · {product.providerName}</p></div><button className="icon-button" onClick={onClose}><X/></button></div><div className="product-drawer-summary"><ProductStatus status={product.status}/><span>{product.applicationCount} applications</span><span>{formatINR(product.businessValue,true)} business</span><span>{product.sellingFranchisees} selling franchisees</span></div><div className="product-quick-actions"><button onClick={onEdit}><Edit3/> Edit Product</button><button onClick={()=>setTab('Availability')}><Users/> Manage Access</button><button onClick={()=>setTab('Business & Applications')}><Eye/> View Applications</button></div><div className="drawer-tabs admin-product-drawer-tabs">{productTabs.map(item=><button className={tab===item?'active':''} onClick={()=>setTab(item)} key={item}>{item}</button>)}</div><div className="drawer-body product-drawer-body">
    {tab==='Overview'&&<><Detail title="Basic information" items={[["Product name",product.name],["Product code",product.code],["Category / vertical",product.category],["Provider",product.providerName],["Product type",product.productType],["Status",product.status],["Launch date",product.launchDate],["Last updated",product.updatedAt]]}/><section className="detail-section"><h3>Description</h3><p className="product-description">{product.shortDescription}</p><small>{product.description}</small></section><Detail title="Commercial information" items={[["Business value",formatINR(product.businessValue)],["Applications",String(product.applicationCount)],["Selling franchisees",String(product.sellingFranchisees)],["Customer availability",product.availableRoles.includes('Customer')?'Available':'Hidden'],["Inquiry",product.inquiryEnabled?'Enabled':'Disabled'],["Buy / Apply",product.buyEnabled?'Enabled':'Disabled']]}/></>}
    {tab==='Configuration'&&<section className="detail-section"><h3>Product configuration</h3><div className="config-toggle-list">{([['Show Product Details','detailsEnabled'],['Enable Inquiry','inquiryEnabled'],['Enable Buy / Apply','buyEnabled'],['Application Enabled','applicationEnabled'],['Featured Product','featured']] as [string,keyof AdminProduct][]).map(([label,key])=><button key={label} onClick={()=>onUpdate({[key]:!product[key]})}><span><b>{label}</b><small>Frontend configuration simulation</small></span><i className={product[key]?'on':''}>{product[key]?<Check/>:<ToggleLeft/>}</i></button>)}</div><Detail title="Display configuration" items={[["Category",product.category],["Provider",product.providerName],["Product status",product.status],["Display priority",String(product.displayPriority)]]}/></section>}
    {tab==='Availability'&&<section className="detail-section">
      <h3>Role availability</h3>
      <div className="availability-grid">{availabilityRoles.map(role=>{
        const active=product.availableRoles.includes(role)
        return <button key={role} className={active?'active':''} onClick={()=>onUpdate({availableRoles:active?product.availableRoles.filter(item=>item!==role):[...product.availableRoles,role]})}>
          <i>{active&&<Check/>}</i><span><b>{role}</b><small>{role==='RM'?'Sell / manage':'View and access'}</small></span>
        </button>
      })}</div>
      <h3>Franchisee availability</h3>
      <div className="availability-choice"><button className={product.franchiseeAvailability==='All'?'active':''} onClick={()=>onUpdate({franchiseeAvailability:'All'})}>All Franchisees</button><button className={product.franchiseeAvailability==='Selected'?'active':''} onClick={()=>onUpdate({franchiseeAvailability:'Selected'})}>Selected Franchisees</button></div>
      {product.franchiseeAvailability==='Selected'&&<div className="franchisee-check-list">{franchiseeChoices.map(name=>{
        const active=product.selectedFranchisees.includes(name)
        return <label key={name}><input type="checkbox" checked={active} onChange={()=>onUpdate({selectedFranchisees:active?product.selectedFranchisees.filter(item=>item!==name):[...product.selectedFranchisees,name]})}/>{name}</label>
      })}</div>}
      <p className="prototype-note"><ShieldCheck/> These controls simulate availability and do not change permission enforcement elsewhere.</p>
    </section>}
    {tab==='Business & Applications'&&<><section className="product-detail-stats">{[['Applications',product.applicationCount],['Business',formatINR(product.businessValue,true)],['Completed',apps.filter(app=>['Completed','Approved'].includes(app.status)).length],['Pending',apps.filter(app=>!['Completed','Approved','Rejected'].includes(app.status)).length],['Delayed',apps.filter(app=>['Delayed','Escalated'].includes(app.status)).length],['Franchisees',product.sellingFranchisees]].map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</section><section className="detail-section"><h3>Applications</h3><div className="product-app-list">{apps.length?apps.map(app=><button key={app.id} onClick={()=>openApp(app.id)}><span><b>{app.id}</b><small>{app.customer} · {app.franchisee}</small></span><span><b>{formatINR(app.amount,true)}</b><small>{app.status}</small></span><ChevronRight/></button>):<p className="muted-copy">No applications are mapped to this catalogue product.</p>}</div></section></>}
    {tab==='Documents'&&<DocumentList documents={product.documents} onToast={onToast}/>} 
    {tab==='Activity'&&<ActivityList items={product.activity}/>} 
    </div><div className="drawer-actions"><button className="secondary-btn" onClick={onEdit}><Edit3/> Edit Product</button><button className="primary-btn" onClick={()=>onUpdate({status:product.status==='Active'?'Inactive':'Active'})}>{product.status==='Active'?'Deactivate':'Activate'} Product</button></div></aside></>
}

function PartnerDrawer({partner,products,onClose,onEdit,onProduct,onUpdate,onToast}:{partner:AdminPartner;products:AdminProduct[];onClose:()=>void;onEdit:()=>void;onProduct:(id:string)=>void;onUpdate:(patch:Partial<AdminPartner>)=>void;onToast:Props['onToast']}){
  const [tab,setTab]=useState<PartnerTab>('Overview')
  return <><button className="drawer-scrim" onClick={onClose}/><aside className="detail-drawer product-360-drawer"><div className="drawer-header"><div><span className="eyebrow">{partner.id}</span><h2>{partner.name}</h2><p>{partner.type} · Relationship owner: {partner.relationshipOwner}</p></div><button className="icon-button" onClick={onClose}><X/></button></div><div className="product-drawer-summary"><PartnerStatusBadge status={partner.status}/><span>{products.length} products</span><span>{partner.applicationCount} applications</span><span>{formatINR(partner.businessValue,true)} business</span></div><div className="product-quick-actions"><button onClick={onEdit}><Edit3/> Edit Partner</button><button onClick={()=>setTab('Products')}><PackageCheck/> View Products</button><button onClick={()=>onUpdate({status:partner.status==='Active'?'Inactive':'Active'})}><ToggleLeft/> {partner.status==='Active'?'Deactivate':'Activate'}</button></div><div className="drawer-tabs admin-product-drawer-tabs">{partnerTabs.map(item=><button className={tab===item?'active':''} onClick={()=>setTab(item)} key={item}>{item}</button>)}</div><div className="drawer-body product-drawer-body">
    {tab==='Overview'&&<Detail title="Partner information" items={[["Partner name",partner.name],["Registered name",partner.legalName],["Partner type",partner.type],["Website",partner.website],["Primary contact",partner.primaryContact.name],["Email",partner.primaryContact.email],["Phone",partner.primaryContact.mobile],["Relationship owner",partner.relationshipOwner],["Status",partner.status],["Partner since",partner.since]]}/>} 
    {tab==='Products'&&<section className="detail-section"><h3>Linked products</h3><div className="linked-product-list">{products.map(product=><button key={product.id} onClick={()=>onProduct(product.id)}><span><b>{product.name}</b><small>{product.code} · {product.category}</small></span><span><b>{product.applicationCount} applications</b><small>{formatINR(product.businessValue,true)} business</small></span><ProductStatus status={product.status}/><ChevronRight/></button>)}</div></section>}
    {tab==='Contacts'&&<section className="detail-section"><h3>Partner contacts</h3><div className="partner-contact-list">{[partner.primaryContact,...partner.secondaryContacts].map(contact=><article key={contact.email}><span>{initials(contact.name)}</span><p><b>{contact.name}</b><small>{contact.designation} · {contact.function}</small><em>{contact.email} · {contact.mobile}</em></p></article>)}</div></section>}
    {tab==='Commercial / Relationship'&&<Detail title="Commercial & relationship" items={[["Relationship owner",partner.relationshipOwner],["Agreement status",partner.agreementStatus],["Onboarding status",partner.onboardingStatus],["Product categories",partner.categories.join(', ')||'Not assigned'],["Service SLA",partner.serviceSla],["Escalation contact",partner.secondaryContacts[0]?.name||'Not assigned'],["Last review",partner.lastReview],["Next review",partner.nextReview]]}/>} 
    {tab==='Documents'&&<DocumentList documents={partner.documents} onToast={onToast}/>} {tab==='Activity'&&<ActivityList items={partner.activity}/>} 
    </div><div className="drawer-actions"><button className="secondary-btn" onClick={onEdit}><Edit3/> Edit Partner</button><button className="primary-btn" onClick={()=>onUpdate({status:partner.status==='Active'?'Inactive':'Active'})}>{partner.status==='Active'?'Deactivate':'Activate'} Partner</button></div></aside></>
}

function Performance({products,partners,onProduct,onPartner}:{products:AdminProduct[];partners:AdminPartner[];onProduct:(id:string)=>void;onPartner:(id:string)=>void}){
  const productRows=[...products].sort((a,b)=>b.businessValue-a.businessValue),partnerRows=[...partners].sort((a,b)=>b.businessValue-a.businessValue),maxProduct=Math.max(...productRows.map(item=>item.businessValue),1),maxPartner=Math.max(...partnerRows.map(item=>item.businessValue),1)
  return <div className="performance-sections"><section className="panel performance-panel"><div className="panel-head"><div><b>Product Performance</b><small>Ranked using business values derived from applications.</small></div></div><div className="performance-table"><div className="performance-head"><span>Product</span><span>Applications</span><span>Business</span><span>Selling Franchisees</span><span>Contribution</span></div>{productRows.map(product=><button key={product.id} onClick={()=>onProduct(product.id)}><span><b>{product.name}</b><small>{product.providerName}</small></span><b>{product.applicationCount}</b><b>{formatINR(product.businessValue,true)}</b><b>{product.sellingFranchisees}</b><span className="contribution"><i style={{width:`${product.businessValue/maxProduct*100}%`}}/></span></button>)}</div></section><section className="panel performance-panel"><div className="panel-head"><div><b>Partner Performance</b><small>Product and application coverage by provider.</small></div></div><div className="performance-table"><div className="performance-head"><span>Partner</span><span>Products</span><span>Applications</span><span>Business</span><span>Contribution</span></div>{partnerRows.map(partner=><button key={partner.id} onClick={()=>onPartner(partner.id)}><span><b>{partner.name}</b><small>{partner.type}</small></span><b>{products.filter(product=>product.providerId===partner.id).length}</b><b>{partner.applicationCount}</b><b>{formatINR(partner.businessValue,true)}</b><span className="contribution"><i style={{width:`${partner.businessValue/maxPartner*100}%`}}/></span></button>)}</div></section></div>
}

function Resources({resources,products,partners,onToast}:{resources:AdminResource[];products:AdminProduct[];partners:AdminPartner[];onToast:Props['onToast']}){
  const [search,setSearch]=useState(''),[category,setCategory]=useState('All Categories'),[product,setProduct]=useState('All Products'),[partner,setPartner]=useState('All Partners')
  const rows=resources.filter(resource=>{const q=search.toLowerCase();return (!q||[resource.name,resource.type,resource.productName,resource.partnerName].some(value=>value.toLowerCase().includes(q)))&&(category==='All Categories'||resource.category===category)&&(product==='All Products'||resource.productId===product)&&(partner==='All Partners'||resource.partnerId===partner)})
  return <section className="panel admin-product-panel"><div className="panel-head"><div><b>Product Resources</b><small>Central catalogue, training and partner document library.</small></div><span>{rows.length} resources</span></div><div className="product-admin-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search resources"/><div><Select value={category} onChange={setCategory}>{['All Categories',...Array.from(new Set(resources.map(item=>item.category)))].map(item=><option key={item}>{item}</option>)}</Select><Select value={product} onChange={setProduct}><option>All Products</option>{products.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</Select><Select value={partner} onChange={setPartner}><option>All Partners</option>{partners.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</Select></div></div><div className="product-admin-table-wrap"><table className="product-admin-table resource-table"><thead><tr><th>Resource</th><th>Product</th><th>Partner</th><th>Type</th><th>Version</th><th>Updated</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(resource=><tr key={resource.id}><td data-label="Resource"><b>{resource.name}</b><small>{resource.id}</small></td><td data-label="Product">{resource.productName}</td><td data-label="Partner">{resource.partnerName}</td><td data-label="Type">{resource.type}</td><td data-label="Version">{resource.version}</td><td data-label="Updated">{resource.updated}</td><td data-label="Status"><DocumentStatus status={resource.status}/></td><td data-label="Action"><div className="resource-actions"><button onClick={()=>onToast(`${resource.name} opened`)}>View</button><button onClick={()=>onToast(`${resource.name} download prepared`)}><Download/></button><button onClick={()=>onToast(`Replace metadata opened for ${resource.name}`)}>Replace</button></div></td></tr>)}</tbody></table></div></section>
}

interface ProductDraft { name:string;code:string;shortDescription:string;description:string;category:ProductCategory;productType:string;status:AdminProductStatus;providerId:string;launchDate:string;availableRoles:AvailabilityRole[];franchiseeAvailability:FranchiseeAvailability;selectedFranchisees:string[];detailsEnabled:boolean;inquiryEnabled:boolean;buyEnabled:boolean;applicationEnabled:boolean;featured:boolean;displayPriority:number;documentName:string;documentType:string;documentVersion:string }
function ProductForm({product,partners,onClose,onSave}:{product:AdminProduct|null;partners:AdminPartner[];onClose:()=>void;onSave:(draft:ProductDraft)=>void}){
  const [step,setStep]=useState(1),[error,setError]=useState(''),[draft,setDraft]=useState<ProductDraft>(product?draftProduct(product):{name:'',code:'',shortDescription:'',description:'',category:'Insurance',productType:'Insurance',status:'Draft',providerId:partners[0]?.id||'',launchDate:'2026-09-05',availableRoles:['Admin'],franchiseeAvailability:'All',selectedFranchisees:[],detailsEnabled:true,inquiryEnabled:true,buyEnabled:false,applicationEnabled:true,featured:false,displayPriority:20,documentName:'Product Guide',documentType:'Product Guide',documentVersion:'v1.0'})
  const update=<K extends keyof ProductDraft>(key:K,value:ProductDraft[K])=>setDraft(current=>({...current,[key]:value}))
  const toggleRole=(role:AvailabilityRole)=>update('availableRoles',draft.availableRoles.includes(role)?draft.availableRoles.filter(item=>item!==role):[...draft.availableRoles,role])
  const next=()=>{const message=validateProduct(step,draft);if(message){setError(message);return}setError('');setStep(value=>value+1)}
  const labels=['Basic Details','Provider & Category','Availability','Customer Actions','Documents','Review']
  return <><button className="drawer-scrim" onClick={onClose}/><aside className="form-drawer admin-product-form"><div className="drawer-header"><div><span className="eyebrow">PRODUCT CATALOGUE</span><h2>{product?'Edit Product':'Add Product'}</h2><p>Configure a local Admin catalogue record.</p></div><button className="icon-button" onClick={onClose}><X/></button></div><Stepper labels={labels} step={step}/><form onSubmit={event=>{event.preventDefault();const message=validateProduct(6,draft);if(message)setError(message);else onSave(draft)}}><div className="admin-product-form-body">
    {step===1&&<><h3>Basic details</h3><div className="form-row"><label>Product Name<input value={draft.name} onChange={e=>update('name',e.target.value)}/></label><label>Product Code<input value={draft.code} onChange={e=>update('code',e.target.value)} placeholder="PRD-INS-001"/></label></div><label>Short Description<input value={draft.shortDescription} onChange={e=>update('shortDescription',e.target.value)}/></label><label>Detailed Description<textarea value={draft.description} onChange={e=>update('description',e.target.value)}/></label><div className="form-row"><label>Product Category<select value={draft.category} onChange={e=>update('category',e.target.value as ProductCategory)}>{productCategories.map(item=><option key={item}>{item}</option>)}</select></label><label>Product Type<input value={draft.productType} onChange={e=>update('productType',e.target.value)}/></label></div><label>Status<select value={draft.status} onChange={e=>update('status',e.target.value as AdminProductStatus)}>{['Draft','Active','Inactive'].map(item=><option key={item}>{item}</option>)}</select></label></>}
    {step===2&&<><h3>Provider & category</h3><label>Provider / Partner<select value={draft.providerId} onChange={e=>update('providerId',e.target.value)}><option value="">Select partner</option>{partners.map(item=><option value={item.id} key={item.id}>{item.name} · {item.type}</option>)}</select></label><div className="form-row"><label>Category / Vertical<select value={draft.category} onChange={e=>update('category',e.target.value as ProductCategory)}>{productCategories.map(item=><option key={item}>{item}</option>)}</select></label><label>Sub-category / Type<input value={draft.productType} onChange={e=>update('productType',e.target.value)}/></label></div><label>Launch Date<input type="date" value={draft.launchDate} onChange={e=>update('launchDate',e.target.value)}/></label></>}
    {step===3&&<><h3>Availability</h3><fieldset className="admin-checkbox-grid"><legend>Available to</legend>{availabilityRoles.map(role=><label key={role}><input type="checkbox" checked={draft.availableRoles.includes(role)} onChange={()=>toggleRole(role)}/><span>{role}</span></label>)}</fieldset><fieldset className="admin-radio-row"><legend>Franchisee availability</legend><label><input type="radio" checked={draft.franchiseeAvailability==='All'} onChange={()=>update('franchiseeAvailability','All')}/> All Franchisees</label><label><input type="radio" checked={draft.franchiseeAvailability==='Selected'} onChange={()=>update('franchiseeAvailability','Selected')}/> Selected Franchisees</label></fieldset>{draft.franchiseeAvailability==='Selected'&&<fieldset className="admin-checkbox-grid compact"><legend>Select franchisees</legend>{franchiseeChoices.map(name=><label key={name}><input type="checkbox" checked={draft.selectedFranchisees.includes(name)} onChange={()=>update('selectedFranchisees',draft.selectedFranchisees.includes(name)?draft.selectedFranchisees.filter(item=>item!==name):[...draft.selectedFranchisees,name])}/><span>{name}</span></label>)}</fieldset>}</>}
    {step===4&&<><h3>Customer actions</h3><div className="form-toggle-grid">{([['Show Product Details','detailsEnabled'],['Enable Inquiry','inquiryEnabled'],['Enable Buy / Apply','buyEnabled'],['Application Enabled','applicationEnabled'],['Featured Product','featured']] as [string,keyof ProductDraft][]).map(([label,key])=><label key={label}><input type="checkbox" checked={Boolean(draft[key])} onChange={()=>update(key,!draft[key] as never)}/><span><b>{label}</b><small>Configure the Admin prototype flag</small></span></label>)}</div><label>Display Priority<input type="number" min="1" value={draft.displayPriority} onChange={e=>update('displayPriority',Number(e.target.value))}/></label></>}
    {step===5&&<><h3>Document metadata</h3><p className="admin-form-copy">Add the initial resource metadata. No file is uploaded or stored.</p><label>Document Name<input value={draft.documentName} onChange={e=>update('documentName',e.target.value)}/></label><div className="form-row"><label>Document Type<select value={draft.documentType} onChange={e=>update('documentType',e.target.value)}>{['Product Brochure','Proposal Form','Product Guide','Terms & Conditions','Training Material','Required Documents'].map(item=><option key={item}>{item}</option>)}</select></label><label>Version<input value={draft.documentVersion} onChange={e=>update('documentVersion',e.target.value)}/></label></div></>}
    {step===6&&<><h3>Review product</h3><ReviewGrid items={[["Product",draft.name],["Code",draft.code],["Category",`${draft.category} · ${draft.productType}`],["Provider",partners.find(item=>item.id===draft.providerId)?.name||'Not selected'],["Availability",draft.availableRoles.join(', ')],["Franchisees",draft.franchiseeAvailability],["Customer actions",`${draft.detailsEnabled?'Details · ':''}${draft.inquiryEnabled?'Inquiry · ':''}${draft.buyEnabled?'Buy / Apply':''}`],["Status",draft.status],["Document",`${draft.documentName} · ${draft.documentVersion}`]]}/></>}
    {error&&<p className="admin-form-error"><AlertTriangle/>{error}</p>}</div><FormNav step={step} total={6} onBack={()=>step===1?onClose():setStep(value=>value-1)} onNext={next} submitLabel={product?'Save Changes':'Save Product'}/></form></aside></>
}

interface PartnerDraft { name:string;type:string;legalName:string;contact:string;designation:string;email:string;mobile:string;owner:string;status:PartnerStatus;website:string;categories:string[];notes:string }
function PartnerForm({partner,onClose,onSave}:{partner:AdminPartner|null;onClose:()=>void;onSave:(draft:PartnerDraft)=>void}){
  const [draft,setDraft]=useState<PartnerDraft>(partner?{name:partner.name,type:partner.type,legalName:partner.legalName,contact:partner.primaryContact.name,designation:partner.primaryContact.designation,email:partner.primaryContact.email,mobile:partner.primaryContact.mobile.replaceAll('•','0'),owner:partner.relationshipOwner,status:partner.status,website:partner.website,categories:[...partner.categories],notes:''}:{name:'',type:'Insurance Company',legalName:'',contact:'',designation:'',email:'',mobile:'',owner:'Rohan Mehta',status:'Onboarding',website:'',categories:[],notes:''})
  const update=<K extends keyof PartnerDraft>(key:K,value:PartnerDraft[K])=>setDraft(current=>({...current,[key]:value}))
  return <><button className="drawer-scrim" onClick={onClose}/><aside className="form-drawer admin-partner-form"><div className="drawer-header"><div><span className="eyebrow">PROVIDER RELATIONSHIPS</span><h2>{partner?'Edit Partner':'Add Partner'}</h2><p>Maintain provider and relationship metadata locally.</p></div><button className="icon-button" onClick={onClose}><X/></button></div><form onSubmit={event=>{event.preventDefault();onSave(draft)}}><h3>Partner details</h3><div className="form-row"><label>Partner Name<input required value={draft.name} onChange={e=>update('name',e.target.value)}/></label><label>Partner Type<select value={draft.type} onChange={e=>update('type',e.target.value)}>{partnerTypes.map(item=><option key={item}>{item}</option>)}</select></label></div><label>Legal / Registered Name<input value={draft.legalName} onChange={e=>update('legalName',e.target.value)}/></label><div className="form-row"><label>Status<select value={draft.status} onChange={e=>update('status',e.target.value as PartnerStatus)}>{['Onboarding','Active','Inactive'].map(item=><option key={item}>{item}</option>)}</select></label><label>Website<input value={draft.website} onChange={e=>update('website',e.target.value)}/></label></div><h3>Primary contact</h3><div className="form-row"><label>Name<input required value={draft.contact} onChange={e=>update('contact',e.target.value)}/></label><label>Designation<input value={draft.designation} onChange={e=>update('designation',e.target.value)}/></label></div><div className="form-row"><label>Email<input required type="email" value={draft.email} onChange={e=>update('email',e.target.value)}/></label><label>Mobile<input required value={draft.mobile} onChange={e=>update('mobile',e.target.value)}/></label></div><label>Relationship Owner<input value={draft.owner} onChange={e=>update('owner',e.target.value)}/></label><fieldset className="admin-checkbox-grid compact"><legend>Product categories</legend>{productCategories.map(item=><label key={item}><input type="checkbox" checked={draft.categories.includes(item)} onChange={()=>update('categories',draft.categories.includes(item)?draft.categories.filter(value=>value!==item):[...draft.categories,item])}/><span>{item}</span></label>)}</fieldset><label>Notes<textarea value={draft.notes} onChange={e=>update('notes',e.target.value)}/></label><div className="form-actions"><button type="button" className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn">{partner?'Save Changes':'Save Partner'}</button></div></form></aside></>
}

function Detail({title,items}:{title:string;items:[string,string][]}){return <section className="detail-section"><h3>{title}</h3><div className="detail-grid">{items.map(([label,value])=><div key={label}><span>{label}</span><b>{value||'—'}</b></div>)}</div></section>}
function DocumentList({documents,onToast}:{documents:AdminDocument[];onToast:Props['onToast']}){return <section className="detail-section"><h3>Documents & resources</h3><div className="drawer-document-table">{documents.map(document=><article key={document.id}><span><FileText/></span><p><b>{document.name}</b><small>{document.type} · {document.version} · {document.updated}</small></p><DocumentStatus status={document.status}/><div><button onClick={()=>onToast(`${document.name} opened`)}>View</button><button onClick={()=>onToast(`${document.name} download prepared`)}><Download/></button><button onClick={()=>onToast(`Replace metadata opened for ${document.name}`)}>Replace</button></div></article>)}</div></section>}
function ActivityList({items}:{items:{id:string;title:string;detail:string;timestamp:string}[]}){return <section className="detail-section"><h3>Recent activity</h3><div className="product-activity-list">{items.map(item=><article key={item.id}><time>{item.timestamp}</time><span><Activity/></span><p><b>{item.title}</b><small>{item.detail}</small></p></article>)}</div></section>}
function ProductStatus({status}:{status:AdminProductStatus}){return <span className={`admin-product-status product-status-${status.toLowerCase().replaceAll(' ','-')}`}><i/>{status}</span>}
function PartnerStatusBadge({status}:{status:PartnerStatus}){return <span className={`admin-product-status partner-status-${status.toLowerCase().replaceAll(' ','-')}`}><i/>{status}</span>}
function DocumentStatus({status}:{status:AdminDocument['status']}){return <span className={`resource-status resource-${status.toLowerCase().replaceAll(' ','-')}`}>{status}</span>}
function EmptySearch({onClear}:{onClear:()=>void}){return <div className="product-empty"><PackageCheck/><b>No matching records</b><p>Adjust the search or filters to continue.</p><button onClick={onClear}>Clear filters</button></div>}
function Stepper({labels,step}:{labels:string[];step:number}){return <div className="admin-product-stepper">{labels.map((label,index)=><div key={label} className={step===index+1?'active':step>index+1?'complete':''}><i>{step>index+1?<Check/>:index+1}</i><span>{label}</span></div>)}</div>}
function ReviewGrid({items}:{items:[string,string][]}){return <div className="admin-review-grid">{items.map(([label,value])=><div key={label}><span>{label}</span><b>{value||'—'}</b></div>)}</div>}
function FormNav({step,total,onBack,onNext,submitLabel}:{step:number;total:number;onBack:()=>void;onNext:()=>void;submitLabel:string}){return <div className="form-actions admin-form-nav"><button type="button" className="secondary-btn" onClick={onBack}>{step===1?'Cancel':'Back'}</button>{step<total?<button type="button" className="primary-btn" onClick={onNext}>Continue <ChevronRight/></button>:<button className="primary-btn">{submitLabel}</button>}</div>}
function initials(name:string){return name.split(' ').map(part=>part[0]).join('').slice(0,2).toUpperCase()}
function productApps(product:AdminProduct,apps:Application[]){return apps.filter(app=>applicationMatchesAdminProduct(product,app))}
function displayDate(value:string){if(!value)return '';const [year,month,day]=value.split('-');return new Date(Number(year),Number(month)-1,Number(day)).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}
function validateProduct(step:number,draft:ProductDraft):string{if(step===1&&(!draft.name.trim()||!draft.code.trim()||!draft.category))return 'Product name, code and category are required.';if(step===2&&!draft.providerId)return 'Select a provider or partner.';if(step===3&&(!draft.availableRoles.length||draft.franchiseeAvailability==='Selected'&&!draft.selectedFranchisees.length))return 'Select at least one role and the permitted franchisees.';if(step===5&&(!draft.documentName.trim()||!draft.documentVersion.trim()))return 'Enter the initial document name and version.';if(step===6)return [1,2,3,5].map(value=>validateProduct(value,draft)).find(Boolean)||'';return ''}
function draftProduct(product:AdminProduct):ProductDraft{return {name:product.name,code:product.code,shortDescription:product.shortDescription,description:product.description,category:product.category,productType:product.productType,status:product.status,providerId:product.providerId,launchDate:'',availableRoles:[...product.availableRoles],franchiseeAvailability:product.franchiseeAvailability,selectedFranchisees:[...product.selectedFranchisees],detailsEnabled:product.detailsEnabled,inquiryEnabled:product.inquiryEnabled,buyEnabled:product.buyEnabled,applicationEnabled:product.applicationEnabled,featured:product.featured,displayPriority:product.displayPriority,documentName:product.documents[0]?.name||'Product Guide',documentType:product.documents[0]?.type||'Product Guide',documentVersion:product.documents[0]?.version||'v1.0'} }
function productFromDraft(draft:ProductDraft,base:AdminProduct):AdminProduct{const providerName=(base.providerId===draft.providerId?base.providerName:'');return {...base,name:draft.name,code:draft.code,shortDescription:draft.shortDescription,description:draft.description,category:draft.category,productType:draft.productType,status:draft.status,providerId:draft.providerId,providerName,launchDate:draft.launchDate?displayDate(draft.launchDate):base.launchDate,availableRoles:draft.availableRoles,franchiseeAvailability:draft.franchiseeAvailability,selectedFranchisees:draft.selectedFranchisees,detailsEnabled:draft.detailsEnabled,inquiryEnabled:draft.inquiryEnabled,buyEnabled:draft.buyEnabled,applicationEnabled:draft.applicationEnabled,featured:draft.featured,displayPriority:draft.displayPriority,attentionReasons:draft.status==='Under Review'?['Product configuration is under review']:[],documents:[{id:`DOC-${base.id}-${Date.now()}`,name:draft.documentName,type:draft.documentType,version:draft.documentVersion,updated:'Just now',status:'Current'},...base.documents.slice(1)],updatedAt:'Just now',activity:[{id:`PA-${Date.now()}`,title:'Product profile updated',detail:'Admin catalogue changes saved locally',timestamp:'Just now'},...base.activity]}}
function partnerFromDraft(draft:PartnerDraft,base:AdminPartner):AdminPartner{return {...base,name:draft.name,type:draft.type,legalName:draft.legalName||draft.name,website:draft.website,status:draft.status,primaryContact:{name:draft.contact,designation:draft.designation,email:draft.email,mobile:maskMobile(draft.mobile),function:'Partnerships'},relationshipOwner:draft.owner,categories:draft.categories,attentionReasons:draft.status==='Onboarding'?['Partner onboarding is pending']:[],activity:[{id:`PRA-${Date.now()}`,title:'Partner profile updated',detail:draft.notes||'Admin relationship changes saved locally',timestamp:'Just now'},...base.activity]}}
function blankProduct(index:number):AdminProduct{return {id:`APRD-${String(index+1).padStart(3,'0')}`,code:'',name:'',category:'Insurance',productType:'Insurance',providerId:'',providerName:'',shortDescription:'',description:'',status:'Draft',detailsEnabled:true,inquiryEnabled:true,buyEnabled:false,applicationEnabled:true,featured:false,displayPriority:index+1,availableRoles:['Admin'],franchiseeAvailability:'All',selectedFranchisees:[],applicationCount:0,businessValue:0,sellingFranchisees:0,launchDate:'',updatedAt:'Just now',attentionReasons:[],documents:[],activity:[]}}
function blankPartner(index:number):AdminPartner{return {id:`PRV-${String(index+1).padStart(3,'0')}`,name:'',type:'Other Financial Partner',legalName:'',website:'',status:'Onboarding',primaryContact:{name:'',designation:'',email:'',mobile:'',function:'Partnerships'},secondaryContacts:[],relationshipOwner:'Admin Team',productIds:[],applicationCount:0,businessValue:0,since:'05 Sep 2026',agreementStatus:'Pending',onboardingStatus:'In Progress',serviceSla:'To be agreed',lastReview:'Not reviewed',nextReview:'To be scheduled',categories:[],attentionReasons:['Partner onboarding is pending'],documents:[],activity:[]}}
function maskMobile(value:string){const digits=value.replace(/\D/g,'');return digits.length>=10?`+91 ${digits.slice(-10,-8)}••• ••${digits.slice(-3)}`:value}
