import { useMemo, useState, type ReactNode } from 'react'
import { ArrowLeft, BadgeCheck, BriefcaseBusiness, Check, FileCheck2, Store } from 'lucide-react'
import { franchisees } from '../data/mockData'
import { buildAdminCustomers } from '../data/adminCustomersData'
import { StatusBadge } from '../components/UI'
import { FranchiseesPage, AddFranchiseePage } from './FranchiseesPage'
import { franchiseeWorkspaceService } from '../franchisee/services/franchiseeWorkspaceService'
import { authenticatedFranchisee, subFranchiseeService } from '../franchisee/services/subFranchiseeService'
import { currentFranchiseeId, franchiseeEmployeeRepository, type EmployeeStatus, type FranchiseeEmployee } from '../franchisee/employees'
import { EmployeeCreatePage, EmployeeDirectory } from '../franchisee/pages/EmployeesPage'
import { AgentDirectory, AgentForm } from '../franchisee/pages/AgentsPage'
import { SubFranchiseeCreatePage } from '../franchisee/components/SubFranchiseeCreatePage'
import { assignmentEligibility, assignmentProgress, buildAgentBusinessLines, franchiseeAgentRepository, onboardingStatus, pendingRequirementCount, type AgentRequirement, type FranchiseeAgent } from '../franchisee/agentOnboarding'
import { AdminFranchiseDetail, buildAdminFranchiseScope, type FranchiseSection } from './AdminFranchiseDetail'
import type { Application } from '../types'
import type { FranchiseeCase, FranchiseeCustomer } from '../franchisee/types'

interface Props { route:string; apps:Application[]; onNavigate:(page:string)=>void; onToast:(message:string)=>void }
type EmployeeTab='Overview'|'Work Details'|'Business Lines'|'Customers'|'Documents'|'Access / Permissions'|'Activity'
type AgentTab='Overview'|'Customers'|'Business Lines'|'Compliance'|'Documents'|'Activity'

export function AdminOnboarding({route,apps,onNavigate,onToast}:Props){
  const store=useMemo(()=>franchiseeWorkspaceService.load(),[])
  const [employees,setEmployees]=useState(()=>franchiseeEmployeeRepository.load()),[agents,setAgents]=useState(()=>franchiseeAgentRepository.load(store.products))
  const lines=useMemo(()=>buildAgentBusinessLines(store.products),[store.products])
  const adminCustomers=useMemo(()=>buildAdminCustomers(apps),[apps])
  const franchiseMatch=route.match(/^onboarding\/franchisees\/([^/]+)(?:\/(sub-franchisees|employees|agents|customers|business-lines)(?:\/([^/]+))?)?$/)
  const employeeId=route.match(/^onboarding\/employees\/([^/]+)$/)?.[1],agentId=route.match(/^onboarding\/agents\/([^/]+)$/)?.[1],franchiseId=franchiseMatch?.[1]
  if(route==='onboarding/employees/new')return <div className="admin-onboarding-page"><EmployeeCreatePage employees={employees} customers={store.customers} products={store.products.map(item=>item.name)} contextLabel={authenticatedFranchisee.name} onClose={()=>onNavigate('onboarding/employees')} onSave={draft=>{const created=franchiseeEmployeeRepository.saveNew(draft);setEmployees(items=>[created,...items]);onToast(`${employeeName(created)} added successfully`);onNavigate(`onboarding/employees/${created.id}`)}}/></div>
  if(employeeId){const employee=employees.find(item=>item.id===employeeId);return employee?<EmployeeDetail employee={employee} employees={employees} customers={store.customers} onBack={()=>onNavigate('onboarding/employees')} onStatus={status=>{const updated=franchiseeEmployeeRepository.changeStatus(employee,status);setEmployees(items=>items.map(item=>item.id===updated.id?updated:item));onToast('Employee status updated')}}/>:<Missing label="Employee" onBack={()=>onNavigate('onboarding/employees')}/>}
  if(route==='onboarding/agents/new')return <div className="franchisee-agents"><AgentForm presentation="page" lines={lines} customers={store.customers} products={store.products} onClose={()=>onNavigate('onboarding/agents')} onSave={agent=>{setAgents(items=>[agent,...items]);onToast(`${agent.name} added successfully`);onNavigate(`onboarding/agents/${agent.id}`)}}/></div>
  if(agentId){const agent=agents.find(item=>item.id===agentId);return agent?<AgentDetail agent={agent} customers={store.customers} onBack={()=>onNavigate('onboarding/agents')} onVerify={(lineId,requirement)=>{const updated=franchiseeAgentRepository.updateRequirement(agent.id,lineId,requirement.id,'Verified',store.products,requirement.document);if(updated){setAgents(items=>items.map(item=>item.id===updated.id?updated:item));onToast(`${requirement.name} verified by Admin`)}}}/>:<Missing label="Agent" onBack={()=>onNavigate('onboarding/agents')}/>}
  if(route==='onboarding/franchisees/new')return <AddFranchiseePage onClose={()=>onNavigate('onboarding/franchisees')} onCreate={()=>{onToast('Franchisee added successfully');onNavigate('onboarding/franchisees')}}/>
  if(franchiseId){
    const item=franchisees.find(row=>row.code===decodeURIComponent(franchiseId))
    if(!item)return <Missing label="Franchisee" onBack={()=>onNavigate('onboarding/franchisees')}/>
    const scope=buildAdminFranchiseScope(item,employees,agents,adminCustomers,store),section=(franchiseMatch?.[2]||'sub-franchisees') as FranchiseSection,selectedId=franchiseMatch?.[3]&&decodeURIComponent(franchiseMatch[3]),base=`onboarding/franchisees/${encodeURIComponent(item.code)}`
    if(selectedId==='new'){
      const returnToSection=()=>onNavigate(`${base}/${section}`)
      if(!scope.connected)return <Missing label="Franchisee ownership" onBack={returnToSection}/>
      if(section==='sub-franchisees')return <SubFranchiseeCreatePage products={store.products.filter(product=>product.enabled).map(product=>product.name)} parent={{id:authenticatedFranchisee.id,name:item.name,code:item.code,territory:item.city}} onBack={returnToSection} onSave={draft=>{const created=subFranchiseeService.create(draft,{parentFranchiseeId:authenticatedFranchisee.id,headOfficeId:authenticatedFranchisee.headOfficeId});onToast(`${created.firmName} submitted for Head Office approval`);returnToSection()}}/>
      if(section==='employees')return <div className="admin-onboarding-page franchisee-employees"><EmployeeCreatePage employees={scope.employees} customers={scope.workspaceCustomers} products={store.products.map(product=>product.name)} franchiseeId={currentFranchiseeId} contextLabel={item.name} onClose={returnToSection} onSave={draft=>{const created=franchiseeEmployeeRepository.saveNew({...draft,franchiseeId:currentFranchiseeId,subFranchiseeId:undefined});setEmployees(rows=>[created,...rows]);onToast(`${employeeName(created)} added successfully`);returnToSection()}}/></div>
      if(section==='agents')return <div className="franchisee-agents"><AgentForm presentation="page" lines={lines} customers={scope.workspaceCustomers} products={store.products} franchiseeId={currentFranchiseeId} franchiseeName={item.name} onClose={returnToSection} onSave={agent=>{setAgents(rows=>[agent,...rows]);onToast(`${agent.name} added successfully`);returnToSection()}}/></div>
    }
    if(section==='employees'&&selectedId){
      const employee=scope.employees.find(row=>row.id===selectedId),sub=scope.subFranchisees.find(row=>row.id===employee?.subFranchiseeId)
      return employee?<EmployeeDetail employee={employee} employees={scope.employees} customers={scope.workspaceCustomers} cases={store.cases} parentName={item.name} subFranchiseName={sub?.firmName} onBack={()=>onNavigate(`${base}/employees`)} onStatus={status=>{const updated=franchiseeEmployeeRepository.changeStatus(employee,status);setEmployees(rows=>rows.map(row=>row.id===updated.id?updated:row));onToast('Employee status updated')}} onOpenCustomer={customer=>{const admin=adminCustomers.find(row=>row.email===customer.email||row.mobile===customer.mobile);if(admin)onNavigate(`customers/${encodeURIComponent(admin.id)}/360`);else onToast('This mapped workspace customer has no matching Admin Customer 360 record.')}}/>:<Missing label="Employee" onBack={()=>onNavigate(`${base}/employees`)}/>
    }
    if(section==='agents'&&selectedId){const agent=scope.agents.find(row=>row.id===selectedId),sub=scope.subFranchisees.find(row=>row.id===agent?.subFranchiseeId);return agent?<AgentDetail agent={agent} customers={scope.workspaceCustomers} cases={store.cases} parentName={item.name} subFranchiseName={sub?.firmName} onBack={()=>onNavigate(`${base}/agents`)} onVerify={(lineId,requirement)=>{const updated=franchiseeAgentRepository.updateRequirement(agent.id,lineId,requirement.id,'Verified',store.products,requirement.document);if(updated){setAgents(rows=>rows.map(row=>row.id===updated.id?updated:row));onToast(`${requirement.name} verified by Admin`)}}} onOpenCustomer={customer=>{const admin=adminCustomers.find(row=>row.email===customer.email||row.mobile===customer.mobile);if(admin)onNavigate(`customers/${encodeURIComponent(admin.id)}/360`);else onToast('This mapped workspace customer has no matching Admin Customer 360 record.')}}/>:<Missing label="Agent" onBack={()=>onNavigate(`${base}/agents`)}/>}
    return <AdminFranchiseDetail item={item} scope={scope} store={store} applications={apps} section={section} selectedId={selectedId} onBack={()=>onNavigate('onboarding/franchisees')} onNavigate={onNavigate}/>
  }
  if(route==='onboarding/agents')return <div className="franchisee-agents"><AgentDirectory agents={agents} lines={lines.map(item=>item.name)} eyebrow="ADMIN TEAM" description="View and manage agents across the available partner network." parentFranchise={authenticatedFranchisee.name} onOpen={agent=>onNavigate(`onboarding/agents/${agent.id}`)} onAdd={()=>onNavigate('onboarding/agents/new')}/></div>
  if(route==='onboarding/franchisees')return <FranchiseesPage role="admin" onToast={onToast} onOpenFranchisee={item=>onNavigate(`onboarding/franchisees/${item.code}`)} onAddFranchisee={()=>onNavigate('onboarding/franchisees/new')}/>
  return <div className="franchisee-employees"><EmployeeDirectory employees={employees} eyebrow="ADMIN TEAM" description="View and manage employee records across the available partner network." includeDepartment onOpen={employee=>onNavigate(`onboarding/employees/${employee.id}`)} onAdd={()=>onNavigate('onboarding/employees/new')}/></div>
}


function EmployeeDetail({employee,employees,customers,cases=[],parentName=authenticatedFranchisee.name,subFranchiseName,onBack,onStatus,onOpenCustomer}:{employee:FranchiseeEmployee;employees:FranchiseeEmployee[];customers:FranchiseeCustomer[];cases?:FranchiseeCase[];parentName?:string;subFranchiseName?:string;onBack:()=>void;onStatus:(status:EmployeeStatus)=>void;onOpenCustomer?:(customer:FranchiseeCustomer)=>void}){
  const [tab,setTab]=useState<EmployeeTab>('Overview'),tabs:EmployeeTab[]=['Overview','Work Details','Business Lines','Customers','Documents','Access / Permissions','Activity'],assigned=customers.filter(item=>employee.assignedCustomerIds.includes(item.id)),manager=employees.find(item=>item.id===employee.reportingManagerId)
  return <DetailShell eyebrow={`${employee.employeeId} · EMPLOYEE`} title={employeeName(employee)} subtitle={`${employee.designation} · ${employee.department}`} onBack={onBack} actions={<select value={employee.status} onChange={e=>onStatus(e.target.value as EmployeeStatus)}>{['Active','On Leave','Inactive','Exited'].map(item=><option key={item}>{item}</option>)}</select>}><DetailStats values={[['Status',employee.status],['Customers',String(assigned.length)],['Business Lines',String(employee.assignedProducts.length)],['Documents',String(employee.documents.length)]]}/><Tabs values={tabs} current={tab} set={value=>setTab(value as EmployeeTab)}/>{tab==='Overview'&&<InfoPanel title="Employee Overview" rows={[['Employee ID',employee.employeeId],['Mobile',employee.mobile],['Work Email',employee.email],['Personal Email',employee.personalEmail||'Not recorded'],['Joining Date',date(employee.joiningDate)],['Work Location',employee.workLocation||'Not recorded'],['Parent Franchise',parentName],...(subFranchiseName?[['Sub-Franchise',subFranchiseName] as [string,string]]:[]),['Status',employee.status]]}/>} {tab==='Work Details'&&<InfoPanel title="Work Details" rows={[['Designation',employee.designation],['Role',employee.role],['Department',employee.department],['Employment Type',employee.employmentType],['Reporting Manager',manager?employeeName(manager):'Unassigned'],['Probation End',date(employee.probationEndDate)]]}/>} {tab==='Business Lines'&&<CardList values={employee.assignedProducts} empty="No business lines assigned."/>} {tab==='Customers'&&(onOpenCustomer?<MappedCustomerTable customers={assigned} cases={cases} onOpen={onOpenCustomer}/>:<CardList values={assigned.map(item=>`${item.name} · ${item.id}`)} empty="No customers assigned."/>)} {tab==='Documents'&&<DocumentList values={employee.documents.map(item=>[item.documentType,item.file?.fileName||'No file uploaded',item.status])}/>} {tab==='Access / Permissions'&&<InfoPanel title="Access / Permissions" rows={[['Platform Access',employee.platformAccess?'Enabled':'Not enabled'],['Access Role',employee.platformAccess?employee.role:'No login role'],['Record Ownership',subFranchiseName?`${parentName} / ${subFranchiseName}`:parentName]]}/>} {tab==='Activity'&&<ActivityList values={employee.activity.map(item=>[item.title,item.detail,item.timestamp])}/>}</DetailShell>
}



function AgentDetail({agent,customers,cases=[],parentName=authenticatedFranchisee.name,subFranchiseName,onBack,onVerify,onOpenCustomer}:{agent:FranchiseeAgent;customers:FranchiseeCustomer[];cases?:FranchiseeCase[];parentName?:string;subFranchiseName?:string;onBack:()=>void;onVerify:(lineId:string,requirement:AgentRequirement)=>void;onOpenCustomer?:(customer:FranchiseeCustomer)=>void}){
  const [tab,setTab]=useState<AgentTab>('Overview'),tabs:AgentTab[]=['Overview','Customers','Business Lines','Compliance','Documents','Activity'],assigned=customers.filter(item=>(agent.assignedCustomerIds||[]).includes(item.id)),documents=agent.assignments.flatMap(line=>line.requirements.filter(item=>item.document).map(item=>[item.name,item.document?.fileName||'',item.status] as [string,string,string]))
  return <DetailShell eyebrow={`${agent.agentCode} · AGENT`} title={agent.name} subtitle={`${agent.designation} · ${parentName}`} onBack={onBack}><DetailStats values={[['Status',agentStatus(agent)],['Compliance',complianceStatus(agent)],['Business Lines',String(agent.assignments.length)],['Pending Requirements',String(pendingRequirementCount(agent))]]}/><Tabs values={tabs} current={tab} set={value=>setTab(value as AgentTab)}/>{tab==='Overview'&&<InfoPanel title="Agent Overview" rows={[['Agent ID',agent.agentCode],['Mobile',agent.mobile],['Email',agent.email],['Agent Type',agent.designation],['Parent Franchise',parentName],...(subFranchiseName?[['Sub-Franchise',subFranchiseName] as [string,string]]:[]),['Created',dateTime(agent.createdAt)],['Status',agentStatus(agent)],['Compliance',complianceStatus(agent)]]}/>} {tab==='Customers'&&(onOpenCustomer?<MappedCustomerTable customers={assigned} cases={cases} onOpen={onOpenCustomer}/>:<CardList values={assigned.map(item=>`${item.name} · ${item.id}`)} empty="No customers assigned."/>)} {tab==='Business Lines'&&<div className="onboarding-card-grid">{agent.assignments.map(line=><article key={line.businessLineId}><BriefcaseBusiness/><div><b>{line.businessLine}</b><small>{assignmentProgress(line)}% complete · {assignmentEligibility(line)}</small></div></article>)}</div>} {tab==='Compliance'&&<div className="onboarding-compliance">{agent.assignments.map(line=><section className="panel" key={line.businessLineId}><div className="panel-head"><div><b>{line.businessLine}</b><small>{assignmentProgress(line)}% complete</small></div><StatusBadge status={assignmentEligibility(line)}/></div><AdminTable headers={['Requirement','Type','Status','Document','Admin Action']}>{line.requirements.map(requirement=><tr key={requirement.id}><td><b>{requirement.name}</b><small>{requirement.mandatory?'Mandatory':'Optional'}</small></td><td>{requirement.type}</td><td><StatusBadge status={requirement.status}/></td><td>{requirement.document?.fileName||(requirement.documentRequired?'Required':'Not required')}</td><td>{requirement.status==='Pending HO Verification'?<button className="onboarding-view" onClick={()=>onVerify(line.businessLineId,requirement)}><Check/> Verify</button>:<span>—</span>}</td></tr>)}</AdminTable></section>)}</div>} {tab==='Documents'&&<DocumentList values={documents}/>} {tab==='Activity'&&<ActivityList values={agent.activity.map(item=>[item.title,item.detail,`${item.time} · ${item.actor}`])}/>}</DetailShell>
}


function DetailShell({eyebrow,title,subtitle,onBack,actions,children}:{eyebrow:string;title:string;subtitle:string;onBack:()=>void;actions?:ReactNode;children:ReactNode}){return <div className="page admin-onboarding-page onboarding-detail"><button className="onboarding-back" onClick={onBack}><ArrowLeft/> Back to List</button><header><div><span>{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div>{actions}</header>{children}</div>}
function DetailStats({values}:{values:[string,string][]}){return <section className="onboarding-detail-stats">{values.map(([label,value])=><article key={label}><span>{label}</span><b>{value}</b></article>)}</section>}
function Tabs({values,current,set}:{values:string[];current:string;set:(value:string)=>void}){return <nav className="onboarding-tabs">{values.map(item=><button className={current===item?'active':''} onClick={()=>set(item)} key={item}>{item}</button>)}</nav>}
function InfoPanel({title,rows}:{title:string;rows:[string,string][]}){return <section className="panel onboarding-info"><div className="panel-head"><b>{title}</b></div><div>{rows.map(([label,value])=><article key={label}><span>{label}</span><b>{value||'—'}</b></article>)}</div></section>}
function AdminTable({headers,children}:{headers:string[];children:ReactNode}){return <div className="onboarding-table-wrap"><table className="onboarding-table"><thead><tr>{headers.map(item=><th key={item}>{item}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function MappedCustomerTable({customers,cases,onOpen}:{customers:FranchiseeCustomer[];cases:FranchiseeCase[];onOpen:(customer:FranchiseeCustomer)=>void}){return <section className="panel onboarding-list-panel"><AdminTable headers={['Customer','Contact','Products','Open Cases','KYC','Action']}>{customers.length?customers.map(customer=>{const openCases=cases.filter(record=>record.customerId===customer.id&&!['Completed','Rejected','Approved / Issued'].includes(record.status)).length;return <tr key={customer.id}><td><b>{customer.name}</b><small>{customer.id}</small></td><td><b>{customer.mobile}</b><small>{customer.email}</small></td><td><span className="onboarding-compact"><b>{customer.products.slice(0,2).join(', ')||'None'}</b>{customer.products.length>2&&<small>+{customer.products.length-2} more</small>}</span></td><td>{openCases}</td><td><StatusBadge status={customer.kyc}/></td><td><button className="onboarding-view" onClick={()=>onOpen(customer)}>Open 360</button></td></tr>}):<tr><td colSpan={6}>No customers assigned.</td></tr>}</AdminTable></section>}
function CardList({values,empty}:{values:string[];empty:string}){return <section className="panel onboarding-card-list">{values.length?values.map(value=><article key={value}><Check/><b>{value}</b></article>):<p>{empty}</p>}</section>}
function DocumentList({values}:{values:[string,string,string][]}){return <section className="panel onboarding-documents">{values.length?values.map(([name,file,status],index)=><article key={`${name}-${index}`}><FileCheck2/><div><b>{name}</b><small>{file}</small></div><StatusBadge status={status}/></article>):<p>No documents are recorded.</p>}</section>}
function ActivityList({values}:{values:[string,string,string][]}){return <section className="panel onboarding-activity">{values.map(([title,detail,time],index)=><article key={`${title}-${index}`}><BadgeCheck/><div><b>{title}</b><small>{detail}</small></div><time>{time}</time></article>)}</section>}
function Missing({label,onBack}:{label:string;onBack:()=>void}){return <div className="page onboarding-missing"><Store/><h2>{label} unavailable</h2><p>The requested record is not available in the current Admin data scope.</p><button className="primary-btn" onClick={onBack}><ArrowLeft/> Back to List</button></div>}
function employeeName(item:FranchiseeEmployee){return [item.firstName,item.middleName,item.lastName].filter(Boolean).join(' ')}
function date(value?:string){return value?new Date(`${value}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—'}
function dateTime(value:string){return new Date(value).toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function agentStatus(agent:FranchiseeAgent){return onboardingStatus(agent)==='Eligible / Active'?'Active':'Onboarding'}
function complianceStatus(agent:FranchiseeAgent){const status=onboardingStatus(agent);return status==='Eligible / Active'?'Complete':status==='Pending Verification'?'Verification Required':'Pending'}
