import { useMemo, useState } from 'react'
import { AlertTriangle, ArrowRight, BarChart3, Building2, CalendarDays, CheckCircle2, ChevronDown, Download, FileClock, FilterX, PackageCheck, TrendingDown, TrendingUp, Users, X } from 'lucide-react'
import { PageHeader, Select, StatCard } from '../components/UI'
import { formatAdminBusinessINR } from '../data/adminBusinessData'
import { buildAdminCustomers } from '../data/adminCustomersData'
import { buildAdminPartners, buildAdminProducts } from '../data/adminProductsPartnersData'
import { buildAdminReportView, defaultReportFilters, reportPeriods, type AdminReportView, type FranchiseeReportMetric, type ReportFilters } from '../data/adminReportsData'
import { franchisees } from '../data/mockData'
import type { Application } from '../types'

interface Props { apps:Application[]; onNavigate:(page:string,filter?:string)=>void; onToast:(message:string)=>void }
type ReportTab='Overview'|'Business'|'Applications'|'Franchisees'|'Products & Partners'|'Operations'|'Customers'
const tabs:ReportTab[]=['Overview','Business','Applications','Franchisees','Products & Partners','Operations','Customers']

export function AdminReportsMIS({apps,onNavigate,onToast}:Props){
  const customers=useMemo(()=>buildAdminCustomers(apps),[apps])
  const products=useMemo(()=>buildAdminProducts(apps),[apps])
  const partners=useMemo(()=>buildAdminPartners(products,apps),[products,apps])
  const [filters,setFilters]=useState<ReportFilters>(defaultReportFilters)
  const [tab,setTab]=useState<ReportTab>('Overview')
  const [exportOpen,setExportOpen]=useState(false)
  const view=useMemo(()=>buildAdminReportView(apps,franchisees,customers,products,partners,filters),[apps,customers,products,partners,filters])
  const updateFilter=<K extends keyof ReportFilters>(key:K,value:ReportFilters[K])=>setFilters(current=>({...current,[key]:value}))
  const goApplications=(status?:string)=>{if(status)sessionStorage.setItem('troth-filter',status);onNavigate('applications')}
  return <div className="page admin-reports-mis">
    <PageHeader eyebrow="MANAGEMENT INFORMATION SYSTEM" title="Reports & MIS" description="Analyse business, conversion, franchisee and operational performance across Troth One." actions={<button className="primary-btn" onClick={()=>setExportOpen(true)}><Download/> Export Report</button>}/>
    <ReportFilterBar filters={filters} apps={apps} onChange={updateFilter} onReset={()=>setFilters(defaultReportFilters)}/>
    <ExecutiveKpis view={view}/>
    <nav className="report-primary-tabs" aria-label="Report sections">{tabs.map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</nav>
    {tab==='Overview'&&<Overview view={view} onTab={setTab} onApplications={goApplications} onNavigate={onNavigate}/>} 
    {tab==='Business'&&<BusinessReport view={view} onNavigate={onNavigate}/>} 
    {tab==='Applications'&&<ApplicationsReport view={view} onApplications={goApplications}/>} 
    {tab==='Franchisees'&&<FranchiseeReport rows={view.franchisees} onNavigate={onNavigate}/>} 
    {tab==='Products & Partners'&&<ProductsPartnersReport view={view} productsAttention={products.filter(item=>item.attentionReasons.length).length} partnersAttention={partners.filter(item=>item.attentionReasons.length).length} onNavigate={onNavigate}/>} 
    {tab==='Operations'&&<OperationsReport view={view} onApplications={goApplications}/>} 
    {tab==='Customers'&&<CustomersReport view={view} onNavigate={onNavigate}/>} 
    {exportOpen&&<ExportModal tab={tab} period={filters.period} onClose={()=>setExportOpen(false)} onExport={(scope,format)=>{setExportOpen(false);onToast(`${scope} ${format} report export prepared for prototype.`)}}/>}
  </div>
}

function ReportFilterBar({filters,apps,onChange,onReset}:{filters:ReportFilters;apps:Application[];onChange:<K extends keyof ReportFilters>(key:K,value:ReportFilters[K])=>void;onReset:()=>void}){
  const values=(key:'product'|'franchisee'|'rm'|'provider'|'city')=>Array.from(new Set(apps.map(app=>app[key]))).sort()
  return <section className="report-filter-bar"><div className="report-filter-heading"><div className="report-filter-title"><CalendarDays/><span><b>Report Filters</b><small>Refine analytics across all sections</small></span></div><button className="report-reset" onClick={onReset}><FilterX/> Reset Filters</button></div><div className="report-filter-controls"><Select label="Period" value={filters.period} onChange={value=>onChange('period',value as ReportFilters['period'])}>{reportPeriods.map(item=><option key={item}>{item}</option>)}</Select><Select label="Product" value={filters.product} onChange={value=>onChange('product',value)}>{['All Products',...values('product')].map(item=><option key={item}>{item}</option>)}</Select><Select label="Franchisee" value={filters.franchisee} onChange={value=>onChange('franchisee',value)}>{['All Franchisees',...values('franchisee')].map(item=><option key={item}>{item}</option>)}</Select><Select label="RM" value={filters.rm} onChange={value=>onChange('rm',value)}>{['All RMs',...values('rm')].map(item=><option key={item}>{item}</option>)}</Select><Select label="Partner" value={filters.partner} onChange={value=>onChange('partner',value)}>{['All Partners',...values('provider')].map(item=><option key={item}>{item}</option>)}</Select><Select label="Region / City" value={filters.city} onChange={value=>onChange('city',value)}>{['All Regions / Cities',...values('city')].map(item=><option key={item}>{item}</option>)}</Select><Select label="Status" value={filters.status} onChange={value=>onChange('status',value)}>{['All Statuses',...Array.from(new Set(apps.map(app=>app.status)))].map(item=><option key={item}>{item}</option>)}</Select></div></section>
}

function ExecutiveKpis({view}:{view:AdminReportView}){const summary=view.summary;return <section className="report-kpi-grid"><StatCard label="Total Business" value={formatAdminBusinessINR(summary.businessValue)} meta={`Previous: ${formatAdminBusinessINR(summary.previousBusiness)}`} tone="green" icon={<BarChart3/>}/><StatCard label="Business Growth" value={signed(summary.growthPercent)} meta="Versus equivalent period" tone={summary.growthPercent>=0?'blue':'red'} icon={summary.growthPercent>=0?<TrendingUp/>:<TrendingDown/>}/><StatCard label="Applications" value={summary.applications} meta="Matching current filters" tone="navy" icon={<FileClock/>}/><StatCard label="Conversion Rate" value={`${summary.conversionPercent.toFixed(1)}%`} meta="Approved and completed" tone="violet" icon={<CheckCircle2/>}/><StatCard label="Active Franchisees" value={`${summary.activeFranchisees} / ${summary.totalFranchisees}`} meta="Contributing in scope" tone="blue" icon={<Building2/>}/><StatCard label="SLA Performance" value={`${summary.slaPercent.toFixed(1)}%`} meta="Cases within 10 days" tone="amber" icon={<FileClock/>}/></section>}

function Overview({view,onTab,onApplications,onNavigate}:{view:AdminReportView;onTab:(tab:ReportTab)=>void;onApplications:(status?:string)=>void;onNavigate:Props['onNavigate']}){return <div className="report-overview-grid"><TrendPanel view={view} className="report-span-2"/><FunnelPanel view={view} onClick={onApplications}/><RankingPanel title="Top Products" subtitle="Business contribution" rows={view.products.slice(0,5).map(item=>({name:item.product,meta:`${item.applications} applications`,value:formatAdminBusinessINR(item.businessValue),percent:item.contributionPercent}))} onClick={()=>onNavigate('products')}/><RankingPanel title="Top Franchisees" subtitle="Highest business contribution" rows={view.franchisees.slice(0,5).map(item=>({name:item.franchiseeName,meta:`${item.city} · ${item.applications} applications`,value:formatAdminBusinessINR(item.businessValue),percent:view.summary.businessValue?item.businessValue/view.summary.businessValue*100:0}))} onClick={()=>onNavigate('franchisees')}/><AgeingPanel view={view} onClick={()=>onTab('Applications')}/><AttentionPanel view={view} onTab={onTab} onApplications={onApplications}/></div>}

function BusinessReport({view,onNavigate}:{view:AdminReportView;onNavigate:Props['onNavigate']}){return <div className="report-section-stack"><TrendPanel view={view}/><ReportTable title="Business by Product" subtitle="Sorted by contribution" headers={['Product','Business','Contribution','Applications','Conversion','Growth']} rows={view.products.map(item=>[item.product,formatAdminBusinessINR(item.businessValue),<Contribution value={item.contributionPercent}/>,item.applications,`${item.conversionPercent.toFixed(1)}%`,<Growth value={item.growthPercent}/>])} onRow={()=>onNavigate('products')}/><FranchiseeReport rows={view.franchisees} onNavigate={onNavigate}/><ReportTable title="Business by Partner" subtitle="Provider contribution from mapped applications" headers={['Partner','Products','Applications','Business','Conversion','Delayed']} rows={view.partners.map(item=>[item.partner,item.products,item.applications,formatAdminBusinessINR(item.businessValue),`${item.conversionPercent.toFixed(1)}%`,item.delayedCases])} onRow={()=>onNavigate('products')}/></div>}

function ApplicationsReport({view,onApplications}:{view:AdminReportView;onApplications:(status?:string)=>void}){const exceptionRows=view.filteredApps.filter(app=>['Delayed','Escalated','Action Required'].includes(app.status));return <div className="report-section-stack"><div className="report-two-col"><FunnelPanel view={view} onClick={onApplications}/><AgeingPanel view={view} onClick={()=>onApplications()}/></div><section className="report-mini-kpis">{[['Average TAT',`${average(view.filteredApps.map(app=>app.ageing)).toFixed(1)} days`],['Within SLA',`${view.summary.slaPercent.toFixed(1)}%`],['Outside SLA',`${(100-view.summary.slaPercent).toFixed(1)}%`],['Oldest Open',`${view.oldestOpen} days`],['Delayed',view.filteredApps.filter(app=>app.status==='Delayed').length],['Escalated',view.filteredApps.filter(app=>app.status==='Escalated').length]].map(([label,value])=><button key={label} onClick={()=>typeof label==='string'&&['Delayed','Escalated'].includes(label)?onApplications(label):onApplications()}><span>{label}</span><b>{value}</b></button>)}</section><ReportTable title="Delayed, Escalated & Action Required" subtitle="Applications requiring intervention" headers={['Application','Customer','Product','Franchisee','Owner','Ageing','Status']} rows={exceptionRows.map(app=>[app.id,app.customer,app.productName,app.franchisee,app.assignedTo,`${app.ageing} days`,app.status])} onRow={index=>{const app=exceptionRows[index];if(app){sessionStorage.setItem('troth-open-app',app.id);onApplications()}}}/><ReportTable title="Product-wise Application Performance" subtitle="Volume, completion and delay by product" headers={['Product','Applications','Completed','Pending','Delayed','Conversion','Franchisees']} rows={view.products.map(item=>[item.product,item.applications,item.completed,item.pending,item.delayed,`${item.conversionPercent.toFixed(1)}%`,item.sellingFranchisees])}/></div>}

function FranchiseeReport({rows,onNavigate}:{rows:FranchiseeReportMetric[];onNavigate:Props['onNavigate']}){const [sort,setSort]=useState<'business'|'applications'|'conversion'|'growth'|'delayed'>('business');const sorted=[...rows].sort((a,b)=>sort==='business'?b.businessValue-a.businessValue:sort==='applications'?b.applications-a.applications:sort==='conversion'?b.conversionPercent-a.conversionPercent:sort==='growth'?b.growthPercent-a.growthPercent:b.delayedCases-a.delayedCases);return <section className="panel report-table-panel"><div className="panel-head"><div><b>Franchisee Performance</b><small>Business, conversion, growth and exception ranking</small></div><label className="report-sort">Sort by <select value={sort} onChange={event=>setSort(event.target.value as typeof sort)}><option value="business">Business</option><option value="applications">Applications</option><option value="conversion">Conversion</option><option value="growth">Growth</option><option value="delayed">Delayed Cases</option></select><ChevronDown/></label></div><div className="mis-table-wrap"><table className="mis-table"><thead><tr>{['Franchisee','City / RM','Business','Applications','Customers','Conversion','Growth','Delayed','Status'].map(item=><th key={item}>{item}</th>)}</tr></thead><tbody>{sorted.map(row=><tr key={row.franchiseeName} onClick={()=>onNavigate('franchisees')}><td data-label="Franchisee"><b>{row.franchiseeName}</b></td><td data-label="City / RM"><b>{row.city}</b><small>{row.rm}</small></td><td data-label="Business"><b>{formatAdminBusinessINR(row.businessValue)}</b></td><td data-label="Applications">{row.applications}</td><td data-label="Customers">{row.customers}</td><td data-label="Conversion">{row.conversionPercent.toFixed(1)}%</td><td data-label="Growth"><Growth value={row.growthPercent}/></td><td data-label="Delayed">{row.delayedCases}</td><td data-label="Status"><ReportStatus value={row.status}/></td></tr>)}</tbody></table></div></section>}

function ProductsPartnersReport({view,productsAttention,partnersAttention,onNavigate}:{view:AdminReportView;productsAttention:number;partnersAttention:number;onNavigate:Props['onNavigate']}){return <div className="report-section-stack"><section className="report-attention-summary"><button onClick={()=>onNavigate('products')}><AlertTriangle/><span><b>{productsAttention}</b><small>Products needing attention</small></span><ArrowRight/></button><button onClick={()=>onNavigate('products')}><Building2/><span><b>{partnersAttention}</b><small>Partner agreements needing attention</small></span><ArrowRight/></button></section><ReportTable title="Product Performance" subtitle="Operational performance by product" headers={['Product','Applications','Business','Completed','Pending','Delayed','Conversion','Selling Franchisees']} rows={view.products.map(item=>[item.product,item.applications,formatAdminBusinessINR(item.businessValue),item.completed,item.pending,item.delayed,`${item.conversionPercent.toFixed(1)}%`,item.sellingFranchisees])} onRow={()=>onNavigate('products')}/><ReportTable title="Partner / Provider Performance" subtitle="Mapped product and provider contribution" headers={['Partner','Products','Applications','Business','Conversion','Delayed','Relationship']} rows={view.partners.map(item=>[item.partner,item.products,item.applications,formatAdminBusinessINR(item.businessValue),`${item.conversionPercent.toFixed(1)}%`,item.delayedCases,<ReportStatus value={item.relationshipStatus}/>])} onRow={()=>onNavigate('products')}/></div>}

function OperationsReport({view,onApplications}:{view:AdminReportView;onApplications:(status?:string)=>void}){const op=view.operations;const rows=['Insurance','Loan Protector'].map(product=>{const apps=view.filteredApps.filter(app=>app.product===product);return [product,apps.filter(app=>!['Completed','Rejected'].includes(app.status)).length,apps.filter(app=>app.status==='Completed').length,apps.filter(app=>app.status==='Action Required').length,apps.filter(app=>app.status==='Delayed').length,apps.filter(app=>app.status==='Escalated').length,`${average(apps.map(app=>app.ageing)).toFixed(1)} days`,`${percent(apps.filter(app=>app.ageing<=10).length,apps.length).toFixed(1)}%`]});const assignees=Array.from(group(view.filteredApps.filter(app=>['Insurance','Loan Protector'].includes(app.product)),app=>app.assignedTo),([name,apps])=>[name,apps.length,apps.filter(app=>app.status==='Action Required').length,apps.filter(app=>['Delayed','Escalated'].includes(app.status)).length,`${average(apps.map(app=>app.ageing)).toFixed(1)} days`]);const support=view.support;return <div className="report-section-stack"><section className="report-mini-kpis">{[['Open Workload',op.open],['Completed',op.completed],['Action Required',op.actionRequired],['Delayed',op.delayed],['Escalated',op.escalated],['Average TAT',`${op.averageTat.toFixed(1)} days`],['SLA',`${op.slaPercent.toFixed(1)}%`]].map(([label,value])=><button key={label} onClick={()=>['Action Required','Delayed','Escalated'].includes(String(label))?onApplications(String(label)):onApplications()}><span>{label}</span><b>{value}</b></button>)}</section><ReportTable title="Product Operations" subtitle="Operations scope remains Insurance and Loan Protector" headers={['Product','Open','Completed','Action Required','Delayed','Escalated','Average TAT','SLA']} rows={rows}/><ReportTable title="Assignee Workload" subtitle="Current operational ownership from application records" headers={['Assignee','Cases','Action Required','Delayed / Escalated','Average Ageing']} rows={assignees}/><section className="panel support-performance-panel"><div className="panel-head"><div><b>Support Performance</b><small>Isolated Admin report fixture for prototype service analytics</small></div></div><div>{[['Open Tickets',support.open],['Awaiting Response',support.awaitingResponse],['Resolved',support.resolved],['Overdue',support.overdue],['Average Response',`${support.averageResponseHours} hours`]].map(([label,value])=><article key={label}><span>{label}</span><b>{value}</b></article>)}</div></section></div>}

function CustomersReport({view,onNavigate}:{view:AdminReportView;onNavigate:Props['onNavigate']}){const item=view.customers,growth=percent(item.newCustomers-item.previousNew,item.previousNew);return <div className="report-section-stack"><section className="customer-report-kpis">{[['Total Customers',item.total,'Current Admin directory'],['New Customers',item.newCustomers,`${signed(growth)} vs previous period`],['Active Customers',item.active,'Currently engaged'],['With Active Applications',item.activeApplications,'Open application relationship'],['Need Attention',item.attention,'KYC, follow-up or application']].map(([label,value,meta])=><button key={label} onClick={()=>onNavigate('customers')}><span>{label}</span><b>{value}</b><small>{meta}</small><ArrowRight/></button>)}</section><div className="report-two-col"><CountRanking title="Customers by Franchisee" rows={item.byFranchisee} total={item.total} onClick={()=>onNavigate('customers')}/><CountRanking title="Customers by Product Interest" rows={item.byInterest} total={item.total} onClick={()=>onNavigate('customers')}/></div></div>}

function TrendPanel({view,className='' }:{view:AdminReportView;className?:string}){const max=Math.max(...view.trend.flatMap(item=>[item.value,item.previous]),1);return <section className={`panel report-trend-panel ${className}`}><div className="panel-head"><div><b>Business Performance</b><small>Current period versus equivalent previous period</small></div><span>{signed(view.summary.growthPercent)}</span></div><div className="trend-summary"><div><span>Total Business</span><b>{formatAdminBusinessINR(view.summary.businessValue)}</b></div><div><span>Previous Period</span><b>{formatAdminBusinessINR(view.summary.previousBusiness)}</b></div><div><span>Growth</span><b>{signed(view.summary.growthPercent)}</b></div><div><span>Average / Day</span><b>{formatAdminBusinessINR(view.trend.length?view.summary.businessValue/view.trend.length:0)}</b></div><div><span>Average / Application</span><b>{formatAdminBusinessINR(view.summary.applications?view.summary.businessValue/view.summary.applications:0)}</b></div><div><span>Average / Franchisee</span><b>{formatAdminBusinessINR(view.summary.activeFranchisees?view.summary.businessValue/view.summary.activeFranchisees:0)}</b></div></div><div className="mis-trend-chart">{view.trend.map(point=><div key={point.label} title={`${point.label}: ${formatAdminBusinessINR(point.value)}`}><span><i style={{height:`${point.previous/max*100}%`}}/><b style={{height:`${point.value/max*100}%`}}/></span><small>{point.label}</small></div>)}</div><div className="trend-legend"><span><i className="current"/>Current period</span><span><i/>Previous period</span></div></section>}
function FunnelPanel({view,onClick}:{view:AdminReportView;onClick:(status?:string)=>void}){const max=Math.max(...view.funnel.map(item=>item.count),1);return <section className="panel report-funnel-panel"><div className="panel-head"><div><b>Application Funnel</b><small>Current filtered application stages</small></div></div><div>{view.funnel.map(item=><button key={item.status} onClick={()=>onClick(item.status)}><span>{item.status}</span><i><b style={{width:`${item.count/max*100}%`}}/></i><strong>{item.count}</strong><small>{item.percent.toFixed(1)}%</small></button>)}</div></section>}
function AgeingPanel({view,onClick}:{view:AdminReportView;onClick:()=>void}){return <section className="panel report-ageing-panel"><div className="panel-head"><div><b>Application Ageing & SLA</b><small>{view.summary.slaPercent.toFixed(1)}% within 10-day SLA</small></div></div><div className="ageing-bars">{view.ageing.map(item=><button key={item.label} onClick={onClick}><span><b>{item.label}</b><small>{item.count} cases</small></span><i><b style={{width:`${item.percent}%`}}/></i><strong>{item.percent.toFixed(0)}%</strong></button>)}</div><div className="ageing-footer"><span>Average TAT <b>{average(view.filteredApps.map(app=>app.ageing)).toFixed(1)} days</b></span><span>Oldest Open <b>{view.oldestOpen} days</b></span></div></section>}
function RankingPanel({title,subtitle,rows,onClick}:{title:string;subtitle:string;rows:{name:string;meta:string;value:string;percent:number}[];onClick:()=>void}){return <section className="panel report-ranking"><div className="panel-head"><div><b>{title}</b><small>{subtitle}</small></div></div><div>{rows.map((row,index)=><button key={row.name} onClick={onClick}><em>{index+1}</em><span><b>{row.name}</b><small>{row.meta}</small><i><b style={{width:`${row.percent}%`}}/></i></span><strong>{row.value}</strong><ArrowRight/></button>)}</div></section>}
function AttentionPanel({view,onTab,onApplications}:{view:AdminReportView;onTab:(tab:ReportTab)=>void;onApplications:(status?:string)=>void}){const items=[{label:'Applications delayed',value:view.filteredApps.filter(app=>app.status==='Delayed').length,action:()=>onApplications('Delayed')},{label:'Applications escalated',value:view.filteredApps.filter(app=>app.status==='Escalated').length,action:()=>onApplications('Escalated')},{label:'Franchisees below target',value:view.franchisees.filter(item=>item.status==='Needs Attention').length,action:()=>onTab('Franchisees')},{label:'Support tickets overdue',value:view.support.overdue,action:()=>onTab('Operations')},{label:'Customers needing attention',value:view.customers.attention,action:()=>onTab('Customers')}];return <section className="panel management-attention"><div className="panel-head"><div><b>Management Attention</b><small>Concise exceptions requiring review</small></div></div><div>{items.map(item=><button key={item.label} onClick={item.action}><AlertTriangle/><span>{item.label}</span><b>{item.value}</b><ArrowRight/></button>)}</div></section>}
function ReportTable({title,subtitle,headers,rows,onRow}:{title:string;subtitle:string;headers:string[];rows:(string|number|React.ReactNode)[][];onRow?:(index:number)=>void}){return <section className="panel report-table-panel"><div className="panel-head"><div><b>{title}</b><small>{subtitle}</small></div><span>{rows.length} rows</span></div><div className="mis-table-wrap"><table className="mis-table"><thead><tr>{headers.map(item=><th key={item}>{item}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index} onClick={()=>onRow?.(index)} className={onRow?'clickable':''}>{row.map((cell,cellIndex)=><td data-label={headers[cellIndex]} key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div></section>}
function CountRanking({title,rows,total,onClick}:{title:string;rows:{name:string;count:number}[];total:number;onClick:()=>void}){return <section className="panel count-ranking"><div className="panel-head"><div><b>{title}</b><small>Customer distribution</small></div></div><div>{rows.slice(0,8).map(row=><button key={row.name} onClick={onClick}><span><b>{row.name}</b><small>{row.count} customers</small></span><i><b style={{width:`${percent(row.count,total)}%`}}/></i><strong>{percent(row.count,total).toFixed(0)}%</strong></button>)}</div></section>}
function Contribution({value}:{value:number}){return <span className="table-contribution"><i><b style={{width:`${value}%`}}/></i><small>{value.toFixed(1)}%</small></span>}
function Growth({value}:{value:number}){return <span className={`report-growth ${value>=0?'positive':'negative'}`}>{value>=0?<TrendingUp/>:<TrendingDown/>}{signed(value)}</span>}
function ReportStatus({value}:{value:string}){return <span className={`report-status report-status-${value.toLowerCase().replaceAll(' ','-')}`}><i/>{value}</span>}
function ExportModal({tab,period,onClose,onExport}:{tab:ReportTab;period:string;onClose:()=>void;onExport:(scope:string,format:string)=>void}){const [scope,setScope]=useState('Current Tab'),[format,setFormat]=useState('Excel');return <div className="modal-wrap"><button className="modal-scrim" onClick={onClose}/><form className="modal report-export-modal" onSubmit={event=>{event.preventDefault();onExport(scope,format)}}><div className="modal-heading"><span className="modal-icon"><Download/></span><div><span className="eyebrow">REPORT EXPORT</span><h2>Export Reports & MIS</h2></div><button type="button" className="icon-button" onClick={onClose}><X/></button></div><label>Report Scope<select value={scope} onChange={e=>setScope(e.target.value)}><option>Current Tab</option><option>Full MIS</option></select></label><label>Included View<input readOnly value={scope==='Current Tab'?tab:'All report sections'}/></label><label>Period<input readOnly value={period}/></label><label>Format<select value={format} onChange={e=>setFormat(e.target.value)}><option>Excel</option><option>PDF</option></select></label><p className="export-prototype-note">This prototype prepares export feedback only; no file is generated.</p><div className="form-actions"><button type="button" className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn"><Download/> Prepare Export</button></div></form></div>}
function signed(value:number){return `${value>=0?'+':''}${value.toFixed(1)}%`}
function percent(value:number,total:number){return total?value/total*100:0}
function average(values:number[]){return values.length?values.reduce((sum,value)=>sum+value,0)/values.length:0}
function group<T,K>(rows:T[],key:(row:T)=>K){const map=new Map<K,T[]>();rows.forEach(row=>{const value=key(row);map.set(value,[...(map.get(value)||[]),row])});return map}
