import { useMemo, useState } from 'react'
import { Activity, AlertTriangle, BriefcaseBusiness, CalendarPlus, Check, ChevronRight, Download, Edit3, FileCheck2, Mail, MapPin, Phone, Plus, UserRound, Users, X } from 'lucide-react'
import { PageHeader, SearchBox, Select, StatCard } from '../components/UI'
import { formatINR } from '../data/mockData'
import {
  buildAdminCustomers, customerCategories, customerProducts, customerSources,
  type AdminCustomer, type AdminCustomerStatus, type AdminKycStatus, type CustomerFollowUp, type CustomerType,
} from '../data/adminCustomersData'
import type { Application, ProductType } from '../types'

interface Props { apps:Application[]; onNavigate:(page:string,filter?:string)=>void; onToast:(message:string)=>void }
type CustomerTab='Overview'|'Products'|'Applications'|'Relationship'|'KYC & Docs'|'Activity'
const customerTabs:CustomerTab[]=['Overview','Products','Applications','Relationship','KYC & Docs','Activity']
const statuses:AdminCustomerStatus[]=['Active','New','Follow-up Required','KYC Pending','Inactive']

export function AdminCustomers({apps,onNavigate,onToast}:Props) {
  const [customers,setCustomers]=useState<AdminCustomer[]>(()=>buildAdminCustomers(apps))
  const [selectedId,setSelectedId]=useState<string|null>(null)
  const [formCustomer,setFormCustomer]=useState<AdminCustomer|null|undefined>(undefined)
  const [search,setSearch]=useState('')
  const [statusFilter,setStatusFilter]=useState('All Statuses')
  const [franchiseeFilter,setFranchiseeFilter]=useState('All Franchisees')
  const [rmFilter,setRmFilter]=useState('All RMs')
  const [productFilter,setProductFilter]=useState('All Products')
  const [cityFilter,setCityFilter]=useState('All Cities')
  const [attentionOnly,setAttentionOnly]=useState(false)
  const selected=customers.find(customer=>customer.id===selectedId)||null
  const options=(key:'franchisee'|'rm'|'city')=>Array.from(new Set(customers.map(customer=>customer[key]))).sort()
  const rows=useMemo(()=>customers.filter(customer=>{
    const query=search.trim().toLowerCase()
    const matchesQuery=!query||[customer.name,customer.id,customer.email,customer.mobile,customer.franchisee,customer.rm,customer.city].some(value=>value.toLowerCase().includes(query))
    return matchesQuery&&(statusFilter==='All Statuses'||customer.status===statusFilter)&&(franchiseeFilter==='All Franchisees'||customer.franchisee===franchiseeFilter)&&(rmFilter==='All RMs'||customer.rm===rmFilter)&&(cityFilter==='All Cities'||customer.city===cityFilter)&&(productFilter==='All Products'||customer.productInterests.includes(productFilter as ProductType))&&(!attentionOnly||customer.attentionReasons.length>0)
  }),[customers,search,statusFilter,franchiseeFilter,rmFilter,productFilter,cityFilter,attentionOnly])

  const clearFilters=()=>{setSearch('');setStatusFilter('All Statuses');setFranchiseeFilter('All Franchisees');setRmFilter('All RMs');setProductFilter('All Products');setCityFilter('All Cities');setAttentionOnly(false)}
  const saveCustomer=(draft:CustomerDraft)=>{
    if(formCustomer){
      setCustomers(current=>current.map(customer=>customer.id===formCustomer.id?customerFromDraft(draft,customer):customer))
      onToast(`${draftName(draft)} updated locally`)
    }else{
      const created=customerFromDraft(draft,{...emptyCustomer,id:`CUS-${String(124+customers.length).padStart(6,'0')}`,createdAt:'05 Sep 2026',lastActivityAt:'Just now'})
      created.activity=[{id:`ACT-${Date.now()}`,title:'Customer added to directory',detail:`Source: ${draft.source}`,timestamp:'Just now'}]
      setCustomers(current=>[created,...current]);setSelectedId(created.id);onToast(`${created.name} added to the customer directory`)
    }
    setFormCustomer(undefined)
  }
  const addFollowUp=(customerId:string,followUp:CustomerFollowUp)=>{
    setCustomers(current=>current.map(customer=>customer.id===customerId?{...customer,status:'Follow-up Required',nextFollowUpAt:`${followUp.date}, ${followUp.time}`,followUps:[followUp,...customer.followUps],activity:[{id:`ACT-${Date.now()}`,title:`${followUp.type} follow-up scheduled`,detail:`${followUp.date}, ${followUp.time} · ${followUp.assignedTo}`,timestamp:'Just now'},...customer.activity]}:customer))
    onToast('Follow-up added to the customer relationship timeline')
  }

  return <div className="page admin-customers">
    <PageHeader eyebrow="CUSTOMER MANAGEMENT" title="Customers" description="Manage customer relationships, ownership, products and activity across Troth One." actions={<><button className="secondary-btn" onClick={()=>onToast('Customer export prepared for this prototype')}><Download/> Export</button><button className="primary-btn" onClick={()=>setFormCustomer(null)}><Plus/> Add Customer</button></>}/>
    <section className="customer-summary-grid">
      <StatCard label="Total Customers" value={customers.length} meta="Across the partner network" tone="navy" icon={<Users/>} onClick={clearFilters}/>
      <StatCard label="Active Customers" value={customers.filter(item=>item.status==='Active').length} meta="Currently engaged" tone="green" icon={<UserRound/>} onClick={()=>{clearFilters();setStatusFilter('Active')}}/>
      <StatCard label="New This Month" value={customers.filter(item=>item.createdAt.includes('Sep 2026')).length} meta="Added in September" tone="blue" icon={<Plus/>} onClick={()=>{clearFilters();setStatusFilter('New')}}/>
      <StatCard label="Need Attention" value={customers.filter(item=>item.attentionReasons.length).length} meta="KYC, application or follow-up" tone="amber" icon={<AlertTriangle/>} onClick={()=>{clearFilters();setAttentionOnly(true)}}/>
      <StatCard label="Total Business" value={formatINR(customers.reduce((sum,item)=>sum+item.businessValue,0),true)} meta={`${customers.reduce((sum,item)=>sum+item.activeApplications,0)} active applications`} tone="violet" icon={<BriefcaseBusiness/>}/>
    </section>

    <section className="panel customer-directory-panel">
      <div className="panel-head"><div><b>Customer Directory</b><small>Search, segment and manage customers across the network.</small></div><span>{rows.length} of {customers.length} customers</span></div>
      <div className="customer-directory-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search customer, ID, contact or owner"/><div>
        <Select value={statusFilter} onChange={setStatusFilter}>{['All Statuses',...statuses].map(item=><option key={item}>{item}</option>)}</Select>
        <Select value={franchiseeFilter} onChange={setFranchiseeFilter}>{['All Franchisees',...options('franchisee')].map(item=><option key={item}>{item}</option>)}</Select>
        <Select value={rmFilter} onChange={setRmFilter}>{['All RMs',...options('rm')].map(item=><option key={item}>{item}</option>)}</Select>
        <Select value={productFilter} onChange={setProductFilter}>{['All Products',...customerProducts].map(item=><option key={item}>{item}</option>)}</Select>
        <Select value={cityFilter} onChange={setCityFilter}>{['All Cities',...options('city')].map(item=><option key={item}>{item}</option>)}</Select>
        <button className={`attention-filter ${attentionOnly?'active':''}`} onClick={()=>setAttentionOnly(value=>!value)}><AlertTriangle/> Needs attention</button>
      </div></div>
      <div className="customer-table-wrap"><table className="admin-customer-table"><thead><tr><th>Customer</th><th>Contact</th><th>Franchisee / RM</th><th>Products</th><th>Applications</th><th>Business</th><th>Status</th><th>Next Action</th></tr></thead><tbody>{rows.map(customer=><tr key={customer.id} onClick={()=>setSelectedId(customer.id)}>
        <td data-label="Customer"><span className="customer-avatar">{initials(customer.name)}</span><span><b>{customer.name}</b><small>{customer.id} · {customer.city} · {customer.category}</small></span></td>
        <td data-label="Contact"><b>{customer.mobile}</b><small>{customer.email}</small></td>
        <td data-label="Franchisee / RM"><b>{customer.franchisee}</b><small>{customer.rm}</small></td>
        <td data-label="Products"><div className="customer-product-chips">{customer.productInterests.slice(0,2).map(product=><span key={product}>{product}</span>)}</div></td>
        <td data-label="Applications"><b>{customer.activeApplications} active</b><small>{apps.filter(app=>app.customer===customer.name).length} total</small></td>
        <td data-label="Business"><b>{formatINR(customer.businessValue,true)}</b></td><td data-label="Status"><CustomerStatus status={customer.status}/></td>
        <td data-label="Next Action"><b>{customer.nextFollowUpAt}</b>{customer.attentionReasons[0]&&<small className="attention-copy">{customer.attentionReasons[0]}</small>}<ChevronRight className="row-chevron"/></td>
      </tr>)}</tbody></table></div>
      {!rows.length&&<div className="customer-empty"><Users/><b>No customers match these filters</b><p>Clear the search or adjust the directory filters.</p><button onClick={clearFilters}>Clear filters</button></div>}
    </section>
    {selected&&<CustomerDrawer customer={selected} apps={apps.filter(app=>app.customer===selected.name)} onClose={()=>setSelectedId(null)} onEdit={()=>setFormCustomer(selected)} onAddFollowUp={followUp=>addFollowUp(selected.id,followUp)} onNavigate={onNavigate} onToast={onToast}/>} 
    {formCustomer!==undefined&&<CustomerForm customer={formCustomer} customers={customers} onClose={()=>setFormCustomer(undefined)} onSave={saveCustomer}/>} 
  </div>
}

function CustomerDrawer({customer,apps,onClose,onEdit,onAddFollowUp,onNavigate,onToast}:{customer:AdminCustomer;apps:Application[];onClose:()=>void;onEdit:()=>void;onAddFollowUp:(followUp:CustomerFollowUp)=>void;onNavigate:Props['onNavigate'];onToast:Props['onToast']}) {
  const [tab,setTab]=useState<CustomerTab>('Overview')
  const [followUpOpen,setFollowUpOpen]=useState(false)
  const openApplication=(app:Application)=>{sessionStorage.setItem('troth-open-app',app.id);onNavigate('applications')}
  const newApplication=()=>{sessionStorage.setItem('troth-franchisee-action','new-application');onToast(`Start a new application for ${customer.name}`);onNavigate('applications')}
  return <><button className="drawer-scrim" onClick={onClose}/><aside className="detail-drawer customer-360-drawer">
    <div className="drawer-header"><div><span className="eyebrow">CUSTOMER 360 · {customer.id}</span><h2>{customer.name}</h2><p>{customer.type} · {customer.category} · Customer since {customer.createdAt}</p></div><button className="icon-button" onClick={onClose}><X/></button></div>
    <div className="customer-360-summary"><CustomerStatus status={customer.status}/><span><Phone/> {customer.mobile}</span><span><Mail/> {customer.email}</span><span><MapPin/> {customer.city}</span><span><BriefcaseBusiness/> {formatINR(customer.businessValue,true)} business</span></div>
    <div className="customer-quick-actions"><button onClick={onEdit}><Edit3/> Edit</button><button onClick={newApplication}><Plus/> New Application</button><button onClick={()=>setFollowUpOpen(value=>!value)}><CalendarPlus/> Add Follow-up</button></div>
    {followUpOpen&&<FollowUpForm customer={customer} onCancel={()=>setFollowUpOpen(false)} onSave={followUp=>{onAddFollowUp(followUp);setFollowUpOpen(false)}}/>}
    <div className="drawer-tabs customer-tabs">{customerTabs.map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</div>
    <div className="drawer-body customer-drawer-body">
      {tab==='Overview'&&<><InfoSection title="Personal information" items={[[customer.type==='Business'?'Business name':'Full name',customer.name],['Date of birth / incorporation',customer.dob],['Gender',customer.gender],['Occupation / business type',customer.occupation],['Annual income',customer.annualIncome],['Preferred contact',customer.preferredContact]]}/><InfoSection title="Contact information" items={[["Primary mobile",customer.mobile],["Alternate mobile",customer.alternateMobile||'Not provided'],["Email",customer.email],["City",customer.city],["State",customer.state],["Pincode",customer.pincode],["Address",[customer.address,customer.addressLine2].filter(Boolean).join(', ')]]}/><InfoSection title="Relationship information" items={[["Customer since",customer.createdAt],["Franchisee",customer.franchisee],["Relationship manager",customer.rm],["Customer source",customer.source],["Customer category",customer.category],["Preferred contact",customer.preferredContact]]}/><InfoSection title="Business summary" items={[["Products held / interested",String(customer.productInterests.length)],["Active applications",String(customer.activeApplications)],["Completed applications",String(apps.filter(app=>app.status==='Completed').length)],["Total business value",formatINR(customer.businessValue)]]}/>{customer.attentionReasons.length>0&&<section className="detail-section customer-attention"><h3>Attention required</h3>{customer.attentionReasons.map(reason=><p key={reason}><AlertTriangle/>{reason}</p>)}</section>}</>}
      {tab==='Products'&&<section className="detail-section"><h3>Product relationships</h3><div className="customer-product-list">{customer.productInterests.map(product=>{const related=apps.filter(app=>app.product===product);const latest=related[0];return <article key={product}><span><BriefcaseBusiness/></span><div><b>{latest?.productName||product}</b><small>{latest?`${latest.provider} · ${latest.status} · Updated ${latest.updated}`:'Interested · no application started'}</small></div><strong>{formatINR(related.reduce((sum,app)=>sum+app.amount,0),true)}</strong></article>})}</div></section>}
      {tab==='Applications'&&<section className="detail-section"><div className="customer-section-title"><div><h3>Applications</h3><small>Open any application in the main Applications workspace.</small></div><button className="primary-btn" onClick={newApplication}><Plus/> New Application</button></div><div className="customer-application-list">{apps.map(app=><button key={app.id} onClick={()=>openApplication(app)}><span><b>{app.productName}</b><small>{app.id} · {app.provider} · {app.franchisee}</small></span><span><b>{formatINR(app.amount,true)}</b><small>{app.assignedTo} · {app.updated}</small></span><span className={`customer-app-status app-${app.status.toLowerCase().replaceAll(' ','-')}`}>{app.status}</span><ChevronRight/></button>)}</div></section>}
      {tab==='Relationship'&&<><InfoSection title="Relationship summary" items={[["Assigned franchisee",customer.franchisee],["Relationship manager",customer.rm],["Lead / customer source",customer.source],["Last contact",customer.lastActivityAt],["Next follow-up",customer.nextFollowUpAt],["Preferred contact",customer.preferredContact]]}/><section className="detail-section"><h3>Relationship notes</h3><div className="customer-note-list">{customer.relationshipNotes.map(note=><p key={note}>{note}</p>)}</div></section><section className="detail-section"><div className="customer-section-title"><h3>Follow-ups</h3><button className="secondary-btn" onClick={()=>setFollowUpOpen(true)}><CalendarPlus/> Add</button></div><div className="customer-followup-list">{customer.followUps.length?customer.followUps.map(item=><article key={item.id}><span><CalendarPlus/></span><p><b>{item.type} · {item.date}, {item.time}</b><small>{item.note} · {item.assignedTo}</small></p></article>):<p className="muted-copy">No follow-ups scheduled.</p>}</div></section></>}
      {tab==='KYC & Docs'&&<><section className="detail-section"><div className="customer-kyc-head"><div><h3>KYC status</h3><small>Only masked references are displayed.</small></div><KycStatus status={customer.kycStatus}/></div><div className="customer-document-list">{customer.documents.map(doc=><article key={doc.name}><span><FileCheck2/></span><p><b>{doc.name}</b><small>{doc.reference||'No reference stored'}</small></p><em className={`doc-${doc.status.toLowerCase().replaceAll(' ','-')}`}>{doc.status}</em></article>)}</div></section><section className="customer-privacy-note"><FileCheck2/><p><b>Sensitive information is protected</b><span>Full PAN, Aadhaar and document contents are intentionally not shown in this prototype.</span></p></section></>}
      {tab==='Activity'&&<section className="detail-section"><h3>Customer activity</h3><div className="customer-activity-list">{customer.activity.map(item=><article key={item.id}><time>{item.timestamp}</time><span><Activity/></span><p><b>{item.title}</b><small>{item.detail}</small></p></article>)}</div></section>}
    </div>
  </aside></>
}

function FollowUpForm({customer,onCancel,onSave}:{customer:AdminCustomer;onCancel:()=>void;onSave:(item:CustomerFollowUp)=>void}) {
  const [type,setType]=useState('Call'),[date,setDate]=useState('2026-09-08'),[time,setTime]=useState('11:00'),[note,setNote]=useState(''),[assignedTo,setAssignedTo]=useState(customer.rm)
  return <form className="customer-followup-form" onSubmit={event=>{event.preventDefault();onSave({id:`FU-${Date.now()}`,type,date:displayDate(date),time,note,assignedTo})}}><b>Schedule follow-up</b><label>Type<select value={type} onChange={e=>setType(e.target.value)}>{['Call','Meeting','Email','WhatsApp','Document Follow-up','Renewal Discussion','Cross-sell Discussion'].map(item=><option key={item}>{item}</option>)}</select></label><label>Date<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Time<input required type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label>Assigned to<input required value={assignedTo} onChange={e=>setAssignedTo(e.target.value)}/></label><label className="followup-note">Note<input required value={note} onChange={e=>setNote(e.target.value)} placeholder="Purpose and expected next action"/></label><div><button type="button" onClick={onCancel}>Cancel</button><button className="primary-btn">Save Follow-up</button></div></form>
}

interface CustomerDraft { type:CustomerType; title:string; firstName:string; middleName:string; lastName:string; businessName:string; businessType:string; contactPerson:string; email:string; mobile:string; alternateMobile:string; address:string; addressLine2:string; city:string; state:string; pincode:string; country:string; source:string; franchisee:string; rm:string; category:string; preferredContact:string; dob:string; gender:string; occupation:string; annualIncome:string; kycStatus:AdminKycStatus; panAvailable:boolean; consent:boolean; productInterests:ProductType[]; status:AdminCustomerStatus }
const blankDraft:CustomerDraft={type:'Individual',title:'Mr',firstName:'',middleName:'',lastName:'',businessName:'',businessType:'',contactPerson:'',email:'',mobile:'',alternateMobile:'',address:'',addressLine2:'',city:'',state:'Gujarat',pincode:'',country:'India',source:'Franchisee Referral',franchisee:'Direct / Head Office',rm:'Unassigned',category:'Retail',preferredContact:'WhatsApp',dob:'',gender:'Prefer not to say',occupation:'',annualIncome:'₹5L–₹10L',kycStatus:'Not Started',panAvailable:false,consent:false,productInterests:[],status:'New'}

function CustomerForm({customer,customers,onClose,onSave}:{customer:AdminCustomer|null;customers:AdminCustomer[];onClose:()=>void;onSave:(draft:CustomerDraft)=>void}) {
  const [step,setStep]=useState(1),[error,setError]=useState('')
  const [draft,setDraft]=useState<CustomerDraft>(customer?draftFromCustomer(customer):blankDraft)
  const update=<K extends keyof CustomerDraft>(key:K,value:CustomerDraft[K])=>setDraft(current=>({...current,[key]:value}))
  const next=()=>{const message=validateStep(step,draft);if(message){setError(message);return}setError('');setStep(value=>Math.min(5,value+1))}
  const toggleProduct=(product:ProductType)=>update('productInterests',draft.productInterests.includes(product)?draft.productInterests.filter(item=>item!==product):[...draft.productInterests,product])
  const titles=['Identity','Contact','Relationship','Profile & KYC','Review']
  return <><button className="drawer-scrim" onClick={onClose}/><aside className="form-drawer customer-form-drawer"><div className="drawer-header"><div><span className="eyebrow">CUSTOMER MANAGEMENT</span><h2>{customer?'Edit Customer':'Add Customer'}</h2><p>{customer?'Update the local Customer 360 profile.':'Create a complete customer relationship record.'}</p></div><button className="icon-button" onClick={onClose}><X/></button></div>
    <div className="customer-stepper">{titles.map((title,index)=><div key={title} className={step===index+1?'active':step>index+1?'complete':''}><i>{step>index+1?<Check/>:index+1}</i><span>{title}</span></div>)}</div>
    <form onSubmit={event=>{event.preventDefault();const message=validateStep(5,draft);if(message){setError(message);return}onSave(draft)}}><div className="customer-form-content">
      {step===1&&<><h3>Customer identity</h3><div className="form-row"><label>Customer Type<select value={draft.type} onChange={e=>update('type',e.target.value as CustomerType)}><option>Individual</option><option>Business</option></select></label><label>Status<select value={draft.status} onChange={e=>update('status',e.target.value as AdminCustomerStatus)}>{statuses.map(status=><option key={status}>{status}</option>)}</select></label></div>{draft.type==='Business'?<><label>Business / Company Name<input value={draft.businessName} onChange={e=>update('businessName',e.target.value)} placeholder="Registered or trading name"/></label><div className="form-row"><label>Business Type<input value={draft.businessType} onChange={e=>update('businessType',e.target.value)} placeholder="e.g. Private Limited"/></label><label>Contact Person<input value={draft.contactPerson} onChange={e=>update('contactPerson',e.target.value)} placeholder="Primary contact"/></label></div></>:<><div className="form-row three"><label>Title<select value={draft.title} onChange={e=>update('title',e.target.value)}><option>Mr</option><option>Ms</option><option>Mrs</option><option>Dr</option></select></label><label>First Name<input value={draft.firstName} onChange={e=>update('firstName',e.target.value)} placeholder="First name"/></label><label>Middle Name (optional)<input value={draft.middleName} onChange={e=>update('middleName',e.target.value)} placeholder="Middle name"/></label></div><label>Last Name<input value={draft.lastName} onChange={e=>update('lastName',e.target.value)} placeholder="Last name"/></label></>}<div className="form-row"><label>Date of Birth / Incorporation<input type="date" value={draft.dob} onChange={e=>update('dob',e.target.value)}/></label>{draft.type==='Individual'&&<label>Gender<select value={draft.gender} onChange={e=>update('gender',e.target.value)}><option>Male</option><option>Female</option><option>Other</option><option>Prefer not to say</option></select></label>}</div></>}
      {step===2&&<><h3>Contact & address</h3><div className="form-row three"><label>Primary Mobile<input value={draft.mobile} onChange={e=>update('mobile',e.target.value)} placeholder="10-digit mobile"/></label><label>Alternate Mobile<input value={draft.alternateMobile} onChange={e=>update('alternateMobile',e.target.value)} placeholder="Optional"/></label><label>Preferred Contact<select value={draft.preferredContact} onChange={e=>update('preferredContact',e.target.value)}><option>Phone</option><option>WhatsApp</option><option>Email</option></select></label></div><label>Email<input type="email" value={draft.email} onChange={e=>update('email',e.target.value)} placeholder="customer@example.in"/></label><label>Address Line 1<input value={draft.address} onChange={e=>update('address',e.target.value)} placeholder="House / building / street"/></label><label>Address Line 2<input value={draft.addressLine2} onChange={e=>update('addressLine2',e.target.value)} placeholder="Area / landmark (optional)"/></label><div className="form-row three"><label>City<input value={draft.city} onChange={e=>update('city',e.target.value)}/></label><label>State<input value={draft.state} onChange={e=>update('state',e.target.value)}/></label><label>Pincode<input value={draft.pincode} onChange={e=>update('pincode',e.target.value)}/></label></div><label>Country<input disabled value={draft.country}/></label></>}
      {step===3&&<><h3>Relationship setup</h3><div className="form-row"><label>Lead Source<select value={draft.source} onChange={e=>update('source',e.target.value)}>{customerSources.map(item=><option key={item}>{item}</option>)}</select></label><label>Customer Category<select value={draft.category} onChange={e=>update('category',e.target.value)}>{customerCategories.map(item=><option key={item}>{item}</option>)}</select></label></div><label>Franchisee<select value={draft.franchisee} onChange={e=>update('franchisee',e.target.value)}>{['Direct / Head Office',...Array.from(new Set(customers.map(item=>item.franchisee))).filter(item=>item!=='Direct / Head Office')].map(item=><option key={item}>{item}</option>)}</select></label><div className="form-row"><label>Relationship Manager<select value={draft.rm} onChange={e=>update('rm',e.target.value)}>{['Unassigned',...Array.from(new Set(customers.map(item=>item.rm))).filter(item=>item!=='Unassigned')].map(item=><option key={item}>{item}</option>)}</select></label><label>Preferred Contact<select value={draft.preferredContact} onChange={e=>update('preferredContact',e.target.value)}><option>WhatsApp</option><option>Phone</option><option>Email</option></select></label></div></>}
      {step===4&&<><h3>Profile, KYC & interests</h3><div className="form-row"><label>Occupation / Business Type<input value={draft.occupation} onChange={e=>update('occupation',e.target.value)}/></label><label>Annual Income<select value={draft.annualIncome} onChange={e=>update('annualIncome',e.target.value)}><option>Below ₹5L</option><option>₹5L–₹10L</option><option>₹10L–₹15L</option><option>₹15L–₹25L</option><option>₹25L+</option></select></label></div><label>KYC Status<select value={draft.kycStatus} onChange={e=>update('kycStatus',e.target.value as AdminKycStatus)}><option>Not Started</option><option>Pending</option><option>Needs Review</option><option>Complete</option></select></label><fieldset className="customer-interest-field"><legend>Products Interested In</legend><div>{customerProducts.map(product=><label key={product}><input type="checkbox" checked={draft.productInterests.includes(product)} onChange={()=>toggleProduct(product)}/><span>{product}</span></label>)}</div></fieldset><label className="checkbox-line"><input type="checkbox" checked={draft.panAvailable} onChange={e=>update('panAvailable',e.target.checked)}/><span>PAN is available (full PAN will not be displayed)</span></label><label className="checkbox-line"><input type="checkbox" checked={draft.consent} onChange={e=>update('consent',e.target.checked)}/><span>Customer has agreed to receive service-related communication.</span></label></>}
      {step===5&&<><h3>Review customer</h3><div className="customer-review-card"><div><span>Customer</span><b>{draftName(draft)}</b><small>{draft.type} · {draft.category}</small></div><div><span>Contact</span><b>{draft.mobile}</b><small>{draft.email}</small></div><div><span>Location</span><b>{draft.city}, {draft.state}</b><small>{draft.address} · {draft.pincode}</small></div><div><span>Relationship</span><b>{draft.franchisee}</b><small>{draft.rm} · {draft.source}</small></div><div><span>KYC</span><b>{draft.kycStatus}</b><small>{draft.panAvailable?'PAN available':'PAN not recorded'}</small></div><div><span>Interests</span><b>{draft.productInterests.join(', ')||'None selected'}</b><small>Preferred contact: {draft.preferredContact}</small></div></div><div className="customer-consent-note"><FileCheck2/><p><b>Privacy-conscious record</b><span>Sensitive identifiers remain masked in Customer 360.</span></p></div></>}
      {error&&<p className="customer-form-error"><AlertTriangle/>{error}</p>}
    </div><div className="form-actions customer-form-actions"><button type="button" className="secondary-btn" onClick={()=>step===1?onClose():setStep(value=>value-1)}>{step===1?'Cancel':'Back'}</button>{step<5?<button type="button" className="primary-btn" onClick={next}>Continue <ChevronRight/></button>:<button className="primary-btn">{customer?'Save Changes':'Add Customer'}</button>}</div></form>
  </aside></>
}

function InfoSection({title,items}:{title:string;items:string[][]}) { return <section className="detail-section"><h3>{title}</h3><div className="detail-grid">{items.map(([label,value])=><div key={label}><span>{label}</span><b>{value||'—'}</b></div>)}</div></section> }
function CustomerStatus({status}:{status:AdminCustomerStatus}) { return <span className={`customer-status customer-status-${status.toLowerCase().replaceAll(' ','-')}`}><i/>{status}</span> }
function KycStatus({status}:{status:AdminKycStatus}) { return <span className={`customer-kyc kyc-${status.toLowerCase().replaceAll(' ','-')}`}>{status}</span> }
function initials(name:string){return name.split(' ').map(part=>part[0]).join('').slice(0,2).toUpperCase()}
function draftName(draft:CustomerDraft){return draft.type==='Business'?draft.businessName.trim():`${draft.firstName} ${draft.middleName} ${draft.lastName}`.replace(/\s+/g,' ').trim()}
function displayDate(value:string){if(!value)return '';const [year,month,day]=value.split('-');return new Date(Number(year),Number(month)-1,Number(day)).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}
function validateStep(step:number,draft:CustomerDraft):string {
  if(step===1&&(draft.type==='Individual'?(!draft.firstName.trim()||!draft.lastName.trim()):(!draft.businessName.trim()||!draft.contactPerson.trim())))return draft.type==='Business'?'Enter the business name and contact person.':'Enter the customer first and last name.'
  if(step===2&&(!isIndianMobile(draft.mobile)||!/^\S+@\S+\.\S+$/.test(draft.email)||!draft.city.trim()||!draft.address.trim()))return 'Enter a valid 10-digit Indian mobile, email, address and city.'
  if(step===3&&(!draft.franchisee||!draft.rm))return 'Choose the franchisee and relationship manager.'
  if(step===4&&!draft.consent)return 'Record customer consent before continuing.'
  if(step===5)return validateStep(1,draft)||validateStep(2,draft)||validateStep(3,draft)||validateStep(4,draft)
  return ''
}
function draftFromCustomer(customer:AdminCustomer):CustomerDraft { const [firstName,...rest]=customer.name.split(' ');return {type:customer.type,title:customer.title||'Mr',firstName,middleName:customer.middleName||'',lastName:rest.join(' '),businessName:customer.type==='Business'?customer.name:'',businessType:customer.businessType||'',contactPerson:customer.contactPerson||'',email:customer.email,mobile:customer.mobile.replaceAll('•','0'),alternateMobile:customer.alternateMobile?.replaceAll('•','0')||'',address:customer.address,addressLine2:customer.addressLine2||'',city:customer.city,state:customer.state,pincode:customer.pincode,country:'India',source:customer.source,franchisee:customer.franchisee,rm:customer.rm,category:customer.category,preferredContact:customer.preferredContact,dob:'',gender:customer.gender,occupation:customer.occupation,annualIncome:customer.annualIncome,kycStatus:customer.kycStatus,panAvailable:customer.documents.some(doc=>doc.name==='PAN'&&doc.status==='Available'),consent:true,productInterests:[...customer.productInterests],status:customer.status} }
function customerFromDraft(draft:CustomerDraft,base:AdminCustomer):AdminCustomer { const attentionReasons=[...(draft.kycStatus==='Pending'||draft.kycStatus==='Needs Review'?['KYC documents require attention']:[]),...(draft.status==='Follow-up Required'?['Relationship follow-up is due']:[])];return {...base,name:draftName(draft),type:draft.type,title:draft.title,middleName:draft.middleName,businessType:draft.businessType,contactPerson:draft.contactPerson,email:draft.email,mobile:maskMobile(draft.mobile),alternateMobile:draft.alternateMobile?maskMobile(draft.alternateMobile):undefined,address:draft.address,addressLine2:draft.addressLine2,city:draft.city,state:draft.state,pincode:draft.pincode,source:draft.source,franchisee:draft.franchisee,rm:draft.rm,category:draft.category,preferredContact:draft.preferredContact,dob:draft.dob?displayDate(draft.dob):base.dob,gender:draft.gender,occupation:draft.occupation||draft.businessType,annualIncome:draft.annualIncome,kycStatus:draft.kycStatus,status:draft.status,productInterests:draft.productInterests,attentionReasons,relationshipNotes:base.relationshipNotes.length?base.relationshipNotes:['Customer record created; add relationship context after the first interaction.'],documents:[{name:'PAN',status:draft.panAvailable?'Available':'Pending',reference:draft.panAvailable?'A•••••4K':undefined},{name:'Aadhaar',status:'Pending'},{name:'Address Proof',status:'Pending'},{name:'Bank Proof',status:'Pending'},{name:'Photo',status:'Pending'},{name:'Other',status:'Pending'}],lastActivityAt:'Just now',activity:[{id:`ACT-${Date.now()}`,title:'Customer profile updated',detail:'Contact, relationship or profile details changed',timestamp:'Just now'},...base.activity]} }
function isIndianMobile(value:string){const digits=value.replace(/\D/g,'');return digits.length===10||digits.length===12&&digits.startsWith('91')}
function maskMobile(value:string){const digits=value.replace(/\D/g,'');return digits.length>=10?`+91 ${digits.slice(-10,-8)}••• ••${digits.slice(-3)}`:value}
const emptyCustomer:AdminCustomer={id:'',name:'',type:'Individual',email:'',mobile:'',city:'',state:'',address:'',pincode:'',status:'New',kycStatus:'Not Started',franchisee:'Direct / Head Office',rm:'Unassigned',source:'Website',category:'Retail',preferredContact:'WhatsApp',dob:'',gender:'',occupation:'',annualIncome:'',createdAt:'',lastActivityAt:'',nextFollowUpAt:'Not scheduled',productInterests:[],attentionReasons:[],businessValue:0,activeApplications:0,documents:[],followUps:[],activity:[],relationshipNotes:[]}
