import { useMemo, useState, type ReactNode } from 'react'
import { AlertTriangle, ArrowLeft, BriefcaseBusiness, CalendarClock, CalendarPlus, Check, Download, Edit3, Eye, FileCheck2, FileText, MapPin, PiggyBank, Plus, ShieldCheck, UserRound, WalletCards, X } from 'lucide-react'
import { DataTable, FilterSelect, Filters, Modal, PageHeader, Panel, StatusBadge, Timeline } from '../franchisee/components/FranchiseeUI'
import { CustomerOnboardingWizard, type CustomerOwnershipDraft } from '../franchisee/components/CustomerOnboardingWizard'
import type { CustomerOnboardingDraft } from '../franchisee/customer360Types'
import { formatINR } from '../data/mockData'
import { buildAdminCustomers, customerCategories, customerProducts, customerSources, type AdminCustomer, type AdminCustomerStatus, type AdminKycStatus, type CustomerFollowUp, type CustomerType } from '../data/adminCustomersData'
import type { Application, ProductType } from '../types'

interface Props { apps:Application[]; route?:string; onNavigate:(page:string,filter?:string)=>void; onToast:(message:string)=>void }
type MainSection='Investment'|'Products'|'Loans'|'Cases'|'Renewals'
type MoreSection='Documents'|'Communication'|'Cross-Sell'
type FormSection='Address'|'Ownership'|'Profile & KYC'|'Review'
const statuses:AdminCustomerStatus[]=['Active','New','Follow-up Required','KYC Pending','Inactive']
const moreSections:MoreSection[]=['Documents','Communication','Cross-Sell']
const formSections:FormSection[]=['Address','Ownership','Profile & KYC','Review']
const formSectionIcons:Record<FormSection,ReactNode>={Address:<MapPin/>,Ownership:<BriefcaseBusiness/>,'Profile & KYC':<ShieldCheck/>,Review:<Check/>}

export function AdminCustomers({apps,route='customers',onNavigate,onToast}:Props) {
  const [customers,setCustomers]=useState<AdminCustomer[]>(()=>buildAdminCustomers(apps))
  const [editing,setEditing]=useState(false)
  const [adminCreateDraft,setAdminCreateDraft]=useState<{customer:CustomerOnboardingDraft;ownership:CustomerOwnershipDraft}>()
  const [search,setSearch]=useState(''),[productFilter,setProductFilter]=useState('All Products'),[kycFilter,setKycFilter]=useState('All KYC'),[sourceFilter,setSourceFilter]=useState('All Sources')
  const customerId=route.match(/^customers\/([^/]+)\/360$/)?.[1]
  const selected=customers.find(customer=>customer.id===customerId)||null
  const sourceOptions=['All Sources',...Array.from(new Set(customers.map(customer=>customer.source).filter(Boolean))).sort()]
  const rows=useMemo(()=>customers.filter(customer=>{const q=search.trim().toLowerCase(),query=!q||[customer.name,customer.id,customer.email,customer.mobile].some(value=>value.toLowerCase().includes(q));return query&&(productFilter==='All Products'||productsFor(customer,apps).includes(productFilter as ProductType))&&(kycFilter==='All KYC'||customer.kycStatus===kycFilter)&&(sourceFilter==='All Sources'||customer.source===sourceFilter)}),[customers,apps,search,productFilter,kycFilter,sourceFilter])
  const save=(draft:CustomerDraft,current:AdminCustomer|null)=>{if(current){setCustomers(items=>items.map(item=>item.id===current.id?fromDraft(draft,item):item));onToast(`${draftName(draft)} updated locally`);setEditing(false)}else{const created=fromDraft(draft,{...emptyCustomer,id:`CUS-${String(124+customers.length).padStart(6,'0')}`,createdAt:'05 Sep 2026',lastActivityAt:'Just now'});created.activity=[{id:`ACT-${Date.now()}`,title:'Customer added to directory',detail:`Source: ${draft.source}`,timestamp:'Just now'}];setCustomers(items=>[created,...items]);onToast(`${created.name} added to the customer directory`);onNavigate(`customers/${created.id}/360`)}}
  const addFollowUp=(item:CustomerFollowUp)=>{if(!selected)return;setCustomers(items=>items.map(customer=>customer.id===selected.id?{...customer,status:'Follow-up Required',nextFollowUpAt:`${item.date}, ${item.time}`,followUps:[item,...customer.followUps],activity:[{id:`ACT-${Date.now()}`,title:`${item.type} follow-up scheduled`,detail:`${item.date}, ${item.time} · ${item.assignedTo}`,timestamp:'Just now'},...customer.activity]}:customer));onToast('Follow-up added to the customer relationship timeline')}

  if(route==='customers/new'){
    const franchisees=['Direct / Head Office',...Array.from(new Set(customers.map(item=>item.franchisee))).filter(item=>item!=='Direct / Head Office')]
    const relationshipManagers=['Unassigned',...Array.from(new Set(customers.map(item=>item.rm))).filter(item=>item!=='Unassigned')]
    const ownership=adminCreateDraft?.ownership||{franchisee:'Direct / Head Office',relationshipManager:'Unassigned',status:'New'}
    return <CustomerOnboardingWizard presentation="page" initial={adminCreateDraft?.customer} ownership={{initial:ownership,franchisees,relationshipManagers,statuses}} onClose={()=>onNavigate('customers')} onSaveDraft={(customer,nextOwnership)=>{setAdminCreateDraft({customer,ownership:nextOwnership||ownership});onToast('Customer draft saved locally')}} onCreate={(customer,nextOwnership)=>{const created=fromOnboardingDraft(customer,nextOwnership||ownership,{...emptyCustomer,id:`CUS-${String(124+customers.length).padStart(6,'0')}`});setCustomers(items=>[created,...items]);setAdminCreateDraft(undefined);onToast(`${created.name} added to the customer directory`);onNavigate(`customers/${created.id}/360`)}}/>
  }
  if(customerId)return selected?(editing?<CustomerForm customer={selected} customers={customers} onClose={()=>setEditing(false)} onSave={draft=>save(draft,selected)}/>:<Customer360 customer={selected} apps={apps.filter(app=>app.customer===selected.name)} onBack={()=>onNavigate('customers')} onEdit={()=>setEditing(true)} onAddFollowUp={addFollowUp} onNavigate={onNavigate} onToast={onToast}/>):<MissingCustomer onBack={()=>onNavigate('customers')}/>

  return <div className="admin-customers franchisee-customers-page">
    <PageHeader eyebrow="CUSTOMER RELATIONSHIPS" title="Customers" description="A clear view of each customer's profile, investments, loans and relationship across the network." actions={<button className="tf-primary" onClick={()=>onNavigate('customers/new')}><Plus/> Add New Customer</button>}/>
    <Panel title="Customer Directory" subtitle={`${rows.length} customers`}><Filters search={search} onSearch={setSearch}><FilterSelect label="KYC" value={kycFilter} onChange={setKycFilter} options={['All KYC','Complete','Pending','Needs Review','Not Started']}/><FilterSelect label="Products" value={productFilter} onChange={setProductFilter} options={['All Products',...customerProducts]}/><FilterSelect label="Source" value={sourceFilter} onChange={setSourceFilter} options={sourceOptions}/></Filters>
      <DataTable headers={['Customer Name','Contact','Source','Insurance Premium','Investments','Loans','KYC','Open 360']} empty={!rows.length}>{rows.map(customer=>{const related=apps.filter(app=>app.customer===customer.name),insurance=related.filter(app=>app.product==='Insurance'),investments=related.filter(isInvestment),loans=related.filter(isLoan),recorded=productsFor(customer,apps),investmentCount=new Set([...investments.map(item=>item.product),...recorded.filter(isInvestmentProduct)]).size,loanNames=[...new Set([...loans.map(item=>item.productName),...recorded.filter(isLoanProduct)])];return <tr key={customer.id}><td><button className="tf-link-stack" onClick={()=>onNavigate(`customers/${customer.id}/360`)}><b>{customer.name}</b><small>{customer.id}</small></button></td><td><b>{customer.mobile}</b><small>{customer.email||'Email not recorded'}</small></td><td><b>{customer.source}</b></td><td>{insurance.length?<b>{formatINR(total(insurance))}</b>:<span className="tf-customer-none">—</span>}</td><td>{investmentCount?<><b>{investments.length?`${formatINR(total(investments))} Current Value`:`${investmentCount} Product${investmentCount===1?'':'s'}`}</b><small>{investmentCount} investment{investmentCount===1?'':'s'}</small></>:<span className="tf-customer-none">No Investments</span>}</td><td>{loanNames.length?<><b>{loanNames[0]}</b><small>{loans.length?formatINR(total(loans)):'—'}</small></>:<span className="tf-customer-none">No Loans</span>}</td><td><StatusBadge tone={kycTone(customer.kycStatus)}>{customer.kycStatus}</StatusBadge></td><td><button className="tf-customer-open" onClick={()=>onNavigate(`customers/${customer.id}/360`)}>Open 360</button></td></tr>})}</DataTable>
    </Panel>
  </div>
}

function Customer360({customer,apps,onBack,onEdit,onAddFollowUp,onNavigate,onToast}:{customer:AdminCustomer;apps:Application[];onBack:()=>void;onEdit:()=>void;onAddFollowUp:(item:CustomerFollowUp)=>void;onNavigate:Props['onNavigate'];onToast:Props['onToast']}){
  const [section,setSection]=useState<MainSection>('Investment'),[more,setMore]=useState<MoreSection>('Documents'),[followUpOpen,setFollowUpOpen]=useState(false),[preview,setPreview]=useState<string>()
  const investments=apps.filter(isInvestment),loans=apps.filter(isLoan),cases=apps.filter(app=>!['Completed','Rejected'].includes(app.status)),linkedProducts=apps.filter(app=>app.status!=='Rejected'),renewals=adminRenewalsFor(customer),crossSell=customer.productInterests.filter(product=>!apps.some(app=>app.product===product))
  const cards:{name:MainSection;icon:ReactNode;value:string;detail:string}[]=[{name:'Investment',icon:<PiggyBank/>,value:investments.length?formatINR(total(investments),true):'No investments',detail:`${investments.length} recorded`},{name:'Products',icon:<BriefcaseBusiness/>,value:String(linkedProducts.length),detail:'Products through TROTH'},{name:'Loans',icon:<WalletCards/>,value:loans.length?formatINR(total(loans),true):'No loans',detail:`${loans.length} recorded`},{name:'Cases',icon:<FileCheck2/>,value:String(cases.length),detail:'Open applications'},{name:'Renewals',icon:<CalendarClock/>,value:String(renewals.length),detail:'Due soon'}]
  return <div className="tf-customer360-page admin-customer360-page"><button className="tf-360-back" onClick={onBack}><ArrowLeft/> Back to Customers</button><header className="tf-360-basic"><div className="tf-360-basic-title"><div className="tf-360-avatar">{initials(customer.name)}</div><div><span>CUSTOMER 360°</span><h1>{customer.name}</h1><p>{customer.id} · {customer.city}</p></div></div><div className="tf-head-actions"><button className="tf-secondary" onClick={onEdit}><Edit3/> Edit Customer</button><button className="tf-secondary" onClick={()=>setFollowUpOpen(value=>!value)}><CalendarPlus/> Add Follow-up</button></div><div className="tf-360-basic-grid"><Info label="Customer ID" value={customer.id}/><Info label="Mobile Number" value={customer.mobile}/><Info label="Email Address" value={customer.email}/><Info label="Customer Type" value={customer.type}/><Info label="Source" value={customer.source}/><Info label="KYC Status" value={customer.kycStatus}/><Info label="Customer Since" value={customer.createdAt}/><Info label="Assigned Employee / Agent" value={customer.rm}/><Info label="Business Source / Franchise" value={customer.franchisee}/><Info label="Status" value={customer.status}/><Info label="City" value={customer.city}/><Info label="Category" value={customer.category}/></div></header>
    {followUpOpen&&<FollowUpForm customer={customer} onCancel={()=>setFollowUpOpen(false)} onSave={item=>{onAddFollowUp(item);setFollowUpOpen(false)}}/>}<div className="tf-360-primary-cards" role="tablist" aria-label="Customer 360 sections">{cards.map(card=><button type="button" role="tab" aria-selected={section===card.name} className={section===card.name?'active':''} key={card.name} onClick={()=>setSection(card.name)}><span className="tf-kpi-icon">{card.icon}</span><span>{card.name}</span><b>{card.value}</b><small>{card.detail}</small></button>)}</div>
    <div className="tf-360-detail-content">{section==='Investment'&&<ApplicationTable title="Investment Details" rows={investments} empty="No investment applications are recorded for this customer." onOpen={()=>onNavigate('applications')}/>} {section==='Products'&&<ProductsDetail customer={customer} apps={linkedProducts}/>} {section==='Loans'&&<ApplicationTable title="Loan Details" rows={loans} empty="No loan applications are recorded for this customer." onOpen={()=>onNavigate('applications')}/>} {section==='Cases'&&<ApplicationTable title="Open Cases" rows={cases} empty="No open cases are recorded for this customer." onOpen={()=>onNavigate('applications')}/>} {section==='Renewals'&&<RenewalsDetail rows={renewals}/>}</div>
    <section className="tf-360-more"><header><div><h2>More Customer Information</h2><p>Documents, communication history and relationship opportunities remain available here.</p></div><nav>{moreSections.map(item=><button className={more===item?'active':''} key={item} onClick={()=>setMore(item)}>{item}</button>)}</nav></header>{more==='Documents'&&<Documents customer={customer} onPreview={setPreview}/>} {more==='Communication'&&<Communication customer={customer} onToast={onToast}/>} {more==='Cross-Sell'&&<CrossSell products={crossSell}/>}</section>{preview&&<SamplePreview title={preview} customer={customer} onClose={()=>setPreview(undefined)}/>}</div>
}

interface AdminProductPreview { title:string; label:string; fields:{label:string;value:string}[] }
interface AdminRenewalRow { id:string; product:string; provider:string; policyNumber:string; renewalDueDate:string; daysRemaining:number; currentPremium:number; status:'Upcoming'|'Due Soon'|'Overdue'; lastFollowUp:string }

function ProductsDetail({customer,apps}:{customer:AdminCustomer;apps:Application[]}){const [preview,setPreview]=useState<AdminProductPreview>();return <><AdminProductTable title="Products Through TROTH" subtitle="Products recorded through your TROTH relationship" rows={apps} customer={customer} onPreview={setPreview}/><AdminProductTable title="Other Company Products" subtitle="Products recorded with another provider or intermediary" rows={[]} customer={customer} onPreview={setPreview}/>{!apps.length&&<Empty text="No product holdings are recorded for this customer."/>}{preview&&<ProductPreviewModal preview={preview} onClose={()=>setPreview(undefined)}/>}</>}
function AdminProductTable({title,subtitle,rows,customer,onPreview}:{title:string;subtitle:string;rows:Application[];customer:AdminCustomer;onPreview:(preview:AdminProductPreview)=>void}){return <Panel title={title} subtitle={subtitle}><DataTable headers={['Product','Company / Provider','Status','Start Date','Renewal / Maturity','Value / Cover / Outstanding','Actions']} empty={!rows.length}>{rows.map(item=>{const document=adminProductDocument(customer,item);return <tr key={item.id}><td><b>{item.productName}</b><small>{friendlyAdminCategory(item.product)}</small></td><td>{item.provider||'Not recorded'}</td><td><StatusBadge>{item.status}</StatusBadge></td><td>—</td><td>—</td><td>{formatINR(item.amount)}</td><td><div className="tf-document-actions"><button type="button" title={`View ${document.label}`} aria-label={`View ${document.label}`} onClick={()=>onPreview(document)}><Eye/></button><button type="button" title={`${document.label} not available for download`} aria-label={`${document.label} not available for download`} disabled><Download/></button></div></td></tr>})}</DataTable></Panel>}
function RenewalsDetail({rows}:{rows:AdminRenewalRow[]}){return <Panel title="Renewals Due Soon" subtitle="Upcoming insurance renewals and recorded maturity dates"><DataTable headers={['Product','Company / Provider','Reference','Renewal / Maturity Date','Days Remaining','Amount','Status','Action']} empty={!rows.length}>{rows.map(row=><tr key={row.id}><td><b>{row.product}</b></td><td>{row.provider}</td><td>{row.policyNumber}</td><td>{displayDate(row.renewalDueDate)}</td><td>{row.daysRemaining<0?`${Math.abs(row.daysRemaining)} days overdue`:`${row.daysRemaining} days`}</td><td>{formatINR(row.currentPremium)}</td><td><StatusBadge tone={row.status==='Overdue'?'red':row.status==='Due Soon'?'amber':'green'}>{row.status}</StatusBadge><small>Last follow-up: {row.lastFollowUp}</small></td><td><span>—</span></td></tr>)}</DataTable></Panel>}
function ProductPreviewModal({preview,onClose}:{preview:AdminProductPreview;onClose:()=>void}){return <Modal title={preview.title} subtitle="Demonstration preview only" onClose={onClose}><div className="tf-document-preview"><article className="tf-sample-document"><div className="tf-sample-banner"><FileText/><span><b>SAMPLE / DEMO</b><small>No previewable file is available in this demo.</small></span></div><h3>{preview.title}</h3><dl>{preview.fields.map(field=><div key={field.label}><dt>{field.label}</dt><dd>{field.value}</dd></div>)}</dl><p>This is a sample preview for demonstration purposes only.</p></article></div></Modal>}
function ApplicationTable({title,rows,empty,onOpen}:{title:string;rows:Application[];empty:string;onOpen:()=>void}){return <Panel title={title} subtitle="Values from the Admin application workspace.">{rows.length?<DataTable headers={['Product','Provider','Value','Status / Stage','Owner','Updated','Action']}>{rows.map(item=><tr key={item.id}><td><b>{item.productName}</b><small>{item.id}</small></td><td>{item.provider}</td><td>{formatINR(item.amount,true)}</td><td><StatusBadge>{item.status}</StatusBadge><small>{item.stage}</small></td><td>{item.rm}</td><td>{item.updated}</td><td><button className="tf-text-btn" onClick={onOpen}>Open Case</button></td></tr>)}</DataTable>:<Empty text={empty}/>}</Panel>}
function Documents({customer,onPreview}:{customer:AdminCustomer;onPreview:(name:string)=>void}){return <Panel title="KYC & Documents" subtitle="Admin-visible document records. Unavailable files are not presented as live documents."><DataTable headers={['Document','Reference','Status','Actions']} empty={!customer.documents.length}>{customer.documents.map(doc=><tr key={doc.name}><td><b>{doc.name}</b></td><td>{doc.reference||<span className="tf-document-none">No reference stored</span>}</td><td><StatusBadge>{doc.status}</StatusBadge></td><td><div className="tf-document-actions"><button title={`View ${doc.name}`} aria-label={`View ${doc.name}`} onClick={()=>onPreview(doc.name)}><Eye/></button><button title="Download unavailable: no file is stored" aria-label="Download unavailable: no file is stored" disabled><Download/></button></div></td></tr>)}</DataTable></Panel>}
function Communication({customer,onToast}:{customer:AdminCustomer;onToast:(message:string)=>void}){const items=customer.activity.map(item=>({id:item.id,title:item.title,detail:item.detail,time:item.timestamp,actor:customer.rm}));return <Panel title="Communication" subtitle="Follow-ups and activity recorded against this customer." action={<button className="tf-secondary" onClick={()=>onToast('Use Add Follow-up above to record a customer interaction')}>Record communication</button>}>{items.length?<Timeline items={items}/>:<Empty text="No communication has been recorded for this customer."/>}</Panel>}
function CrossSell({products}:{products:ProductType[]}){return <Panel title="Cross-Sell Opportunities" subtitle="Product interests without a corresponding application.">{products.length?<div className="admin-cross-sell">{products.map(product=><article key={product}><ShieldCheck/><div><b>{product}</b><small>Customer interest is recorded; no application exists yet.</small></div></article>)}</div>:<Empty text="No data-backed cross-sell opportunity is currently identified."/>}</Panel>}
function Empty({text}:{text:string}){return <div className="tf-360-empty"><WalletCards/><b>No information to show</b><span>{text}</span></div>}
function MissingCustomer({onBack}:{onBack:()=>void}){return <div className="tf-360-empty page"><UserRound/><b>Customer unavailable</b><span>This customer does not exist in the current Admin scope.</span><button className="tf-primary" onClick={onBack}><ArrowLeft/> Back to Customers</button></div>}

interface CustomerDraft { type:CustomerType; title:string; firstName:string; middleName:string; lastName:string; businessName:string; businessType:string; contactPerson:string; email:string; mobile:string; alternateMobile:string; address:string; addressLine2:string; city:string; state:string; pincode:string; country:string; source:string; franchisee:string; rm:string; category:string; preferredContact:string; dob:string; gender:string; occupation:string; annualIncome:string; kycStatus:AdminKycStatus; panAvailable:boolean; consent:boolean; productInterests:ProductType[]; status:AdminCustomerStatus }
const blankDraft:CustomerDraft={type:'Individual',title:'Mr',firstName:'',middleName:'',lastName:'',businessName:'',businessType:'',contactPerson:'',email:'',mobile:'',alternateMobile:'',address:'',addressLine2:'',city:'',state:'Gujarat',pincode:'',country:'India',source:'Franchisee Referral',franchisee:'Direct / Head Office',rm:'Unassigned',category:'Retail',preferredContact:'WhatsApp',dob:'',gender:'Prefer not to say',occupation:'',annualIncome:'₹5L–₹10L',kycStatus:'Not Started',panAvailable:false,consent:false,productInterests:[],status:'New'}

function CustomerForm({customer,customers,onClose,onSave}:{customer:AdminCustomer|null;customers:AdminCustomer[];onClose:()=>void;onSave:(draft:CustomerDraft)=>void}){
  const [draft,setDraft]=useState<CustomerDraft>(customer?toDraft(customer):blankDraft),[section,setSection]=useState<FormSection>('Address'),[error,setError]=useState('')
  const update=<K extends keyof CustomerDraft>(key:K,value:CustomerDraft[K])=>setDraft(current=>({...current,[key]:value})),toggle=(product:ProductType)=>update('productInterests',draft.productInterests.includes(product)?draft.productInterests.filter(item=>item!==product):[...draft.productInterests,product])
  const submit=()=>{const message=validate(5,draft);if(message){setError(message);const failed=[1,2,3,4].find(step=>validate(step,draft));if(failed===2)setSection('Address');if(failed===3)setSection('Ownership');if(failed===4)setSection('Profile & KYC');return}onSave(draft)}
  const franchisees=['Direct / Head Office',...Array.from(new Set(customers.map(item=>item.franchisee))).filter(item=>item!=='Direct / Head Office')],rms=['Unassigned',...Array.from(new Set(customers.map(item=>item.rm))).filter(item=>item!=='Unassigned')]
  return <div className="admin-customer-form-page tf-onboarding-organized"><button className="tf-360-back" onClick={onClose}><ArrowLeft/> {customer?'Back to Customer 360':'Back to Customers'}</button><PageHeader eyebrow="CUSTOMER MANAGEMENT" title={customer?'Edit Customer':'Add New Customer'} description={customer?'Update the Admin customer record and ownership context.':'Create a complete customer relationship record across the Admin network.'}/><form className="tf-wizard-form tf-organized-form" onSubmit={event=>{event.preventDefault();submit()}}><div className="tf-wizard-scroll">
    <FormPanel title="Basic Information" copy="Identity and customer classification remain visible while completing the form."><div className="form-row"><Field label="Customer Type"><select value={draft.type} onChange={e=>update('type',e.target.value as CustomerType)}><option>Individual</option><option>Business</option></select></Field><Field label="Status"><select value={draft.status} onChange={e=>update('status',e.target.value as AdminCustomerStatus)}>{statuses.map(item=><option key={item}>{item}</option>)}</select></Field></div>{draft.type==='Business'?<><Field label="Business / Company Name"><input value={draft.businessName} onChange={e=>update('businessName',e.target.value)}/></Field><div className="form-row"><Field label="Business Type"><input value={draft.businessType} onChange={e=>update('businessType',e.target.value)}/></Field><Field label="Contact Person"><input value={draft.contactPerson} onChange={e=>update('contactPerson',e.target.value)}/></Field></div></>:<><div className="form-row three"><Field label="Title"><select value={draft.title} onChange={e=>update('title',e.target.value)}>{['Mr','Ms','Mrs','Dr'].map(item=><option key={item}>{item}</option>)}</select></Field><Field label="First Name"><input value={draft.firstName} onChange={e=>update('firstName',e.target.value)}/></Field><Field label="Middle Name (optional)"><input value={draft.middleName} onChange={e=>update('middleName',e.target.value)}/></Field></div><Field label="Last Name"><input value={draft.lastName} onChange={e=>update('lastName',e.target.value)}/></Field></>}<div className="form-row"><Field label="Date of Birth / Incorporation"><input type="date" value={draft.dob} onChange={e=>update('dob',e.target.value)}/></Field>{draft.type==='Individual'&&<Field label="Gender"><select value={draft.gender} onChange={e=>update('gender',e.target.value)}>{['Male','Female','Other','Prefer not to say'].map(item=><option key={item}>{item}</option>)}</select></Field>}</div></FormPanel>
    <FormPanel title="Contact Information" copy="Primary contact details remain visible at all times."><div className="form-row three"><Field label="Primary Mobile"><input value={draft.mobile} onChange={e=>update('mobile',e.target.value)}/></Field><Field label="Alternate Mobile"><input value={draft.alternateMobile} onChange={e=>update('alternateMobile',e.target.value)}/></Field><Field label="Preferred Contact"><select value={draft.preferredContact} onChange={e=>update('preferredContact',e.target.value)}>{['Phone','WhatsApp','Email'].map(item=><option key={item}>{item}</option>)}</select></Field></div><Field label="Email"><input type="email" value={draft.email} onChange={e=>update('email',e.target.value)}/></Field></FormPanel>
    <div className="tf-additional-heading admin-additional-heading"><div><span>ADDITIONAL INFORMATION</span><h3>Complete the customer profile</h3><p>Only one additional section opens at a time. Your entered information is retained when switching.</p></div></div><nav className="tf-section-selector admin-form-selector">{formSections.map(item=><button type="button" className={section===item?'active':''} onClick={()=>setSection(item)} key={item}><i>{formSectionIcons[item]}</i><span><b>{item}</b><small>{sectionStatus(item,draft)}</small></span></button>)}</nav>
    <section className="tf-active-form-section admin-active-form-section">{section==='Address'&&<Address draft={draft} update={update}/>} {section==='Ownership'&&<Ownership draft={draft} update={update} franchisees={franchisees} rms={rms}/>} {section==='Profile & KYC'&&<Profile draft={draft} update={update} toggle={toggle}/>} {section==='Review'&&<Review draft={draft}/>}</section>{error&&<p className="customer-form-error tf-wizard-error"><AlertTriangle/>{error}</p>}</div><footer className="tf-wizard-actions admin-customer-form-actions"><span/><button type="button" className="tf-secondary" onClick={onClose}>Cancel</button><button className="tf-primary"><Check/> {customer?'Save Changes':'Add Customer'}</button></footer></form></div>
}

function Address({draft,update}:{draft:CustomerDraft;update:Updater}){return <><h2>Address</h2><Field label="Address Line 1"><input value={draft.address} onChange={e=>update('address',e.target.value)}/></Field><Field label="Address Line 2"><input value={draft.addressLine2} onChange={e=>update('addressLine2',e.target.value)}/></Field><div className="form-row three"><Field label="City"><input value={draft.city} onChange={e=>update('city',e.target.value)}/></Field><Field label="State"><input value={draft.state} onChange={e=>update('state',e.target.value)}/></Field><Field label="Pincode"><input value={draft.pincode} onChange={e=>update('pincode',e.target.value)}/></Field></div><Field label="Country"><input disabled value={draft.country}/></Field></>}
function Ownership({draft,update,franchisees,rms}:{draft:CustomerDraft;update:Updater;franchisees:string[];rms:string[]}){return <><h2>Relationship & Ownership</h2><div className="form-row"><Field label="Lead Source"><select value={draft.source} onChange={e=>update('source',e.target.value)}>{customerSources.map(item=><option key={item}>{item}</option>)}</select></Field><Field label="Customer Category"><select value={draft.category} onChange={e=>update('category',e.target.value)}>{customerCategories.map(item=><option key={item}>{item}</option>)}</select></Field></div><Field label="Business Source / Franchisee"><select value={draft.franchisee} onChange={e=>update('franchisee',e.target.value)}>{franchisees.map(item=><option key={item}>{item}</option>)}</select></Field><div className="form-row"><Field label="Relationship Manager"><select value={draft.rm} onChange={e=>update('rm',e.target.value)}>{rms.map(item=><option key={item}>{item}</option>)}</select></Field><Field label="Preferred Contact"><select value={draft.preferredContact} onChange={e=>update('preferredContact',e.target.value)}>{['WhatsApp','Phone','Email'].map(item=><option key={item}>{item}</option>)}</select></Field></div></>}
function Profile({draft,update,toggle}:{draft:CustomerDraft;update:Updater;toggle:(p:ProductType)=>void}){return <><h2>Profile, KYC & Interests</h2><div className="form-row"><Field label="Occupation / Business Type"><input value={draft.occupation} onChange={e=>update('occupation',e.target.value)}/></Field><Field label="Annual Income"><select value={draft.annualIncome} onChange={e=>update('annualIncome',e.target.value)}>{['Below ₹5L','₹5L–₹10L','₹10L–₹15L','₹15L–₹25L','₹25L+'].map(item=><option key={item}>{item}</option>)}</select></Field></div><Field label="KYC Status"><select value={draft.kycStatus} onChange={e=>update('kycStatus',e.target.value as AdminKycStatus)}>{['Not Started','Pending','Needs Review','Complete'].map(item=><option key={item}>{item}</option>)}</select></Field><fieldset className="customer-interest-field"><legend>Products Interested In</legend><div>{customerProducts.map(product=><label key={product}><input type="checkbox" checked={draft.productInterests.includes(product)} onChange={()=>toggle(product)}/><span>{product}</span></label>)}</div></fieldset><label className="checkbox-line"><input type="checkbox" checked={draft.panAvailable} onChange={e=>update('panAvailable',e.target.checked)}/><span>PAN is available (full PAN will not be displayed)</span></label><label className="checkbox-line"><input type="checkbox" checked={draft.consent} onChange={e=>update('consent',e.target.checked)}/><span>Customer has agreed to receive service-related communication.</span></label></>}
function Review({draft}:{draft:CustomerDraft}){return <><h2>Review Customer</h2><div className="customer-review-card"><Info label="Customer" value={draftName(draft)||'Not entered'}/><Info label="Contact" value={`${draft.mobile||'Not entered'} · ${draft.email||'Not entered'}`}/><Info label="Location" value={[draft.city,draft.state,draft.pincode].filter(Boolean).join(', ')||'Not entered'}/><Info label="Ownership" value={`${draft.franchisee} · ${draft.rm}`}/><Info label="KYC" value={draft.kycStatus}/><Info label="Interests" value={draft.productInterests.join(', ')||'None selected'}/></div></>}

type Updater=<K extends keyof CustomerDraft>(key:K,value:CustomerDraft[K])=>void
function FormPanel({title,copy,children}:{title:string;copy:string;children:ReactNode}){return <section className="tf-fixed-form-section admin-fixed-form-section"><header className="tf-step-intro"><h3>{title}</h3><p>{copy}</p></header>{children}</section>}
function Field({label,children}:{label:string;children:ReactNode}){return <label>{label}{children}</label>}
function Info({label,value}:{label:string;value:string}){return <div><span>{label}</span><b>{value||'—'}</b></div>}
function FollowUpForm({customer,onCancel,onSave}:{customer:AdminCustomer;onCancel:()=>void;onSave:(item:CustomerFollowUp)=>void}){const [type,setType]=useState('Call'),[date,setDate]=useState('2026-09-08'),[time,setTime]=useState('11:00'),[note,setNote]=useState(''),[assignedTo,setAssignedTo]=useState(customer.rm);return <form className="customer-followup-form admin-followup" onSubmit={event=>{event.preventDefault();onSave({id:`FU-${Date.now()}`,type,date:displayDate(date),time,note,assignedTo})}}><b>Schedule follow-up</b><label>Type<select value={type} onChange={e=>setType(e.target.value)}>{['Call','Meeting','Email','WhatsApp','Document Follow-up','Renewal Discussion','Cross-sell Discussion'].map(item=><option key={item}>{item}</option>)}</select></label><label>Date<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Time<input required type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label>Assigned to<input required value={assignedTo} onChange={e=>setAssignedTo(e.target.value)}/></label><label className="followup-note">Note<input required value={note} onChange={e=>setNote(e.target.value)}/></label><div><button type="button" onClick={onCancel}>Cancel</button><button className="primary-btn">Save Follow-up</button></div></form>}
function SamplePreview({title,customer,onClose}:{title:string;customer:AdminCustomer;onClose:()=>void}){return <div className="admin-preview-wrap"><button className="drawer-scrim" onClick={onClose}/><section className="admin-preview"><header><div><span>SAMPLE / DEMO</span><h2>{title}</h2><p>No previewable file is stored for this document.</p></div><button className="icon-button" onClick={onClose}><X/></button></header><div><FileText/><dl><Info label="Customer" value={customer.name}/><Info label="Document" value={title}/><Info label="Reference" value={customer.documents.find(item=>item.name===title)?.reference||'Not recorded'}/><Info label="Status" value={customer.documents.find(item=>item.name===title)?.status||'Pending'}/></dl><p>This is a sample preview for demonstration purposes only.</p></div></section></div>}
function kycTone(status:AdminKycStatus):'green'|'amber'|'red'|'blue'|'gray'{return status==='Complete'?'green':status==='Needs Review'?'red':status==='Pending'?'amber':'gray'}
function productsFor(customer:AdminCustomer,apps:Application[]){return Array.from(new Set([...customer.productInterests,...apps.filter(app=>app.customer===customer.name).map(app=>app.product)]))}
function isInvestment(app:Application){return ['Mutual Fund','Demat','Research','Advisory'].includes(app.product)}
function isLoan(app:Application){return app.product==='Loans'||app.product==='Loan Protector'}
function isInvestmentProduct(product:ProductType){return ['Mutual Fund','Demat','Research','Advisory'].includes(product)}
function isLoanProduct(product:ProductType){return product==='Loans'||product==='Loan Protector'}
function total(rows:Application[]){return rows.reduce((sum,item)=>sum+item.amount,0)}
const adminProductDocumentLabels:Record<ProductType,string>={Insurance:'Policy',Loans:'Sanction Letter','Loan Protector':'Policy / Certificate','Mutual Fund':'Statement',Demat:'Account Statement',Research:'Confirmation',Advisory:'Agreement'}
function friendlyAdminCategory(product:ProductType){return product==='Mutual Fund'||product==='Demat'||product==='Research'||product==='Advisory'?'Investment':product}
function adminProductDocument(customer:AdminCustomer,item:Application):AdminProductPreview{const label=adminProductDocumentLabels[item.product];return {title:`SAMPLE ${label.toUpperCase()}`,label,fields:[{label:'Customer Name',value:customer.name},{label:'Product',value:item.productName},{label:'Product Type',value:item.product},{label:'Company / Provider',value:item.provider||'Not recorded'},{label:'Reference',value:item.id},{label:'Value / Cover / Outstanding',value:formatINR(item.amount)},{label:'Status',value:item.status}]}}
function adminRenewalsFor(customer:AdminCustomer):AdminRenewalRow[]{const today=new Date();today.setHours(0,0,0,0);return customer.policies.filter(policy=>!['expired','lapsed'].includes(policy.status.toLowerCase())&&Boolean(policy.renewalDate)).map(policy=>{const due=new Date(`${policy.renewalDate}T00:00:00`),daysRemaining=Math.ceil((due.getTime()-today.getTime())/86_400_000),status:AdminRenewalRow['status']=daysRemaining<0?'Overdue':daysRemaining<=30?'Due Soon':'Upcoming';return {id:policy.id,product:policy.planName||policy.category,provider:policy.insurer,policyNumber:policy.policyNumber,renewalDueDate:policy.renewalDate,daysRemaining,currentPremium:policy.premiumAmount||0,status,lastFollowUp:'Not recorded'}}).filter(row=>Number.isFinite(row.daysRemaining)&&row.daysRemaining<=30)}
function initials(name:string){return name.split(' ').map(part=>part[0]).join('').slice(0,2).toUpperCase()}
function draftName(draft:CustomerDraft){return draft.type==='Business'?draft.businessName.trim():`${draft.firstName} ${draft.middleName} ${draft.lastName}`.replace(/\s+/g,' ').trim()}
function displayDate(value:string){if(!value)return '';const [year,month,day]=value.split('-');return new Date(Number(year),Number(month)-1,Number(day)).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}
function fromOnboardingDraft(draft:CustomerOnboardingDraft,ownership:CustomerOwnershipDraft,base:AdminCustomer):AdminCustomer{
  const address=draft.contact.currentAddress
  const name=draft.customerType==='Business'?draft.basic.businessName?.trim()||'Unnamed Business':[draft.basic.firstName,draft.basic.middleName,draft.basic.lastName].filter(Boolean).join(' ')
  const kycStatus:AdminKycStatus=draft.kyc.status==='Complete'?'Complete':draft.kyc.status==='Not Started'?'Not Started':'Pending'
  const productInterests=adminProductInterests(draft)
  const createdAt=displayDate(draft.basic.customerSince||new Date().toISOString().slice(0,10))
  return {...base,name,type:draft.customerType,title:draft.basic.title,middleName:draft.basic.middleName,businessType:draft.basic.entityType,contactPerson:draft.basic.primaryContact,email:draft.contact.email,mobile:draft.contact.primaryMobile,alternateMobile:draft.contact.alternateMobile,address:address.line1,addressLine2:[address.line2,address.landmark].filter(Boolean).join(', '),city:address.city,state:address.state,pincode:address.pinCode,source:draft.preferences.source,franchisee:ownership.franchisee,rm:ownership.relationshipManager,category:draft.preferences.category,preferredContact:draft.preferences.preferredContactMethod,dob:displayDate(draft.customerType==='Business'?draft.basic.incorporationDate||'':draft.basic.dateOfBirth||''),gender:draft.customerType==='Individual'?draft.basic.gender||'':'',occupation:draft.customerType==='Business'?draft.basic.businessActivity||draft.basic.industry||'':draft.profile.occupation||draft.profile.designation||'',annualIncome:draft.financial.annualIncomeRange||'',kycStatus,status:statuses.includes(ownership.status as AdminCustomerStatus)?ownership.status as AdminCustomerStatus:'New',createdAt,lastActivityAt:'Just now',nextFollowUpAt:'Not scheduled',productInterests,attentionReasons:kycStatus==='Pending'?['KYC documents require attention']:[],businessValue:draft.financial.netWorth||draft.investments.reduce((sum,item)=>sum+(item.currentValue||0),0),activeApplications:0,documents:draft.documents.map(document=>({name:document.documentType,status:document.status==='Verified'||document.status==='Uploaded'?'Available':document.status==='Expired'?'Needs Review':'Pending',reference:document.documentNumber})),followUps:[],activity:[{id:`ACT-${Date.now()}`,title:'Customer added to directory',detail:`Source: ${draft.preferences.source} · ${ownership.franchisee}`,timestamp:'Just now'}],relationshipNotes:draft.preferences.notes?[draft.preferences.notes]:['Customer record created; add relationship context after the first interaction.'],policies:draft.policies,onboardingProfile:draft}
}
function adminProductInterests(draft:CustomerOnboardingDraft):ProductType[]{
  const values=new Set<ProductType>()
  const add=(value:string)=>{if(value.includes('Insurance'))values.add('Insurance');if(value.includes('Loan'))values.add(value==='Loan Protector'?'Loan Protector':'Loans');if(value==='Mutual Funds'||value==='Mutual Fund'||value==='SIP')values.add('Mutual Fund');if(value==='Demat'||value==='Stocks')values.add('Demat');if(value==='Wealth Management')values.add('Advisory')}
  draft.preferences.interests.forEach(add);draft.policies.forEach(policy=>add(policy.category));draft.loans.forEach(loan=>add(loan.loanType));draft.investments.forEach(investment=>add(investment.investmentType));return [...values]
}
function validate(step:number,draft:CustomerDraft):string{if(step===1&&(draft.type==='Individual'?(!draft.firstName.trim()||!draft.lastName.trim()):(!draft.businessName.trim()||!draft.contactPerson.trim())))return draft.type==='Business'?'Enter the business name and contact person.':'Enter the customer first and last name.';if(step===2&&(!isIndianMobile(draft.mobile)||!/^\S+@\S+\.\S+$/.test(draft.email)||!draft.city.trim()||!draft.address.trim()))return 'Enter a valid 10-digit Indian mobile, email, address and city.';if(step===3&&(!draft.franchisee||!draft.rm))return 'Choose the franchisee and relationship manager.';if(step===4&&!draft.consent)return 'Record customer consent before continuing.';if(step===5)return validate(1,draft)||validate(2,draft)||validate(3,draft)||validate(4,draft);return ''}
function sectionStatus(section:FormSection,draft:CustomerDraft){if(section==='Address')return draft.address&&draft.city?'Complete':'Required';if(section==='Ownership')return draft.franchisee&&draft.rm?'Complete':'Required';if(section==='Profile & KYC')return draft.consent?'Complete':draft.occupation||draft.productInterests.length?'In progress':'Not started';return validate(5,draft)?'Needs attention':'Ready to save'}
function toDraft(customer:AdminCustomer):CustomerDraft{const [firstName,...rest]=customer.name.split(' ');return {type:customer.type,title:customer.title||'Mr',firstName,middleName:customer.middleName||'',lastName:rest.join(' '),businessName:customer.type==='Business'?customer.name:'',businessType:customer.businessType||'',contactPerson:customer.contactPerson||'',email:customer.email,mobile:customer.mobile,alternateMobile:customer.alternateMobile||'',address:customer.address,addressLine2:customer.addressLine2||'',city:customer.city,state:customer.state,pincode:customer.pincode,country:'India',source:customer.source,franchisee:customer.franchisee,rm:customer.rm,category:customer.category,preferredContact:customer.preferredContact,dob:'',gender:customer.gender,occupation:customer.occupation,annualIncome:customer.annualIncome,kycStatus:customer.kycStatus,panAvailable:customer.documents.some(doc=>doc.name==='PAN'&&doc.status==='Available'),consent:true,productInterests:[...customer.productInterests],status:customer.status}}
function fromDraft(draft:CustomerDraft,base:AdminCustomer):AdminCustomer{const attentionReasons=[...(draft.kycStatus==='Pending'||draft.kycStatus==='Needs Review'?['KYC documents require attention']:[]),...(draft.status==='Follow-up Required'?['Relationship follow-up is due']:[])];return {...base,name:draftName(draft),type:draft.type,title:draft.title,middleName:draft.middleName,businessType:draft.businessType,contactPerson:draft.contactPerson,email:draft.email,mobile:draft.mobile,alternateMobile:draft.alternateMobile||undefined,address:draft.address,addressLine2:draft.addressLine2,city:draft.city,state:draft.state,pincode:draft.pincode,source:draft.source,franchisee:draft.franchisee,rm:draft.rm,category:draft.category,preferredContact:draft.preferredContact,dob:draft.dob?displayDate(draft.dob):base.dob,gender:draft.gender,occupation:draft.occupation||draft.businessType,annualIncome:draft.annualIncome,kycStatus:draft.kycStatus,status:draft.status,productInterests:draft.productInterests,attentionReasons,relationshipNotes:base.relationshipNotes.length?base.relationshipNotes:['Customer record created; add relationship context after the first interaction.'],documents:[{name:'PAN',status:draft.panAvailable?'Available':'Pending',reference:draft.panAvailable?'A•••••4K':undefined},{name:'Aadhaar',status:'Pending'},{name:'Address Proof',status:'Pending'},{name:'Bank Proof',status:'Pending'},{name:'Photo',status:'Pending'},{name:'Other',status:'Pending'}],lastActivityAt:'Just now',activity:[{id:`ACT-${Date.now()}`,title:'Customer profile updated',detail:'Contact, relationship or profile details changed',timestamp:'Just now'},...base.activity]}}
function isIndianMobile(value:string){const digits=value.replace(/\D/g,'');return digits.length===10||digits.length===12&&digits.startsWith('91')}
const emptyCustomer:AdminCustomer={id:'',name:'',type:'Individual',email:'',mobile:'',city:'',state:'',address:'',pincode:'',status:'New',kycStatus:'Not Started',franchisee:'Direct / Head Office',rm:'Unassigned',source:'Website',category:'Retail',preferredContact:'WhatsApp',dob:'',gender:'',occupation:'',annualIncome:'',createdAt:'',lastActivityAt:'',nextFollowUpAt:'Not scheduled',productInterests:[],attentionReasons:[],businessValue:0,activeApplications:0,documents:[],followUps:[],activity:[],relationshipNotes:[],policies:[]}
