import { useEffect, useMemo, useState, type Dispatch, type SetStateAction } from 'react'
import { ArrowRight, BriefcaseBusiness, Calculator, CalendarDays, Car, CircleDollarSign, Ellipsis, GraduationCap, Home, Landmark, MapPin, Pencil, PiggyBank, Plus, ShieldCheck, Target, Trash2, TrendingUp, X } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { PageHeader, StatusBadge } from '../components/UI'
import { formatINR } from '../data/mockData'
import { getGoalMetrics, goalCategories, goalPriorities, goalStatuses, normaliseGoalStatus, priorityRank, type CustomerGoal, type GoalCategory, type GoalPriority, type GoalStatus } from '../data/customerGoalsData'

interface Props { goals:CustomerGoal[]; setGoals:Dispatch<SetStateAction<CustomerGoal[]>>; onNavigate:(page:string,filter?:string)=>void; onToast:(message:string)=>void }
type Filter='All Goals'|'Active'|'Completed'|'Paused'
type Draft={name:string;category:GoalCategory;targetAmount:string;currentAmount:string;targetDate:string;priority:GoalPriority;status:GoalStatus;monthlyContribution:string;expectedReturn:string;linkedProduct:string;notes:string}
const iconMap:Record<GoalCategory,LucideIcon>={
  'Emergency Fund':ShieldCheck,Home,Car,'Child Education':GraduationCap,Retirement:PiggyBank,Travel:MapPin,Wedding:CircleDollarSign,'Wealth Creation':TrendingUp,Business:BriefcaseBusiness,Other:Target
}
const emptyDraft:Draft={name:'',category:'Emergency Fund',targetAmount:'',currentAmount:'0',targetDate:'',priority:'Medium',status:'On Track',monthlyContribution:'0',expectedReturn:'10',linkedProduct:'',notes:''}
const toDraft=(goal:CustomerGoal):Draft=>({name:goal.name,category:goal.category,targetAmount:String(goal.targetAmount),currentAmount:String(goal.currentAmount),targetDate:goal.targetDate,priority:goal.priority,status:goal.status,monthlyContribution:String(goal.monthlyContribution??0),expectedReturn:String(goal.expectedReturn??10),linkedProduct:goal.linkedProduct??'',notes:goal.notes??''})
const readableDate=(value:string,monthOnly=false)=>new Intl.DateTimeFormat('en-IN',monthOnly?{month:'short',year:'numeric'}:{day:'numeric',month:'short',year:'numeric'}).format(new Date(value.includes('T')?value:`${value}T12:00:00`))
const sortGoals=(items:CustomerGoal[])=>[...items].sort((a,b)=>priorityRank[a.priority]-priorityRank[b.priority]||a.targetDate.localeCompare(b.targetDate)||(b.updatedAt??b.createdAt).localeCompare(a.updatedAt??a.createdAt))

export function CustomerGoals({goals,setGoals,onNavigate,onToast}:Props){
  const [filter,setFilter]=useState<Filter>('All Goals')
  const [selected,setSelected]=useState<CustomerGoal|null>(null)
  const [editing,setEditing]=useState<CustomerGoal|null|undefined>(undefined)
  const [progressGoal,setProgressGoal]=useState<CustomerGoal|null>(null)
  const [deleteGoal,setDeleteGoal]=useState<CustomerGoal|null>(null)
  const [more,setMore]=useState<string|null>(null)
  useEffect(()=>{if(sessionStorage.getItem('troth-goals-add')==='true'){sessionStorage.removeItem('troth-goals-add');setEditing(null)}const id=sessionStorage.getItem('troth-open-goal');if(id){sessionStorage.removeItem('troth-open-goal');setSelected(goals.find(goal=>goal.id===id)??null)}},[])
  const active=goals.filter(goal=>!['Completed','Paused'].includes(normaliseGoalStatus(goal)))
  const monthlyNeed=active.reduce((sum,goal)=>sum+getGoalMetrics(goal).estimatedMonthlyContribution,0)
  const visible=sortGoals(goals.filter(goal=>filter==='All Goals'||filter==='Active'&&!['Completed','Paused'].includes(normaliseGoalStatus(goal))||normaliseGoalStatus(goal)===filter))
  const save=(goal:CustomerGoal)=>{setGoals(current=>current.some(item=>item.id===goal.id)?current.map(item=>item.id===goal.id?goal:item):[goal,...current]);setEditing(undefined);setSelected(goal);onToast(editing?'Goal updated successfully':'Goal created successfully')}
  const togglePause=(goal:CustomerGoal)=>{const status=goal.status==='Paused'?'On Track':'Paused';setGoals(current=>current.map(item=>item.id===goal.id?{...item,status,updatedAt:new Date().toISOString()}:item));setSelected(current=>current?.id===goal.id?{...current,status}:current);setMore(null);onToast(status==='Paused'?'Goal paused':'Goal resumed')}
  const remove=()=>{if(!deleteGoal)return;setGoals(current=>current.filter(goal=>goal.id!==deleteGoal.id));setSelected(null);setDeleteGoal(null);onToast('Goal deleted')}
  return <div className="page customer-goals-page">
    <PageHeader eyebrow="FINANCIAL PLANNING" title="My Goals" description="Set financial goals, track progress and understand what it may take to reach them." actions={<><button className="secondary-btn" onClick={()=>onNavigate('calculator')}><Calculator/> Goal Calculator</button><button className="primary-btn" onClick={()=>setEditing(null)}><Plus/> Add Goal</button></>}/>
    <section className="goals-summary-grid">
      <Summary icon={Target} label="Active Goals" value={String(active.length)} meta={`${goals.length-active.length} completed or paused`}/>
      <Summary icon={Landmark} label="Total Target" value={formatINR(goals.reduce((sum,goal)=>sum+goal.targetAmount,0),true)} meta="Across all goals"/>
      <Summary icon={PiggyBank} label="Saved Towards Goals" value={formatINR(goals.reduce((sum,goal)=>sum+goal.currentAmount,0),true)} meta="Current progress"/>
      <Summary icon={TrendingUp} label="Estimated Monthly Need" value={formatINR(monthlyNeed)} meta="Active goals only"/>
    </section>
    <div className="goals-toolbar"><div>{(['All Goals','Active','Completed','Paused'] as Filter[]).map(item=><button className={filter===item?'active':''} onClick={()=>setFilter(item)} key={item}>{item}<span>{item==='All Goals'?goals.length:item==='Active'?active.length:goals.filter(goal=>normaliseGoalStatus(goal)===item).length}</span></button>)}</div></div>
    {visible.length?<section className="goal-card-grid">{visible.map(goal=><GoalCard key={goal.id} goal={goal} more={more===goal.id} onView={()=>setSelected(goal)} onEdit={()=>setEditing(goal)} onMore={()=>setMore(more===goal.id?null:goal.id)} onPause={()=>togglePause(goal)} onDelete={()=>setDeleteGoal(goal)}/>)}</section>:<div className="goals-empty"><Target/><h3>No {filter.toLowerCase()}</h3><p>Create a goal or choose another filter to see your plan.</p><button className="primary-btn" onClick={()=>setEditing(null)}><Plus/> Add Goal</button></div>}
    {selected&&<GoalDetails goal={goals.find(goal=>goal.id===selected.id)??selected} onClose={()=>setSelected(null)} onEdit={()=>setEditing(goals.find(goal=>goal.id===selected.id)??selected)} onProgress={()=>setProgressGoal(goals.find(goal=>goal.id===selected.id)??selected)} onPause={()=>togglePause(goals.find(goal=>goal.id===selected.id)??selected)} onDelete={()=>setDeleteGoal(goals.find(goal=>goal.id===selected.id)??selected)} onNavigate={onNavigate}/>} 
    {editing!==undefined&&<GoalEditor goal={editing} onClose={()=>setEditing(undefined)} onSave={save}/>} 
    {progressGoal&&<ProgressModal goal={progressGoal} onClose={()=>setProgressGoal(null)} onSave={(currentAmount,monthlyContribution)=>{const updated={...progressGoal,currentAmount,monthlyContribution,status:normaliseGoalStatus({...progressGoal,currentAmount}),updatedAt:new Date().toISOString()};setGoals(current=>current.map(goal=>goal.id===updated.id?updated:goal));setSelected(updated);setProgressGoal(null);onToast('Goal progress updated')}}/>}
    {deleteGoal&&<ConfirmDelete goal={deleteGoal} onClose={()=>setDeleteGoal(null)} onDelete={remove}/>} 
  </div>
}

function Summary({icon:Icon,label,value,meta}:{icon:LucideIcon;label:string;value:string;meta:string}){return <article className="goal-summary-card"><span><Icon/></span><div><small>{label}</small><strong>{value}</strong><p>{meta}</p></div></article>}

function GoalCard({goal,more,onView,onEdit,onMore,onPause,onDelete}:{goal:CustomerGoal;more:boolean;onView:()=>void;onEdit:()=>void;onMore:()=>void;onPause:()=>void;onDelete:()=>void}){
  const Icon=iconMap[goal.category], metrics=getGoalMetrics(goal), status=normaliseGoalStatus(goal)
  return <article className={`goal-card goal-status-${status.toLowerCase().replaceAll(' ','-')}`}><div className="goal-card-top"><span className="goal-category-icon"><Icon/></span><div><small>{goal.category}</small><h3>{goal.name}</h3></div><button className="goal-more-btn" aria-label="More goal actions" onClick={onMore}><Ellipsis/></button>{more&&<div className="goal-more-menu"><button onClick={onPause}>{status==='Paused'?'Resume Goal':'Pause Goal'}</button><button className="danger" onClick={onDelete}><Trash2/> Delete Goal</button></div>}</div><div className="goal-badges"><span className={`goal-priority priority-${goal.priority.toLowerCase()}`}>{goal.priority} priority</span><StatusBadge status={status}/></div><div className="goal-amounts"><div><span>Target</span><b>{formatINR(goal.targetAmount)}</b></div><div><span>Current</span><b>{formatINR(goal.currentAmount)}</b></div></div><div className="goal-progress-label"><span>Progress</span><b>{Math.round(metrics.progress)}%</b></div><div className="goal-progress"><i style={{width:`${metrics.progress}%`}}/></div><div className="goal-facts"><div><CalendarDays/><span>Target Date<b>{readableDate(goal.targetDate,true)}</b></span></div><div><CircleDollarSign/><span>Remaining<b>{formatINR(metrics.remaining)}</b></span></div><div><TrendingUp/><span>Estimated Monthly Need<b>{formatINR(metrics.estimatedMonthlyContribution)}</b></span></div></div><div className="goal-card-actions"><button onClick={onView}>View Details <ArrowRight/></button><button onClick={onEdit}><Pencil/> Edit</button><button onClick={onMore}>More</button></div></article>
}

function GoalDetails({goal,onClose,onEdit,onProgress,onPause,onDelete,onNavigate}:{goal:CustomerGoal;onClose:()=>void;onEdit:()=>void;onProgress:()=>void;onPause:()=>void;onDelete:()=>void;onNavigate:(page:string)=>void}){
  const [tab,setTab]=useState<'Overview'|'Plan'|'Activity & Notes'>('Overview'), metrics=getGoalMetrics(goal), status=normaliseGoalStatus(goal)
  return <><button className="drawer-scrim" aria-label="Close goal details" onClick={onClose}/><aside className="detail-drawer goal-detail-drawer"><div className="drawer-header"><div><span className="eyebrow">{goal.category.toUpperCase()}</span><h2>{goal.name}</h2><p>Your current plan and progress</p></div><button className="icon-button" onClick={onClose}><X/></button></div><div className="drawer-summary"><span className={`goal-priority priority-${goal.priority.toLowerCase()}`}>{goal.priority} priority</span><StatusBadge status={status}/></div><div className="drawer-tabs">{(['Overview','Plan','Activity & Notes'] as const).map(item=><button className={tab===item?'active':''} onClick={()=>setTab(item)} key={item}>{item}</button>)}</div><div className="drawer-body">
    {tab==='Overview'&&<section className="detail-section"><h3>Goal overview</h3><div className="detail-grid">{[['Category',goal.category],['Priority',goal.priority],['Status',status],['Target Amount',formatINR(goal.targetAmount)],['Current Amount',formatINR(goal.currentAmount)],['Progress',`${Math.round(metrics.progress)}%`],['Remaining',formatINR(metrics.remaining)],['Target Date',readableDate(goal.targetDate)],['Months Remaining',String(metrics.monthsRemaining)]].map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div></section>}
    {tab==='Plan'&&<><section className="detail-section"><h3>Financial plan</h3><div className="detail-grid"><div><span>Estimated Monthly Contribution</span><b>{formatINR(metrics.estimatedMonthlyContribution)}</b></div><div><span>Current Monthly Contribution</span><b>{formatINR(goal.monthlyContribution??0)}</b></div><div><span>Expected Return Assumption</span><b>{goal.expectedReturn??0}% p.a.</b></div><div><span>Linked Product</span><b>{goal.linkedProduct||'Not linked'}</b></div></div><p className="goal-disclaimer">Illustrative estimate only. Returns are not guaranteed and this is not investment advice.</p></section><div className="goal-plan-actions"><button className="secondary-btn" onClick={()=>{if(goal.linkedProduct)sessionStorage.setItem('troth-product-filter',goal.linkedProduct);onNavigate('my-products')}}>Explore Products</button><button className="secondary-btn" onClick={()=>onNavigate('calculator')}><Calculator/> Use Goal Calculator</button></div></>}
    {tab==='Activity & Notes'&&<><section className="detail-section"><h3>Notes</h3><p>{goal.notes||'No notes added for this goal.'}</p></section><section className="detail-section"><h3>Activity</h3><div className="timeline">{goal.updatedAt&&<div><i/><p><b>Goal details or contribution updated</b><span>{readableDate(goal.updatedAt)}</span></p></div>}<div><i/><p><b>Goal created</b><span>{readableDate(goal.createdAt)}</span></p></div></div></section></>}
  </div><div className="drawer-actions goal-drawer-actions"><button className="secondary-btn" onClick={onProgress}>Update Progress</button><button className="primary-btn" onClick={onEdit}><Pencil/> Edit Goal</button><button className="secondary-btn" onClick={onPause}>{status==='Paused'?'Resume':'Pause'}</button><button className="goal-delete-icon" aria-label="Delete goal" onClick={onDelete}><Trash2/></button></div></aside></>
}

function GoalEditor({goal,onClose,onSave}:{goal:CustomerGoal|null;onClose:()=>void;onSave:(goal:CustomerGoal)=>void}){
  const [step,setStep]=useState(1),[draft,setDraft]=useState<Draft>(()=>goal?toDraft(goal):emptyDraft),[error,setError]=useState('')
  const set=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft(current=>({...current,[key]:value}))
  const preview=useMemo(()=>getGoalMetrics({...goal,id:goal?.id??'preview',name:draft.name,category:draft.category,targetAmount:Number(draft.targetAmount)||0,currentAmount:Number(draft.currentAmount)||0,targetDate:draft.targetDate||new Date().toISOString().slice(0,10),priority:draft.priority,status:draft.status,monthlyContribution:Number(draft.monthlyContribution)||0,expectedReturn:Number(draft.expectedReturn)||0,linkedProduct:draft.linkedProduct,notes:draft.notes,createdAt:goal?.createdAt??new Date().toISOString()}),[draft,goal])
  const next=()=>{if(step===1&&(!draft.name.trim()||Number(draft.targetAmount)<=0||!draft.targetDate)){setError('Complete all required goal details to continue.');return}setError('');setStep(value=>Math.min(3,value+1))}
  const submit=()=>{const now=new Date().toISOString();const candidate:CustomerGoal={id:goal?.id??`goal-${Date.now()}`,name:draft.name.trim(),category:draft.category,targetAmount:Number(draft.targetAmount),currentAmount:Number(draft.currentAmount)||0,targetDate:draft.targetDate,priority:draft.priority,status:draft.status,monthlyContribution:Number(draft.monthlyContribution)||0,expectedReturn:Number(draft.expectedReturn)||0,linkedProduct:draft.linkedProduct||undefined,notes:draft.notes.trim()||undefined,createdAt:goal?.createdAt??now,updatedAt:goal?now:undefined};candidate.status=normaliseGoalStatus(candidate);onSave(candidate)}
  return <><button className="drawer-scrim" aria-label="Close goal form" onClick={onClose}/><aside className="form-drawer goal-form-drawer"><div className="drawer-header"><div><span className="eyebrow">{goal?'UPDATE PLAN':'NEW FINANCIAL GOAL'}</span><h2>{goal?'Edit Goal':'Add Goal'}</h2><p>Build a clear, trackable financial plan.</p></div><button className="icon-button" onClick={onClose}><X/></button></div><div className="goal-stepper">{['Goal Details','Financial Plan','Review'].map((label,index)=><div className={step>=index+1?'active':''} key={label}><i>{index+1}</i><span>{label}</span></div>)}</div><div className="goal-form-body">
    {step===1&&<><h3>Goal Details</h3><label>Goal Name *<input value={draft.name} onChange={e=>set('name',e.target.value)} placeholder="e.g. Dream Home"/></label><div className="form-row"><label>Goal Category *<select value={draft.category} onChange={e=>set('category',e.target.value as GoalCategory)}>{goalCategories.map(item=><option key={item}>{item}</option>)}</select></label><label>Priority *<select value={draft.priority} onChange={e=>set('priority',e.target.value as GoalPriority)}>{goalPriorities.map(item=><option key={item}>{item}</option>)}</select></label></div><div className="form-row"><label>Target Amount *<input type="number" min="1" value={draft.targetAmount} onChange={e=>set('targetAmount',e.target.value)} placeholder="₹ 0"/></label><label>Target Date *<input type="date" value={draft.targetDate} onChange={e=>set('targetDate',e.target.value)}/></label></div><label>Notes<textarea value={draft.notes} onChange={e=>set('notes',e.target.value)} placeholder="Add context for this goal (optional)"/></label></>}
    {step===2&&<><h3>Financial Plan</h3><div className="form-row"><label>Current Amount Saved / Invested<input type="number" min="0" value={draft.currentAmount} onChange={e=>set('currentAmount',e.target.value)}/></label><label>Current Monthly Contribution<input type="number" min="0" value={draft.monthlyContribution} onChange={e=>set('monthlyContribution',e.target.value)}/></label></div><div className="form-row"><label>Expected Return %<input type="number" min="0" max="30" step="0.1" value={draft.expectedReturn} onChange={e=>set('expectedReturn',e.target.value)}/></label><label>Linked Product<select value={draft.linkedProduct} onChange={e=>set('linkedProduct',e.target.value)}><option value="">Not linked</option>{['Mutual Fund','Investment','Loan','Insurance','Other'].map(item=><option key={item}>{item}</option>)}</select></label></div>{goal&&<label>Status<select value={draft.status} onChange={e=>set('status',e.target.value as GoalStatus)}>{goalStatuses.map(item=><option key={item}>{item}</option>)}</select></label>}<Preview draft={draft} preview={preview}/></>}
    {step===3&&<><h3>Review Goal</h3><div className="goal-review-grid">{[['Goal',draft.name],['Category',draft.category],['Target',formatINR(Number(draft.targetAmount))],['Target Date',readableDate(draft.targetDate)],['Current Amount',formatINR(Number(draft.currentAmount))],['Priority',draft.priority],['Estimated Monthly Contribution',formatINR(preview.estimatedMonthlyContribution)],['Linked Product',draft.linkedProduct||'Not linked']].map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div><p className="goal-disclaimer">This estimate is illustrative and does not guarantee future returns.</p></>}
    {error&&<div className="goal-form-error">{error}</div>}
  </div><div className="form-actions goal-form-actions"><button type="button" className="secondary-btn" onClick={step===1?onClose:()=>setStep(value=>value-1)}>{step===1?'Cancel':'Back'}</button>{step<3?<button type="button" className="primary-btn" onClick={next}>Continue <ArrowRight/></button>:<button type="button" className="primary-btn" onClick={submit}>{goal?'Save Changes':'Create Goal'}</button>}</div></aside></>
}

function Preview({draft,preview}:{draft:Draft;preview:ReturnType<typeof getGoalMetrics>}){return <section className="goal-preview"><h4>Calculation Preview</h4><div>{[['Goal Target',formatINR(Number(draft.targetAmount)||0)],['Current Progress',formatINR(Number(draft.currentAmount)||0)],['Remaining',formatINR(preview.remaining)],['Time Remaining',`${preview.monthsRemaining} months`],['Estimated Monthly Contribution',formatINR(preview.estimatedMonthlyContribution)]].map(([label,value])=><span key={label}><small>{label}</small><b>{value}</b></span>)}</div></section>}

function ProgressModal({goal,onClose,onSave}:{goal:CustomerGoal;onClose:()=>void;onSave:(amount:number,monthly:number)=>void}){const [amount,setAmount]=useState(String(goal.currentAmount)),[monthly,setMonthly]=useState(String(goal.monthlyContribution??0));return <div className="modal-wrap"><button className="modal-scrim" onClick={onClose}/><form className="modal goal-progress-modal" onSubmit={event=>{event.preventDefault();onSave(Number(amount),Number(monthly))}}><div className="modal-heading"><div className="modal-icon"><TrendingUp/></div><div><span className="eyebrow">TRACK PROGRESS</span><h2>Update {goal.name}</h2></div><button type="button" className="icon-button" onClick={onClose}><X/></button></div><label>Current Amount *<input required type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Monthly Contribution<input type="number" min="0" value={monthly} onChange={e=>setMonthly(e.target.value)}/></label><div className="form-actions"><button type="button" className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn">Update Progress</button></div></form></div>}
function ConfirmDelete({goal,onClose,onDelete}:{goal:CustomerGoal;onClose:()=>void;onDelete:()=>void}){return <div className="modal-wrap"><button className="modal-scrim" onClick={onClose}/><div className="modal goal-delete-modal"><div className="modal-heading"><div className="modal-icon danger"><Trash2/></div><div><span className="eyebrow">REMOVE GOAL</span><h2>Delete this goal?</h2></div><button className="icon-button" onClick={onClose}><X/></button></div><p>This will remove <b>{goal.name}</b> from your goal plan.</p><div className="form-actions"><button className="secondary-btn" onClick={onClose}>Cancel</button><button className="danger-btn" onClick={onDelete}>Delete Goal</button></div></div></div>}
