import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, BriefcaseBusiness, Check, Download, FileText, HeartPulse, Landmark, PhoneCall, Search, ShieldCheck, TrendingUp, WalletCards, X } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { PageHeader, StatusBadge } from '../components/UI'
import { customerProductIds, productCatalogue, type CatalogueProduct } from '../data/productCatalogue'
import { customerProductService } from '../services/customerProductService'

const iconMap:Record<CatalogueProduct['icon'],LucideIcon>={shield:ShieldCheck,landmark:Landmark,heart:HeartPulse,trend:TrendingUp,wallet:WalletCards,file:FileText,briefcase:BriefcaseBusiness}
const filters=['All','Insurance','Loans','Loan Protector','Mutual Funds','Investments','Research / Advisory'] as const
type Filter=(typeof filters)[number]
interface PurchasedProductDetails {reference:string;facts:[string,string][];due:string;renewable?:boolean;policyDocumentId?:string;supportContactKey:string}
const ownershipDetails:Record<string,PurchasedProductDetails>={
  'health-insurance':{reference:'Policy HDF12345678',facts:[['Sum insured','₹25,00,000'],['Premium','₹18,750 / year'],['Insurer','HDFC ERGO']],due:'Expires 21 Sep 2026',renewable:true,policyDocumentId:'POL-HDF12345678',supportContactKey:'customer-support'},
  'home-loan':{reference:'Loan A/c ••••7192',facts:[['Sanctioned','₹25,00,000'],['Outstanding','₹19,80,000'],['EMI','₹35,000 / month']],due:'Next EMI 05 Sep 2026',supportContactKey:'customer-support'},
  'equity-mutual-fund':{reference:'Folio ••••5318',facts:[['Current value','₹8,75,430'],['Invested value','₹7,90,000'],['SIP','₹10,000 / month']],due:'Next SIP 15 Sep 2026',supportContactKey:'customer-support'}
}

export function CustomerProducts({onToast}:{onToast:(message:string)=>void}){
  const requested=sessionStorage.getItem('troth-product-filter')||'All'
  const aliases:Record<string,Filter>={'Demat':'Investments','PMS / AIF':'Investments','Bonds':'Investments','Research / Advisory':'Research / Advisory','Renewals':'Insurance'}
  const initial=(aliases[requested]||requested) as Filter
  const [filter,setFilter]=useState<Filter>(filters.includes(initial)?initial:'All')
  const [search,setSearch]=useState('')
  const [detail,setDetail]=useState<CatalogueProduct|null>(null)
  const [buyProduct,setBuyProduct]=useState<CatalogueProduct|null>(null)
  const [inquiryProduct,setInquiryProduct]=useState<CatalogueProduct|null>(null)
  const [inquiries,setInquiries]=useState<string[]>([])
  useEffect(()=>{sessionStorage.removeItem('troth-product-filter');const focus=sessionStorage.getItem('troth-product-focus');sessionStorage.removeItem('troth-product-focus');if(focus==='explore')window.setTimeout(()=>document.getElementById('explore-products')?.scrollIntoView({behavior:'smooth'}),120);else window.scrollTo(0,0)},[])
  const matches=(p:CatalogueProduct)=>filter==='All'||p.category===filter
  const matchesSearch=(p:CatalogueProduct)=>`${p.name} ${p.category} ${p.shortDescription}`.toLowerCase().includes(search.toLowerCase())
  const purchased=useMemo(()=>productCatalogue.filter(p=>customerProductIds.includes(p.id)&&matches(p)&&matchesSearch(p)),[filter,search])
  const explore=useMemo(()=>productCatalogue.filter(p=>p.status==='Active'&&!customerProductIds.includes(p.id)&&matches(p)&&matchesSearch(p)),[filter,search])
  const openBuy=(p:CatalogueProduct)=>{setDetail(null);setInquiryProduct(null);setBuyProduct(p)}
  const openInquiry=(p:CatalogueProduct)=>{setDetail(null);setBuyProduct(null);setInquiryProduct(p)}
  return <div className="page customer-products-page">
    <PageHeader eyebrow="MY FINANCIAL PRODUCTS" title="My Products" description="Manage your existing financial products and explore more solutions from Troth One." actions={<button className="secondary-btn" onClick={()=>onToast('Consolidated statement downloaded')}><Download size={17}/> Download statement</button>}/>
    <section className="customer-products-summary compact"><button onClick={()=>setFilter('All')}><span>Active products</span><strong>3</strong><small>Across protection, credit and investment</small></button><button onClick={()=>setFilter('Insurance')}><span>Upcoming renewals</span><strong>1</strong><small>Health policy • 21 Sep 2026</small></button><button onClick={()=>onToast('Active applications opened')}><span>Active applications</span><strong>3</strong><small>Across your recent requests</small></button><button onClick={()=>onToast('Pending actions opened')}><span>Pending actions</span><strong>2</strong><small>Your response is required</small></button></section>
    <div className="products-control-bar"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products..."/>{search&&<button onClick={()=>setSearch('')}><X/></button>}</label><div>{filters.map(item=><button key={item} className={filter===item?'active':''} onClick={()=>setFilter(item)}>{item}</button>)}</div></div>
    <section className="product-section purchased-section"><div className="product-section-heading"><div><span>WHAT I ALREADY HAVE</span><h2>My Products</h2><p>Your active financial products and services.</p></div><b>{purchased.length} {purchased.length===1?'product':'products'}</b></div>{purchased.length?<div className="purchased-product-grid">{purchased.map(p=><PurchasedCard key={p.id} product={p} onDetails={()=>setDetail(p)} onToast={onToast}/>)}</div>:<ProductsEmpty purchased={customerProductIds.length>0} filter={filter} onReset={()=>setFilter('All')}/>}</section>
    <section className="product-section explore-section" id="explore-products"><div className="product-section-heading"><div><span>DISCOVER WHAT’S NEXT</span><h2>Explore More Products</h2><p>Discover additional financial solutions available through Troth One.</p></div><b>{explore.length} available</b></div>{explore.length?<div className="explore-product-grid">{explore.map(p=><RelatedProductCard key={p.id} product={p} onBuy={()=>openBuy(p)} onInquiry={()=>openInquiry(p)} onDetails={()=>setDetail(p)}/>)}</div>:<div className="products-empty"><span><Search/></span><h3>No products found</h3><p>Try another category or search term.</p><button onClick={()=>{setFilter('All');setSearch('')}}>Clear filters</button></div>}</section>
    {detail&&<ProductDetails product={detail} owned={customerProductIds.includes(detail.id)} onClose={()=>setDetail(null)} onBuy={()=>openBuy(detail)} onInquiry={()=>openInquiry(detail)}/>} 
    {buyProduct&&<BuyJourney product={buyProduct} onClose={()=>setBuyProduct(null)} onComplete={()=>{setBuyProduct(null);onToast(`${buyProduct.name} application started successfully`)}}/>}
    {inquiryProduct&&<InquiryModal product={inquiryProduct} alreadySubmitted={inquiries.includes(inquiryProduct.id)} onClose={()=>setInquiryProduct(null)} onSubmit={()=>{setInquiries(current=>[...current,inquiryProduct.id]);setInquiryProduct(null);onToast('Inquiry submitted successfully. Our team will contact you shortly.')}}/>}
  </div>
}

function ProductsEmpty({purchased,filter,onReset}:{purchased:boolean;filter:string;onReset:()=>void}){return <div className="products-empty"><span><WalletCards/></span><h3>{purchased?`No purchased products in ${filter}`:"You don't have any active products yet."}</h3><p>{purchased?'Choose another filter to see your products.':'Explore Troth One financial solutions and choose what fits your needs.'}</p><button onClick={onReset}>Show all products</button></div>}
function PurchasedCard({product:p,onDetails,onToast}:{product:CatalogueProduct;onDetails:()=>void;onToast:(s:string)=>void}){const [contactOpen,setContactOpen]=useState(false);const Icon=iconMap[p.icon];const data=ownershipDetails[p.id];const contact=customerProductService.getSupportContact(data.supportContactKey);return <article className="purchased-product-card"><div className="owned-ribbon"><Check/> Purchased</div><div className="purchased-card-top"><span className={`catalogue-product-icon icon-${p.icon}`}><Icon/></span><div className="purchased-status-actions">{p.canClaim&&<button className="claim-action" onClick={()=>onToast(customerProductService.beginClaim(data.reference))}><FileText/> Claim</button>}<StatusBadge status="Active"/></div></div><span className="product-category-label">{p.category}</span><h3>{p.name}</h3><p>{data.reference}</p><div className="purchased-facts">{data.facts.map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div><div className="product-next-date">{data.due}</div><div className="purchased-actions"><button onClick={onDetails}>View Details</button><button onClick={()=>onToast('Service request form opened')}>Request Service</button>{data.renewable&&<button onClick={()=>onToast('Renewal request started')}>Renew</button>}{p.category==='Mutual Funds'&&<button onClick={()=>onToast('Statement downloaded')}><Download/> Statement</button>}{p.canDownloadPolicy&&data.policyDocumentId&&<button onClick={()=>onToast(customerProductService.downloadPolicy(data.policyDocumentId!))}><Download/> Download Policy</button>}<button className="contact-action" aria-expanded={contactOpen} onClick={()=>setContactOpen(open=>!open)}><PhoneCall/> Contact</button></div>{contactOpen&&<div className="product-contact-popover" role="dialog" aria-label={`${p.name} support contact`}><button className="contact-popover-close" aria-label="Close contact information" onClick={()=>setContactOpen(false)}><X/></button><b>Need help with this product?</b><span>{contact.label}: {contact.phone}</span>{contact.dialable?<a href={`tel:${contact.phone.replace(/\s/g,'')}`}>Call now</a>:<small>Phone integration pending configuration</small>}</div>}</article>}
export function RelatedProductCard({product:p,onBuy,onInquiry,onDetails}:{product:CatalogueProduct;onBuy:()=>void;onInquiry:()=>void;onDetails:()=>void}){const Icon=iconMap[p.icon];return <article className="explore-product-card"><div className="explore-card-top"><span className={`catalogue-product-icon icon-${p.icon}`}><Icon/></span><span>{p.category}</span></div><h3>{p.name}</h3><p>{p.shortDescription}</p><ul>{p.highlights.slice(0,3).map(x=><li key={x}><Check/>{x}</li>)}</ul><div className="explore-actions"><button className="buy-action" onClick={onBuy}>Buy Now</button><button className="inquiry-action" onClick={onInquiry}>Inquiry</button><button className="details-action" onClick={onDetails}>Product Details <ArrowRight/></button></div></article>}
export function ProductDetails({product:p,owned,onClose,onBuy,onInquiry}:{product:CatalogueProduct;owned:boolean;onClose:()=>void;onBuy:()=>void;onInquiry:()=>void}){const Icon=iconMap[p.icon];return <><button className="drawer-scrim" onClick={onClose}/><aside className="detail-drawer catalogue-detail-drawer"><div className="drawer-header"><div><span className="eyebrow">{p.category.toUpperCase()}</span><h2>{p.name}</h2><p>{p.shortDescription}</p></div><button className="icon-button" onClick={onClose}><X/></button></div><div className="catalogue-detail-body"><div className="catalogue-detail-intro"><span className={`catalogue-product-icon icon-${p.icon}`}><Icon/></span><div><small>WHO IS THIS FOR?</small><p>{p.eligibility[0]}. Troth One can help you understand suitable options and next steps.</p></div></div><DetailList title="Key Benefits" items={p.benefits}/><DetailList title="Basic Eligibility" items={p.eligibility}/><DetailList title="Documents Generally Required" items={p.requiredDocuments}/><div className="important-note"><b>Important Note</b><p>{p.importantNote}</p></div></div><div className="drawer-actions catalogue-drawer-actions">{!owned&&<><button className="primary-btn" onClick={onBuy}>Buy Now</button><button className="secondary-btn" onClick={onInquiry}>Submit Inquiry</button></>}<button className="secondary-btn" onClick={onClose}>Close</button></div></aside></>}
function DetailList({title,items}:{title:string;items:string[]}){return <section className="catalogue-detail-section"><h3>{title}</h3><ul>{items.map(item=><li key={item}><Check/>{item}</li>)}</ul></section>}
export function BuyJourney({product:p,onClose,onComplete}:{product:CatalogueProduct;onClose:()=>void;onComplete:()=>void}){return <><button className="drawer-scrim" onClick={onClose}/><aside className="form-drawer buy-journey"><div className="drawer-header"><div><span className="eyebrow">START APPLICATION</span><h2>{p.name}</h2><p>Your selected product is already filled in.</p></div><button className="icon-button" onClick={onClose}><X/></button></div><div className="journey-progress"><i className="active">1</i><span/><i>2</i><span/><i>3</i><b>Basic details</b><b>Requirements</b><b>Review</b></div><form onSubmit={e=>{e.preventDefault();onComplete()}}><label>Selected product<input value={p.name} readOnly/></label><div className="form-row"><label>Customer name<input value="Vivek Joshi" readOnly/></label><label>Mobile number<input value="+91 98765 28426" readOnly/></label></div><label>Email address<input type="email" value="vivek.joshi@example.in" readOnly/></label><label>{p.category==='Loans'?'Required loan amount':p.category==='Insurance'||p.category==='Loan Protector'?'Preferred cover amount':'Initial investment amount'}<input required placeholder="Enter approximate amount"/></label><label>Anything we should know?<textarea placeholder="Add a short requirement or preference (optional)"/></label><div className="journey-consent"><input type="checkbox" required/><span>I consent to Troth One contacting me and sharing these details with relevant product partners.</span></div><div className="form-actions"><button type="button" className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn">Continue Application</button></div></form></aside></>}
export function InquiryModal({product:p,alreadySubmitted,onClose,onSubmit}:{product:CatalogueProduct;alreadySubmitted:boolean;onClose:()=>void;onSubmit:()=>void}){return <div className="modal-wrap"><button className="modal-scrim" onClick={onClose}/><form className="modal inquiry-modal" onSubmit={e=>{e.preventDefault();onSubmit()}}><div className="modal-heading"><div className="modal-icon"><FileText/></div><div><span className="eyebrow">PRODUCT INQUIRY</span><h2>{p.name}</h2></div><button type="button" className="icon-button" onClick={onClose}><X/></button></div>{alreadySubmitted&&<div className="inquiry-notice"><Check/> You have already submitted an inquiry for this product.</div>}<div className="form-row"><label>Customer Name<input value="Vivek Joshi" readOnly/></label><label>Mobile<input value="+91 98765 28426" readOnly/></label></div><label>Email<input type="email" value="vivek.joshi@example.in" readOnly/></label><label>Selected Product<input value={p.name} readOnly/></label><label>Preferred Contact Time<select><option>Any time</option><option>Morning, 9 AM – 12 PM</option><option>Afternoon, 12 PM – 4 PM</option><option>Evening, 4 PM – 7 PM</option></select></label><label>Message / Requirement<textarea placeholder="Tell us briefly what you would like to know (optional)"/></label><div className="form-actions"><button type="button" className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn">Submit Inquiry</button></div></form></div>}
