import { useMemo, useState } from 'react'
import { ArrowLeft, BriefcaseBusiness, Calculator, Check, ChevronRight, GraduationCap, HeartPulse, Landmark, PiggyBank, Save, ShieldCheck, Target, TrendingUp, X } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { PageHeader } from '../components/UI'
import { calculate, calculators, type CalculationResult, type CalculatorCategory, type CalculatorDefinition } from '../data/calculators'
import { productCatalogue, type CatalogueProduct } from '../data/productCatalogue'
import { BuyJourney, InquiryModal, ProductDetails, RelatedProductCard } from './CustomerProducts'

const categoryIcons:Record<CalculatorCategory,LucideIcon>={Investments:TrendingUp,Loans:Landmark,Insurance:ShieldCheck,Protection:HeartPulse,Goals:Target}
const specialIcons:Record<string,LucideIcon>={retirement:PiggyBank,education:GraduationCap,goal:Target}
const categories=['All','Investments','Loans','Insurance','Protection','Goals'] as const
type Saved={id:number;name:string;label:string;date:string}

export function CustomerCalculator({onNavigate,onToast}:{onNavigate:(page:string)=>void;onToast:(message:string)=>void}){
  const [category,setCategory]=useState<(typeof categories)[number]>('All')
  const [selected,setSelected]=useState<CalculatorDefinition|null>(null)
  const [values,setValues]=useState<Record<string,string|number>>({})
  const [saved,setSaved]=useState<Saved[]>([])
  const [detail,setDetail]=useState<CatalogueProduct|null>(null);const [buy,setBuy]=useState<CatalogueProduct|null>(null);const [inquiry,setInquiry]=useState<CatalogueProduct|null>(null)
  const filtered=calculators.filter(c=>category==='All'||c.category===category)
  const result=useMemo(()=>selected?calculate(selected,values):null,[selected,values])
  const choose=(def:CalculatorDefinition)=>{setSelected(def);setValues(Object.fromEntries(def.fields.map(f=>[f.key,f.defaultValue])));window.setTimeout(()=>document.getElementById('calculator-workspace')?.scrollIntoView({behavior:'smooth'}),50)}
  const related=selected?selected.relatedProductIds.map(id=>productCatalogue.find(p=>p.id===id)).filter(Boolean) as CatalogueProduct[]:[]
  const productAction=(type:'detail'|'buy'|'inquiry',p:CatalogueProduct)=>{if(type==='detail')setDetail(p);if(type==='buy')setBuy(p);if(type==='inquiry')setInquiry(p)}
  return <div className="page calculator-page"><PageHeader eyebrow="PLAN YOUR FINANCIAL FUTURE" title="Financial Calculators" description="Plan your goals, estimate your requirements and explore suitable Troth One solutions." actions={saved.length?<button className="secondary-btn" onClick={()=>document.getElementById('saved-calculations')?.scrollIntoView({behavior:'smooth'})}><Save/> {saved.length} saved</button>:undefined}/>
    <section className="calculator-intro"><div><span><Calculator/></span><div><h2>What would you like to plan?</h2><p>Select a calculator to see a simple, indicative estimate. You can change every assumption.</p></div></div><button onClick={()=>onNavigate('support')}>Need help choosing? <ChevronRight/></button></section>
    <div className="calculator-category-tabs">{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}<span>{c==='All'?calculators.length:calculators.filter(x=>x.category===c).length}</span></button>)}</div>
    <section className="calculator-cards">{filtered.map(def=><CalculatorCard key={def.id} definition={def} active={selected?.id===def.id} onSelect={()=>choose(def)}/>)}</section>
    {selected&&result&&<section className="calculator-workspace" id="calculator-workspace"><div className="calculator-workspace-head"><button onClick={()=>setSelected(null)}><ArrowLeft/> All calculators</button><div><span>{selected.category}</span><h2>{selected.name}</h2><p>{selected.description}</p></div><button className="icon-button" onClick={()=>setSelected(null)}><X/></button></div><div className="calculator-split"><CalculatorForm definition={selected} values={values} onChange={(key,value)=>setValues(current=>({...current,[key]:value}))}/><CalculatorResult result={result} definition={selected} onSave={()=>{setSaved(current=>[...current,{id:Date.now(),name:selected.name,label:result.saveLabel,date:'02 Sep 2026'}]);onToast('Calculation saved')}}/></div><div className="calculator-related"><div className="product-section-heading"><div><span>RELATED TROTH ONE SOLUTIONS</span><h2>Products That May Help</h2><p>Explore relevant options after reviewing your estimate.</p></div></div><div className="explore-product-grid calculator-related-grid">{related.map(p=><RelatedProductCard key={p.id} product={p} onDetails={()=>productAction('detail',p)} onBuy={()=>productAction('buy',p)} onInquiry={()=>productAction('inquiry',p)}/>)}</div></div></section>}
    {saved.length>0&&<section className="saved-calculations" id="saved-calculations"><div className="product-section-heading"><div><span>YOUR PLANS</span><h2>Saved Calculations</h2><p>Return to scenarios you want to discuss or compare.</p></div></div><div>{saved.map(item=><article key={item.id}><span><Save/></span><div><b>{item.name}</b><p>{item.label}</p><small>Saved {item.date}</small></div><button onClick={()=>setSaved(current=>current.filter(x=>x.id!==item.id))}>Remove</button></article>)}</div></section>}
    {detail&&<ProductDetails product={detail} owned={false} onClose={()=>setDetail(null)} onBuy={()=>{setDetail(null);setBuy(detail)}} onInquiry={()=>{setDetail(null);setInquiry(detail)}}/>}
    {buy&&<BuyJourney product={buy} onClose={()=>setBuy(null)} onComplete={()=>{setBuy(null);onToast(`${buy.name} application started successfully`)}}/>}
    {inquiry&&<InquiryModal product={inquiry} alreadySubmitted={false} onClose={()=>setInquiry(null)} onSubmit={()=>{setInquiry(null);onToast('Inquiry submitted successfully. Our team will contact you shortly.')}}/>}
  </div>
}

function CalculatorCard({definition:def,active,onSelect}:{definition:CalculatorDefinition;active:boolean;onSelect:()=>void}){const Icon=specialIcons[def.kind]||categoryIcons[def.category];return <article className={`calculator-card ${active?'active':''}`}><span className={`calculator-card-icon calc-${def.category.toLowerCase()}`}><Icon/></span><small>{def.category}</small><h3>{def.name}</h3><p>{def.description}</p><div>Related product <b>{def.productLabel}</b></div><button onClick={onSelect}>Calculate <ChevronRight/></button></article>}
function CalculatorForm({definition:def,values,onChange}:{definition:CalculatorDefinition;values:Record<string,string|number>;onChange:(key:string,value:string|number)=>void}){return <div className="calculator-form"><div className="calculator-panel-title"><span>1</span><div><h3>Your Inputs</h3><p>Adjust the values to match your scenario.</p></div></div><div className="calculator-fields">{def.fields.map(field=><label key={field.key}><span>{field.label}</span><div className={field.suffix?'has-suffix':''}>{field.type==='select'?<select value={values[field.key]} onChange={e=>onChange(field.key,e.target.value)}>{field.options?.map(option=><option key={option}>{option}</option>)}</select>:<input type="number" value={values[field.key]} min={field.min} max={field.max} step={field.step} onChange={e=>onChange(field.key,Number(e.target.value))}/>} {field.suffix&&<i>{field.suffix}</i>}</div></label>)}</div><div className="input-guidance"><Check/><p><b>You’re in control.</b> These assumptions are editable and used only for this illustrative calculation.</p></div></div>}
function CalculatorResult({result:r,definition:def,onSave}:{result:CalculationResult;definition:CalculatorDefinition;onSave:()=>void}){const total=r.chart?r.chart.primary+r.chart.secondary:0;return <div className="calculator-result"><div className="calculator-panel-title"><span>2</span><div><h3>Estimated Result</h3><p>Based on the assumptions entered.</p></div></div><div className="result-hero"><small>{r.headline}</small><strong>{r.headlineValue}</strong><span>Indicative estimate</span></div><div className="result-breakdown">{r.results.map(item=><div key={item.label}><span>{item.label}</span><b>{item.value}</b></div>)}</div>{r.chart&&<div className="result-chart"><div><i style={{width:`${r.chart.primary/total*100}%`}}/><i style={{width:`${r.chart.secondary/total*100}%`}}/></div><p><span><i/>{r.chart.primaryLabel}</span><span><i/>{r.chart.secondaryLabel}</span></p></div>}<div className="result-meaning"><b>What This Means</b><p>{r.meaning}</p></div><div className="calculation-disclaimer">{def.disclaimer}</div><button className="save-calculation" onClick={onSave}><Save/> Save Calculation</button></div>}
