import { useMemo, useState } from 'react'
import { ArrowLeft, Calculator, Check, ChevronRight, GraduationCap, HeartPulse, Landmark, PiggyBank, Save, ShieldCheck, Target, TrendingUp, X } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { PageHeader } from '../components/UI'
import { calculate, calculators, type CalculationResult, type CalculatorCategory, type CalculatorDefinition } from '../data/calculators'
import { productCatalogue, type CatalogueProduct } from '../data/productCatalogue'
import { BuyJourney, InquiryModal, ProductDetails, RelatedProductCard } from './CustomerProducts'

const categoryIcons:Record<CalculatorCategory,LucideIcon>={Investments:TrendingUp,Loans:Landmark,Insurance:ShieldCheck,Protection:HeartPulse,Goals:Target}
const specialIcons:Record<string,LucideIcon>={retirement:PiggyBank,education:GraduationCap,goal:Target}
const categories=['All','Investments','Loans','Insurance','Protection','Goals'] as const
const baseLoanCalculator=calculators.find(item=>item.id==='home-loan-emi')!
const loanCalculator:CalculatorDefinition={...baseLoanCalculator,id:'customer-loan',name:'Loan Calculator',description:'Estimate EMI and total repayment for your loan.',productLabel:'Loan Solutions',relatedProductIds:['home-loan','personal-loan','business-loan','loan-against-property']}
const customerCalculators=[...calculators.filter(item=>item.category!=='Loans'),loanCalculator]
type Saved={id:number;name:string;label:string;date:string}

export function CustomerCalculator({onNavigate,onToast}:{onNavigate:(page:string)=>void;onToast:(message:string)=>void}){
  const [category,setCategory]=useState<(typeof categories)[number]>('All')
  const [selected,setSelected]=useState<CalculatorDefinition|null>(null)
  const [values,setValues]=useState<Record<string,string|number>>({})
  const [saved,setSaved]=useState<Saved[]>([])
  const [detail,setDetail]=useState<CatalogueProduct|null>(null);const [buy,setBuy]=useState<CatalogueProduct|null>(null);const [inquiry,setInquiry]=useState<CatalogueProduct|null>(null)
  const filtered=customerCalculators.filter(item=>category==='All'||item.category===category)
  const result=useMemo(()=>selected?calculate(selected,values):null,[selected,values])
  const choose=(definition:CalculatorDefinition)=>{setSelected(definition);setValues(Object.fromEntries(definition.fields.map(field=>[field.key,field.defaultValue])));window.setTimeout(()=>document.getElementById('calculator-workspace')?.scrollIntoView({behavior:'smooth'}),50)}
  const related=selected?selected.relatedProductIds.map(id=>productCatalogue.find(product=>product.id===id)).filter(Boolean) as CatalogueProduct[]:[]
  const productAction=(type:'detail'|'buy'|'inquiry',product:CatalogueProduct)=>{if(type==='detail')setDetail(product);if(type==='buy')setBuy(product);if(type==='inquiry')setInquiry(product)}
  return <div className="page calculator-page"><PageHeader eyebrow="PLAN YOUR FINANCIAL FUTURE" title="Financial Calculators" description="Plan your goals, estimate your requirements and explore suitable Troth One solutions." actions={saved.length?<button className="secondary-btn" onClick={()=>document.getElementById('saved-calculations')?.scrollIntoView({behavior:'smooth'})}><Save/> {saved.length} saved</button>:undefined}/>
    <section className="calculator-intro"><div><span><Calculator/></span><div><h2>What would you like to plan?</h2><p>Select a calculator to see a simple, indicative estimate. You can change every assumption.</p></div></div><button onClick={()=>onNavigate('support')}>Need help choosing? <ChevronRight/></button></section>
    <div className="calculator-category-tabs">{categories.map(item=><button key={item} className={category===item?'active':''} onClick={()=>setCategory(item)}>{item}<span>{item==='All'?customerCalculators.length:customerCalculators.filter(calculator=>calculator.category===item).length}</span></button>)}</div>
    <section className="calculator-cards">{filtered.map(definition=><CalculatorCard key={definition.id} definition={definition} active={selected?.id===definition.id} onSelect={()=>choose(definition)}/>)}</section>
    {selected&&result&&<section className="calculator-workspace" id="calculator-workspace"><div className="calculator-workspace-head"><button onClick={()=>setSelected(null)}><ArrowLeft/> All calculators</button><div><span>{selected.category}</span><h2>{selected.name}</h2><p>{selected.description}</p></div><button className="icon-button" onClick={()=>setSelected(null)}><X/></button></div><div className="calculator-split"><CalculatorForm definition={selected} values={values} onChange={(key,value)=>setValues(current=>({...current,[key]:value}))}/><CalculatorResult result={result} definition={selected} onSave={()=>{setSaved(current=>[...current,{id:Date.now(),name:selected.name,label:result.saveLabel,date:'02 Sep 2026'}]);onToast('Calculation saved')}}/></div><div className="calculator-related"><div className="product-section-heading"><div><span>RELATED TROTH ONE SOLUTIONS</span><h2>Products That May Help</h2><p>Explore relevant options after reviewing your estimate.</p></div></div><div className="explore-product-grid calculator-related-grid">{related.map(product=><RelatedProductCard key={product.id} product={product} onDetails={()=>productAction('detail',product)} onBuy={()=>productAction('buy',product)} onInquiry={()=>productAction('inquiry',product)}/>)}</div></div></section>}
    {saved.length>0&&<section className="saved-calculations" id="saved-calculations"><div className="product-section-heading"><div><span>YOUR PLANS</span><h2>Saved Calculations</h2><p>Return to scenarios you want to discuss or compare.</p></div></div><div>{saved.map(item=><article key={item.id}><span><Save/></span><div><b>{item.name}</b><p>{item.label}</p><small>Saved {item.date}</small></div><button onClick={()=>setSaved(current=>current.filter(savedItem=>savedItem.id!==item.id))}>Remove</button></article>)}</div></section>}
    {detail&&<ProductDetails product={detail} owned={false} onClose={()=>setDetail(null)} onBuy={()=>{setDetail(null);setBuy(detail)}} onInquiry={()=>{setDetail(null);setInquiry(detail)}}/>}
    {buy&&<BuyJourney product={buy} onClose={()=>setBuy(null)} onComplete={()=>{setBuy(null);onToast(`${buy.name} application started successfully`)}}/>}
    {inquiry&&<InquiryModal product={inquiry} alreadySubmitted={false} onClose={()=>setInquiry(null)} onSubmit={()=>{setInquiry(null);onToast('Inquiry submitted successfully. Our team will contact you shortly.')}}/>}
  </div>
}

function CalculatorCard({definition,active,onSelect}:{definition:CalculatorDefinition;active:boolean;onSelect:()=>void}){const Icon=specialIcons[definition.kind]||categoryIcons[definition.category];return <article className={`calculator-card ${active?'active':''}`}><span className={`calculator-card-icon calc-${definition.category.toLowerCase()}`}><Icon/></span><small>{definition.category}</small><h3>{definition.name}</h3><p>{definition.description}</p><div>Related product <b>{definition.productLabel}</b></div><button onClick={onSelect}>Calculate <ChevronRight/></button></article>}
function CalculatorForm({definition,values,onChange}:{definition:CalculatorDefinition;values:Record<string,string|number>;onChange:(key:string,value:string|number)=>void}){return <div className="calculator-form"><div className="calculator-panel-title"><span>1</span><div><h3>Your Inputs</h3><p>Adjust the values to match your scenario.</p></div></div><div className="calculator-fields">{definition.fields.map(field=><label key={field.key}><span>{field.label}</span><div className={field.suffix?'has-suffix':''}>{field.type==='select'?<select value={values[field.key]} onChange={event=>onChange(field.key,event.target.value)}>{field.options?.map(option=><option key={option}>{option}</option>)}</select>:<input type="number" value={values[field.key]} min={field.min} max={field.max} step={field.step} onChange={event=>onChange(field.key,Number(event.target.value))}/>} {field.suffix&&<i>{field.suffix}</i>}</div></label>)}</div><div className="input-guidance"><Check/><p><b>You’re in control.</b> These assumptions are editable and used only for this illustrative calculation.</p></div></div>}
function CalculatorResult({result,definition,onSave}:{result:CalculationResult;definition:CalculatorDefinition;onSave:()=>void}){const total=result.chart?result.chart.primary+result.chart.secondary:0;return <div className="calculator-result"><div className="calculator-panel-title"><span>2</span><div><h3>Estimated Result</h3><p>Based on the assumptions entered.</p></div></div><div className="result-hero"><small>{result.headline}</small><strong>{result.headlineValue}</strong><span>Indicative estimate</span></div><div className="result-breakdown">{result.results.map(item=><div key={item.label}><span>{item.label}</span><b>{item.value}</b></div>)}</div>{result.chart&&<div className="result-chart"><div><i style={{width:`${result.chart.primary/total*100}%`}}/><i style={{width:`${result.chart.secondary/total*100}%`}}/></div><p><span><i/>{result.chart.primaryLabel}</span><span><i/>{result.chart.secondaryLabel}</span></p></div>}<div className="result-meaning"><b>What This Means</b><p>{result.meaning}</p></div><div className="calculation-disclaimer">{definition.disclaimer}</div><button className="save-calculation" onClick={onSave}><Save/> Save Calculation</button></div>}
