import { useEffect, useState } from 'react'
import { ArrowRight, Bot, ChevronDown, FileText, Headphones, LifeBuoy, Mail, PhoneCall, Plus, X } from 'lucide-react'
import { PageHeader, StatusBadge } from '../components/UI'
import type { Application } from '../types'
import { FloatingAIAssistant } from '../components/FloatingAIAssistant'

const tickets=[['SR-10248','Statement request','Mutual Funds','30 Aug 2026','In Progress','Today, 10:15 AM'],['SR-10231','Nominee update','Health Insurance','28 Aug 2026','New','01 Sep 2026'],['SR-10192','EMI schedule query','Home Loan','18 Aug 2026','Completed','22 Aug 2026']]
const faqs=[['How long does application verification take?','Timelines vary by product and provider. Your Applications page shows the current stage and any action needed from you.'],['Where can I upload a requested document?','Open Applications, select the application, and use its Documents section—or use Documents & Profile for general KYC documents.'],['How do I request a policy renewal?','Open My Products, choose the policy and select Renew or Request Service.'],['Can Troth One guarantee investment returns or loan approval?','No. Returns are market-linked, and loan approval depends on lender policies, credit profile, documents and underwriting.']]

export function CustomerSupport({apps,onNavigate,onToast}:{apps:Application[];onNavigate:(page:string)=>void;onToast:(message:string)=>void}){
  const [requestOpen,setRequestOpen]=useState(false);const [openFaq,setOpenFaq]=useState<number|null>(0)
  useEffect(()=>{const openRequest=()=>{sessionStorage.removeItem('troth-support-request');setRequestOpen(true)};if(sessionStorage.getItem('troth-support-request')==='true')openRequest();window.addEventListener('troth-open-support-request',openRequest);return()=>window.removeEventListener('troth-open-support-request',openRequest)},[])
  return <div className="page customer-support-page"><PageHeader eyebrow="HELP & SUPPORT" title="Support" description="How can we help? Raise requests, contact our team and track support in one place." actions={<button className="primary-btn" onClick={()=>setRequestOpen(true)}><Plus/> Raise Service Request</button>}/>
    <section className="support-quick-actions"><button onClick={()=>setRequestOpen(true)}><span><LifeBuoy/></span><div><b>Raise Service Request</b><small>Get trackable help for a product or process</small></div><ArrowRight/></button><button onClick={()=>onToast('Callback requested. Our team will contact you shortly.')}><span><PhoneCall/></span><div><b>Request Callback</b><small>Ask your advisor or support team to call</small></div><ArrowRight/></button><button onClick={()=>document.getElementById('support-faqs')?.scrollIntoView({behavior:'smooth'})}><span><FileText/></span><div><b>FAQs & Help</b><small>Find answers to common questions</small></div><ArrowRight/></button><button onClick={()=>onToast('Support email copied: support@trothone.in')}><span><Mail/></span><div><b>Contact Support</b><small>support@trothone.in • Mon–Sat</small></div><ArrowRight/></button></section>
    <div className="floating-ai-note"><span><Bot/></span><div><b>Need a quick answer?</b><p>Use Troth AI from the bottom-right corner on any customer page.</p></div></div>
    <section className="support-content-grid"><div className="customer-card support-tickets"><div className="customer-card-head"><div><h2>My Support Requests</h2><p>Recent questions and service requests</p></div><button onClick={()=>onToast('All support requests opened')}>View all</button></div><div className="support-ticket-table"><div className="ticket-head"><span>Ticket</span><span>Category / Product</span><span>Created</span><span>Status</span><span>Last Update</span><span/></div>{tickets.map(([id,category,product,date,status,updated])=><button key={id} onClick={()=>onToast(`${id} details opened`)}><span><b>{id}</b></span><span><b>{category}</b><small>{product}</small></span><span>{date}</span><StatusBadge status={status}/><span>{updated}</span><ArrowRight/></button>)}</div></div><div className="customer-card faq-card" id="support-faqs"><div className="customer-card-head"><div><h2>FAQs / Help</h2><p>Common questions, simply answered</p></div></div><div className="faq-list">{faqs.map(([q,a],i)=><button className={openFaq===i?'open':''} key={q} onClick={()=>setOpenFaq(openFaq===i?null:i)}><div><b>{q}</b><ChevronDown/></div>{openFaq===i&&<p>{a}</p>}</button>)}</div></div></section>
    {requestOpen&&<SupportRequestModal onClose={()=>setRequestOpen(false)} onSubmit={()=>{setRequestOpen(false);onToast('Service request submitted successfully')}}/>}
    <FloatingAIAssistant page="support" apps={apps} onNavigate={onNavigate} onToast={onToast}/>
  </div>
}

function SupportRequestModal({onClose,onSubmit}:{onClose:()=>void;onSubmit:()=>void}){return <div className="modal-wrap"><button className="modal-scrim" onClick={onClose}/><form className="modal" onSubmit={e=>{e.preventDefault();onSubmit()}}><div className="modal-heading"><div className="modal-icon"><Headphones/></div><div><span className="eyebrow">HUMAN SUPPORT</span><h2>Raise Service Request</h2></div><button type="button" className="icon-button" onClick={onClose}><X/></button></div><label>Category<select><option>Application support</option><option>Product service</option><option>Documents / KYC</option><option>Payment or renewal</option><option>Technology issue</option></select></label><label>Related product<select><option>General</option><option>Health Insurance</option><option>Home Loan</option><option>Mutual Funds</option></select></label><label>How can we help?<textarea required placeholder="Describe your request"/></label><div className="form-actions"><button type="button" className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn">Submit Request</button></div></form></div>}
