import { useMemo, useState } from 'react'
import { ChevronRight, MapPin, Plus, X } from 'lucide-react'
import { formatINR, franchisees } from '../data/mockData'
import type { Franchisee, Role } from '../types'
import { PageHeader, SearchBox, Select, StatCard, StatusBadge } from '../components/UI'

export function FranchiseesPage({role,onToast}:{role:Role;onToast:(s:string)=>void}) {
  const [search,setSearch]=useState(''); const [city,setCity]=useState('All cities'); const [selected,setSelected]=useState<Franchisee|null>(null); const [add,setAdd]=useState(false)
  const available=role==='rm'?franchisees.filter(f=>f.rm==='Rohan Mehta'):franchisees
  const rows=useMemo(()=>available.filter(f=>(city==='All cities'||f.city===city)&&(f.name.toLowerCase().includes(search.toLowerCase())||f.code.toLowerCase().includes(search.toLowerCase()))),[available,city,search])
  return <div className="page"><PageHeader eyebrow="PARTNER NETWORK" title={role==='rm'?'My franchisees':'Franchisees'} description={role==='rm'?'Review assigned partners, activity, business and cases needing support.':'Manage partner offices, RM mappings, users and business performance.'} actions={role==='admin'?<button className="primary-btn" onClick={()=>setAdd(true)}><Plus size={17}/> Add franchisee</button>:undefined}/>
    <section className="mini-stats"><StatCard label="Total network" value={available.length} meta="Partner offices"/><StatCard label="Active" value={available.filter(f=>f.status==='Active').length} meta="Currently operating" tone="green"/><StatCard label="Customers" value={available.reduce((s,f)=>s+f.customers,0)} meta="Across network" tone="blue"/><StatCard label="Business" value={formatINR(available.reduce((s,f)=>s+f.business,0),true)} meta="This financial year" tone="violet"/></section>
    <div className="table-panel"><div className="table-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search name or code"/><Select value={city} onChange={setCity}><option>All cities</option>{['Ahmedabad','Surat','Vadodara','Rajkot','Gandhinagar'].map(x=><option key={x}>{x}</option>)}</Select></div><div className="result-count"><b>{rows.length} franchisees</b></div>
      <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Franchisee</th><th>City</th><th>Assigned RM</th><th>Customers</th><th>Applications</th><th>Business</th><th>Pending cases</th><th>Status</th><th/></tr></thead><tbody>{rows.map(f=><tr key={f.code} onClick={()=>setSelected(f)}><td><b className="link-text">{f.name}</b><small>{f.code}</small></td><td><span>{f.city}</span></td><td><b>{f.rm}</b></td><td><b>{f.customers}</b></td><td><b>{f.applications}</b></td><td><b>{formatINR(f.business)}</b></td><td><span className={f.pending>5?'attention-text':''}>{f.pending}</span></td><td><StatusBadge status={f.status}/></td><td><ChevronRight size={17}/></td></tr>)}</tbody></table></div>
    </div>{selected&&<FranchiseeDrawer item={selected} onClose={()=>setSelected(null)} onToast={onToast}/>} {add&&<AddFranchisee onClose={()=>setAdd(false)} onCreate={()=>{setAdd(false);onToast('Franchisee added successfully')}}/>}</div>
}

function FranchiseeDrawer({item:f,onClose,onToast}:{item:Franchisee;onClose:()=>void;onToast:(s:string)=>void}) {
  const [tab,setTab]=useState('Overview'); const tabs=['Overview','Customers','Applications','Business','CRM','Users & Branches','Support','Documents','Activity']
  return <><button className="drawer-scrim" onClick={onClose}/><aside className="detail-drawer franchisee-drawer"><div className="drawer-header"><div><span className="eyebrow">{f.code}</span><h2>{f.name}</h2><p><MapPin size={14}/>{f.city} • RM: {f.rm}</p></div><button className="icon-button" onClick={onClose}><X size={21}/></button></div><div className="drawer-summary"><StatusBadge status={f.status}/><span>Joined <b>18 Mar 2023</b></span><span>Last active <b>Today</b></span></div><div className="drawer-tabs">{tabs.map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><div className="drawer-body">
    <section className="drawer-stat-grid"><StatCard label="Customers" value={f.customers} meta="12 active this month"/><StatCard label="Applications" value={f.applications} meta="Active applications" tone="blue"/><StatCard label="Pending cases" value={f.pending} meta="Needs attention" tone={f.pending>5?'red':'amber'}/><StatCard label="Total business" value={formatINR(f.business,true)} meta="This financial year" tone="green"/></section>
    {tab==='Overview'?<div className="two-col-detail"><section className="detail-section"><h3>Partner information</h3><div className="detail-grid"><div><span>Primary contact</span><b>Neha Patel</b></div><div><span>Mobile</span><b>+91 98765 43210</b></div><div><span>Email</span><b>partner@trothdemo.in</b></div><div><span>Assigned RM</span><b>{f.rm}</b></div></div></section><section className="detail-section"><h3>Attention required</h3><div className="callout warning"><b>{f.pending} cases need follow-up</b><p>2 documents pending and 1 application delayed.</p><button onClick={()=>onToast('Cases filtered')}>Review cases</button></div></section></div>:<section className="detail-section"><h3>{tab}</h3><div className="empty-inline"><span>✓</span><b>{tab} information is up to date</b><p>This tab demonstrates the consolidated Franchisee 360 structure.</p></div></section>}
  </div></aside></>
}

function AddFranchisee({onClose,onCreate}:{onClose:()=>void;onCreate:()=>void}) { return <><button className="drawer-scrim" onClick={onClose}/><aside className="form-drawer"><div className="drawer-header"><div><span className="eyebrow">PARTNER NETWORK</span><h2>Add franchisee</h2><p>Create a new partner office.</p></div><button className="icon-button" onClick={onClose}><X size={21}/></button></div><form onSubmit={e=>{e.preventDefault();onCreate()}}><label>Franchisee name<input required placeholder="Business or trading name"/></label><div className="form-row"><label>City<select><option>Ahmedabad</option><option>Surat</option><option>Vadodara</option></select></label><label>Assigned RM<select><option>Rohan Mehta</option><option>Kavya Shah</option></select></label></div><label>Primary contact<input required placeholder="Contact person"/></label><label>Mobile number<input required placeholder="+91"/></label><label>Email<input type="email" placeholder="name@company.in"/></label><div className="form-actions"><button type="button" className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn">Add franchisee</button></div></form></aside></> }
