import { useEffect, useMemo, useState, type ChangeEvent, type ReactNode } from 'react'
import { ArrowLeft, BadgeIndianRupee, Building2, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, CircleAlert, CreditCard, Eye, FileCheck2, FileText, Landmark, LoaderCircle, LockKeyhole, MapPin, Pencil, Plus, RefreshCw, ShieldCheck, Trash2, Upload, UserRound, UsersRound, X } from 'lucide-react'
import { formatINR, franchisees } from '../data/mockData'
import type { Franchisee, Role } from '../types'
import type { SubFranchisee } from '../franchisee/subFranchiseeTypes'
import { authenticatedFranchisee, subFranchiseeService } from '../franchisee/services/subFranchiseeService'
import { PageHeader, SearchBox, Select, StatCard, StatusBadge } from '../components/UI'

type ChildLoad={status:'loading'|'ready'|'error';rows:SubFranchisee[];message?:string}

export function FranchiseesPage({role,onToast}:{role:Role;onToast:(s:string)=>void}) {
  const [search,setSearch]=useState(''),[city,setCity]=useState('All cities'),[selected,setSelected]=useState<Franchisee|null>(null),[selectedSub,setSelectedSub]=useState<SubFranchisee|null>(null),[add,setAdd]=useState(false)
  const [expanded,setExpanded]=useState<string>(),[children,setChildren]=useState<Record<string,ChildLoad>>({})
  const available=role==='rm'?franchisees.filter(f=>f.rm==='Rohan Mehta'):franchisees
  const rows=useMemo(()=>available.filter(f=>(city==='All cities'||f.city===city)&&(f.name.toLowerCase().includes(search.toLowerCase())||f.code.toLowerCase().includes(search.toLowerCase()))),[available,city,search])
  const relationshipId=(franchisee:Franchisee)=>franchisee.name==='Troth Finserve'?authenticatedFranchisee.id:franchisee.code
  const canExpand=(franchisee:Franchisee)=>role==='admin'&&relationshipId(franchisee)===authenticatedFranchisee.id
  const toggle=(franchisee:Franchisee)=>{
    if(!canExpand(franchisee))return
    if(expanded===franchisee.code){setExpanded(undefined);return}
    setExpanded(franchisee.code)
    if(children[franchisee.code])return
    setChildren(current=>({...current,[franchisee.code]:{status:'loading',rows:[]}}))
    window.setTimeout(()=>{try{const parentId=relationshipId(franchisee);const items=subFranchiseeService.list().filter(item=>item.parentFranchiseeId===parentId);setChildren(current=>({...current,[franchisee.code]:{status:'ready',rows:items}}))}catch(error){setChildren(current=>({...current,[franchisee.code]:{status:'error',rows:[],message:error instanceof Error?error.message:'Unable to load Sub-Franchisees'}}))}},220)
  }
  if(role!=='admin')return <LegacyFranchiseeList rows={rows} available={available} search={search} city={city} setSearch={setSearch} setCity={setCity} selected={selected} setSelected={setSelected} onToast={onToast}/>
  if(add)return <AddFranchiseePage onClose={()=>setAdd(false)} onCreate={()=>{setAdd(false);onToast('Franchisee added successfully')}}/>
  return <div className="page admin-franchisee-page"><PageHeader eyebrow="PARTNER NETWORK" title="Franchisees" description="Manage partner offices, RM mappings, users and business performance." actions={<button className="primary-btn" onClick={()=>setAdd(true)}><Plus size={17}/> Add franchisee</button>}/>
    <section className="mini-stats"><StatCard label="Total network" value={available.length} meta="Partner offices"/><StatCard label="Active" value={available.filter(f=>f.status==='Active').length} meta="Currently operating" tone="green"/><StatCard label="Customers" value={available.reduce((s,f)=>s+f.customers,0)} meta="Across network" tone="blue"/><StatCard label="Business" value={formatINR(available.reduce((s,f)=>s+f.business,0),true)} meta="This financial year" tone="violet"/></section>
    <div className="table-panel"><div className="table-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search name or code"/><Select value={city} onChange={setCity}><option>All cities</option>{['Ahmedabad','Surat','Vadodara','Rajkot','Gandhinagar'].map(x=><option key={x}>{x}</option>)}</Select></div><div className="result-count"><b>{rows.length} franchisees</b><span>Expand a mapped Franchisee to view its Sub-Franchisees.</span></div>
      <div className="data-table-wrap"><table className="data-table admin-franchisee-table"><thead><tr><th aria-label="Expand"/><th>Franchisee</th><th>City</th><th>Assigned RM</th><th>Customers</th><th>Applications</th><th>Business</th><th>Pending cases</th><th>Status</th><th/></tr></thead><tbody>{rows.map(f=>{const open=expanded===f.code,load=children[f.code];return <FragmentRow key={f.code}><tr className={`admin-franchisee-row ${open?'expanded':''}`} onClick={()=>setSelected(f)}><td className="admin-expand-cell">{canExpand(f)&&<button className="admin-expand-btn" aria-label={`${open?'Collapse':'Expand'} ${f.name}`} aria-expanded={open} onClick={event=>{event.stopPropagation();toggle(f)}}>{open?<ChevronDown/>:<ChevronRight/>}</button>}</td><td><b className="link-text">{f.name}</b><small>{f.code}{canExpand(f)?' · Sub-Franchisees available':''}</small></td><td><span>{f.city}</span></td><td><b>{f.rm}</b></td><td><b>{f.customers}</b></td><td><b>{f.applications}</b></td><td><b>{formatINR(f.business)}</b></td><td><span className={f.pending>5?'attention-text':''}>{f.pending}</span></td><td><StatusBadge status={f.status}/></td><td><ChevronRight size={17}/></td></tr>{open&&<tr className="admin-sub-row"><td colSpan={10}><SubFranchiseeNest parent={f} load={load} onRetry={()=>{setChildren(current=>{const next={...current};delete next[f.code];return next});setExpanded(undefined);window.setTimeout(()=>toggle(f),0)}} onView={setSelectedSub} onToast={onToast}/></td></tr>}</FragmentRow>})}</tbody></table></div>
    </div>{selected&&<FranchiseeDrawer item={selected} onClose={()=>setSelected(null)} onToast={onToast}/>} {selectedSub&&<SubFranchiseeDrawer item={selectedSub} onClose={()=>setSelectedSub(null)} onToast={onToast}/>}</div>
}

function LegacyFranchiseeList({rows,available,search,city,setSearch,setCity,selected,setSelected,onToast}:{rows:Franchisee[];available:Franchisee[];search:string;city:string;setSearch:(value:string)=>void;setCity:(value:string)=>void;selected:Franchisee|null;setSelected:(value:Franchisee|null)=>void;onToast:(value:string)=>void}){
  return <div className="page"><PageHeader eyebrow="PARTNER NETWORK" title="My franchisees" description="Review assigned partners, activity, business and cases needing support."/><section className="mini-stats"><StatCard label="Total network" value={available.length} meta="Partner offices"/><StatCard label="Active" value={available.filter(f=>f.status==='Active').length} meta="Currently operating" tone="green"/><StatCard label="Customers" value={available.reduce((sum,item)=>sum+item.customers,0)} meta="Across network" tone="blue"/><StatCard label="Business" value={formatINR(available.reduce((sum,item)=>sum+item.business,0),true)} meta="This financial year" tone="violet"/></section><div className="table-panel"><div className="table-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search name or code"/><Select value={city} onChange={setCity}><option>All cities</option>{['Ahmedabad','Surat','Vadodara','Rajkot','Gandhinagar'].map(value=><option key={value}>{value}</option>)}</Select></div><div className="result-count"><b>{rows.length} franchisees</b></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Franchisee</th><th>City</th><th>Assigned RM</th><th>Customers</th><th>Applications</th><th>Business</th><th>Pending cases</th><th>Status</th><th/></tr></thead><tbody>{rows.map(item=><tr key={item.code} onClick={()=>setSelected(item)}><td><b className="link-text">{item.name}</b><small>{item.code}</small></td><td><span>{item.city}</span></td><td><b>{item.rm}</b></td><td><b>{item.customers}</b></td><td><b>{item.applications}</b></td><td><b>{formatINR(item.business)}</b></td><td><span className={item.pending>5?'attention-text':''}>{item.pending}</span></td><td><StatusBadge status={item.status}/></td><td><ChevronRight size={17}/></td></tr>)}</tbody></table></div></div>{selected&&<FranchiseeDrawer item={selected} onClose={()=>setSelected(null)} onToast={onToast}/>}</div>
}

function FragmentRow({children}:{children:ReactNode}){return <>{children}</>}

function SubFranchiseeNest({parent,load,onRetry,onView,onToast}:{parent:Franchisee;load?:ChildLoad;onRetry:()=>void;onView:(item:SubFranchisee)=>void;onToast:(value:string)=>void}){
  if(!load||load.status==='loading')return <div className="admin-sub-state"><LoaderCircle className="spinning"/><div><b>Loading Sub-Franchisees</b><span>Retrieving records mapped to {parent.name}…</span></div></div>
  if(load.status==='error')return <div className="admin-sub-state error"><ShieldCheck/><div><b>Sub-Franchisees could not be loaded</b><span>{load.message}</span></div><button onClick={onRetry}>Retry</button></div>
  if(!load.rows.length)return <div className="admin-sub-state"><UsersRound/><div><b>No Sub-Franchisees</b><span>No records are currently mapped to this Franchisee.</span></div></div>
  return <section className="admin-sub-nest"><header><div><span>ADMIN → FRANCHISEE → SUB-FRANCHISEE</span><h3>Sub-Franchisees under {parent.name}</h3></div><b>{load.rows.length} {load.rows.length===1?'record':'records'}</b></header><div className="admin-sub-table-wrap"><table><thead><tr><th>Code / Firm Name</th><th>Contact Person</th><th>Mobile & Email</th><th>City</th><th>KYC Status</th><th>Status</th><th>Date Added</th><th>Actions</th></tr></thead><tbody>{load.rows.map(item=><tr key={item.id}><td><button className="admin-sub-name" onClick={()=>onView(item)}><b>{item.firmName}</b><small>{item.code}</small></button></td><td>{item.contactPerson}</td><td><span>{item.mobile}</span><small>{item.email}</small></td><td>{item.city}</td><td><StatusBadge status={item.kycStatus}/></td><td><StatusBadge status={item.status}/></td><td>{new Date(`${item.dateAdded}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}</td><td><div className="admin-sub-actions"><button onClick={()=>onView(item)}>View</button><button onClick={()=>{onView(item);onToast('Documents opened for review')}}>Documents</button></div></td></tr>)}</tbody></table></div></section>
}

function FranchiseeDrawer({item:f,onClose,onToast}:{item:Franchisee;onClose:()=>void;onToast:(s:string)=>void}) {
  const [tab,setTab]=useState('Overview'); const tabs=['Overview','Customers','Applications','Business','CRM','Users & Branches','Support','Documents','Activity']
  return <><button className="drawer-scrim" onClick={onClose}/><aside className="detail-drawer franchisee-drawer"><div className="drawer-header"><div><span className="eyebrow">{f.code}</span><h2>{f.name}</h2><p><MapPin size={14}/>{f.city} · RM: {f.rm}</p></div><button className="icon-button" onClick={onClose}><X size={21}/></button></div><div className="drawer-summary"><StatusBadge status={f.status}/><span>Joined <b>18 Mar 2023</b></span><span>Last active <b>Today</b></span></div><div className="drawer-tabs">{tabs.map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><div className="drawer-body">
    <section className="drawer-stat-grid"><StatCard label="Customers" value={f.customers} meta="12 active this month"/><StatCard label="Applications" value={f.applications} meta="Active applications" tone="blue"/><StatCard label="Pending cases" value={f.pending} meta="Needs attention" tone={f.pending>5?'red':'amber'}/><StatCard label="Total business" value={formatINR(f.business,true)} meta="This financial year" tone="green"/></section>
    {tab==='Overview'?<div className="two-col-detail"><section className="detail-section"><h3>Partner information</h3><div className="detail-grid"><div><span>Primary contact</span><b>Neha Patel</b></div><div><span>Mobile</span><b>+91 98765 43210</b></div><div><span>Email</span><b>partner@trothdemo.in</b></div><div><span>Assigned RM</span><b>{f.rm}</b></div></div></section><section className="detail-section"><h3>Attention required</h3><div className="callout warning"><b>{f.pending} cases need follow-up</b><p>2 documents pending and 1 application delayed.</p><button onClick={()=>onToast('Cases filtered')}>Review cases</button></div></section></div>:<section className="detail-section"><h3>{tab}</h3><div className="empty-inline"><span>✓</span><b>{tab} information is up to date</b><p>This tab demonstrates the consolidated Franchisee 360 structure.</p></div></section>}
  </div></aside></>
}

function SubFranchiseeDrawer({item,onClose,onToast}:{item:SubFranchisee;onClose:()=>void;onToast:(value:string)=>void}){
  return <><button className="drawer-scrim" onClick={onClose}/><aside className="detail-drawer admin-sub-detail"><div className="drawer-header"><div><span className="eyebrow">{item.code}</span><h2>{item.firmName}</h2><p><MapPin size={14}/>{item.city}, {item.state}</p></div><button className="icon-button" onClick={onClose}><X/></button></div><div className="drawer-summary"><StatusBadge status={item.status}/><span>Parent <b>{authenticatedFranchisee.name}</b></span><span>KYC <b>{item.kycStatus}</b></span></div><div className="drawer-body"><section className="detail-section"><h3>Sub-Franchisee information</h3><div className="detail-grid"><Detail label="Contact person" value={item.contactPerson}/><Detail label="Mobile" value={item.mobile}/><Detail label="Email" value={item.email}/><Detail label="Legal entity" value={item.legalEntityType}/><Detail label="PAN" value={item.pan}/><Detail label="Territory" value={item.territory}/><Detail label="Date added" value={new Date(`${item.dateAdded}T00:00:00`).toLocaleDateString('en-IN')}/><Detail label="Product access" value={item.products.join(', ')}/></div></section><section className="detail-section"><h3>Documents / KYC</h3><div className="admin-sub-documents">{item.documents.length?item.documents.map(document=><article key={document.id}><FileText/><div><b>{document.type}</b><small>{document.fileName}</small></div><StatusBadge status={document.status}/><button onClick={()=>onToast('Document preview requires storage integration')}>Preview</button></article>):<div className="admin-sub-empty"><FileText/><span>No documents uploaded</span></div>}</div></section></div></aside></>
}
function Detail({label,value}:{label:string;value:string}){return <div><span>{label}</span><b>{value||'—'}</b></div>}

type EntityType='Individual'|'Proprietorship'|'Partnership'|'LLP'|'Private Limited'|'Public Limited'|'Other'
type Address={line1:string;line2:string;area:string;landmark:string;city:string;district:string;state:string;pinCode:string;country:string}
type AdminDocument={type:string;required:boolean;fileName?:string;size?:number;status:'Not Uploaded'|'Uploaded'}
type AdminFranchiseeDraft={name:string;contact:string;mobile:string;alternateMobile:string;email:string;alternateEmail:string;entityType:EntityType;legalName:string;tradeName:string;pan:string;gstin:string;registrationNumber:string;incorporationDate:string;yearsInBusiness:string;natureOfBusiness:string;experience:string;employees:string;businessAddress:Address;communicationAddress:Address;sameAddress:boolean;territory:string;region:string;rm:string;documents:AdminDocument[];accountHolder:string;bankName:string;branchName:string;accountNumber:string;confirmAccountNumber:string;ifsc:string;accountType:'Savings'|'Current';products:string[];effectiveFrom:string;franchiseCategory:string;loginMobile:string;loginEmail:string;sendInvitation:boolean}
const emptyAddress:Address={line1:'',line2:'',area:'',landmark:'',city:'Ahmedabad',district:'Ahmedabad',state:'Gujarat',pinCode:'',country:'India'}
const baseDocuments:AdminDocument[]=[{type:'PAN Card',required:true,status:'Not Uploaded'},{type:'Identity Proof',required:true,status:'Not Uploaded'},{type:'Passport Size Photograph',required:true,status:'Not Uploaded'},{type:'GST Certificate',required:false,status:'Not Uploaded'},{type:'Address Proof',required:true,status:'Not Uploaded'},{type:'Cancelled Cheque',required:true,status:'Not Uploaded'},{type:'Franchise Agreement',required:false,status:'Not Uploaded'}]
const initialAdminDraft=():AdminFranchiseeDraft=>({name:'',contact:'',mobile:'',alternateMobile:'',email:'',alternateEmail:'',entityType:'Proprietorship',legalName:'',tradeName:'',pan:'',gstin:'',registrationNumber:'',incorporationDate:'',yearsInBusiness:'',natureOfBusiness:'Financial Services',experience:'',employees:'',businessAddress:{...emptyAddress},communicationAddress:{...emptyAddress},sameAddress:true,territory:'Ahmedabad',region:'West',rm:'Rohan Mehta',documents:baseDocuments.map(item=>({...item})),accountHolder:'',bankName:'',branchName:'',accountNumber:'',confirmAccountNumber:'',ifsc:'',accountType:'Current',products:['Insurance'],effectiveFrom:new Date().toISOString().slice(0,10),franchiseCategory:'Standard',loginMobile:'',loginEmail:'',sendInvitation:true})
const onboardingSteps=[['Basic Information',UserRound],['Business Information',Building2],['Address & Territory',MapPin],['KYC & Documents',FileCheck2],['Bank Details',Landmark],['Commercial Setup',BadgeIndianRupee],['Login & Access',LockKeyhole],['Review & Submit',CheckCircle2]] as const

function AddFranchiseePage({onClose,onCreate}:{onClose:()=>void;onCreate:()=>void}){
  const [form,setForm]=useState(initialAdminDraft),[step,setStep]=useState(0),[maxVisited,setMaxVisited]=useState(0),[errors,setErrors]=useState<Record<string,string>>({}),[submitting,setSubmitting]=useState(false)
  useEffect(()=>{if(step===0)setForm(current=>({...current,loginMobile:current.mobile,loginEmail:current.email}))},[form.mobile,form.email,step])
  const set=<K extends keyof AdminFranchiseeDraft>(key:K,value:AdminFranchiseeDraft[K])=>{setForm(current=>({...current,[key]:value}));setErrors(current=>{const next={...current};delete next[key];return next})}
  const setAddress=(kind:'businessAddress'|'communicationAddress',key:keyof Address,value:string)=>setForm(current=>{const address={...current[kind],[key]:value};return {...current,[kind]:address,...(kind==='businessAddress'&&current.sameAddress?{communicationAddress:{...address}}:{})}})
  const documentOptions=useMemo(()=>{const options=[...baseDocuments];if(form.entityType==='Private Limited'||form.entityType==='Public Limited')options.push({type:'Certificate of Incorporation',required:true,status:'Not Uploaded'});if(form.entityType==='LLP')options.push({type:'LLP Agreement',required:true,status:'Not Uploaded'});if(form.entityType==='Partnership')options.push({type:'Partnership Deed',required:true,status:'Not Uploaded'});return options.map(option=>form.documents.find(doc=>doc.type===option.type)||option)},[form.documents,form.entityType])
  const validate=(target=step)=>{const next:Record<string,string>={};if(target===0){if(!form.name.trim())next.name='Franchisee name is required.';if(!form.contact.trim())next.contact='Contact person name is required.';if(!/^\+?[0-9 ]{10,16}$/.test(form.mobile))next.mobile='Please enter a valid mobile number.';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email))next.email='Please enter a valid email address.'}if(target===1){if(!form.legalName.trim())next.legalName='Legal business name is required.';if(!/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(form.pan))next.pan='PAN format is invalid.';if(form.gstin&&!/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]Z[0-9A-Z]$/.test(form.gstin))next.gstin='GSTIN format is invalid.'}if(target===2){if(!form.businessAddress.line1.trim())next.line1='Address Line 1 is required.';if(!/^\d{6}$/.test(form.businessAddress.pinCode))next.pinCode='PIN Code must contain 6 digits.';if(!form.territory)next.territory='Territory is required.'}if(target===3){const missing=documentOptions.filter(doc=>doc.required&&!doc.fileName);if(missing.length)next.documents=`Upload ${missing.map(doc=>doc.type).join(', ')}.`}if(target===4){if(!form.accountHolder.trim())next.accountHolder='Account holder name is required.';if(!form.bankName.trim())next.bankName='Bank name is required.';if(!form.accountNumber)next.accountNumber='Account number is required.';if(form.accountNumber!==form.confirmAccountNumber)next.confirmAccountNumber='Account numbers do not match.';if(!/^[A-Z]{4}0[A-Z0-9]{6}$/.test(form.ifsc))next.ifsc='Please enter a valid IFSC code.'}if(target===5&&!form.products.length)next.products='Select at least one product.';if(target===6){if(!/^\+?[0-9 ]{10,16}$/.test(form.loginMobile))next.loginMobile='Please enter a valid login mobile.';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.loginEmail))next.loginEmail='Please enter a valid login email.'}setErrors(next);return Object.keys(next).length===0}
  const next=()=>{if(!validate())return;setStep(value=>Math.min(7,value+1));setMaxVisited(value=>Math.max(value,step+1));window.scrollTo(0,0)}
  const back=()=>{setErrors({});setStep(value=>Math.max(0,value-1));window.scrollTo(0,0)}
  const submit=()=>{for(let index=0;index<7;index++){if(!validate(index)){setStep(index);return}}setSubmitting(true);window.setTimeout(onCreate,500)}
  const upload=(type:string,event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;if(file.size>10*1024*1024){setErrors(current=>({...current,documents:`${file.name} exceeds the 10 MB upload limit.`}));return}setForm(current=>({...current,documents:[...current.documents.filter(doc=>doc.type!==type),{type,required:documentOptions.find(doc=>doc.type===type)?.required||false,fileName:file.name,size:file.size,status:'Uploaded'}]}));setErrors(current=>{const value={...current};delete value.documents;return value});event.target.value=''}
  const uploadedRequired=documentOptions.filter(doc=>doc.required&&doc.fileName).length,totalRequired=documentOptions.filter(doc=>doc.required).length
  return <div className="page admin-franchisee-page admin-add-franchisee"><button className="admin-add-back" onClick={onClose}><ArrowLeft/> Back to Franchisees</button><div className="admin-add-breadcrumb">Admin Dashboard <ChevronRight/> Franchisees <ChevronRight/> <b>Add Franchisee</b></div><PageHeader eyebrow="PARTNER ONBOARDING" title="Add Franchisee" description="Create and onboard a new franchisee with business, KYC, banking, commercial and access details."/>
    <div className="admin-onboarding-stepper">{onboardingSteps.map(([label,Icon],index)=><button key={label} type="button" className={`${step===index?'active':''} ${index<step?'done':''}`} disabled={index>maxVisited} onClick={()=>{if(index<=maxVisited){setStep(index);setErrors({})}}}><i>{index<step?<Check/>:<Icon/>}</i><span><small>STEP {index+1}</small><b>{label}</b></span></button>)}</div>
    <form onSubmit={event=>{event.preventDefault();step===7?submit():next()}}>{step===0&&<AdminFormSection icon={<UserRound/>} title="Basic Information" copy="Primary Franchisee and authorized contact details."><div className="admin-add-fields"><Field label="Franchisee / Firm Name" required error={errors.name}><input autoFocus value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Business or trading name"/></Field><Field label="Contact Person Name" required error={errors.contact}><input value={form.contact} onChange={e=>set('contact',e.target.value)} placeholder="Full name"/></Field><Field label="Mobile Number" required error={errors.mobile}><input inputMode="tel" value={form.mobile} onChange={e=>{set('mobile',e.target.value.replace(/[^0-9+ ]/g,''));if(!form.loginMobile)set('loginMobile',e.target.value)}} placeholder="+91 98765 43210"/></Field><Field label="Alternate Mobile Number"><input inputMode="tel" value={form.alternateMobile} onChange={e=>set('alternateMobile',e.target.value.replace(/[^0-9+ ]/g,''))}/></Field><Field label="Email Address" required error={errors.email}><input type="email" value={form.email} onChange={e=>{set('email',e.target.value.trim());if(!form.loginEmail)set('loginEmail',e.target.value)}} placeholder="name@company.in"/></Field><Field label="Alternate Email"><input type="email" value={form.alternateEmail} onChange={e=>set('alternateEmail',e.target.value.trim())}/></Field><Field label="Business Constitution / Entity Type" required><select value={form.entityType} onChange={e=>set('entityType',e.target.value as EntityType)}>{['Individual','Proprietorship','Partnership','LLP','Private Limited','Public Limited','Other'].map(value=><option key={value}>{value}</option>)}</select></Field></div></AdminFormSection>}
      {step===1&&<AdminFormSection icon={<Building2/>} title="Business Information" copy="Legal, registration and operating profile used for due diligence."><div className="admin-add-fields"><Field label="Legal Business Name" required error={errors.legalName}><input autoFocus value={form.legalName} onChange={e=>set('legalName',e.target.value)} placeholder="As per registration documents"/></Field><Field label="Trade Name"><input value={form.tradeName} onChange={e=>set('tradeName',e.target.value)}/></Field><Field label="PAN" required error={errors.pan}><input maxLength={10} value={form.pan} onChange={e=>set('pan',e.target.value.toUpperCase().replace(/\s/g,''))} placeholder="ABCDE1234F"/></Field><Field label="GSTIN" error={errors.gstin}><input maxLength={15} value={form.gstin} onChange={e=>set('gstin',e.target.value.toUpperCase().replace(/\s/g,''))} placeholder="24ABCDE1234F1Z5"/></Field>{!['Individual','Proprietorship'].includes(form.entityType)&&<Field label={form.entityType==='LLP'?'LLPIN':form.entityType.includes('Limited')?'CIN':'Registration Number'}><input value={form.registrationNumber} onChange={e=>set('registrationNumber',e.target.value.toUpperCase().trim())}/></Field>}<Field label="Date of Incorporation"><input type="date" value={form.incorporationDate} onChange={e=>set('incorporationDate',e.target.value)}/></Field><Field label="Years in Business"><input type="number" min="0" max="100" value={form.yearsInBusiness} onChange={e=>set('yearsInBusiness',e.target.value)}/></Field><Field label="Nature of Business"><input value={form.natureOfBusiness} onChange={e=>set('natureOfBusiness',e.target.value)}/></Field><Field label="Financial Services Experience"><select value={form.experience} onChange={e=>set('experience',e.target.value)}><option value="">Select experience</option><option>Less than 1 year</option><option>1–3 years</option><option>3–5 years</option><option>More than 5 years</option></select></Field><Field label="Number of Employees"><input type="number" min="0" value={form.employees} onChange={e=>set('employees',e.target.value)}/></Field></div></AdminFormSection>}
      {step===2&&<AdminFormSection icon={<MapPin/>} title="Address & Territory" copy="Registered address, correspondence address and network allocation."><h3 className="admin-form-subtitle">Registered / Business Address</h3><AddressFields value={form.businessAddress} set={(key,value)=>setAddress('businessAddress',key,value)} errors={errors}/><label className="admin-address-copy"><input type="checkbox" checked={form.sameAddress} onChange={e=>{set('sameAddress',e.target.checked);if(e.target.checked)set('communicationAddress',{...form.businessAddress})}}/><span><b>Same as Business Address</b><small>Use the registered address for all communications.</small></span></label>{!form.sameAddress&&<><h3 className="admin-form-subtitle">Communication Address</h3><AddressFields value={form.communicationAddress} set={(key,value)=>setAddress('communicationAddress',key,value)}/></>}<h3 className="admin-form-subtitle">Franchise Territory</h3><div className="admin-add-fields"><Field label="Territory / Zone" required error={errors.territory}><input value={form.territory} onChange={e=>set('territory',e.target.value)}/></Field><Field label="Branch / Region"><select value={form.region} onChange={e=>set('region',e.target.value)}><option>West</option><option>North</option><option>South</option><option>Central</option></select></Field><Field label="Assigned RM" required><select value={form.rm} onChange={e=>set('rm',e.target.value)}><option>Rohan Mehta</option><option>Kavya Shah</option></select></Field></div></AdminFormSection>}
      {step===3&&<AdminFormSection icon={<FileCheck2/>} title="KYC & Documents" copy="Upload entity-appropriate documents for compliance verification."><div className="admin-kyc-progress"><div><span><ShieldCheck/> KYC Completion</span><b>{uploadedRequired} of {totalRequired} required documents uploaded</b></div><div className="admin-kyc-bar"><i style={{width:`${totalRequired?uploadedRequired/totalRequired*100:0}%`}}/></div><StatusBadge status={uploadedRequired===0?'Not Started':uploadedRequired<totalRequired?'Incomplete':'Pending Verification'}/></div><div className="admin-doc-grid">{documentOptions.map(doc=><DocumentUpload key={doc.type} document={doc} onUpload={event=>upload(doc.type,event)} onRemove={()=>set('documents',form.documents.map(item=>item.type===doc.type?{...item,fileName:undefined,size:undefined,status:'Not Uploaded'}:item))}/>)}</div>{errors.documents&&<InlineError>{errors.documents}</InlineError>}</AdminFormSection>}
      {step===4&&<AdminFormSection icon={<Landmark/>} title="Bank Details" copy="Settlement account details for verified franchise payouts."><div className="admin-bank-status"><CreditCard/><div><b>Bank verification</b><span>Verification will begin after successful Franchisee creation.</span></div><StatusBadge status="Pending"/></div><div className="admin-add-fields"><Field label="Account Holder Name" required error={errors.accountHolder}><input autoFocus value={form.accountHolder} onChange={e=>set('accountHolder',e.target.value)}/></Field><Field label="Bank Name" required error={errors.bankName}><input value={form.bankName} onChange={e=>set('bankName',e.target.value)}/></Field><Field label="Branch Name"><input value={form.branchName} onChange={e=>set('branchName',e.target.value)}/></Field><Field label="Account Type"><select value={form.accountType} onChange={e=>set('accountType',e.target.value as 'Savings'|'Current')}><option>Savings</option><option>Current</option></select></Field><Field label="Account Number" required error={errors.accountNumber}><input type="password" inputMode="numeric" autoComplete="new-password" value={form.accountNumber} onChange={e=>set('accountNumber',e.target.value.replace(/\D/g,''))}/></Field><Field label="Confirm Account Number" required error={errors.confirmAccountNumber}><input inputMode="numeric" value={form.confirmAccountNumber} onChange={e=>set('confirmAccountNumber',e.target.value.replace(/\D/g,''))}/></Field><Field label="IFSC Code" required error={errors.ifsc}><input maxLength={11} value={form.ifsc} onChange={e=>set('ifsc',e.target.value.toUpperCase().replace(/\s/g,''))} placeholder="HDFC0001234"/></Field></div></AdminFormSection>}
      {step===5&&<AdminFormSection icon={<BadgeIndianRupee/>} title="Commercial Setup" copy="Configure access using the platform's existing product catalogue."><div className="admin-commercial-note"><ShieldCheck/><div><b>Existing commercial controls apply</b><span>Commission and payout calculations remain governed by the configured Admin policies.</span></div></div><div className="admin-add-fields"><Field label="Franchisee Category"><select value={form.franchiseCategory} onChange={e=>set('franchiseCategory',e.target.value)}><option>Standard</option><option>Growth</option><option>Strategic</option></select></Field><Field label="Effective From"><input type="date" value={form.effectiveFrom} onChange={e=>set('effectiveFrom',e.target.value)}/></Field></div><fieldset className="admin-product-access"><legend>Products / Verticals <sup>*</sup></legend>{['Insurance','Loans','Loan Protector','Mutual Fund','Demat','Research','Advisory'].map(product=><label key={product}><input type="checkbox" checked={form.products.includes(product)} onChange={()=>set('products',form.products.includes(product)?form.products.filter(value=>value!==product):[...form.products,product])}/><span><Check/>{product}</span></label>)}</fieldset>{errors.products&&<InlineError>{errors.products}</InlineError>}</AdminFormSection>}
      {step===6&&<AdminFormSection icon={<LockKeyhole/>} title="Login & Access" copy="Create the Franchisee account using the existing activation workflow."><div className="admin-access-role"><LockKeyhole/><div><span>System Role</span><b>Franchisee</b><small>Assigned automatically and cannot be changed from this page.</small></div><em>LOCKED</em></div><div className="admin-add-fields"><Field label="Login Mobile" required error={errors.loginMobile}><input autoFocus inputMode="tel" value={form.loginMobile} onChange={e=>set('loginMobile',e.target.value.replace(/[^0-9+ ]/g,''))}/></Field><Field label="Login Email" required error={errors.loginEmail}><input type="email" value={form.loginEmail} onChange={e=>set('loginEmail',e.target.value.trim())}/></Field><Field label="Initial Account Status"><input value="Pending Approval" readOnly/></Field></div><label className="admin-address-copy"><input type="checkbox" checked={form.sendInvitation} onChange={e=>set('sendInvitation',e.target.checked)}/><span><b>Send login invitation after successful creation</b><small>Uses the platform's existing authentication and invitation workflow.</small></span></label></AdminFormSection>}
      {step===7&&<AdminFormSection icon={<CheckCircle2/>} title="Review & Submit" copy="Confirm the complete onboarding record before creating the Franchisee."><div className="admin-review-alert"><CheckCircle2/><div><b>Ready for final review</b><span>Review each section below. Sensitive bank details are masked.</span></div></div><div className="admin-onboarding-review"><ReviewCard title="Basic Information" onEdit={()=>setStep(0)} rows={[['Franchisee',form.name],['Contact',form.contact],['Mobile',form.mobile],['Email',form.email],['Entity Type',form.entityType]]}/><ReviewCard title="Business Information" onEdit={()=>setStep(1)} rows={[['Legal Name',form.legalName],['PAN',form.pan],['GSTIN',form.gstin||'Not provided'],['Nature',form.natureOfBusiness]]}/><ReviewCard title="Address & Territory" onEdit={()=>setStep(2)} rows={[['Address',`${form.businessAddress.line1}, ${form.businessAddress.city}`],['State / PIN',`${form.businessAddress.state} ${form.businessAddress.pinCode}`],['Territory',form.territory],['Assigned RM',form.rm]]}/><ReviewCard title="KYC & Documents" onEdit={()=>setStep(3)} rows={[['Required uploaded',`${uploadedRequired} of ${totalRequired}`],['Total files',String(documentOptions.filter(doc=>doc.fileName).length)],['Status',uploadedRequired===totalRequired?'Pending Verification':'Incomplete']]}/><ReviewCard title="Bank Details" onEdit={()=>setStep(4)} rows={[['Account Holder',form.accountHolder],['Bank',form.bankName],['Account',form.accountNumber?`•••• ${form.accountNumber.slice(-4)}`:'—'],['IFSC',form.ifsc]]}/><ReviewCard title="Commercial Setup" onEdit={()=>setStep(5)} rows={[['Category',form.franchiseCategory],['Products',form.products.join(', ')],['Effective From',form.effectiveFrom]]}/><ReviewCard title="Login & Access" onEdit={()=>setStep(6)} rows={[['Role','Franchisee'],['Login Mobile',form.loginMobile],['Login Email',form.loginEmail],['Invitation',form.sendInvitation?'Send after creation':'Do not send']]}/></div><div className="admin-add-note"><ShieldCheck/><div><b>Creation workflow protected</b><p>Submitting invokes the existing Add Franchisee completion flow. Account activation and downstream verification remain governed by current platform controls.</p></div></div></AdminFormSection>}
      {Object.keys(errors).length>0&&step!==3&&step!==5&&<InlineError>Please correct the highlighted fields before continuing.</InlineError>}<footer><button type="button" className="secondary-btn" onClick={step===0?onClose:back}>{step===0?'Cancel':<><ChevronLeft/> Previous</>}</button><span>Step {step+1} of {onboardingSteps.length}</span><button className="primary-btn" disabled={submitting}>{submitting?<><LoaderCircle className="spinning"/> Creating Franchisee…</>:step===7?<><ShieldCheck/> Create Franchisee</>:<>Continue <ChevronRight/></>}</button></footer></form>
  </div>
}

function AdminFormSection({icon,title,copy,children}:{icon:ReactNode;title:string;copy:string;children:ReactNode}){return <section className="admin-add-section"><header><span>{icon}</span><div><h2>{title}</h2><p>{copy}</p></div></header><div className="admin-add-section-body">{children}</div></section>}
function Field({label,required,error,children}:{label:string;required?:boolean;error?:string;children:ReactNode}){return <label className={`admin-add-field ${error?'invalid':''}`}>{label}{required&&<sup>*</sup>}{children}{error&&<small>{error}</small>}</label>}
function InlineError({children}:{children:ReactNode}){return <div className="admin-add-error"><CircleAlert/>{children}</div>}
function AddressFields({value,set,errors={}}:{value:Address;set:(key:keyof Address,value:string)=>void;errors?:Record<string,string>}){return <div className="admin-add-fields"><Field label="Address Line 1" required error={errors.line1}><input autoFocus value={value.line1} onChange={e=>set('line1',e.target.value)}/></Field><Field label="Address Line 2"><input value={value.line2} onChange={e=>set('line2',e.target.value)}/></Field><Field label="Area / Locality"><input value={value.area} onChange={e=>set('area',e.target.value)}/></Field><Field label="Landmark"><input value={value.landmark} onChange={e=>set('landmark',e.target.value)}/></Field><Field label="City" required><input value={value.city} onChange={e=>set('city',e.target.value)}/></Field><Field label="District"><input value={value.district} onChange={e=>set('district',e.target.value)}/></Field><Field label="State" required><input value={value.state} onChange={e=>set('state',e.target.value)}/></Field><Field label="PIN Code" required error={errors.pinCode}><input inputMode="numeric" maxLength={6} value={value.pinCode} onChange={e=>set('pinCode',e.target.value.replace(/\D/g,''))}/></Field><Field label="Country"><input value={value.country} readOnly/></Field></div>}
function DocumentUpload({document,onUpload,onRemove}:{document:AdminDocument;onUpload:(event:ChangeEvent<HTMLInputElement>)=>void;onRemove:()=>void}){return <article className={`admin-document-card ${document.fileName?'uploaded':''}`}><header><span><FileText/></span><div><b>{document.type}</b><small>{document.required?'Required':'Optional'} · PDF, JPG, JPEG or PNG · Max 10 MB</small></div><em>{document.fileName?'UPLOADED':document.required?'REQUIRED':'OPTIONAL'}</em></header>{document.fileName?<div className="admin-document-file"><FileCheck2/><div><b>{document.fileName}</b><small>{document.size?`${(document.size/1024).toFixed(0)} KB`:'File selected'} · Pending verification</small></div><label title="Replace"><RefreshCw/><input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={onUpload}/></label><button type="button" title="Preview not available before submission"><Eye/></button><button type="button" title="Remove" onClick={onRemove}><Trash2/></button></div>:<label className="admin-document-drop"><Upload/><span><b>Upload document</b><small>Choose a file from your device</small></span><input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={onUpload}/></label>}</article>}
function ReviewCard({title,rows,onEdit}:{title:string;rows:[string,string][];onEdit:()=>void}){return <article><header><h3>{title}</h3><button type="button" onClick={onEdit}><Pencil/> Edit</button></header><div>{rows.map(([label,value])=><p key={label}><span>{label}</span><b>{value||'—'}</b></p>)}</div></article>}
