import { useState } from 'react'
import { ArrowRight, BookOpen, CheckCircle2, Clock3, Download, Headphones, Landmark, Mail, Plus, ShieldCheck, TrendingUp, Upload, UserPlus, WalletCards } from 'lucide-react'
import { formatINR, recentActivity } from '../data/mockData'
import type { Application, Role } from '../types'
import { PageHeader, StatCard, StatusBadge } from '../components/UI'
import { roleConfigs } from '../config/roles'

const titles:Record<string,[string,string]>={
  users:['Users & access','Manage team members, roles and product permissions.'],customers:['Customers & CRM','Customer relationships, leads, meetings and follow-ups in one place.'],products:['Products & partners','Explore and manage financial products and provider relationships.'],operations:['Operations & workflow','Configure stages, document requirements and turnaround rules.'],support:['Support & communication','Track requests, conversations and responses.'],reports:['Reports & MIS','Understand business, conversion and operational performance.'],administration:['Administration','Templates, master data, settings and audit history.'],business:['Business performance','Track product-wise business, conversion and opportunities.'],performance:['Partner performance','Compare franchisees and identify growth opportunities.'],documents:['Document workspace','Verify received documents and follow up on missing items.'],communication:['Communication & actions','Coordinate requirements, remarks and next actions.'],completed:['Completed cases','Review recently completed, issued and disbursed applications.'],'my-products':['My products','Everything you hold with Troth One, together in one place.'],explore:['Explore products','Find the right protection, credit and investment products.'],profile:['Documents & profile','Keep your identity, KYC and consent information up to date.']
}
const productCards=[['Health Insurance','Protect your family against medical expenses.',ShieldCheck],['Home Loan','Funding for your next home with guided support.',Landmark],['Mutual Fund SIP','Build long-term wealth through disciplined investing.',TrendingUp],['Loan Protector','Help protect loan repayments against life events.',WalletCards],['Demat Account','A simple account for market investments.',WalletCards],['Research','Actionable market insight from experienced analysts.',BookOpen]]

export function GenericPage({role,page,apps,onNavigate,onToast}:{role:Role;page:string;apps:Application[];onNavigate:(p:string)=>void;onToast:(s:string)=>void}) {
  const [modal,setModal]=useState(false); const [filter,setFilter]=useState('All'); const [query,setQuery]=useState('')
  const [baseTitle,baseDesc]=titles[page]||['Workspace','Everything you need, in one place.']
  const title=role==='customer'&&page==='documents'?'My documents':baseTitle
  const desc=role==='customer'&&page==='documents'?'View and manage your KYC and account documents.':baseDesc
  const currentUser=roleConfigs[role]
  const customerInitials=currentUser.user.split(' ').map(part=>part[0]).join('')
  const customerEmail=`${currentUser.user.toLowerCase().replaceAll(' ','.')}@example.in`
  const primary=page==='support'?'Raise support request':page==='customers'?'Add customer':page==='documents'||page==='profile'?'Upload document':page==='users'?'Add user':page==='reports'||page==='business'||page==='performance'?'Export report':''
  return <div className="page"><PageHeader eyebrow={page.replaceAll('-',' ').toUpperCase()} title={title} description={desc} actions={primary?<button className="primary-btn" onClick={()=>primary==='Export report'?onToast('Report exported'):setModal(true)}>{primary.includes('Upload')?<Upload size={17}/>:primary.includes('Export')?<Download size={17}/>:<Plus size={17}/>} {primary}</button>:undefined}/>
    {page==='explore'?<section className="product-catalogue">{productCards.map(([name,copy,Icon])=><article key={String(name)}><div className="catalogue-icon"><Icon size={24}/></div><span>POPULAR</span><h3>{String(name)}</h3><p>{String(copy)}</p><div><button onClick={()=>onToast('Callback requested')}>Request callback</button><button onClick={()=>onNavigate('applications')}>Explore <ArrowRight size={15}/></button></div></article>)}</section>
    :page==='my-products'?<section className="product-holdings">{[['Family Health Secure','HDFC ERGO','Active','18 Sep 2026',18500],['Home Advantage Loan','HDFC Bank','Active','05 Oct 2026',2500000],['Balanced Advantage SIP','HDFC AMC','Active','Monthly',5000],['Equity Research Pro','Troth Research','Active','12 Dec 2026',12000]].map(([name,provider,status,due,amount])=><article key={String(name)}><div className="holding-top"><div className="catalogue-icon"><WalletCards size={21}/></div><StatusBadge status={String(status)}/></div><h3>{name}</h3><p>{provider}</p><div className="holding-meta"><span>Amount / Premium<b>{formatINR(Number(amount))}</b></span><span>Next due / Renewal<b>{due}</b></span></div><button onClick={()=>onToast('Product details opened')}>View details <ArrowRight size={15}/></button></article>)}</section>
    :page==='profile'?<div className="content-grid"><section className="panel span-2"><div className="panel-head"><div><b>Personal information</b><small>Verified customer profile</small></div><button onClick={()=>onToast('Profile editing enabled')}>Edit</button></div><div className="profile-block"><div className="profile-avatar">{customerInitials}</div><div><h3>{currentUser.user}</h3><p>+91 98••• ••426 • {customerEmail}</p><span><CheckCircle2 size={14}/> KYC verified</span></div></div><div className="detail-grid profile-details"><div><span>PAN</span><b>ABCDE••••F</b></div><div><span>Date of birth</span><b>12 July 1988</b></div><div><span>City</span><b>Ahmedabad</b></div><div><span>Nominee</span><b>Meera Joshi</b></div></div></section><section className="panel"><div className="panel-head"><div><b>Documents</b><small>4 of 4 available</small></div><button onClick={()=>onNavigate('documents')}>View all</button></div><div className="document-list compact">{['PAN card','Aadhaar card','Cancelled cheque','Signature'].map(x=><div key={x}><span className="doc-icon received">▤</span><div><b>{x}</b><small>Verified</small></div><CheckCircle2 size={18} color="#1b9c6c"/></div>)}</div></section></div>
    :role==='customer'&&page==='documents'?<div className="content-grid customer-documents-view"><section className="panel span-2"><div className="panel-head"><div><b>Identity and KYC documents</b><small>Documents currently available on your profile</small></div><button onClick={()=>setModal(true)}>Upload document</button></div><div className="document-list">{[['PAN card','ABCDE••••F'],['Aadhaar card','•••• •••• 4826'],['Cancelled cheque','HDFC Bank ••••7192'],['Signature','Updated 18 Mar 2026']].map(([name,detail])=><div key={name}><span className="doc-icon received">▤</span><div><b>{name}</b><small>{detail}</small></div><StatusBadge status="Verified"/><button onClick={()=>onToast(`${name} opened`)}>View</button></div>)}</div></section><section className="panel document-guidance"><div className="panel-head"><div><b>Document guidance</b><small>Keep information current</small></div></div><div><CheckCircle2/><p><b>All core documents are verified</b><span>Upload a replacement when an existing document changes or expires.</span></p></div><button className="secondary-btn" onClick={()=>onNavigate('support')}>Need document help?</button></section></div>
    :<><section className="mini-stats"><StatCard label={page==='support'?'Open tickets':'Total records'} value={page==='support'?14:page==='users'?36:apps.length} meta="Across your access"/><StatCard label="Needs attention" value={apps.filter(a=>a.status==='Delayed'||a.status==='Action Required').length} meta="Review recommended" tone="amber"/><StatCard label="Completed" value={apps.filter(a=>a.status==='Completed').length} meta="This month" tone="green"/><StatCard label="On time" value="92%" meta="Current performance" tone="blue"/></section><div className="content-grid"><section className="panel span-2"><div className="panel-head"><div><b>{page==='support'?'Support requests':page==='documents'?'Documents requiring action':page==='reports'||page==='business'||page==='performance'?'Performance overview':'Recent records'}</b><small>Updated today</small></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Open</option><option>Completed</option></select></div><div className="simple-list">{apps.slice(0,6).map((a,i)=><button key={a.id} onClick={()=>onNavigate('applications')}><div className="list-avatar">{page==='support'?<Headphones size={18}/>:page==='users'?<UserPlus size={18}/>:<Clock3 size={18}/>}</div><div><b>{page==='support'?['Document upload issue','Provider update requested','Need product clarification'][i%3]:a.customer}</b><span>{a.id} • {a.productName}</span></div><StatusBadge status={page==='support'?(i%2?'In Progress':'New'):a.status}/><ArrowRight size={16}/></button>)}</div></section><section className="panel"><div className="panel-head"><div><b>Recent activity</b><small>Latest changes</small></div></div><div className="activity-list">{recentActivity.map(([a,b])=><div key={a}><i/><p><b>{a}</b><span>{b}</span></p></div>)}</div></section></div></>}
    {modal&&<div className="modal-wrap"><button className="modal-scrim" onClick={()=>setModal(false)}/><form className="modal" onSubmit={e=>{e.preventDefault();setModal(false);onToast(`${primary} submitted`)}}><div className="modal-icon">{page==='support'?<Headphones/>:page==='customers'?<UserPlus/>:<Upload/>}</div><h2>{primary}</h2><p>Enter the details below. This prototype saves changes locally.</p>{page==='support'?<><label>Request type<select><option>Application support</option><option>Product query</option><option>Technology issue</option></select></label><label>How can we help?<textarea required placeholder="Describe the issue or request"/></label></>:page==='customers'?<><label>Customer name<input required placeholder="Full name"/></label><label>Mobile number<input required placeholder="+91"/></label><label>Email<input type="email" placeholder="name@example.in"/></label></>:<><label>Document type<select><option>PAN card</option><option>Bank statement</option><option>Other</option></select></label><label className="upload-zone"><Upload/><b>Choose a file</b><span>PDF, JPG or PNG • Max 10 MB</span><input type="file"/></label></>}<div className="form-actions"><button type="button" className="secondary-btn" onClick={()=>setModal(false)}>Cancel</button><button className="primary-btn">Submit</button></div></form></div>}
  </div>
}
