import type { OpsCase,OpsQuery,OpsStore,ProductDesk } from './types'
import type { ProductType } from '../types'

export const productDeskConfig:Record<ProductType,ProductDesk>={Insurance:'Insurance Desk',Loans:'Lending Desk','Loan Protector':'General Operations','Mutual Fund':'Wealth Operations',Demat:'Wealth Operations',Research:'Wealth Operations',Advisory:'Wealth Operations'}
const franchises=[['FR-0101','Troth Finserve'],['FR-0102','Aarohi Wealth'],['FR-0103','Navkar Associates'],['FR-0105','Shreeji Finance']] as const
const products:ProductType[]=['Insurance','Loans','Loan Protector','Mutual Fund','Insurance','Loans','Insurance','Mutual Fund','Loan Protector','Insurance','Loans','Demat']
const stages:OpsCase['stage'][]=['Received','Under Review','Query Raised','Query Resolved','Terms Finalized','Awaiting Payment','Payment Confirmed','Issuance Pending','Completed','Under Review','Received','Completed']
const people=['Vivek Joshi','Riya Desai','Arjun Trivedi','Meera Shah','Dev Patel','Diya Bhatt','Kabir Mehta','Aanya Modi','Ishaan Dave','Anika Parekh','Nirav Vora','Sara Gandhi']
const event=(id:string,action:string,note:string,actor='System',role:OpsCase['timeline'][number]['role']='System'):OpsCase['timeline'][number]=>({id,at:'09 Sep 2026 · 10:30 AM',actor,role,action,note})
export const seedCases:OpsCase[]=people.map((customer,i)=>{const product=products[i],stage=stages[i],fr=franchises[i%franchises.length],desk=productDeskConfig[product],age=[1,2,7,4,3,6,2,5,1,8,6,1][i];return{id:`T1-${20260101+i}`,customerId:`TC-${1101+i}`,customer,mobile:`+91 98${String(24000000+i*731).padStart(8,'0')}`,email:`${customer.toLowerCase().replace(' ','.')}@example.in`,franchiseId:fr[0],franchise:fr[1],product,productName:product==='Insurance'?['Health Insurance','Motor Insurance','Term Insurance'][i%3]:product==='Loans'?['Home Loan','Business Loan'][i%2]:product,applicationType:i%4===0?'Renewal':'New Application',amount:product==='Insurance'?24000+i*2750:250000+i*185000,stage,submittedAt:`${String(1+i%8).padStart(2,'0')} Sep 2026`,updatedAt:'09 Sep 2026',age,assignedTo:i%5===0?'Unassigned':'Priya Nair',desk,pendingAction:stage==='Query Raised'?'Review franchise response':stage==='Awaiting Payment'?'Follow up payment':stage==='Issuance Pending'?'Upload final document':stage==='Completed'?'None':'Complete review',documents:[{id:`D-${i}-1`,name:'PAN / KYC.pdf',type:'KYC',source:'Franchise',status:'Reviewed',uploadedAt:'Submission'},{id:`D-${i}-2`,name:product==='Insurance'?'Proposal form.pdf':'Application form.pdf',type:'Application',source:'Franchise',status:i===2?'Incomplete':'Received',uploadedAt:'Submission'}],queryIds:i===2?['Q-26041']:[],payment:{status:stage==='Completed'||stage==='Payment Confirmed'||stage==='Issuance Pending'?'Paid':stage==='Awaiting Payment'?'Link Sent':'Not Started',amount:product==='Insurance'?24000+i*2750:250000+i*185000,reference:stage==='Completed'?`PAY-${6001+i}`:undefined},issuance:{status:stage==='Completed'?'Issued':stage==='Issuance Pending'?'Ready':'Not Started',documentType:stage==='Completed'?'Final policy':undefined,reference:stage==='Completed'?`POL-${8801+i}`:undefined,fileName:stage==='Completed'?'Final document.pdf':undefined},timeline:[event(`E-${i}-1`,'Application submitted','Case entered the Operations queue',fr[1],'Franchise'),event(`E-${i}-2`,stage==='Received'?'Awaiting assignment':'Processing updated',`Case is currently ${stage}`,'Priya Nair','Operations')]}})
export const seedQueries:OpsQuery[]=[{id:'Q-26041',caseId:'T1-20260103',type:'Missing Document',subject:'Latest income proof required',description:'The submitted income proof is incomplete.',requirement:'Upload the latest three-month salary statement.',priority:'High',dueDate:'10 Sep 2026',status:'Response Received',raisedAt:'07 Sep 2026',raisedBy:'Priya Nair',response:'Latest bank statement attached for review.',rmComments:['Rohan Mehta: Franchise confirmed upload today.'],documents:['Bank statement Sep.pdf'],updatedAt:'09 Sep 2026'}]
export const operationsSeed:OpsStore={cases:seedCases,queries:seedQueries,user:{id:'OPS-014',name:'Priya Nair',designation:'Senior Operations Executive',desk:'General Operations',email:'priya.nair@trothone.in',mobile:'+91 98765 41014',scope:'all',allocatedFranchiseIds:franchises.map(x=>x[0]),authorisedDesks:['General Operations','Insurance Desk','Lending Desk','Wealth Operations']}}
