import { AlertTriangle, CheckCircle2, Plus, ShieldCheck, Upload, UserRoundPlus } from 'lucide-react'
import { useMemo, useState, type ChangeEvent } from 'react'
import { assignmentEligibility, assignmentProgress, buildAgentBusinessLines, franchiseeAgentRepository, onboardingStatus, type AgentBusinessLine, type AgentDraft, type AgentFileMetadata, type AgentRequirement, type FranchiseeAgent } from '../agentOnboarding'
import type { FranchiseeCase, FranchiseeCustomer, FranchiseeProduct } from '../types'
import { DataTable, FilterSelect, Filters, Modal, PageHeader, Panel, Progress, StatusBadge, Timeline } from '../components/FranchiseeUI'

export type DetailTab='Profile'|'Onboarding Checklist'|'Documents'|'Activity'
export type SimpleAgentTab='Overview'|'Customers'|'Business Lines'|'Compliance'|'Documents'|'Activity'
const detailTabs:SimpleAgentTab[]=['Overview','Customers','Business Lines','Compliance','Documents','Activity']
const legacyDetailTabs:DetailTab[]=['Profile','Onboarding Checklist','Documents','Activity']

export function AgentsPage({products,customers,cases,onOpenCustomer,onToast}:{products:FranchiseeProduct[];customers:FranchiseeCustomer[];cases:FranchiseeCase[];onOpenCustomer:(id:string)=>void;onToast:(message:string)=>void}){
  const lines=useMemo(()=>buildAgentBusinessLines(products),[products])
  const [agents,setAgents]=useState(()=>franchiseeAgentRepository.load(products)),[search,setSearch]=useState(''),[lineFilter,setLineFilter]=useState('All Business Lines'),[typeFilter,setTypeFilter]=useState('All Agent Types'),[statusFilter,setStatusFilter]=useState('All Statuses'),[complianceFilter,setComplianceFilter]=useState('All Compliance'),[formOpen,setFormOpen]=useState(false),[selected,setSelected]=useState<FranchiseeAgent>(),[tab,setTab]=useState<SimpleAgentTab>('Overview')
  const directAgents=agents.filter(agent=>!agent.subFranchiseeId)
  const agentTypes=[...new Set(directAgents.map(agent=>agent.designation))]
  const rows=directAgents.filter(agent=>(lineFilter==='All Business Lines'||agent.assignments.some(line=>line.businessLine===lineFilter))&&(typeFilter==='All Agent Types'||agent.designation===typeFilter)&&(statusFilter==='All Statuses'||simpleStatus(agent)===statusFilter)&&(complianceFilter==='All Compliance'||complianceStatus(agent)===complianceFilter)&&`${agent.name} ${agent.agentCode} ${agent.mobile} ${agent.email}`.toLowerCase().includes(search.toLowerCase()))
  const updateRequirement=(agent:FranchiseeAgent,lineId:string,requirement:AgentRequirement,status:'Completed'|'Pending HO Verification',document?:AgentFileMetadata)=>{const updated=franchiseeAgentRepository.updateRequirement(agent.id,lineId,requirement.id,status,products,document);if(!updated)return;setAgents(current=>current.map(item=>item.id===updated.id?updated:item));setSelected(updated);onToast(status==='Completed'?`${requirement.name} marked complete`:`${requirement.name} submitted for verification`)}
  const open=(agent:FranchiseeAgent)=>{setSelected(agent);setTab('Overview')}
  return <div className="franchisee-agents">
    <PageHeader eyebrow="FRANCHISE TEAM" title="Agents" description="View and manage agents working with your franchise." actions={<button className="tf-primary" onClick={()=>setFormOpen(true)}><Plus/> Add Agent</button>}/>
    <Panel title="Agent List" subtitle={`${rows.length} agents`}><div className="agents-filters"><Filters search={search} onSearch={setSearch}/><FilterSelect label="Agent Type" value={typeFilter} onChange={setTypeFilter} options={['All Agent Types',...agentTypes]}/><FilterSelect label="Business Line" value={lineFilter} onChange={setLineFilter} options={['All Business Lines',...lines.map(line=>line.name)]}/><FilterSelect label="Compliance" value={complianceFilter} onChange={setComplianceFilter} options={['All Compliance','Complete','Pending','Verification Required']}/><FilterSelect label="Status" value={statusFilter} onChange={setStatusFilter} options={['All Statuses','Active','Onboarding']}/></div>
      <DataTable headers={['Agent Name','Contact','Agent Type','Business Lines','Customers','Compliance','Status','View']} empty={!rows.length}>{rows.map(agent=>{const customerCount=agent.assignedCustomerIds?.length||0;return <tr key={agent.id}><td><button className="agent-identity" onClick={()=>open(agent)}><span>{initials(agent.name)}</span><div><b>{agent.name}</b><small>{agent.agentCode}</small></div></button></td><td><b>{agent.mobile}</b><small>{agent.email}</small></td><td>{agent.designation}</td><td><CompactList values={agent.assignments.map(line=>line.businessLine)}/></td><td><b>{customerCount} Customer{customerCount===1?'':'s'}</b></td><td><StatusBadge>{complianceStatus(agent)}</StatusBadge></td><td><StatusBadge>{simpleStatus(agent)}</StatusBadge></td><td><button className="tf-text-btn" onClick={()=>open(agent)}>View</button></td></tr>})}</DataTable>
    </Panel>
    {formOpen&&<AgentForm lines={lines} products={products} customers={customers} onClose={()=>setFormOpen(false)} onSave={agent=>{setAgents(current=>[agent,...current]);setFormOpen(false);open(agent);onToast(`${agent.name} added successfully`)}}/>}
    {selected&&<SimpleAgentDetail agent={selected} customers={customers} cases={cases} tab={tab} setTab={setTab} onClose={()=>setSelected(undefined)} onOpenCustomer={onOpenCustomer} onUpdate={updateRequirement}/>}
  </div>
}

export function AgentForm({lines,products,customers,subFranchiseeId,onClose,onSave}:{lines:AgentBusinessLine[];products:FranchiseeProduct[];customers:FranchiseeCustomer[];subFranchiseeId?:string;onClose:()=>void;onSave:(agent:FranchiseeAgent)=>void}){
  const [draft,setDraft]=useState<AgentDraft>(()=>({agentCode:franchiseeAgentRepository.nextCode(products),name:'',mobile:'',email:'',designation:'',businessLineIds:[],assignedCustomerIds:[],subFranchiseeId})),[error,setError]=useState('')
  const set=<K extends keyof AgentDraft>(key:K,value:AgentDraft[K])=>setDraft(current=>({...current,[key]:value}))
  const submit=()=>{if(!draft.name.trim()||!draft.mobile.trim()||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(draft.email)||!draft.designation.trim()){setError('Enter the agent name, mobile number, valid email address and agent type.');return}if(!draft.businessLineIds.length){setError('Select at least one business line.');return}onSave(franchiseeAgentRepository.create({...draft,subFranchiseeId},products))}
  return <Modal title="Add Agent" subtitle={subFranchiseeId?'Add an agent to this Sub-Franchisee':'Add an agent to your franchise'} onClose={onClose}><form className="agent-form" onSubmit={event=>{event.preventDefault();submit()}}>
    <section><h3>Personal Details</h3><p>Enter the agent's contact information.</p><div className="agent-fields"><label>Full Name *<input required value={draft.name} onChange={event=>set('name',event.target.value)}/></label><label>Mobile Number *<input required value={draft.mobile} onChange={event=>set('mobile',event.target.value)}/></label><label className="wide">Email Address *<input type="email" required value={draft.email} onChange={event=>set('email',event.target.value)}/></label></div></section>
    <section><h3>Agent Details</h3><p>Use the agent's existing role or partner type.</p><div className="agent-fields"><label>Agent ID / Code *<input required value={draft.agentCode} onChange={event=>set('agentCode',event.target.value)}/></label><label>Agent Type *<input required value={draft.designation} onChange={event=>set('designation',event.target.value)} placeholder="POSP, Insurance Advisor, Loan Agent"/></label></div></section>
    <section><h3>Business Lines</h3><p>Select the business areas this agent will handle.</p><div className="agent-line-picker">{lines.map(line=><label key={line.id}><input type="checkbox" checked={draft.businessLineIds.includes(line.id)} onChange={event=>set('businessLineIds',event.target.checked?[...draft.businessLineIds,line.id]:draft.businessLineIds.filter(id=>id!==line.id))}/><span><b>{line.name}</b><small>{line.requirements.length} required onboarding item{line.requirements.length===1?'':'s'}</small></span></label>)}</div></section>
    <section><h3>Customers</h3><p>Assign only customers handled by this agent.</p><div className="agent-line-picker">{customers.map(customer=><label key={customer.id}><input type="checkbox" checked={draft.assignedCustomerIds.includes(customer.id)} onChange={event=>set('assignedCustomerIds',event.target.checked?[...draft.assignedCustomerIds,customer.id]:draft.assignedCustomerIds.filter(id=>id!==customer.id))}/><span><b>{customer.name}</b><small>{customer.id}</small></span></label>)}{!customers.length&&<p>No customers are available for assignment.</p>}</div></section>
    <section><h3>Compliance & Documents</h3><p>Required registrations, certifications and documents will appear automatically after the business lines are selected.</p></section>
    {error&&<div className="agent-error"><AlertTriangle/>{error}</div>}<footer><button type="button" className="tf-secondary" onClick={onClose}>Cancel</button><button className="tf-primary"><UserRoundPlus/> Save Agent</button></footer>
  </form></Modal>
}

export function SimpleAgentDetail({agent,customers,cases,tab,setTab,onClose,onOpenCustomer,onUpdate}:{agent:FranchiseeAgent;customers:FranchiseeCustomer[];cases:FranchiseeCase[];tab:SimpleAgentTab;setTab:(tab:SimpleAgentTab)=>void;onClose:()=>void;onOpenCustomer:(id:string)=>void;onUpdate?:(agent:FranchiseeAgent,lineId:string,requirement:AgentRequirement,status:'Completed'|'Pending HO Verification',document?:AgentFileMetadata)=>void}){
  const assigned=customers.filter(customer=>(agent.assignedCustomerIds||[]).includes(customer.id))
  const documents=agent.assignments.flatMap(line=>line.requirements.filter(item=>item.document).map(item=>({line:line.businessLine,item})))
  return <Modal title={agent.name} subtitle={`${agent.agentCode} · Agent Detail`} onClose={onClose}><div className="agent-detail-head"><span>{initials(agent.name)}</span><div><h3>{agent.designation}</h3><p>{agent.mobile} · {agent.email}</p></div><StatusBadge>{simpleStatus(agent)}</StatusBadge></div><div className="tf-tabs agent-tabs">{detailTabs.map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</div><div className="agent-detail-body">
    {tab==='Overview'&&<Panel title="Overview" subtitle="Agent contact and work details"><div className="agent-info"><Info label="Agent Name" value={agent.name}/><Info label="Agent ID" value={agent.agentCode}/><Info label="Mobile" value={agent.mobile}/><Info label="Email" value={agent.email}/><Info label="Agent Type" value={agent.designation}/><Info label="Status" value={simpleStatus(agent)}/><Info label="Business Lines" value={agent.assignments.map(line=>line.businessLine).join(', ')||'None assigned'}/><Info label="Customers" value={String(assigned.length)}/></div></Panel>}
    {tab==='Customers'&&<Panel title="Customers" subtitle="Only customers assigned to this agent"><DataTable headers={['Customer Name','Contact','Customer Type','Products','Open Cases','Open 360']} empty={!assigned.length}>{assigned.map(customer=>{const openCases=cases.filter(item=>item.customerId===customer.id&&!['Completed','Rejected','Approved / Issued'].includes(item.status)).length;return <tr key={customer.id}><td><b>{customer.name}</b><small>{customer.id}</small></td><td><b>{customer.mobile}</b><small>{customer.email}</small></td><td>{customer.profile360?.customerType||'Individual'}</td><td><CompactList values={customer.products}/></td><td>{openCases}</td><td><button className="tf-text-btn" onClick={()=>onOpenCustomer(customer.id)}>Open 360</button></td></tr>})}</DataTable>{!assigned.length&&<div className="agent-empty">No customers are assigned to this agent.</div>}</Panel>}
    {tab==='Business Lines'&&<div className="agent-line-status">{agent.assignments.map(line=><article key={line.businessLineId}><header><div><b>{line.businessLine}</b><small>{line.requirements.filter(item=>['Completed','Verified'].includes(item.status)).length} of {line.requirements.length} items complete</small></div><StatusBadge tone={assignmentEligibility(line)==='Eligible'?'green':'amber'}>{assignmentEligibility(line)==='Eligible'?'Ready':'In Progress'}</StatusBadge></header><Progress value={assignmentProgress(line)} label={`${assignmentProgress(line)}% complete`}/></article>)}</div>}
    {tab==='Compliance'&&<div className="agent-checklists">{agent.assignments.map(line=><Panel key={line.businessLineId} title={line.businessLine} subtitle="Compliance checklist"><DataTable headers={['Requirement','Status','Document','Action']}>{line.requirements.map(requirement=><tr key={requirement.id}><td><b>{requirement.name}</b><small>{requirement.type}</small></td><td><StatusBadge>{friendlyRequirementStatus(requirement.status)}</StatusBadge></td><td>{requirement.document?.fileName||(requirement.documentRequired?'Required':'Not required')}</td><td>{onUpdate?<RequirementAction agent={agent} lineId={line.businessLineId} requirement={requirement} onUpdate={onUpdate}/>:<span>View only</span>}</td></tr>)}</DataTable></Panel>)}</div>}
    {tab==='Documents'&&<Panel title="Documents" subtitle="Documents submitted for onboarding"><DataTable headers={['Document','Business Line','Requirement','Submitted','Status']} empty={!documents.length}>{documents.map(({line,item})=><tr key={`${line}-${item.id}`}><td><b>{item.document?.fileName}</b></td><td>{line}</td><td>{item.name}</td><td>{dateTime(item.submittedAt||item.document?.uploadedAt)}</td><td><StatusBadge>{friendlyRequirementStatus(item.status)}</StatusBadge></td></tr>)}</DataTable></Panel>}
    {tab==='Activity'&&<Panel title="Activity" subtitle="Agent history"><Timeline items={agent.activity}/></Panel>}
  </div></Modal>
}

export function AgentDetail({agent,tab,setTab,onClose,onUpdate}:{agent:FranchiseeAgent;tab:DetailTab;setTab:(tab:DetailTab)=>void;onClose:()=>void;onUpdate?:(agent:FranchiseeAgent,lineId:string,requirement:AgentRequirement,status:'Completed'|'Pending HO Verification',document?:AgentFileMetadata)=>void}){
  const status=onboardingStatus(agent),documents=agent.assignments.flatMap(line=>line.requirements.filter(item=>item.document).map(item=>({line:line.businessLine,item})))
  return <Modal title={agent.name} subtitle={`${agent.agentCode} · Agent Onboarding`} onClose={onClose}><div className="agent-detail-head"><span>{initials(agent.name)}</span><div><h3>{agent.designation}</h3><p>{agent.mobile} · {agent.email}</p></div><StatusBadge>{status}</StatusBadge></div><div className="tf-tabs agent-tabs">{legacyDetailTabs.map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</div><div className="agent-detail-body">
    {tab==='Profile'&&<><div className="agent-line-status">{agent.assignments.map(line=><article key={line.businessLineId}><header><div><b>{line.businessLine}</b><small>{line.requirements.filter(requirement=>requirement.status==='Completed'||requirement.status==='Verified').length} of {line.requirements.length} requirements completed</small></div><StatusBadge tone={assignmentEligibility(line)==='Eligible'?'green':'amber'}>{assignmentEligibility(line)}</StatusBadge></header><Progress value={assignmentProgress(line)} label={`${assignmentProgress(line)}% complete`}/><p>{assignmentEligibility(line)==='Eligible'?'All mandatory requirements are complete and required verifications are approved.':'Eligibility is locked until every mandatory requirement is completed and verification-required items are approved by HO.'}</p></article>)}</div><Panel title="Agent Profile" subtitle="Franchise-scoped onboarding record"><div className="agent-info"><Info label="Agent ID" value={agent.agentCode}/><Info label="Full Name" value={agent.name}/><Info label="Mobile" value={agent.mobile}/><Info label="Email" value={agent.email}/><Info label="Designation" value={agent.designation}/><Info label="Created" value={dateTime(agent.createdAt)}/></div></Panel></>}
    {tab==='Onboarding Checklist'&&<div className="agent-checklists">{agent.assignments.map(line=><Panel key={line.businessLineId} title={line.businessLine} subtitle={`${assignmentProgress(line)}% complete`} action={<StatusBadge tone={assignmentEligibility(line)==='Eligible'?'green':'amber'}>{assignmentEligibility(line)}</StatusBadge>}><DataTable headers={['Requirement','Type','Required','Status','Document','Verification','Verified By','Action']}>{line.requirements.map(requirement=><tr key={requirement.id}><td><b>{requirement.name}</b></td><td>{requirement.type}</td><td>{requirement.mandatory?'Mandatory':'Optional'}</td><td><StatusBadge>{requirement.status}</StatusBadge></td><td>{requirement.document?<><b>{requirement.document.fileName}</b><small>{dateTime(requirement.document.uploadedAt)}</small></>:requirement.documentRequired?'Required':'Not required'}</td><td>{requirement.verificationRequired?'HO Compliance':'Franchise completion'}</td><td>{requirement.verifiedBy||'—'}</td><td>{onUpdate?<RequirementAction agent={agent} lineId={line.businessLineId} requirement={requirement} onUpdate={onUpdate}/>:<span>View only</span>}</td></tr>)}</DataTable></Panel>)}</div>}
    {tab==='Documents'&&<Panel title="Agent Documents" subtitle="Metadata only · verification is controlled by Head Office"><DataTable headers={['Document','Business Line','Type','Submitted','Status','Verified By']} empty={!documents.length}>{documents.map(({line,item})=><tr key={`${line}-${item.id}`}><td><b>{item.document?.fileName}</b></td><td>{line}</td><td>{item.name}</td><td>{dateTime(item.submittedAt||item.document?.uploadedAt)}</td><td><StatusBadge>{item.status}</StatusBadge></td><td>{item.verifiedBy||'Awaiting HO Compliance'}</td></tr>)}</DataTable></Panel>}
    {tab==='Activity'&&<Panel title="Activity & Audit Timeline" subtitle="Onboarding and compliance events"><Timeline items={agent.activity}/></Panel>}
  </div></Modal>
}

function RequirementAction({agent,lineId,requirement,onUpdate}:{agent:FranchiseeAgent;lineId:string;requirement:AgentRequirement;onUpdate:(agent:FranchiseeAgent,lineId:string,requirement:AgentRequirement,status:'Completed'|'Pending HO Verification',document?:AgentFileMetadata)=>void}){
  if(requirement.status==='Verified')return <span className="agent-done"><CheckCircle2/> Verified</span>
  if(requirement.status==='Completed')return <span className="agent-done"><CheckCircle2/> Complete</span>
  if(requirement.status==='Pending HO Verification')return <span className="agent-waiting"><ShieldCheck/> Awaiting verification</span>
  if(requirement.verificationRequired&&requirement.documentRequired)return <label className="agent-upload"><Upload/> Upload<input type="file" onChange={(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(file)onUpdate(agent,lineId,requirement,'Pending HO Verification',{fileName:file.name,fileSize:file.size,fileType:file.type||'file',uploadedAt:new Date().toISOString()})}}/></label>
  if(requirement.verificationRequired)return <button className="tf-text-btn" onClick={()=>onUpdate(agent,lineId,requirement,'Pending HO Verification')}>Submit</button>
  return <button className="tf-text-btn" onClick={()=>onUpdate(agent,lineId,requirement,'Completed')}>Mark Complete</button>
}

function simpleStatus(agent:FranchiseeAgent){return onboardingStatus(agent)==='Eligible / Active'?'Active':'Onboarding'}
function complianceStatus(agent:FranchiseeAgent){const status=onboardingStatus(agent);return status==='Eligible / Active'?'Complete':status==='Pending Verification'?'Verification Required':'Pending'}
function friendlyRequirementStatus(status:AgentRequirement['status']){return status==='Pending HO Verification'?'Verification Required':status==='Not Started'?'Not Submitted':status}
function CompactList({values}:{values:string[]}){return <><b>{values.slice(0,2).join(', ')||'None'}</b>{values.length>2&&<small>+{values.length-2} more</small>}</>}
function Info({label,value}:{label:string;value:string}){return <div><span>{label}</span><b>{value}</b></div>}
function initials(name:string){return name.split(/\s+/).slice(0,2).map(part=>part[0]||'').join('').toUpperCase()}
function dateTime(value?:string){if(!value)return '—';const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}
