import { AlertTriangle, BadgeCheck, CheckCircle2, FileCheck2, Plus, ShieldCheck, Upload, UserRoundPlus, UsersRound } from 'lucide-react'
import { useMemo, useState, type ChangeEvent } from 'react'
import { assignmentEligibility, assignmentProgress, buildAgentBusinessLines, franchiseeAgentRepository, onboardingStatus, pendingRequirementCount, type AgentBusinessLine, type AgentDraft, type AgentFileMetadata, type AgentRequirement, type FranchiseeAgent } from '../agentOnboarding'
import type { FranchiseeProduct } from '../types'
import { DataTable, FilterSelect, Filters, Metric, Modal, PageHeader, Panel, Progress, StatusBadge, Timeline } from '../components/FranchiseeUI'

export type DetailTab='Profile'|'Onboarding Checklist'|'Documents'|'Activity'
const detailTabs:DetailTab[]=['Profile','Onboarding Checklist','Documents','Activity']

export function AgentsPage({products,onToast}:{products:FranchiseeProduct[];onToast:(message:string)=>void}){
  const lines=useMemo(()=>buildAgentBusinessLines(products),[products])
  const [agents,setAgents]=useState(()=>franchiseeAgentRepository.load(products)),[search,setSearch]=useState(''),[lineFilter,setLineFilter]=useState('All Business Lines'),[statusFilter,setStatusFilter]=useState('All Statuses'),[complianceFilter,setComplianceFilter]=useState('All Compliance'),[formOpen,setFormOpen]=useState(false),[selected,setSelected]=useState<FranchiseeAgent>(),[tab,setTab]=useState<DetailTab>('Profile')
  const statuses=[...new Set(agents.map(onboardingStatus))]
  const rows=useMemo(()=>agents.filter(agent=>{
    const hasPendingVerification=agent.assignments.some(line=>line.requirements.some(item=>item.status==='Pending HO Verification'))
    return (lineFilter==='All Business Lines'||agent.assignments.some(line=>line.businessLine===lineFilter))
      &&(statusFilter==='All Statuses'||onboardingStatus(agent)===statusFilter)
      &&(complianceFilter==='All Compliance'||(complianceFilter==='Pending HO Verification'?hasPendingVerification:!hasPendingVerification))
      &&`${agent.name} ${agent.agentCode} ${agent.mobile} ${agent.email}`.toLowerCase().includes(search.toLowerCase())
  }),[agents,lineFilter,statusFilter,complianceFilter,search])
  const pendingCompliance=agents.filter(agent=>agent.assignments.some(line=>line.requirements.some(item=>item.status==='Pending HO Verification'))).length
  const updateRequirement=(agent:FranchiseeAgent,lineId:string,requirement:AgentRequirement,status:'Completed'|'Pending HO Verification',document?:AgentFileMetadata)=>{const updated=franchiseeAgentRepository.updateRequirement(agent.id,lineId,requirement.id,status,products,document);if(!updated)return;setAgents(current=>current.map(item=>item.id===updated.id?updated:item));setSelected(updated);onToast(status==='Completed'?`${requirement.name} marked complete`:`${requirement.name} submitted to HO Compliance`)}
  const open=(agent:FranchiseeAgent)=>{setSelected(agent);setTab('Profile')}
  return <div className="franchisee-agents"><PageHeader eyebrow="AGENT CONFIGURATION · ONBOARDING" title="Agents" description="Onboard and configure agents across business lines with mandatory certification and compliance gates." actions={<button className="tf-primary" onClick={()=>setFormOpen(true)}><Plus/> Add Agent</button>}/>
    <div className="tf-metrics agents-summary"><Metric label="Total Agents" value={agents.length} meta="Current franchise records" icon={<UsersRound/>}/><Metric label="Onboarding In Progress" value={agents.filter(agent=>!['Eligible / Active','Draft'].includes(onboardingStatus(agent))).length} meta="Requirements being completed" icon={<UserRoundPlus/>} tone="violet"/><Metric label="Pending Compliance" value={pendingCompliance} meta="Awaiting Head Office" icon={<ShieldCheck/>} tone="orange"/><Metric label="Eligible / Active" value={agents.filter(agent=>onboardingStatus(agent)==='Eligible / Active').length} meta="All assigned lines eligible" icon={<BadgeCheck/>} tone="teal"/><Metric label="Requirements Pending" value={agents.reduce((sum,agent)=>sum+pendingRequirementCount(agent),0)} meta="Across all business lines" icon={<FileCheck2/>} tone="red"/></div>
    <Panel title="Agent Directory" subtitle={`${rows.length} agent records in this franchise`}><div className="agents-filters"><Filters search={search} onSearch={setSearch}/><FilterSelect label="Business Line" value={lineFilter} onChange={setLineFilter} options={['All Business Lines',...lines.map(line=>line.name)]}/><FilterSelect label="Onboarding Status" value={statusFilter} onChange={setStatusFilter} options={['All Statuses',...statuses]}/><FilterSelect label="Compliance" value={complianceFilter} onChange={setComplianceFilter} options={['All Compliance','Pending HO Verification','No Pending Verification']}/></div><DataTable headers={['Agent / Team Member','Contact','Assigned Business Lines','Onboarding Progress','Pending Requirements','Compliance','Eligibility','Last Updated','Action']} empty={!rows.length}>{rows.map(agent=>{const progress=Math.round(agent.assignments.reduce((sum,line)=>sum+assignmentProgress(line),0)/Math.max(1,agent.assignments.length)),status=onboardingStatus(agent),eligible=agent.assignments.filter(line=>assignmentEligibility(line)==='Eligible').length;return <tr key={agent.id}><td><button className="agent-identity" onClick={()=>open(agent)}><span>{initials(agent.name)}</span><div><b>{agent.name}</b><small>{agent.agentCode} · {agent.designation}</small></div></button></td><td><b>{agent.mobile}</b><small>{agent.email}</small></td><td><div className="agent-line-chips">{agent.assignments.map(line=><span key={line.businessLineId}>{line.businessLine}</span>)}</div></td><td><b>{progress}%</b><Progress value={progress}/></td><td><b>{pendingRequirementCount(agent)}</b></td><td><StatusBadge>{status==='Pending Verification'?'Pending HO Verification':status}</StatusBadge></td><td><b>{eligible} / {agent.assignments.length}</b><small>business lines eligible</small></td><td>{dateTime(agent.updatedAt)}</td><td><button className="tf-text-btn" onClick={()=>open(agent)}>{status==='Eligible / Active'?'View':'Continue Onboarding'}</button></td></tr>})}</DataTable></Panel>
    {formOpen&&<AgentForm lines={lines} products={products} onClose={()=>setFormOpen(false)} onSave={agent=>{setAgents(current=>[agent,...current]);setFormOpen(false);open(agent);onToast(`${agent.name} onboarding started`)}}/>}
    {selected&&<AgentDetail agent={selected} tab={tab} setTab={setTab} onClose={()=>setSelected(undefined)} onUpdate={updateRequirement}/>} 
  </div>
}

function AgentForm({lines,products,onClose,onSave}:{lines:AgentBusinessLine[];products:FranchiseeProduct[];onClose:()=>void;onSave:(agent:FranchiseeAgent)=>void}){
  const [draft,setDraft]=useState<AgentDraft>(()=>({agentCode:franchiseeAgentRepository.nextCode(products),name:'',mobile:'',email:'',designation:'',businessLineIds:[]})),[error,setError]=useState('')
  const set=<K extends keyof AgentDraft>(key:K,value:AgentDraft[K])=>setDraft(current=>({...current,[key]:value}))
  const submit=()=>{if(!draft.name.trim()||!draft.mobile.trim()||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(draft.email)||!draft.designation.trim()){setError('Enter the agent’s name, mobile, valid email and designation.');return}if(!draft.businessLineIds.length){setError('Assign at least one business line.');return}onSave(franchiseeAgentRepository.create(draft,products))}
  return <Modal title="Add Agent" subtitle="Start controlled business-line onboarding" onClose={onClose}><form className="agent-form" onSubmit={event=>{event.preventDefault();submit()}}><section><h3>Agent profile</h3><div className="agent-fields"><label>Full Name<input required value={draft.name} onChange={event=>set('name',event.target.value)}/></label><label>Agent ID<input required value={draft.agentCode} onChange={event=>set('agentCode',event.target.value)}/></label><label>Mobile<input required value={draft.mobile} onChange={event=>set('mobile',event.target.value)}/></label><label>Email<input type="email" required value={draft.email} onChange={event=>set('email',event.target.value)}/></label><label className="wide">Designation / Role<input required value={draft.designation} onChange={event=>set('designation',event.target.value)}/></label></div></section><section><h3>Assign business lines</h3><p>Select one or more lines. Requirements load automatically from the onboarding configuration.</p><div className="agent-line-picker">{lines.map(line=><label key={line.id}><input type="checkbox" checked={draft.businessLineIds.includes(line.id)} onChange={event=>set('businessLineIds',event.target.checked?[...draft.businessLineIds,line.id]:draft.businessLineIds.filter(id=>id!==line.id))}/><span><b>{line.name}</b><small>{line.productIds.length} mapped product{line.productIds.length===1?'':'s'} · {line.requirements.length} mandatory requirements</small></span></label>)}</div></section>{error&&<div className="agent-error"><AlertTriangle/>{error}</div>}<footer><button type="button" className="tf-secondary" onClick={onClose}>Cancel</button><button className="tf-primary"><UserRoundPlus/> Start Onboarding</button></footer></form></Modal>}

export function AgentDetail({agent,tab,setTab,onClose,onUpdate}:{agent:FranchiseeAgent;tab:DetailTab;setTab:(tab:DetailTab)=>void;onClose:()=>void;onUpdate?:(agent:FranchiseeAgent,lineId:string,requirement:AgentRequirement,status:'Completed'|'Pending HO Verification',document?:AgentFileMetadata)=>void}){
  const status=onboardingStatus(agent),documents=agent.assignments.flatMap(line=>line.requirements.filter(item=>item.document).map(item=>({line:line.businessLine,item})))
  return <Modal title={agent.name} subtitle={`${agent.agentCode} · Agent Onboarding`} onClose={onClose}><div className="agent-detail-head"><span>{initials(agent.name)}</span><div><h3>{agent.designation}</h3><p>{agent.mobile} · {agent.email}</p></div><StatusBadge>{status}</StatusBadge></div><div className="tf-tabs agent-tabs">{detailTabs.map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</div><div className="agent-detail-body">
    {tab==='Profile'&&<><div className="agent-line-status">{agent.assignments.map(line=><article key={line.businessLineId}><header><div><b>{line.businessLine}</b><small>{line.requirements.filter(requirement=>requirement.status==='Completed'||requirement.status==='Verified').length} of {line.requirements.length} requirements completed</small></div><StatusBadge tone={assignmentEligibility(line)==='Eligible'?'green':'amber'}>{assignmentEligibility(line)}</StatusBadge></header><Progress value={assignmentProgress(line)} label={`${assignmentProgress(line)}% complete`}/><p>{assignmentEligibility(line)==='Eligible'?'All mandatory requirements are complete and required verifications are approved.':'Eligibility is locked until every mandatory requirement is completed and verification-required items are approved by HO.'}</p></article>)}</div><Panel title="Agent Profile" subtitle="Franchise-scoped onboarding record"><div className="agent-info"><Info label="Agent ID" value={agent.agentCode}/><Info label="Full Name" value={agent.name}/><Info label="Mobile" value={agent.mobile}/><Info label="Email" value={agent.email}/><Info label="Designation" value={agent.designation}/><Info label="Created" value={dateTime(agent.createdAt)}/></div></Panel></>}
    {tab==='Onboarding Checklist'&&<div className="agent-checklists">{agent.assignments.map(line=><Panel key={line.businessLineId} title={line.businessLine} subtitle={`${assignmentProgress(line)}% complete`} action={<StatusBadge tone={assignmentEligibility(line)==='Eligible'?'green':'amber'}>{assignmentEligibility(line)}</StatusBadge>}><DataTable headers={['Requirement','Type','Required','Status','Document','Verification','Verified By','Action']}>{line.requirements.map(requirement=><tr key={requirement.id}><td><b>{requirement.name}</b></td><td>{requirement.type}</td><td>{requirement.mandatory?'Mandatory':'Optional'}</td><td><StatusBadge>{requirement.status}</StatusBadge></td><td>{requirement.document?<><b>{requirement.document.fileName}</b><small>{dateTime(requirement.document.uploadedAt)}</small></>:requirement.documentRequired?'Required':'Not required'}</td><td>{requirement.verificationRequired?'HO Compliance':'Franchise completion'}</td><td>{requirement.verifiedBy||'—'}</td><td>{onUpdate?<RequirementAction agent={agent} lineId={line.businessLineId} requirement={requirement} onUpdate={onUpdate}/>:<span>View only</span>}</td></tr>)}</DataTable></Panel>)}</div>}
    {tab==='Documents'&&<Panel title="Agent Documents" subtitle="Metadata only · verification is controlled by Head Office"><DataTable headers={['Document','Business Line','Type','Submitted','Status','Verified By']} empty={!documents.length}>{documents.map(({line,item})=><tr key={`${line}-${item.id}`}><td><b>{item.document?.fileName}</b></td><td>{line}</td><td>{item.name}</td><td>{dateTime(item.submittedAt||item.document?.uploadedAt)}</td><td><StatusBadge>{item.status}</StatusBadge></td><td>{item.verifiedBy||'Awaiting HO Compliance'}</td></tr>)}</DataTable></Panel>}
    {tab==='Activity'&&<Panel title="Activity & Audit Timeline" subtitle="Onboarding and compliance events"><Timeline items={agent.activity}/></Panel>}
  </div></Modal>
}

function RequirementAction({agent,lineId,requirement,onUpdate}:{agent:FranchiseeAgent;lineId:string;requirement:AgentRequirement;onUpdate:(agent:FranchiseeAgent,lineId:string,requirement:AgentRequirement,status:'Completed'|'Pending HO Verification',document?:AgentFileMetadata)=>void}){
  if(requirement.status==='Verified')return <span className="agent-done"><CheckCircle2/> Verified by HO</span>
  if(requirement.status==='Completed')return <span className="agent-done"><CheckCircle2/> Completed</span>
  if(requirement.status==='Pending HO Verification')return <span className="agent-waiting"><ShieldCheck/> Awaiting HO</span>
  if(requirement.verificationRequired&&requirement.documentRequired)return <label className="agent-upload"><Upload/> Upload & Submit<input type="file" onChange={(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(file)onUpdate(agent,lineId,requirement,'Pending HO Verification',{fileName:file.name,fileSize:file.size,fileType:file.type||'file',uploadedAt:new Date().toISOString()})}}/></label>
  if(requirement.verificationRequired)return <button className="tf-text-btn" onClick={()=>onUpdate(agent,lineId,requirement,'Pending HO Verification')}>Submit to HO</button>
  return <button className="tf-text-btn" onClick={()=>onUpdate(agent,lineId,requirement,'Completed')}>Mark Complete</button>
}

function Info({label,value}:{label:string;value:string}){return <div><span>{label}</span><b>{value}</b></div>}
function initials(name:string){return name.split(/\s+/).slice(0,2).map(part=>part[0]||'').join('').toUpperCase()}
function dateTime(value?:string){if(!value)return '—';const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}
