import { FileCheck2, FilePlus2, MessageSquareReply, Plus, Upload } from 'lucide-react'
import { useMemo, useState } from 'react'
import type { FranchiseeCase, FranchiseeCustomer, FranchiseeProduct } from '../types'
import { DataTable, Documents, FilterSelect, Filters, Modal, money, Panel, StatusBadge, PageHeader, Timeline } from '../components/FranchiseeUI'

export function ApplicationsPage({cases,customers,products,prefill,onClearPrefill,onCreate,onResolve,onToast}:{cases:FranchiseeCase[];customers:FranchiseeCustomer[];products:FranchiseeProduct[];prefill?:{customerId?:string;product?:string};onClearPrefill:()=>void;onCreate:(customer:FranchiseeCustomer|undefined,product:string,amount:number,status:FranchiseeCase['status'])=>void;onResolve:(item:FranchiseeCase,response:string)=>void;onToast:(s:string)=>void}){
  const [tab,setTab]=useState(prefill?'new':'list'),[search,setSearch]=useState(''),[status,setStatus]=useState('All statuses'),[selected,setSelected]=useState<FranchiseeCase>()
  const rows=useMemo(()=>cases.filter(item=>(tab!=='pending'||item.status==='Query Raised')&&(status==='All statuses'||item.status===status)&&`${item.id} ${item.customer} ${item.product}`.toLowerCase().includes(search.toLowerCase())),[cases,tab,status,search])
  const showTab=(next:string)=>{setTab(next);if(next!=='new')onClearPrefill()}
  return <>
  <PageHeader eyebrow="OPERATIONAL HEART" title="Applications & Case Tracking" description="Create cases, follow every HO hand-off, and answer consolidated pending queries." /* actions={<button className="tf-primary" onClick={()=>showTab('new')}><Plus/> New application</button>} *//>
    <div className="tf-tabs tf-page-tabs"><button className={tab==='list'?'active':''} onClick={()=>showTab('list')}>My Applications</button><button className={tab==='pending'?'active':''} onClick={()=>showTab('pending')}>Pending Actions <em>{cases.filter(c=>c.status==='Query Raised').length}</em></button><button className={tab==='new'?'active':''} onClick={()=>showTab('new')}>New Application</button></div>
    {tab==='new'?<NewApplication customers={customers} products={products} prefill={prefill} onCreate={(...args)=>{onCreate(...args);showTab('list')}}/>:<Panel title={tab==='pending'?'Pending Actions / HO Queries':'My Applications'} subtitle={tab==='pending'?'Items currently waiting on the franchise; a reply returns them to HO.':'Every case raised by this franchise'}><Filters search={search} onSearch={setSearch}><FilterSelect label="Status" value={status} onChange={setStatus} options={['All statuses','Draft','Submitted','Under Review','Query Raised','Query Resolved','Approved / Issued','Completed','Rejected']}/></Filters><DataTable headers={['Case','Customer','Product','Value','Status','Assigned / next handler','Updated','']} empty={!rows.length}>{rows.map(item=><tr key={item.id}><td><button className="tf-link-stack" onClick={()=>setSelected(item)}><b>{item.id}</b><small>{item.status==='Query Raised'?'Action required':'Tracked case'}</small></button></td><td>{item.customer}</td><td>{item.product}</td><td><b>{money(item.amount)}</b></td><td><StatusBadge>{item.status}</StatusBadge></td><td><b>{item.status==='Query Raised'?'Franchise must act':item.assignedTeam}</b><small>{item.status==='Query Raised'?'Returns to HO Operations after response':'Status owned by assigned handler'}</small></td><td>{item.updated}</td><td><button className="tf-text-btn" onClick={()=>setSelected(item)}>Open case</button></td></tr>)}</DataTable></Panel>}
    {selected&&<CaseDetail item={selected} onClose={()=>setSelected(undefined)} onResolve={response=>{onResolve(selected,response);setSelected(undefined)}} onToast={onToast}/>}</>
}

function NewApplication({customers,products,prefill,onCreate}:{customers:FranchiseeCustomer[];products:FranchiseeProduct[];prefill?:{customerId?:string;product?:string};onCreate:(customer:FranchiseeCustomer|undefined,product:string,amount:number,status:FranchiseeCase['status'])=>void}){
  return <Panel title="New Application / Quote Request" subtitle="Submission creates a tracked case in the HO Operations queue."><form className="tf-form tf-wide-form" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);onCreate(customers.find(c=>c.id===fd.get('customer')),String(fd.get('product')),Number(fd.get('amount')),'Submitted')}}><div className="tf-form-row"><label>Customer<select name="customer" defaultValue={prefill?.customerId||''} required><option value="" disabled>Select customer</option>{customers.map(c=><option value={c.id} key={c.id}>{c.name} · {c.id}</option>)}</select></label><label>Product<select name="product" defaultValue={prefill?.product||''} required><option value="" disabled>Select product</option>{products.filter(p=>p.enabled).map(p=><option key={p.id}>{p.name}</option>)}</select></label></div><div className="tf-form-row"><label>Application / investment amount<input name="amount" type="number" min="1" required placeholder="₹"/></label><label>Request type<select name="type"><option>New Application</option><option>Quote Request</option><option>Renewal / Service</option></select></label></div><label>Application details<textarea name="details" placeholder="Add product-specific requirement, plan, tenure, cover, or scheme information" required/></label><div className="tf-checklist"><b>Required-document checklist</b><label><input type="checkbox" required/> Customer PAN / KYC is available</label><label><input type="checkbox" required/> Bank proof has been selected for upload</label><label><input type="checkbox"/> Product-specific form / declaration attached</label><button type="button" className="tf-secondary"><Upload/> Select documents</button></div><div className="tf-routing"><FileCheck2/><div><b>Next handler: Head Office Operations</b><p>The case will be marked Submitted and routed to the Head Office Operations queue for processing.</p></div></div><div className="tf-form-actions"><button type="button" className="tf-secondary" onClick={e=>{const form=e.currentTarget.form;if(!form)return;const fd=new FormData(form);onCreate(customers.find(c=>c.id===fd.get('customer')),String(fd.get('product')||'Product to be selected'),Number(fd.get('amount')||0),'Draft')}}>Save draft</button><button className="tf-primary"><FilePlus2/> Submit application</button></div></form></Panel>
}

function CaseDetail({item,onClose,onResolve,onToast}:{item:FranchiseeCase;onClose:()=>void;onResolve:(s:string)=>void;onToast:(s:string)=>void}){
  const [response,setResponse]=useState('')
  return <Modal title={item.id} subtitle={`${item.customer} · ${item.product}`} onClose={onClose}><div className="tf-360-head"><div><span>Application value</span><strong>{money(item.amount)}</strong><small>{item.assignedTeam}{(item.sourceLeadId||item.sourceInquiryId)&&` · Source: ${item.sourceLeadId||item.sourceInquiryId}`}</small></div><StatusBadge>{item.status}</StatusBadge>{['Approved / Issued','Completed'].includes(item.status)&&<button className="tf-primary" onClick={()=>onToast('Issued document prepared for download')}><FileCheck2/> Download issued document</button>}</div>{item.query&&<div className="tf-query-box"><MessageSquareReply/><div><b>HO query — franchise action required</b><p>{item.query}</p></div></div>}<div className="tf-modal-grid"><Panel title="Documents"><Documents items={item.documents}/>{item.status==='Query Raised'&&<button className="tf-secondary tf-full"><Upload/> Upload requested item</button>}</Panel><Panel title="Case timeline"><Timeline items={item.timeline}/></Panel></div>{item.status==='Query Raised'&&<form className="tf-reply" onSubmit={e=>{e.preventDefault();onResolve(response)}}><label>Response to HO Operations<textarea value={response} onChange={e=>setResponse(e.target.value)} required placeholder="Add your response and confirm the replacement document..."/></label><div className="tf-form-actions"><button type="button" className="tf-secondary" onClick={onClose}>Cancel</button><button className="tf-primary">Send response & return to HO queue</button></div></form>}</Modal>
}
