import { BriefcaseBusiness, Download, IndianRupee, ReceiptIndianRupee, RotateCcw, WalletCards, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { franchiseeBusinessReportRecords, type FranchiseeBusinessReportRecord } from '../businessReportsData'
import { DataTable, FilterSelect, Metric, money, Panel, StatusBadge, PageHeader } from '../components/FranchiseeUI'

type ReportTab='Overview'|'Business Report'|'Revenue Report'|'Product Report'|'Customer Report'
type ProductRow={product:string;cases:number;business:number;revenue:number}
type CustomerRow={customerId:string;customer:string;products:string[];cases:number;business:number;revenue:number;lastDate:string}
const reportTabs:ReportTab[]=['Overview','Business Report','Revenue Report','Product Report','Customer Report']
const today=new Date('2026-09-07T12:00:00')

export function BusinessRevenuePage({availableProducts,availableCustomers,onOpenCustomer,onToast}:{availableProducts:string[];availableCustomers:string[];onOpenCustomer:(customerId:string)=>void;onToast:(s:string)=>void}){
  const [tab,setTab]=useState<ReportTab>('Overview'),[period,setPeriod]=useState('This Month'),[product,setProduct]=useState('All Products'),[customer,setCustomer]=useState('All Customers'),[businessType,setBusinessType]=useState('All'),[customFrom,setCustomFrom]=useState('2026-04-01'),[customTo,setCustomTo]=useState('2026-09-07'),[businessStatus,setBusinessStatus]=useState('All Statuses'),[productSort,setProductSort]=useState('Business'),[selectedProduct,setSelectedProduct]=useState<ProductRow>(),[exportOpen,setExportOpen]=useState(false)
  const products=useMemo(()=>unique([...availableProducts,...franchiseeBusinessReportRecords.map(x=>x.product)]).sort(),[availableProducts]),customers=useMemo(()=>unique([...availableCustomers,...franchiseeBusinessReportRecords.map(x=>x.customerName)]).sort(),[availableCustomers])
  const scopeRows=useMemo(()=>franchiseeBusinessReportRecords.filter(row=>(product==='All Products'||row.product===product)&&(customer==='All Customers'||row.customerName===customer)&&(businessType==='All'||row.businessType===businessType)),[product,customer,businessType])
  const rows=useMemo(()=>scopeRows.filter(row=>inPeriod(row.date,period,customFrom,customTo)),[scopeRows,period,customFrom,customTo])
  const totals=calculateTotals(rows),productRows=groupProducts(rows),customerRows=groupCustomers(rows)
  const reset=()=>{setPeriod('This Month');setProduct('All Products');setCustomer('All Customers');setBusinessType('All');setBusinessStatus('All Statuses')}
  const exportReport=(report:string,format:string)=>{setExportOpen(false);onToast(`${report} prepared for ${format} export`)}
  return <div className="franchisee-business-reports"><PageHeader eyebrow="BUSINESS REPORTING" title="Business & Revenue Reports" description="View your total business, revenue and detailed performance across products." actions={<div className="fbr-export"><button className="tf-secondary" onClick={()=>setExportOpen(value=>!value)}><Download/> Export Report</button>{exportOpen&&<ExportMenu onExport={exportReport}/>}</div>}/>
    <div className="fbr-filter-bar"><FilterSelect label="Period" value={period} onChange={setPeriod} options={['This Month','Last Month','This Quarter','This Financial Year','Custom Range']}/><FilterSelect label="Product" value={product} onChange={setProduct} options={['All Products',...products]}/><FilterSelect label="Customer" value={customer} onChange={setCustomer} options={['All Customers',...customers]}/><FilterSelect label="Business Type" value={businessType} onChange={setBusinessType} options={['All','New','Renewal']}/>{period==='Custom Range'&&<><label className="fbr-date"><span>From</span><input type="date" value={customFrom} onChange={e=>setCustomFrom(e.target.value)}/></label><label className="fbr-date"><span>To</span><input type="date" value={customTo} onChange={e=>setCustomTo(e.target.value)}/></label></>}<button className="fbr-reset" onClick={reset}><RotateCcw/> Reset</button></div>
    <Summary totals={totals}/><nav className="tf-tabs tf-page-tabs fbr-tabs">{reportTabs.map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</nav>
    {tab==='Overview'&&<Overview rows={rows} trendRows={scopeRows} productRows={productRows} totals={totals}/>} 
    {tab==='Business Report'&&<BusinessReport rows={rows} status={businessStatus} setStatus={setBusinessStatus}/>} 
    {tab==='Revenue Report'&&<RevenueReport rows={rows}/>} 
    {tab==='Product Report'&&<ProductReport rows={productRows} totals={totals} sort={productSort} setSort={setProductSort} select={setSelectedProduct}/>} 
    {tab==='Customer Report'&&<CustomerReport rows={customerRows} open={onOpenCustomer}/>} 
    {selectedProduct&&<ProductDetail product={selectedProduct} records={rows.filter(x=>x.product===selectedProduct.product)} onClose={()=>setSelectedProduct(undefined)}/>} 
  </div>
}

function Summary({totals}:{totals:ReturnType<typeof calculateTotals>}){return <div className="tf-metrics tf-metrics-4 fbr-summary"><Metric label="Total Business" value={money(totals.business)} meta="Selected period" icon={<BriefcaseBusiness/>}/><Metric label="Total Revenue" value={money(totals.revenue)} meta="Selected period" icon={<IndianRupee/>} tone="teal"/><Metric label="Business Cases" value={totals.cases} meta="Across all products" icon={<WalletCards/>} tone="violet"/><Metric label="Average Revenue per Business" value={money(totals.averageRevenue)} meta="Revenue ÷ business cases" icon={<ReceiptIndianRupee/>} tone="orange"/></div>}

function Overview({rows,trendRows,productRows,totals}:{rows:FranchiseeBusinessReportRecord[];trendRows:FranchiseeBusinessReportRecord[];productRows:ProductRow[];totals:ReturnType<typeof calculateTotals>}){return <><Panel title="Product-wise Business & Revenue" subtitle="Compare business and revenue contribution across your products."><div className="fbr-product-layout"><div><h3>Business Contribution by Product</h3><ContributionBars rows={productRows} total={totals.business}/></div><ProductTable rows={productRows} totals={totals}/></div></Panel><div className="fbr-overview-grid"><Panel title="Business Trend" subtitle="Month-wise business and revenue for the last 6 months"><BusinessTrend rows={trendRows}/></Panel><Panel title="Top Products" subtitle="Highest business value in the selected period"><TopProducts rows={productRows.slice(0,5)}/></Panel></div>{!rows.length&&<p className="fbr-empty">No report records match the selected filters.</p>}</>}
function ContributionBars({rows,total}:{rows:ProductRow[];total:number}){return <div className="fbr-bars">{rows.map(row=>{const share=percent(row.business,total);return <div key={row.product}><span>{row.product}</span><i><b style={{width:`${share}%`}}/></i><strong>{share.toFixed(1)}%</strong></div>})}{!rows.length&&<small>No product data for this period.</small>}</div>}
function ProductTable({rows,totals,onSelect}:{rows:ProductRow[];totals:ReturnType<typeof calculateTotals>;onSelect?:(row:ProductRow)=>void}){return <DataTable headers={['Product','Business Cases','Business Value','Revenue','Business Contribution','Revenue Contribution']} empty={!rows.length}>{rows.map(row=><tr key={row.product} className={onSelect?'fbr-clickable':''} onClick={()=>onSelect?.(row)}><td><b>{row.product}</b></td><td>{row.cases}</td><td><b>{money(row.business)}</b></td><td>{money(row.revenue)}</td><td>{percent(row.business,totals.business).toFixed(1)}%</td><td>{percent(row.revenue,totals.revenue).toFixed(1)}%</td></tr>)}</DataTable>}
function BusinessTrend({rows}:{rows:FranchiseeBusinessReportRecord[]}){const months=lastSixMonths(),data=months.map(month=>{const records=rows.filter(x=>x.date.startsWith(month.key));return {...month,...calculateTotals(records)}}),max=Math.max(...data.map(x=>x.business),1);return <div className="fbr-trend">{data.map(item=><div key={item.key}><div className="fbr-trend-bars"><i style={{height:`${Math.max(3,item.business/max*100)}%`}} title={`Business ${money(item.business)}`}/><em style={{height:`${Math.max(2,item.revenue/max*100*8)}%`}} title={`Revenue ${money(item.revenue)}`}/></div><b>{item.label}</b><span>{money(item.business)}</span><small>{money(item.revenue)} revenue</small></div>)}<div className="fbr-legend"><span><i/> Business</span><span><i/> Revenue</span></div></div>}
function TopProducts({rows}:{rows:ProductRow[]}){return <div className="fbr-top-products">{rows.map((row,index)=><div key={row.product}><em>{index+1}</em><span><b>{row.product}</b><small>{row.cases} business cases</small></span><strong>{money(row.business)}<small>{money(row.revenue)} revenue</small></strong></div>)}{!rows.length&&<p>No product data.</p>}</div>}

function BusinessReport({rows,status,setStatus}:{rows:FranchiseeBusinessReportRecord[];status:string;setStatus:(v:string)=>void}){const filtered=status==='All Statuses'?rows:rows.filter(x=>x.businessStatus===status),totals=calculateTotals(filtered);return <Panel title="Detailed Business Report" subtitle="Transaction-level franchise business"><div className="fbr-local-filter"><FilterSelect label="Status" value={status} onChange={setStatus} options={['All Statuses',...unique(rows.map(x=>x.businessStatus))]}/></div><DataTable headers={['Date','Business Reference','Customer','Product','Business Type','Business Value','Status']} empty={!filtered.length}>{filtered.map(row=><tr key={row.id}><td>{date(row.date)}</td><td><b>{row.businessReference}</b></td><td>{row.customerName}</td><td>{row.product}</td><td>{row.businessType}</td><td><b>{money(row.businessValue)}</b></td><td><StatusBadge>{row.businessStatus}</StatusBadge></td></tr>)}</DataTable><ReportFooter items={[['Total Cases',String(totals.cases)],['Total Business',money(totals.business)]]}/></Panel>}
function RevenueReport({rows}:{rows:FranchiseeBusinessReportRecord[]}){const totals=calculateTotals(rows);return <Panel title="Detailed Revenue Report" subtitle="Expected, approved and paid franchise revenue"><DataTable headers={['Date','Reference','Customer','Product','Business Value','Revenue','Revenue Status','Revenue Date']} empty={!rows.length}>{rows.map(row=><tr key={row.id}><td>{date(row.date)}</td><td><b>{row.id}</b></td><td>{row.customerName}</td><td>{row.product}</td><td>{money(row.businessValue)}</td><td><b>{money(row.revenue)}</b></td><td><StatusBadge>{row.revenueStatus}</StatusBadge></td><td>{date(row.revenueDate)}</td></tr>)}</DataTable><ReportFooter items={[['Total Business',money(totals.business)],['Total Revenue',money(totals.revenue)],['Average Revenue',money(totals.averageRevenue)]]}/></Panel>}
function ProductReport({rows,totals,sort,setSort,select}:{rows:ProductRow[];totals:ReturnType<typeof calculateTotals>;sort:string;setSort:(v:string)=>void;select:(row:ProductRow)=>void}){const sorted=[...rows].sort((a,b)=>sort==='Revenue'?b.revenue-a.revenue:sort==='Cases'?b.cases-a.cases:b.business-a.business);return <Panel title="Product Performance Report" subtitle="Click a row to inspect product details" action={<FilterSelect label="Sort by" value={sort} onChange={setSort} options={['Business','Revenue','Cases']}/>}><DataTable headers={['Product','Cases','Business Value','Revenue','Average Business','Average Revenue','Business Share','Revenue Share','Revenue Ratio']} empty={!sorted.length}>{sorted.map(row=><tr key={row.product} className="fbr-clickable" onClick={()=>select(row)}><td><b>{row.product}</b></td><td>{row.cases}</td><td><b>{money(row.business)}</b></td><td>{money(row.revenue)}</td><td>{money(row.business/row.cases)}</td><td>{money(row.revenue/row.cases)}</td><td>{percent(row.business,totals.business).toFixed(1)}%</td><td>{percent(row.revenue,totals.revenue).toFixed(1)}%</td><td>{percent(row.revenue,row.business).toFixed(2)}%</td></tr>)}</DataTable></Panel>}
function CustomerReport({rows,open}:{rows:CustomerRow[];open:(id:string)=>void}){return <Panel title="Customer-wise Business Report" subtitle="Customers ranked by total business"><DataTable headers={['Customer','Products','Business Cases','Total Business','Total Revenue','Last Business Date','']} empty={!rows.length}>{rows.map(row=><tr key={row.customerId}><td><b>{row.customer}</b></td><td>{row.products.join(', ')}</td><td>{row.cases}</td><td><b>{money(row.business)}</b></td><td>{money(row.revenue)}</td><td>{date(row.lastDate)}</td><td><button className="tf-text-btn" onClick={()=>open(row.customerId)}>View in Customer Directory</button></td></tr>)}</DataTable></Panel>}

function ProductDetail({product,records,onClose}:{product:ProductRow;records:FranchiseeBusinessReportRecord[];onClose:()=>void}){const customers=groupCustomers(records).slice(0,3);return <><button className="fbr-drawer-scrim" onClick={onClose}/><aside className="fbr-drawer"><header><div><span>PRODUCT REPORT</span><h2>{product.product}</h2></div><button onClick={onClose}><X/></button></header><div className="fbr-detail-metrics"><Stat label="Total Business" value={money(product.business)}/><Stat label="Total Revenue" value={money(product.revenue)}/><Stat label="Business Cases" value={String(product.cases)}/><Stat label="Average Business" value={money(product.business/product.cases)}/><Stat label="Average Revenue" value={money(product.revenue/product.cases)}/></div><h3>Recent Business</h3><div className="fbr-detail-list">{[...records].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map(row=><article key={row.id}><span><b>{row.customerName}</b><small>{date(row.date)} · {row.businessReference}</small></span><strong>{money(row.businessValue)}</strong></article>)}</div><h3>Top Customers</h3><div className="fbr-detail-list">{customers.map(row=><article key={row.customerId}><span><b>{row.customer}</b><small>{row.cases} cases</small></span><strong>{money(row.business)}</strong></article>)}</div></aside></>}
function ExportMenu({onExport}:{onExport:(report:string,format:string)=>void}){const [format,setFormat]=useState('Excel');return <div className="fbr-export-menu"><label>Format<select value={format} onChange={e=>setFormat(e.target.value)}><option>Excel</option><option>PDF</option></select></label>{['Business Report','Revenue Report','Product Report','Customer Report','Full Report'].map(report=><button key={report} onClick={()=>onExport(report,format)}>{report}<Download/></button>)}</div>}
function ReportFooter({items}:{items:[string,string][]}){return <footer className="fbr-report-footer">{items.map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</footer>}
function Stat({label,value}:{label:string;value:string}){return <div><span>{label}</span><b>{value}</b></div>}

function calculateTotals(rows:FranchiseeBusinessReportRecord[]){const business=rows.reduce((sum,row)=>sum+row.businessValue,0),revenue=rows.reduce((sum,row)=>sum+row.revenue,0),cases=rows.length;return {business,revenue,cases,averageRevenue:cases?revenue/cases:0}}
function groupProducts(rows:FranchiseeBusinessReportRecord[]):ProductRow[]{const map=new Map<string,ProductRow>();rows.forEach(row=>{const item=map.get(row.product)||{product:row.product,cases:0,business:0,revenue:0};item.cases++;item.business+=row.businessValue;item.revenue+=row.revenue;map.set(row.product,item)});return [...map.values()].sort((a,b)=>b.business-a.business)}
function groupCustomers(rows:FranchiseeBusinessReportRecord[]):CustomerRow[]{const map=new Map<string,CustomerRow>();rows.forEach(row=>{const item=map.get(row.customerId)||{customerId:row.customerId,customer:row.customerName,products:[],cases:0,business:0,revenue:0,lastDate:row.date};item.cases++;item.business+=row.businessValue;item.revenue+=row.revenue;item.lastDate=item.lastDate>row.date?item.lastDate:row.date;if(!item.products.includes(row.product))item.products.push(row.product);map.set(row.customerId,item)});return [...map.values()].sort((a,b)=>b.business-a.business)}
function inPeriod(dateValue:string,period:string,from:string,to:string){const date=new Date(`${dateValue}T00:00:00`);if(period==='Custom Range')return dateValue>=from&&dateValue<=to;const year=today.getFullYear(),month=today.getMonth();if(period==='This Month')return date.getFullYear()===year&&date.getMonth()===month;if(period==='Last Month'){const last=new Date(year,month-1,1);return date.getFullYear()===last.getFullYear()&&date.getMonth()===last.getMonth()}if(period==='This Quarter'){const start=Math.floor(month/3)*3;return date.getFullYear()===year&&date.getMonth()>=start&&date.getMonth()<start+3}const fyStart=month>=3?year:year-1,fyEnd=fyStart+1;return date>=new Date(fyStart,3,1)&&date<new Date(fyEnd,3,1)}
function lastSixMonths(){return Array.from({length:6},(_,index)=>{const value=new Date(today.getFullYear(),today.getMonth()-5+index,1);return {key:`${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,'0')}`,label:value.toLocaleDateString('en-IN',{month:'short'})}})}
function unique<T>(values:T[]){return [...new Set(values)]}
function percent(value:number,total:number){return total?value/total*100:0}
function date(value?:string){return value?new Date(`${value}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—'}
