import { ArrowLeft, ArrowUpRight, BriefcaseBusiness, CalendarClock, FileCheck2, Lightbulb, Phone, ShieldCheck, ShoppingBag, TrendingUp, UserRound, WalletCards } from 'lucide-react'
import { useEffect, useState, type ReactNode } from 'react'
import { DataTable, money, Modal, Panel, StatusBadge, Timeline } from '../components/FranchiseeUI'
import type { FranchiseeCustomer, FranchiseeStore } from '../types'
import { customer360Service, type Customer360Workspace } from '../services/customer360Service'

type Tab='Overview'|'Holdings'|'Portfolio'|'Documents & KYC'|'Communications'|'Cases'|'Opportunities'|'Renewals'
type Drilldown='active-products'|'renewals-due'|'document-actions'
const tabs:Tab[]=['Overview','Holdings','Portfolio','Documents & KYC','Communications','Cases','Opportunities','Renewals']
const tabLabels:Record<Tab,string>={Overview:'Overview',Holdings:'Holdings',Portfolio:'Portfolio','Documents & KYC':'KYC & Documents',Communications:'Communication',Cases:'Open Cases',Opportunities:'Cross-Sell',Renewals:'Renewals'}

export function Customer360Page({customerId,store,onBack,onApply,onSupport,onViewCases}:{customerId:string;store:FranchiseeStore;onBack:()=>void;onApply:(customer:FranchiseeCustomer)=>void;onSupport:(customer:FranchiseeCustomer)=>void;onViewCases:()=>void}){
  const [tab,setTab]=useState<Tab>('Overview'),[drilldown,setDrilldown]=useState<Drilldown>(),[state,setState]=useState<{loading:boolean;data:Customer360Workspace|null;error?:string}>({loading:true,data:null})
  useEffect(()=>{setState({loading:true,data:null});Promise.resolve().then(()=>customer360Service.load(customerId,store)).then(data=>setState({loading:false,data})).catch(()=>setState({loading:false,data:null,error:'Customer 360 could not be loaded.'}))},[customerId,store])
  if(state.loading)return <div className="tf-360-state" role="status"><span className="tf-spinner"/><b>Loading Customer 360…</b></div>
  if(state.error)return <State title="Unable to load Customer 360" detail={state.error} onBack={onBack}/>
  if(!state.data)return <State title="Customer unavailable" detail="This customer does not exist or is outside your franchise access." onBack={onBack}/>
  const data=state.data,customer=data.customer,profile=customer.profile360,activeHoldings=data.holdings.filter(item=>!['closed','expired','lapsed'].includes(item.status.toLowerCase())),renewalsDue=data.renewals.filter(item=>item.daysRemaining<=30),documentActions=data.documents.filter(item=>item.status!=='Verified'),activeProducts=new Set(activeHoldings.map(item=>item.productId)).size
  const openDetail=(next:Tab,filter?:Drilldown)=>{setTab(next);setDrilldown(filter)}
  return <div className="tf-customer360-page"><Modal title={customer.name} subtitle={`${customer.id} · Customer 360`} onClose={onBack}>
    <button className="tf-360-back" onClick={onBack}><ArrowLeft/> Back to Customers</button>
    <header className="tf-360-profile"><div className="tf-360-avatar">{initials(customer.name)}</div><div className="tf-360-identity"><span>CUSTOMER 360°</span><h1>{customer.name}</h1><p>{customer.id} · {customer.city} · Customer since {date(profile?.basic.customerSince)}</p><div><a href={`tel:${customer.mobile}`}><Phone/> {customer.mobile}</a><a href={`mailto:${customer.email}`}>{customer.email}</a></div></div><div className="tf-360-status"><StatusBadge>{customer.kyc} KYC</StatusBadge><StatusBadge tone="blue">{profile?.preferences.category||'Active relationship'}</StatusBadge><small>Assigned RM: {profile?.preferences.relationshipManager||'Unassigned'}</small></div><div className="tf-head-actions"><button className="tf-secondary" onClick={()=>onSupport(customer)}>Service request</button><button className="tf-primary" onClick={()=>onApply(customer)}><ShoppingBag/> Buy / Apply</button></div></header>
    <div className="tf-360-summary"><div className="tf-360-kpis"><Kpi icon={<WalletCards/>} label="Relationship value" value={money(data.portfolio.totalPortfolioValue)} detail="View value detail" onClick={()=>openDetail('Portfolio')}/><Kpi icon={<BriefcaseBusiness/>} label="Active products" value={activeProducts} detail="View active holdings" onClick={()=>openDetail('Holdings','active-products')}/><Kpi icon={<TrendingUp/>} label="Portfolio performance" value={pct(data.portfolio.returnPercent)} detail="View performance" onClick={()=>openDetail('Portfolio')}/><Kpi icon={<ShieldCheck/>} label="Open cases" value={data.openCases.length} detail="View open cases" onClick={()=>openDetail('Cases')}/><Kpi icon={<CalendarClock/>} label="Renewals due" value={renewalsDue.length} detail="View due renewals" onClick={()=>openDetail('Renewals','renewals-due')}/><Kpi icon={<Lightbulb/>} label="Cross-sell opportunities" value={data.opportunities.length} detail="View opportunities" onClick={()=>openDetail('Opportunities')}/><Kpi icon={<FileCheck2/>} label="Document actions" value={documentActions.length} detail="View pending items" onClick={()=>openDetail('Documents & KYC','document-actions')}/></div></div>
    <nav className="tf-tabs tf-360-page-tabs" aria-label="Customer 360 sections">{tabs.map(item=><button key={item} className={tab===item?'active':''} aria-current={tab===item?'page':undefined} onClick={()=>{setTab(item);setDrilldown(undefined)}}>{tabLabels[item]}</button>)}</nav>
    <div className="tf-360-detail-content">
      {tab==='Overview'&&<Overview data={data} onTab={item=>openDetail(item)}/>} 
      {tab==='Holdings'&&<Holdings data={data} activeOnly={drilldown==='active-products'}/>} {tab==='Portfolio'&&<Portfolio data={data}/>} {tab==='Documents & KYC'&&<Documents data={data} actionsOnly={drilldown==='document-actions'}/>} {tab==='Communications'&&<Communications data={data}/>} {tab==='Cases'&&<Cases data={data} onViewCases={onViewCases}/>} {tab==='Opportunities'&&<Opportunities data={data}/>} {tab==='Renewals'&&<Renewals data={data} dueOnly={drilldown==='renewals-due'} onViewCases={onViewCases}/>} 
    </div>
  </Modal></div>
}

function Overview({data,onTab}:{data:Customer360Workspace;onTab:(tab:Tab)=>void}){const p=data.customer.profile360;return <div className="tf-360-overview"><Panel title="Relationship snapshot" subtitle="Available customer and servicing information"><div className="tf-360-info"><Info label="Customer type" value={p?.customerType||'Legacy record'}/><Info label="Email" value={data.customer.email}/><Info label="Preferred contact" value={p?.preferences.preferredContactMethod||'Not recorded'}/><Info label="Primary goal" value={p?.preferences.primaryGoal||'Not recorded'}/><Info label="Risk preference" value={p?.preferences.riskPreference||'Not assessed'}/><Info label="Last activity" value={data.customer.lastActivity}/></div></Panel><Panel title="Immediate attention" subtitle="Live counts from this customer workspace"><div className="tf-360-attention"><button onClick={()=>onTab('Cases')}><ShieldCheck/><span><b>{data.openCases.length} open cases</b><small>Review service and application work</small></span></button><button onClick={()=>onTab('Renewals')}><CalendarClock/><span><b>{data.renewals.length} renewals</b><small>Upcoming and overdue items</small></span></button><button onClick={()=>onTab('Documents & KYC')}><FileCheck2/><span><b>{data.documents.filter(item=>item.status!=='Verified').length} document actions</b><small>KYC and verification readiness</small></span></button></div></Panel></div>}

function Holdings({data,activeOnly}:{data:Customer360Workspace;activeOnly:boolean}){const [category,setCategory]=useState('All'),categories=['All',...new Set(data.productMaster.map(item=>item.category))],active=data.holdings.filter(item=>!['closed','expired','lapsed'].includes(item.status.toLowerCase())),source=activeOnly?active:data.holdings,visible=data.productMaster.filter(item=>(category==='All'||item.category===category)&&(!activeOnly||source.some(holding=>holding.productId===item.id)));return <Panel title={activeOnly?'Active product holdings':'Full holdings'} subtitle={activeOnly?`${new Set(active.map(item=>item.productId)).size} active products · exact records represented by the summary card`:`${data.productMaster.length} products from the Franchisee product master · ${data.holdings.length} recorded holdings`} action={<select className="tf-360-select" value={category} onChange={event=>setCategory(event.target.value)}>{categories.map(item=><option key={item}>{item}</option>)}</select>}><div className="tf-holding-groups">{visible.map(product=>{const rows=source.filter(item=>item.productId===product.id);return <section key={product.id}><header><div><b>{product.name}</b><small>{product.category}</small></div><StatusBadge tone={rows.length?'green':'gray'}>{rows.length?`${rows.length} held`:'Not held'}</StatusBadge></header>{rows.length?<DataTable headers={['Provider / Institution','Reference','Investment / Cover / Loan','Current value / outstanding','Status','Start date','Maturity / renewal','Return']} >{rows.map(item=><tr key={item.id}><td>{item.provider||'Not recorded'}</td><td>{mask(item.reference)}</td><td>{amount(item.investedOrCover)}</td><td>{amount(item.currentValue)}</td><td><StatusBadge>{item.status}</StatusBadge></td><td>{date(item.startDate)}</td><td>{date(item.maturityOrRenewalDate)}</td><td>{pct(item.returnPercent)}</td></tr>)}</DataTable>:<div className="tf-product-empty">No holding recorded for this product.</div>}</section>})}</div></Panel>}

function Portfolio({data}:{data:Customer360Workspace}){const p=data.portfolio,total=p.allocation.reduce((sum,item)=>sum+item.value,0),contributors=data.holdings.filter(item=>item.category==='Investment & Wealth'&&item.currentValue!==undefined);return <><div className="tf-360-overview"><Panel title="Relationship & portfolio overview" subtitle="Relationship value is the existing customer-level metric; investment values are kept separate"><div className="tf-360-info"><Info label="Total relationship value" value={money(p.totalPortfolioValue)}/><Info label="Invested amount" value={amount(p.investedAmount)}/><Info label="Current investment value" value={amount(p.currentValue)}/><Info label="Absolute gain / loss" value={amount(p.absoluteGain)}/><Info label="Recorded return" value={pct(p.returnPercent)}/></div></Panel><Panel title="Investment product allocation" subtitle="Uses current values from recorded investment holdings only"><div className="tf-allocation-bars">{p.allocation.length?p.allocation.map(item=><div key={item.category}><p><b>{item.category}</b><span>{money(item.value)}</span></p><i><em style={{width:`${total?Math.max(3,item.value/total*100):0}%`}}/></i></div>):<Empty text="No valued investment holdings are available for allocation."/>}</div></Panel></div><Panel title="Investment value contributors" subtitle="Exact holdings contributing to the current investment value"><DataTable headers={['Product','Provider','Reference','Invested amount','Current value','Return']} empty={!contributors.length}>{contributors.map(item=><tr key={item.id}><td><b>{item.product}</b></td><td>{item.provider||'Not recorded'}</td><td>{mask(item.reference)}</td><td>{amount(item.investedOrCover)}</td><td>{amount(item.currentValue)}</td><td>{pct(item.returnPercent)}</td></tr>)}</DataTable></Panel></>}

function Documents({data,actionsOnly}:{data:Customer360Workspace;actionsOnly:boolean}){const [status,setStatus]=useState('All'),source=actionsOnly?data.documents.filter(item=>item.status!=='Verified'):data.documents,rows=source.filter(item=>status==='All'||item.status===status);return <Panel title={actionsOnly?'KYC & Document Actions':'KYC & Document Vault'} subtitle={actionsOnly?`${source.length} exact records represented by the summary card`:'Only document metadata available to this Franchisee is shown'} action={<select className="tf-360-select" value={status} onChange={event=>setStatus(event.target.value)}>{['All','Verified','Uploaded','Pending','Expired'].map(item=><option key={item}>{item}</option>)}</select>}><DataTable headers={['Document','Type / file','Uploaded','Expiry','Verification status']} empty={!rows.length}>{rows.map(item=><tr key={item.id}><td><b>{item.documentType}</b></td><td>{item.file?.fileName||'No file available'}</td><td>{date(item.file?.uploadedAt)}</td><td>{date(item.expiryDate)}</td><td><StatusBadge>{item.status}</StatusBadge></td></tr>)}</DataTable></Panel>}

function Communications({data}:{data:Customer360Workspace}){return <Panel title="Communication History" subtitle="Chronological customer relationship activity">{data.communications.length?<Timeline items={data.communications}/>:<Empty text="No communication history is available."/>}</Panel>}

function Cases({data,onViewCases}:{data:Customer360Workspace;onViewCases:()=>void}){return <Panel title="Open Cases" subtitle="Active applications and service work"><DataTable headers={['Case ID','Product','Type','Stage / status','Assigned team','Last updated','Action']} empty={!data.openCases.length}>{data.openCases.map(item=><tr key={item.id}><td><b>{item.id}</b></td><td>{item.product}</td><td>{item.transactionType||'New Business'}</td><td><StatusBadge>{item.status}</StatusBadge></td><td>{item.assignedTeam}</td><td>{item.updated}</td><td><button className="tf-text-btn" onClick={onViewCases}>Open Case</button></td></tr>)}</DataTable></Panel>}

function Opportunities({data}:{data:Customer360Workspace}){const opportunityIds=new Set(data.opportunities.map(item=>item.productId)),heldIds=new Set(data.holdings.map(item=>item.productId));return <div className="tf-opportunity-layout"><Panel title="Cross-sell Opportunities" subtitle={`${data.opportunities.length} prioritized opportunities · ${data.opportunitySource}`} >{data.opportunities.length?<div className="tf-opportunity-grid">{data.opportunities.map(item=><article key={item.id}><header><div><span>RECOMMENDED PRODUCT</span><h3>{item.product}</h3></div><StatusBadge tone={item.priority==='High'?'red':item.priority==='Medium'?'amber':'blue'}>{item.priority} priority</StatusBadge></header><dl><div><dt>Why</dt><dd>{item.reason}</dd></div><div><dt>Based on</dt><dd>{item.basedOn}</dd></div><div><dt>Product gap</dt><dd>{item.productGap}</dd></div></dl><footer><span>{item.suggestedAction}</span><ArrowUpRight/></footer></article>)}</div>:<Empty text="No relevant product-gap opportunity is currently identified from the available customer data."/>}<div className="tf-model-note"><ShieldCheck/><span><b>Recommendation source</b>The repository has no connected Intelligence Model. These explainable rules use only recorded customer holdings, profile signals, relationship value, and the enabled 18-product master. No confidence score is generated.</span></div></Panel><Panel title="Product coverage & gaps" subtitle="All enabled products in the Franchisee catalogue"><div className="tf-coverage-list">{data.productMaster.filter(item=>item.enabled).map(item=><div key={item.id}><span><b>{item.name}</b><small>{item.category}</small></span><StatusBadge tone={heldIds.has(item.id)?'green':opportunityIds.has(item.id)?'amber':'gray'}>{heldIds.has(item.id)?'Active':opportunityIds.has(item.id)?'Opportunity':'No current signal'}</StatusBadge></div>)}</div></Panel></div>}

function Renewals({data,dueOnly,onViewCases}:{data:Customer360Workspace;dueOnly:boolean;onViewCases:()=>void}){const rows=dueOnly?data.renewals.filter(item=>item.daysRemaining<=30):data.renewals;return <Panel title={dueOnly?'Renewals currently due':'Renewals Due'} subtitle={dueOnly?`${rows.length} exact records represented by the summary card`:'Recorded and calculated renewal schedule'}><DataTable headers={['Product','Policy / account','Provider','Renewal date','Days remaining','Premium / amount','Status','Action']} empty={!rows.length}>{rows.map(item=><tr key={item.id}><td><b>{item.product}</b></td><td>{item.policyNumber}</td><td>{item.provider}</td><td>{date(item.renewalDueDate)}</td><td>{item.daysRemaining<0?`${Math.abs(item.daysRemaining)} overdue`:item.daysRemaining}</td><td>{money(item.currentPremium)}</td><td><StatusBadge tone={item.status==='Overdue'?'red':item.status==='Due Soon'?'amber':'green'}>{item.status}</StatusBadge></td><td>{item.caseId?<button className="tf-text-btn" onClick={onViewCases}>View Case</button>:<span>—</span>}</td></tr>)}</DataTable></Panel>}

function Kpi({icon,label,value,detail,onClick}:{icon:ReactNode;label:string;value:string|number;detail:string;onClick:()=>void}){return <button type="button" onClick={onClick} aria-label={`${label}: ${value}. ${detail}`}><span className="tf-kpi-icon">{icon}</span><span>{label}</span><b>{value}</b><small>{detail} <ArrowUpRight/></small></button>}
function Info({label,value}:{label:string;value:string}){return <div><span>{label}</span><b>{value}</b></div>}
function Empty({text}:{text:string}){return <div className="tf-360-empty"><WalletCards/><b>No information to show</b><span>{text}</span></div>}
function State({title,detail,onBack}:{title:string;detail:string;onBack:()=>void}){return <div className="tf-360-state"><UserRound/><b>{title}</b><p>{detail}</p><button className="tf-primary" onClick={onBack}><ArrowLeft/> Back to Customers</button></div>}
function initials(name:string){return name.split(' ').slice(0,2).map(item=>item[0]).join('').toUpperCase()}
function date(value?:string){if(!value)return '—';const parsed=new Date(value.includes('T')?value:`${value}T00:00:00`);return Number.isNaN(parsed.getTime())?'—':parsed.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}
function amount(value?:number){return value===undefined?'—':money(value)}
function pct(value?:number){return value===undefined?'—':`${value>=0?'+':''}${value.toFixed(1)}%`}
function mask(value?:string){if(!value)return 'Not recorded';return value.length<7?'••••':`${value.slice(0,3)}••••${value.slice(-2)}`}
