import { BellRing, BriefcaseBusiness, Edit3, FilePlus2, HeartHandshake, Landmark, PiggyBank, Plus, ShoppingBag, Tags, Upload, UsersRound, WalletCards } from 'lucide-react'
import { useEffect, useMemo, useState, type ReactNode } from 'react'
import type { CustomerOnboardingDraft } from '../customer360Types'
import type { FranchiseeCustomer } from '../types'
import { CustomerOnboardingWizard } from '../components/CustomerOnboardingWizard'
import { DataTable, Documents, FilterSelect, Filters, Modal, money, Panel, StatusBadge, PageHeader, Timeline } from '../components/FranchiseeUI'

type ViewTab='Overview'|'Family'|'Financial Profile'|'Products'|'Insurance'|'Loans'|'Investments'|'Documents'|'Reminders'|'Activity'
const tabs:ViewTab[]=['Overview','Family','Financial Profile','Products','Insurance','Loans','Investments','Documents','Reminders','Activity']
export function CustomersPage({customers,focusCustomerId,onFocusHandled,onOpen360,onAdd,onSaveDraft,draft,onApply,onSupport,onToast}:{customers:FranchiseeCustomer[];focusCustomerId?:string;onFocusHandled?:()=>void;onOpen360:(customerId:string)=>void;onAdd:(input:CustomerOnboardingDraft)=>void;onSaveDraft:(input:CustomerOnboardingDraft)=>void;draft?:CustomerOnboardingDraft;onApply:(customer:FranchiseeCustomer)=>void;onSupport:(customer:FranchiseeCustomer)=>void;onToast:(s:string)=>void}){
  const [search,setSearch]=useState(''),[kyc,setKyc]=useState('All KYC'),[selected,setSelected]=useState<FranchiseeCustomer>(),[adding,setAdding]=useState(false),[tagged,setTagged]=useState<string[]>([]),[tab,setTab]=useState<ViewTab>('Overview')
  const rows=useMemo(()=>customers.filter(c=>(kyc==='All KYC'||c.kyc===kyc)&&`${c.name} ${c.id} ${c.mobile}`.toLowerCase().includes(search.toLowerCase())),[customers,search,kyc])
  useEffect(()=>{if(!focusCustomerId)return;const customer=customers.find(item=>item.id===focusCustomerId);if(customer){setSelected(customer);setTab('Overview')}onFocusHandled?.()},[focusCustomerId,customers,onFocusHandled])
  const open=(customer:FranchiseeCustomer)=>onOpen360(customer.id)
  return <><PageHeader eyebrow="CUSTOMER RELATIONSHIPS" title="Customers" description="Franchise-owned Customer 360 records, relationship value, KYC health, products, and reminder readiness." actions={<button className="tf-primary" onClick={()=>setAdding(true)}><Plus/> Add New Customer</button>}/>
    <Panel title="Customer Directory" subtitle={`${rows.length} mapped customers`} action={tagged.length?<button className="tf-secondary" onClick={()=>{onToast(`${tagged.length} customers tagged for campaign`);setTagged([])}}><Tags/> Apply campaign tag ({tagged.length})</button>:undefined}><Filters search={search} onSearch={setSearch}><FilterSelect label="KYC" value={kyc} onChange={setKyc} options={['All KYC','Verified','Pending','Expired']}/></Filters><DataTable headers={['','Customer','Contact','KYC','Profile','Relationship value','Products','Last activity','']} empty={!rows.length}>{rows.map(customer=><tr key={customer.id}><td><input type="checkbox" checked={tagged.includes(customer.id)} onChange={e=>setTagged(current=>e.target.checked?[...current,customer.id]:current.filter(id=>id!==customer.id))}/></td><td><button className="tf-link-stack" onClick={()=>open(customer)}><b>{customer.name}</b><small>{customer.id} · {customer.city}</small></button></td><td><b>{customer.mobile}</b><small>{customer.email}</small></td><td><StatusBadge>{customer.kyc}</StatusBadge></td><td>{customer.profile360?<span className="tf-complete-pill">{customer.profile360.profileCompleteness}%</span>:<small>Legacy profile</small>}</td><td><b>{money(customer.relationshipValue)}</b><small>{customer.performance>0?`↑ ${customer.performance}%`:'New relationship'}</small></td><td><b>{customer.products.length}</b><small>{customer.products.slice(0,2).join(', ')||'No products yet'}</small></td><td>{customer.lastActivity}</td><td><button className="tf-text-btn" onClick={()=>open(customer)}>Open 360</button></td></tr>)}</DataTable></Panel>
    {selected&&<Customer360 customer={selected} tab={tab} setTab={setTab} onClose={()=>setSelected(undefined)} onApply={onApply} onSupport={onSupport} onToast={onToast}/>} 
    {adding&&<CustomerOnboardingWizard initial={draft} onClose={()=>setAdding(false)} onSaveDraft={value=>{onSaveDraft(value);onToast('Customer onboarding draft saved locally')}} onCreate={value=>{onAdd(value);setAdding(false)}}/>}
  </>
}

function Customer360({customer,tab,setTab,onClose,onApply,onSupport,onToast}:{customer:FranchiseeCustomer;tab:ViewTab;setTab:(tab:ViewTab)=>void;onClose:()=>void;onApply:(c:FranchiseeCustomer)=>void;onSupport:(c:FranchiseeCustomer)=>void;onToast:(s:string)=>void}){const p=customer.profile360;return <Modal title={customer.name} subtitle={`${customer.id} · Customer 360`} onClose={onClose}><div className="tf-360-head"><div><span>{p?'Profile completeness':'Relationship value'}</span><strong>{p?`${p.profileCompleteness}%`:money(customer.relationshipValue)}</strong><small>{p?`${p.reminders.length} reminder configurations · Customer since ${date(p.basic.customerSince)}`:customer.performance>0?`Portfolio performance +${customer.performance}%`:'Legacy customer profile'}</small></div><StatusBadge>{customer.kyc} KYC</StatusBadge><div className="tf-modal-actions"><button className="tf-secondary" onClick={()=>onToast('Contact edit request saved locally')}><Edit3/> Edit</button><button className="tf-primary" onClick={()=>onApply(customer)}><ShoppingBag/> Buy / Apply</button></div></div><div className="tf-tabs tf-360-tabs">{tabs.map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</div><div className="tf-360-content">
  {tab==='Overview'&&<Overview customer={customer}/>} {tab==='Family'&&<Family customer={customer}/>} {tab==='Financial Profile'&&<Financial customer={customer}/>} {tab==='Products'&&<Products customer={customer} onApply={onApply}/>} {tab==='Insurance'&&<Insurance customer={customer}/>} {tab==='Loans'&&<Loans customer={customer}/>} {tab==='Investments'&&<Investments customer={customer}/>} {tab==='Documents'&&<CustomerDocuments customer={customer} onToast={onToast}/>} {tab==='Reminders'&&<Reminders customer={customer}/>} {tab==='Activity'&&<Panel title="Communication & Activity" subtitle="Relationship history"><Timeline items={customer.timeline}/><div className="tf-inline-actions"><button className="tf-secondary" onClick={()=>onToast('Interaction note logged')}><FilePlus2/> Log interaction note</button><button className="tf-secondary" onClick={()=>onSupport(customer)}>Raise service request</button></div></Panel>}
 </div></Modal>}

function Overview({customer}:{customer:FranchiseeCustomer}){const p=customer.profile360;if(!p)return <div className="tf-modal-grid"><Panel title="Legacy Customer Overview" subtitle="Existing records remain fully compatible"><Info rows={[['Customer ID',customer.id],['Mobile',customer.mobile],['Email',customer.email],['City',customer.city],['KYC',customer.kyc]]}/></Panel><Panel title="Holdings" subtitle={`${customer.products.length} active relationships`}><div className="tf-chip-list">{customer.products.length?customer.products.map(x=><span key={x}>{x}</span>):<small>No active holdings</small>}</div></Panel></div>;return <><div className="tf-summary-grid"><Summary icon={<HeartHandshake/>} label="Existing Policies" value={p.policies.length}/><Summary icon={<BriefcaseBusiness/>} label="Existing Loans" value={p.loans.length}/><Summary icon={<PiggyBank/>} label="Investments" value={p.investments.length}/><Summary icon={<Upload/>} label="Documents" value={p.documents.length}/><Summary icon={<BellRing/>} label="Upcoming Reminders" value={p.reminders.filter(x=>x.enabled).length}/></div><div className="tf-modal-grid"><Panel title="Customer Overview" subtitle={p.customerType}><Info rows={[['Customer ID',customer.id],['Mobile',customer.mobile],['Email',customer.email],['City',customer.city],['Occupation',p.profile.occupation||p.basic.industry||'—'],['Customer Category',p.preferences.category],['Franchisee','Troth Finserve'],['Relationship Manager',p.preferences.relationshipManager||'Unassigned'],['Customer Since',date(p.basic.customerSince)]]}/></Panel><Panel title="Needs & Relationship" subtitle="CRM context"><div className="tf-chip-list">{p.preferences.interests.map(x=><span key={x}>{x}</span>)}</div><Info rows={[['Primary goal',p.preferences.primaryGoal||'—'],['Source',p.preferences.source],['Preferred contact',p.preferences.preferredContactMethod],['Risk preference',p.preferences.riskPreference]]}/></Panel></div></>}
function Family({customer}:{customer:FranchiseeCustomer}){const p=customer.profile360;if(!p)return <Empty text="Family information is not available for this legacy record."/>;return <Panel title="Family & Household" subtitle={`${p.profile.family.length} family members · informational CRM data`}><div className="tf-record-grid">{p.profile.family.map(x=><article key={x.id}><UsersRound/><div><b>{x.name}</b><span>{x.relationship} · {x.dependent?'Dependent':'Not dependent'}</span><small>{x.dateOfBirth?`Born ${date(x.dateOfBirth)}`:''} {x.occupation||''}</small></div></article>)}</div>{!p.profile.family.length&&<Empty text="No family members added."/>}{p.profile.nominee.name&&<Info rows={[['Nominee',p.profile.nominee.name],['Relationship',p.profile.nominee.relationship||'—'],['Mobile',p.profile.nominee.mobile||'—']]}/>}</Panel>}
function Financial({customer}:{customer:FranchiseeCustomer}){const f=customer.profile360?.financial;if(!f)return <Empty text="Financial profile is not available for this record."/>;return <div className="tf-modal-grid"><Panel title="Financial Snapshot" subtitle="High-level CRM information"><Info rows={[['Annual income',f.annualIncomeRange||'—'],['Monthly income',inr(f.monthlyIncome)],['Monthly expenses',inr(f.monthlyExpenses)],['Existing monthly EMI',inr(f.monthlyEmi)],['Assets',inr(f.assets)],['Liabilities',inr(f.liabilities)],['Net worth',inr(f.netWorth)]]}/></Panel><Panel title="Banking Relationship" subtitle="No sensitive credentials stored"><Info rows={[['Primary bank',f.primaryBank||'—'],['Account type',f.accountType||'—']]}/><div className="tf-privacy-inline"><Landmark/> Passwords, OTPs and payment credentials are never requested.</div></Panel></div>}
function Products({customer,onApply}:{customer:FranchiseeCustomer;onApply:(c:FranchiseeCustomer)=>void}){return <Panel title="Products & Opportunities" subtitle={`${customer.products.length} known relationships`}><div className="tf-chip-list">{customer.products.map(x=><span key={x}>{x}</span>)}</div>{!customer.products.length&&<Empty text="No existing products recorded."/>}<div className="tf-callout">Ready for the next relationship conversation <button onClick={()=>onApply(customer)}>Start application</button></div></Panel>}
function Insurance({customer}:{customer:FranchiseeCustomer}){const rows=customer.profile360?.policies;if(!rows)return <Empty text="Insurance details are not available for this legacy record."/>;if(!rows.length)return <Empty text={customer.profile360?.noExistingPolicies?'Customer confirmed no existing insurance policies.':'No policies added.'}/>;return <div className="tf-360-cards">{rows.map(x=><article key={x.id}><header><div><small>{x.category}</small><h3>{x.insurer}</h3><span>{x.planName||'Existing policy'}</span></div><StatusBadge>{x.status}</StatusBadge></header><Info rows={[['Policy number',mask(x.policyNumber)],['Sum insured',inr(x.sumInsured)],['Premium',inr(x.premiumAmount)],['Renewal',date(x.renewalDate)],['Purchased through',x.purchasedThrough||'—'],['Reminder',x.renewalReminderEnabled?`${x.reminderOffsets.join(' / ')} days`:'Off']]}/>{dueSoon(x.renewalDate)&&<em className="tf-due-soon">Renewal due soon</em>}</article>)}</div>}
function Loans({customer}:{customer:FranchiseeCustomer}){const rows=customer.profile360?.loans;if(!rows)return <Empty text="Loan details are not available for this legacy record."/>;if(!rows.length)return <Empty text={customer.profile360?.noExistingLoans?'Customer confirmed no existing loans.':'No loans added.'}/>;return <div className="tf-360-cards">{rows.map(x=><article key={x.id}><header><div><small>{x.loanType}</small><h3>{x.lender}</h3><span>{x.accountNumber?maskAccount(x.accountNumber):'Account reference not stored'}</span></div><StatusBadge>{x.status}</StatusBadge></header><Info rows={[['Original amount',inr(x.originalAmount)],['Outstanding',inr(x.outstandingAmount)],['EMI',inr(x.emiAmount)],['Interest',x.interestRate!==undefined?`${x.interestRate}% ${x.interestType||''}`:'—'],['Maturity',date(x.maturityDate)],['EMI reminder',x.emiReminderEnabled?'On':'Off'],['Balance transfer',x.balanceTransferInterest||'—'],['Top-up interest',x.topUpInterest||'—']]}/></article>)}</div>}
function Investments({customer}:{customer:FranchiseeCustomer}){const rows=customer.profile360?.investments;if(!rows)return <Empty text="Investment details are not available for this legacy record."/>;if(!rows.length)return <Empty text={customer.profile360?.noExistingInvestments?'Customer confirmed no existing investments.':'No investments added.'}/>;return <div className="tf-360-cards">{rows.map(x=><article key={x.id}><header><div><small>{x.investmentType}</small><h3>{x.productName||x.provider||'Investment'}</h3><span>{x.provider}</span></div><StatusBadge>{x.status||'Recorded'}</StatusBadge></header><Info rows={[['Invested',inr(x.investmentAmount)],['Current value',inr(x.currentValue)],['SIP',inr(x.sipAmount)],['Maturity',date(x.maturityDate)],['Reminder',x.maturityReminderEnabled||x.sipReminderEnabled||x.reviewReminderEnabled?'Configured':'Off']]}/></article>)}</div>}
function CustomerDocuments({customer,onToast}:{customer:FranchiseeCustomer;onToast:(s:string)=>void}){const rows=customer.profile360?.documents;if(!rows)return <Panel title="Document Vault"><Documents items={customer.documents}/><button className="tf-secondary tf-full" onClick={()=>onToast('Document request added to customer timeline')}><Upload/> Request / upload document</button></Panel>;return <Panel title="Customer Documents" subtitle="Sensitive document numbers are hidden"><DataTable headers={['Document','File','Uploaded','Expiry','Status'] } empty={!rows.length}>{rows.map(x=><tr key={x.id}><td><b>{x.documentType}</b></td><td>{x.file?.fileName||'No file selected'}</td><td>{date(x.file?.uploadedAt)}</td><td>{date(x.expiryDate)}</td><td><StatusBadge>{x.status}</StatusBadge></td></tr>)}</DataTable></Panel>}
function Reminders({customer}:{customer:FranchiseeCustomer}){const rows=customer.profile360?.reminders;if(!rows)return <Empty text="Reminder configuration is not available for this legacy record."/>;return <Panel title="Consolidated Reminders" subtitle="Configuration only · no notification engine is active"><DataTable headers={['Type','Related Product','Due Date','Timing','Channel','Status']} empty={!rows.length}>{rows.map(x=><tr key={x.id}><td><b>{x.type}</b></td><td>{x.title}</td><td>{date(x.dueDate)}</td><td>{x.reminderOffsets.map(v=>v===0?'Due date':`${v}d before`).join(', ')}</td><td>{x.channels.join(', ')}</td><td><StatusBadge>{x.status}</StatusBadge></td></tr>)}</DataTable></Panel>}

function Summary({icon,label,value}:{icon:ReactNode;label:string;value:number}){return <article>{icon}<span>{label}</span><b>{value}</b></article>}
function Info({rows}:{rows:[string,string][]}){return <div className="tf-info-grid">{rows.map(([label,value])=><div key={label}><span>{label}</span><b>{value||'—'}</b></div>)}</div>}
function Empty({text}:{text:string}){return <div className="tf-360-empty"><WalletCards/><b>No information to show</b><span>{text}</span></div>}
function date(value?:string){if(!value)return '—';const parsed=new Date(value.includes('T')?value:`${value}T00:00:00`);return Number.isNaN(parsed.getTime())?'—':parsed.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}
function inr(value?:number){return value===undefined?'—':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value)}
function mask(value:string){return value.length<=5?'•••••':`${value.slice(0,3)}••••${value.slice(-2)}`}
function maskAccount(value:string){return `•••• ${value.replace(/\s/g,'').slice(-4)}`}
function dueSoon(value:string){const days=(new Date(`${value}T00:00:00`).getTime()-Date.now())/86400000;return days>=0&&days<=90}
