import { AlertCircle, CalendarDays, FileClock, Headphones, IndianRupee, Landmark, UsersRound } from 'lucide-react'
import type { FranchiseeStore, FranchiseeRoute } from '../types'
import { MessageSquareText } from 'lucide-react'
import { Metric, money, Panel, Progress, StatusBadge } from '../components/FranchiseeUI'

export function DashboardPage({store,onNavigate}:{store:FranchiseeStore;onNavigate:(r:FranchiseeRoute)=>void;onToast:(s:string)=>void}){
  const queryCount=store.cases.filter(item=>item.status==='Query Raised').length
  const pending=store.cases.filter(item=>!['Completed','Rejected','Draft'].includes(item.status)).length
  const business=store.revenue.reduce((sum,row)=>sum+row.business,0)
  const mix=[['Investment & Wealth',64,'#315bea'],['Loans',24,'#16a394'],['Insurance',9,'#f59e0b'],['Loan Protector',3,'#7c4dff']]
  const trend=[36,48,42,61,58,75,69,86]
  return <>
    <div className="tf-ticker"><b>FRANCHISE UPDATES</b><span>New NPS enablement is live</span><i/> <span>September campaign toolkit available</span><i/> <span>August payout statement published</span><button onClick={()=>onNavigate('notifications')}>View all</button></div>
    <div className="tf-metrics tf-metrics-4"><Metric label="Total Net Worth (AUM)" value={money(store.dashboardSummary.totalNetWorth)} meta="Across active customer holdings" icon={<Landmark/>} onClick={()=>onNavigate('business-revenue')}/><Metric label="Total Revenue" value={money(store.dashboardSummary.totalRevenue)} meta="Total franchise earnings" icon={<IndianRupee/>} tone="teal" onClick={()=>onNavigate('business-revenue')}/><Metric label="Current Month Revenue" value={money(store.dashboardSummary.currentMonthRevenue)} meta="Revenue generated this month" icon={<CalendarDays/>} tone="orange" onClick={()=>onNavigate('business-revenue')}/><Metric label="Total Customers" value={store.dashboardSummary.totalCustomers} meta="Mapped customer relationships" icon={<UsersRound/>} tone="violet" onClick={()=>onNavigate('customers')}/></div>
    <div className="tf-grid tf-grid-2-1">
      <Panel title="Business trend" subtitle="Period-over-period business booked" action={<StatusBadge tone="blue">This Year</StatusBadge>}><div className="tf-chart"><div className="tf-ylabels"><span>₹2 Cr</span><span>₹1 Cr</span><span>₹0</span></div><div className="tf-bars">{trend.map((v,i)=><button key={i} style={{height:`${v}%`}} onClick={()=>onNavigate('business-revenue')} title={`Period ${i+1}: ${v} lakh`}><i/></button>)}</div><div className="tf-xlabels">{['Feb','Mar','Apr','May','Jun','Jul','Aug','Sep'].map(x=><span key={x}>{x}</span>)}</div></div></Panel>
      <Panel title="Business mix" subtitle="Contribution by product group"><div className="tf-mix"><div className="tf-donut" style={{background:'conic-gradient(#315bea 0 64%, #16a394 64% 88%, #f59e0b 88% 97%, #7c4dff 97%)'}}><span><b>{money(business)}</b><small>Total</small></span></div><div>{mix.map(([name,value,color])=><button key={String(name)} onClick={()=>onNavigate('business-revenue')}><i style={{background:String(color)}}/><span>{name}</span><b>{value}%</b></button>)}</div></div></Panel>
    </div>
    <div className="tf-grid tf-grid-3">
      <Panel title="Operational snapshot" subtitle="Items needing franchise action"><div className="tf-action-list"><button onClick={()=>onNavigate('crm')}><MessageSquareText/><span><b>Un-triaged inquiries</b><small>Awaiting lead, case, or close decision</small></span><strong>{store.inquiries.filter(item=>item.status==='Open').length}</strong></button><button onClick={()=>onNavigate('crm')}><UsersRound/><span><b>Open leads</b><small>Follow-ups due across pipeline</small></span><strong>{store.leads.filter(l=>!['Won','Lost'].includes(l.stage)).length}</strong></button><button onClick={()=>onNavigate('applications')}><FileClock/><span><b>Pending applications</b><small>Tracked by HO Operations</small></span><strong>{pending}</strong></button><button className="urgent" onClick={()=>onNavigate('applications')}><AlertCircle/><span><b>HO queries awaiting response</b><small>Franchise must act next</small></span><strong>{queryCount}</strong></button><button onClick={()=>onNavigate('support')}><Headphones/><span><b>Open support tickets</b><small>Across HO desks</small></span><strong>{store.tickets.filter(t=>!['Resolved','Closed'].includes(t.status)).length}</strong></button></div></Panel>
      <Panel title="Product performance" subtitle="AUM mix across key verticals"><div className="tf-performance">{[['Mutual Funds',72],['Shares / Demat',54],['PMS',47],['AIF',32],['Bonds & FD',44],['Insurance',61],['Loans',38],['Loan Protector',24]].map(([name,value])=><button key={String(name)} onClick={()=>onNavigate('products')}><span><b>{name}</b><small>{value}% of target</small></span><Progress value={Number(value)}/></button>)}</div></Panel>
      <Panel title="Activity & ownership" subtitle="Every hand-off stays visible"><div className="tf-handler-list"><div><i className="blue"/><span><b>TAPP-260184 needs your response</b><small>Franchise → reply to HO query</small></span></div><div><i className="amber"/><span><b>PMS case under review</b><small>Handled by HO Operations — Wealth</small></span></div><div><i className="green"/><span><b>Motor policy issued</b><small>Customer 360 updated automatically</small></span></div><div><i className="violet"/><span><b>Certification in progress</b><small>Pass will update Product Mapping</small></span></div></div></Panel>
    </div>
  </>
}
