import { AlertTriangle, ArrowLeft, ArrowRight, Check, Edit3, Plus, Save, ShieldCheck, Trash2, UsersRound, WalletCards, X } from 'lucide-react'
import { useMemo, useState, type ChangeEvent, type ReactNode } from 'react'
import { currentFranchiseeId, employeeDepartments, employeeDocumentTypes, employeeProductOptions, employeeRoles, franchiseeEmployeeRepository, type EmployeeAddress, type EmployeeDocument, type EmployeeDraft, type EmployeeFileMetadata, type EmployeeStatus, type FranchiseeEmployee } from '../employees'
import type { FranchiseeCase, FranchiseeCustomer, RevenueRow } from '../types'
import { DataTable, FilterSelect, Filters, money, Modal, Panel, StatusBadge, PageHeader } from '../components/FranchiseeUI'

export type EmployeeTab='Overview'|'Employment'|'Customers & Business'|'Products'|'Documents'|'Activity'
export type SimpleEmployeeTab='Overview'|'Customers'|'Business Lines'|'Activity'|'Documents'
const tabs:EmployeeTab[]=['Overview','Employment','Customers & Business','Products','Documents','Activity']
const simpleTabs:SimpleEmployeeTab[]=['Overview','Customers','Business Lines','Activity','Documents']
const statuses:EmployeeStatus[]=['Active','On Leave','Inactive','Exited']
export function EmployeesPage({customers,cases,products,creating=false,onCreateEmployee,onExitCreate,onOpenCustomer,onToast}:{customers:FranchiseeCustomer[];cases:FranchiseeCase[];products:string[];creating?:boolean;onCreateEmployee?:()=>void;onExitCreate?:()=>void;onOpenCustomer:(id:string)=>void;onToast:(message:string)=>void}){
  const [employees,setEmployees]=useState(()=>franchiseeEmployeeRepository.load(currentFranchiseeId)),[search,setSearch]=useState(''),[businessLine,setBusinessLine]=useState('All Business Lines'),[role,setRole]=useState('All Roles'),[status,setStatus]=useState('All Statuses'),[selected,setSelected]=useState<FranchiseeEmployee>(),[editing,setEditing]=useState<FranchiseeEmployee|null>(null),[formOpen,setFormOpen]=useState(false),[tab,setTab]=useState<SimpleEmployeeTab>('Overview')
  const directEmployees=employees.filter(employee=>!employee.subFranchiseeId),roles=unique(directEmployees.map(x=>x.role)),businessLines=unique(directEmployees.flatMap(x=>x.assignedProducts))
  const rows=useMemo(()=>directEmployees.filter(employee=>(businessLine==='All Business Lines'||employee.assignedProducts.includes(businessLine))&&(role==='All Roles'||employee.role===role)&&(status==='All Statuses'||employee.status===status)&&`${fullName(employee)} ${employee.employeeId} ${employee.mobile} ${employee.email}`.toLowerCase().includes(search.toLowerCase())),[directEmployees,search,businessLine,role,status])
  const open=(employee:FranchiseeEmployee)=>{setSelected(employee);setTab('Overview')}
  const beginEdit=(employee:FranchiseeEmployee)=>{setSelected(undefined);setEditing(employee);setFormOpen(true)}
  const save=(draft:EmployeeDraft)=>{const employee=editing?franchiseeEmployeeRepository.update(editing,draft):franchiseeEmployeeRepository.saveNew(draft);setEmployees(current=>editing?current.map(x=>x.id===employee.id?employee:x):[employee,...current]);setFormOpen(false);setEditing(null);setSelected(employee);setTab('Overview');onToast(`${fullName(employee)} ${editing?'updated':'added'} successfully`)}
  const changeStatus=(employee:FranchiseeEmployee,next:EmployeeStatus)=>{const updated=franchiseeEmployeeRepository.changeStatus(employee,next);setEmployees(current=>current.map(x=>x.id===employee.id?updated:x));setSelected(updated);onToast(`${fullName(updated)} marked ${next}`)}
  const removeDocument=(employee:FranchiseeEmployee,documentId:string)=>{const draft=draftFrom(employee);draft.documents=draft.documents.filter(document=>document.id!==documentId);const updated=franchiseeEmployeeRepository.update(employee,draft);setEmployees(current=>current.map(x=>x.id===employee.id?updated:x));setSelected(updated);onToast('Employee document metadata removed')}
  if(creating)return <div className="franchisee-employees"><EmployeeCreatePage employees={employees} customers={customers} products={products} onClose={()=>onExitCreate?.()} onSave={draft=>{const employee=franchiseeEmployeeRepository.saveNew(draft);onToast(`${fullName(employee)} added successfully`);onExitCreate?.()}}/></div>
  return <div className="franchisee-employees"><PageHeader eyebrow="FRANCHISE TEAM" title="Employees" description="View and manage employees working under your franchise." actions={<button className="tf-primary" onClick={()=>onCreateEmployee?.()}><Plus/> Add Employee</button>}/>
    <Panel title="Employee List" subtitle={`${rows.length} employees`}><div className="fe-filters"><Filters search={search} onSearch={setSearch}/><FilterSelect label="Role" value={role} onChange={setRole} options={['All Roles',...roles]}/><FilterSelect label="Business Line" value={businessLine} onChange={setBusinessLine} options={['All Business Lines',...businessLines]}/><FilterSelect label="Status" value={status} onChange={setStatus} options={['All Statuses',...statuses]}/></div><DataTable headers={['Employee Name','Contact','Role','Business Lines','Customers','Status','View']} empty={!rows.length}>{rows.map(employee=><tr key={employee.id}><td><button className="fe-employee-cell" onClick={()=>open(employee)}><span>{initials(employee)}</span><div><b>{fullName(employee)}</b><small>{employee.employeeId}</small></div></button></td><td><b>{employee.mobile}</b><small>{employee.email}</small></td><td><b>{employee.role}</b><small>{employee.designation}</small></td><td><CompactList values={employee.assignedProducts}/></td><td><b>{employee.assignedCustomerIds.length} Customer{employee.assignedCustomerIds.length===1?'':'s'}</b></td><td><StatusBadge>{employee.status}</StatusBadge></td><td><button className="tf-text-btn" onClick={()=>open(employee)}>View</button></td></tr>)}</DataTable>{!rows.length&&<div className="fe-empty"><UsersRound/><h3>No employees found.</h3><p>Try changing the search or filters.</p></div>}</Panel>
    {selected&&<SimpleEmployeeDetail employee={selected} employees={employees} customers={customers} cases={cases} tab={tab} setTab={setTab} onClose={()=>setSelected(undefined)} onEdit={()=>beginEdit(selected)} onStatus={next=>changeStatus(selected,next)} onRemoveDocument={documentId=>removeDocument(selected,documentId)} onOpenCustomer={onOpenCustomer} onToast={onToast}/>}
    {formOpen&&<EmployeeForm employee={editing} employees={employees} customers={customers} products={products} onClose={()=>{setFormOpen(false);setEditing(null)}} onSave={save}/>} 
  </div>
}

export function SimpleEmployeeDetail({employee,employees,customers,cases,tab,setTab,onClose,onEdit,onStatus,onRemoveDocument,onOpenCustomer,onToast}:{employee:FranchiseeEmployee;employees:FranchiseeEmployee[];customers:FranchiseeCustomer[];cases:FranchiseeCase[];tab:SimpleEmployeeTab;setTab:(tab:SimpleEmployeeTab)=>void;onClose:()=>void;onEdit?:()=>void;onStatus?:(status:EmployeeStatus)=>void;onRemoveDocument?:(documentId:string)=>void;onOpenCustomer:(id:string)=>void;onToast:(message:string)=>void}){
  const assigned=customers.filter(customer=>employee.assignedCustomerIds.includes(customer.id))
  const manager=employees.find(item=>item.id===employee.reportingManagerId)
  return <Modal title={fullName(employee)} subtitle={`${employee.employeeId} · Employee Detail`} onClose={onClose}>
    <div className="fe-360-head"><span className="fe-avatar">{initials(employee)}</span><div><h3>{employee.designation}</h3><p>{employee.role} · {employee.mobile} · {employee.email}</p></div><StatusBadge>{employee.status}</StatusBadge>{(onStatus||onEdit)&&<div className="tf-modal-actions">{onStatus&&<select value={employee.status} onChange={event=>onStatus(event.target.value as EmployeeStatus)} aria-label="Change employee status">{statuses.map(value=><option key={value}>{value}</option>)}</select>}{onEdit&&<button className="tf-primary" onClick={onEdit}><Edit3/> Edit</button>}</div>}</div>
    <div className="tf-tabs fe-tabs">{simpleTabs.map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</div>
    <div className="fe-360-content">
      {tab==='Overview'&&<Panel title="Overview" subtitle="Employee contact and work details"><Info rows={[['Employee Name',fullName(employee)],['Employee ID',employee.employeeId],['Mobile',employee.mobile],['Email',employee.email],['Role',employee.role],['Designation',employee.designation],['Joining Date',date(employee.joiningDate)],['Reporting To',manager?fullName(manager):'Not assigned'],['Status',employee.status],['Business Lines',employee.assignedProducts.join(', ')||'None assigned']]}/></Panel>}
      {tab==='Customers'&&<Panel title="Customers" subtitle="Only customers assigned to this employee"><DataTable headers={['Customer Name','Contact','Customer Type','Products','Open Cases','Open 360']} empty={!assigned.length}>{assigned.map(customer=>{const openCases=cases.filter(item=>item.customerId===customer.id&&!['Completed','Rejected','Approved / Issued'].includes(item.status)).length;return <tr key={customer.id}><td><b>{customer.name}</b><small>{customer.id}</small></td><td><b>{customer.mobile}</b><small>{customer.email}</small></td><td>{customer.profile360?.customerType||'Individual'}</td><td><CompactList values={customer.products}/></td><td>{openCases}</td><td><button className="tf-text-btn" onClick={()=>onOpenCustomer(customer.id)}>Open 360</button></td></tr>})}</DataTable>{!assigned.length&&<div className="fe-business-empty">No customers are assigned to this employee.</div>}</Panel>}
      {tab==='Business Lines'&&<Panel title="Business Lines" subtitle="Business areas assigned to this employee"><div className="fe-product-cards">{employee.assignedProducts.map(product=><article key={product}><ShieldCheck/><b>{product}</b><small>Assigned</small></article>)}</div>{!employee.assignedProducts.length&&<div className="fe-business-empty">No business lines assigned.</div>}</Panel>}
      {tab==='Documents'&&<Panel title="Documents" subtitle="Employee document records"><DataTable headers={['Document','File','Issue Date','Expiry Date','Status','View']} empty={!employee.documents.length}>{employee.documents.map(document=><tr key={document.id}><td><b>{document.documentType}</b></td><td>{document.file?.fileName||'No file selected'}</td><td>{date(document.issueDate)}</td><td>{date(document.expiryDate)}</td><td><StatusBadge>{document.status}</StatusBadge></td><td><div className="fe-actions"><button className="tf-text-btn" onClick={()=>onToast(`${document.documentType}: ${document.file?.fileName||'No file uploaded'}`)}>View</button>{onRemoveDocument&&<button className="tf-text-btn fe-remove" onClick={()=>onRemoveDocument(document.id)}>Remove</button>}</div></td></tr>)}</DataTable></Panel>}
      {tab==='Activity'&&<Panel title="Activity" subtitle="Employee history"><div className="fe-activity">{employee.activity.map(item=><article key={item.id}><i/><div><b>{item.title}</b><p>{item.detail}</p><small>{item.timestamp}</small></div></article>)}</div></Panel>}
    </div>
  </Modal>
}

export function Employee360({employee,employees,customers,revenue,tab,setTab,onClose,onEdit,onStatus,onRemoveDocument,onOpenCustomer,onToast}:{employee:FranchiseeEmployee;employees:FranchiseeEmployee[];customers:FranchiseeCustomer[];revenue:RevenueRow[];tab:EmployeeTab;setTab:(tab:EmployeeTab)=>void;onClose:()=>void;onEdit?:()=>void;onStatus?:(status:EmployeeStatus)=>void;onRemoveDocument?:(documentId:string)=>void;onOpenCustomer:(id:string)=>void;onToast:(message:string)=>void}){const assigned=customers.filter(x=>employee.assignedCustomerIds.includes(x.id)),manager=employees.find(x=>x.id===employee.reportingManagerId),business=revenue.filter(x=>x.owner===fullName(employee)),businessValue=business.reduce((sum,x)=>sum+x.business,0);return <Modal title={fullName(employee)} subtitle={`${employee.employeeId} · Employee 360`} onClose={onClose}><div className="fe-360-head"><span className="fe-avatar">{initials(employee)}</span><div><h3>{employee.designation}</h3><p>{employee.department} · {employee.mobile} · {employee.email}</p></div><StatusBadge>{employee.status}</StatusBadge>{(onStatus||onEdit)&&<div className="tf-modal-actions">{onStatus&&<select value={employee.status} onChange={e=>onStatus(e.target.value as EmployeeStatus)} aria-label="Change employee status">{statuses.map(x=><option key={x}>{x}</option>)}</select>}{onEdit&&<button className="tf-primary" onClick={onEdit}><Edit3/> Edit Employee</button>}</div>}</div><div className="tf-tabs fe-tabs">{tabs.map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</div><div className="fe-360-content">
  {tab==='Overview'&&<><div className="fe-kpis"><Stat label="Assigned Customers" value={String(assigned.length)}/><Stat label="Assigned Products" value={String(employee.assignedProducts.length)}/><Stat label="Business Cases" value={String(business.length)}/><Stat label="Business Value" value={business.length?money(businessValue):'—'}/></div><Panel title="Employee Overview" subtitle="Core team record"><Info rows={[['Employee ID',employee.employeeId],['Full Name',fullName(employee)],['Mobile',employee.mobile],['Email',employee.email],['Joining Date',date(employee.joiningDate)],['Designation',employee.designation],['Department',employee.department],['Reporting Manager',manager?fullName(manager):'Not assigned'],['Employment Type',employee.employmentType],['Status',employee.status],['Platform Access','Not Enabled']]}/></Panel></>}
  {tab==='Employment'&&<div className="tf-modal-grid"><Panel title="Employment Details" subtitle="No payroll or attendance data"><Info rows={[['Designation',employee.designation],['Department',employee.department],['Primary Role',employee.role],['Employment Type',employee.employmentType],['Joining Date',date(employee.joiningDate)],['Probation End',date(employee.probationEndDate)],['Work Location',employee.workLocation||'—'],['Reporting Manager',manager?fullName(manager):'Not assigned'],['Status',employee.status]]}/></Panel><Panel title="Emergency Contact"><Info rows={[['Name',employee.emergencyContact.name||'—'],['Relationship',employee.emergencyContact.relationship||'—'],['Mobile',employee.emergencyContact.mobile||'—']]}/></Panel></div>}
  {tab==='Customers & Business'&&<><Panel title="Assigned Customers" subtitle="Operational assignment only"><DataTable headers={['Customer','Products','Relationship Value','Last Activity','']} empty={!assigned.length}>{assigned.map(customer=><tr key={customer.id}><td><b>{customer.name}</b><small>{customer.id}</small></td><td>{customer.products.join(', ')||'No products'}</td><td>{money(customer.relationshipValue)}</td><td>{customer.lastActivity}</td><td><button className="tf-text-btn" onClick={()=>onOpenCustomer(customer.id)}>Open Customer 360</button></td></tr>)}</DataTable></Panel>{business.length?<Panel title="Linked Business Contribution" subtitle="Based on matching business owner records"><Info rows={[['Applications / Cases',String(business.length)],['Business Value',money(businessValue)],['Revenue Contribution',money(business.reduce((sum,x)=>sum+x.earning,0))]]}/><div className="fe-product-breakdown">{groupBusiness(business).map(x=><div key={x.product}><span>{x.product}</span><b>{money(x.value)}</b></div>)}</div></Panel>:<div className="fe-business-empty"><WalletCards/><b>No business records are linked to this employee yet.</b><span>Business will appear only when a reliable owner match exists.</span></div>}</>}
  {tab==='Products'&&<Panel title="Assigned Products / Services" subtitle="Operational assignment, not a security permission"><div className="fe-product-cards">{employee.assignedProducts.map(product=><article key={product}><ShieldCheck/><b>{product}</b><small>Assigned</small></article>)}</div>{!employee.assignedProducts.length&&<div className="fe-business-empty">No products assigned.</div>}</Panel>}
  {tab==='Documents'&&<Panel title="Employee Documents" subtitle="File metadata only; no cloud storage is implied"><DataTable headers={['Document','File','Issue Date','Expiry Date','Status','Actions']} empty={!employee.documents.length}>{employee.documents.map(doc=><tr key={doc.id}><td><b>{doc.documentType}</b></td><td>{doc.file?.fileName||'No file selected'}</td><td>{date(doc.issueDate)}</td><td>{date(doc.expiryDate)}</td><td><StatusBadge>{doc.status}</StatusBadge></td><td><div className="fe-actions"><button className="tf-text-btn" onClick={()=>onToast(`${doc.documentType}: ${doc.file?.fileName||'metadata only'}`)}>View metadata</button>{onRemoveDocument&&<button className="tf-text-btn fe-remove" onClick={()=>onRemoveDocument(doc.id)}>Remove</button>}</div></td></tr>)}</DataTable></Panel>}
  {tab==='Activity'&&<Panel title="Employee Activity" subtitle="Simple local employee history"><div className="fe-activity">{employee.activity.map(item=><article key={item.id}><i/><div><b>{item.title}</b><p>{item.detail}</p><small>{item.timestamp}</small></div></article>)}</div></Panel>}
 </div></Modal>}

const blankAddress=():EmployeeAddress=>({line1:'',line2:'',city:'',state:'Gujarat',pinCode:'',country:'India'})
const blankDraft=(subFranchiseeId?:string):EmployeeDraft=>({franchiseeId:currentFranchiseeId,subFranchiseeId,employeeId:franchiseeEmployeeRepository.nextEmployeeId(),title:'Mr',firstName:'',middleName:'',lastName:'',mobile:'',alternateMobile:'',email:'',personalEmail:'',dateOfBirth:'',gender:'Prefer not to say',maritalStatus:'',bloodGroup:'',designation:'',department:'Sales',role:'Sales Executive',employmentType:'Full Time',joiningDate:'2026-09-07',probationEndDate:'',workLocation:'Ahmedabad Main Branch',status:'Active',reportingManagerId:'',assignedProducts:[],assignedCustomerIds:[],address:blankAddress(),permanentSame:true,emergencyContact:{name:'',relationship:'',mobile:''},pan:'',aadhaarAvailable:false,aadhaarNumber:'',drivingLicence:'',passport:'',documents:[],notes:''})
function draftFrom(employee:FranchiseeEmployee):EmployeeDraft{const {id:_,activity:__,createdAt:___,updatedAt:____,platformAccess:_____,...draft}=employee;return structuredClone(draft)}
const stepNames=['Personal Details','Contact & Address','Work Details','Business Lines','Documents','Review']
export function EmployeeForm({employee,employees,customers,products,subFranchiseeId,onClose,onSave}:{employee:FranchiseeEmployee|null;employees:FranchiseeEmployee[];customers:FranchiseeCustomer[];products:string[];subFranchiseeId?:string;onClose:()=>void;onSave:(draft:EmployeeDraft)=>void}){const [draft,setDraft]=useState<EmployeeDraft>(()=>employee?draftFrom(employee):blankDraft(subFranchiseeId)),[step,setStep]=useState(0),[error,setError]=useState('');const set=<K extends keyof EmployeeDraft>(key:K,value:EmployeeDraft[K])=>setDraft(current=>({...current,[key]:value}));const address=(key:keyof EmployeeAddress,value:string,permanent=false)=>set(permanent?'permanentAddress':'address',{...(permanent?(draft.permanentAddress||blankAddress()):draft.address),[key]:value});const go=(next:number)=>{const issue=next>step?validate(step,draft):'';if(issue){setError(issue);return}setError('');setStep(Math.max(0,Math.min(5,next)))};const submit=()=>{const issue=[0,1,2].map(x=>validate(x,draft)).find(Boolean);if(issue){setError(issue);return}onSave({...draft,franchiseeId:currentFranchiseeId,subFranchiseeId})};return <div className="fe-form-wrap"><button className="fe-form-scrim" onClick={onClose}/><aside className="fe-form"><header><div><span>EMPLOYEE</span><h2>{employee?'Edit Employee':'Add Employee'}</h2><p>{stepNames[step]} · Step {step+1} of 6</p></div><button onClick={onClose}><X/></button></header><div className="fe-stepper">{stepNames.map((name,index)=><button key={name} className={step===index?'active':step>index?'done':''} onClick={()=>go(index)}><i>{step>index?<Check/>:index+1}</i><span>{name}</span></button>)}</div><form onSubmit={e=>{e.preventDefault();submit()}}><div className="fe-form-scroll">
  {step===0&&<><Intro title="Personal Details" copy="Enter the employee's basic information."/><div className="fe-field-grid"><Field label="Employee Photo"><FileInput onChange={photo=>set('photo',photo)}/></Field><Field label="Employee ID"><input value={draft.employeeId} onChange={e=>set('employeeId',e.target.value)} /></Field><Field label="Title"><Select value={draft.title} set={v=>set('title',v)} options={['Mr','Mrs','Ms','Dr']}/></Field><Field label="First Name" required><input value={draft.firstName} onChange={e=>set('firstName',e.target.value)}/></Field><Field label="Middle Name"><input value={draft.middleName} onChange={e=>set('middleName',e.target.value)}/></Field><Field label="Last Name" required><input value={draft.lastName} onChange={e=>set('lastName',e.target.value)}/></Field><Field label="Date of Birth"><input type="date" value={draft.dateOfBirth} onChange={e=>set('dateOfBirth',e.target.value)}/></Field><Field label="Gender"><Select value={draft.gender} set={v=>set('gender',v)} options={['Male','Female','Other','Prefer not to say']}/></Field><Field label="Marital Status"><Select value={draft.maritalStatus} set={v=>set('maritalStatus',v)} options={['Single','Married','Other']}/></Field><Field label="Blood Group"><Select value={draft.bloodGroup} set={v=>set('bloodGroup',v)} options={['A+','A-','B+','B-','AB+','AB-','O+','O-']}/></Field><Field label="Joining Date" required><input type="date" value={draft.joiningDate} onChange={e=>set('joiningDate',e.target.value)}/></Field><Field label="Status"><Select value={draft.status} set={v=>set('status',v as EmployeeStatus)} options={statuses}/></Field></div></>}
  {step===1&&<><Intro title="Contact & Address" copy="Capture work contact details, address and emergency contact."/><div className="fe-field-grid"><Field label="Primary Mobile" required><input value={draft.mobile} onChange={e=>set('mobile',e.target.value)}/></Field><Field label="Alternate Mobile"><input value={draft.alternateMobile} onChange={e=>set('alternateMobile',e.target.value)}/></Field><Field label="Work Email" required><input type="email" value={draft.email} onChange={e=>set('email',e.target.value)}/></Field><Field label="Personal Email"><input type="email" value={draft.personalEmail} onChange={e=>set('personalEmail',e.target.value)}/></Field></div><AddressForm title="Current Address" value={draft.address} set={(key,value)=>address(key,value)}/><label className="fe-check"><input type="checkbox" checked={draft.permanentSame} onChange={e=>set('permanentSame',e.target.checked)}/> Permanent address same as current</label>{!draft.permanentSame&&<AddressForm title="Permanent Address" value={draft.permanentAddress||blankAddress()} set={(key,value)=>address(key,value,true)}/>}<fieldset><legend>Emergency Contact</legend><div className="fe-field-grid"><Field label="Name"><input value={draft.emergencyContact.name} onChange={e=>set('emergencyContact',{...draft.emergencyContact,name:e.target.value})}/></Field><Field label="Relationship"><input value={draft.emergencyContact.relationship} onChange={e=>set('emergencyContact',{...draft.emergencyContact,relationship:e.target.value})}/></Field><Field label="Mobile"><input value={draft.emergencyContact.mobile} onChange={e=>set('emergencyContact',{...draft.emergencyContact,mobile:e.target.value})}/></Field></div></fieldset></>}
  {step===2&&<><Intro title="Work Details" copy="Enter the employee's role and joining details."/><div className="fe-field-grid"><Field label="Designation" required><input value={draft.designation} onChange={e=>set('designation',e.target.value)}/></Field><Field label="Department" required><Select value={draft.department} set={v=>set('department',v)} options={employeeDepartments}/></Field><Field label="Employment Type"><Select value={draft.employmentType} set={v=>set('employmentType',v)} options={['Full Time','Part Time','Contract','Intern','Consultant']}/></Field><Field label="Joining Date" required><input type="date" value={draft.joiningDate} onChange={e=>set('joiningDate',e.target.value)}/></Field><Field label="Probation End Date"><input type="date" value={draft.probationEndDate} onChange={e=>set('probationEndDate',e.target.value)}/></Field><Field label="Work Location / Branch"><input value={draft.workLocation} onChange={e=>set('workLocation',e.target.value)}/></Field><Field label="Reporting To"><Select value={draft.reportingManagerId} set={v=>set('reportingManagerId',v)} options={employees.filter(x=>x.id!==employee?.id).map(x=>x.id)} labels={Object.fromEntries(employees.map(x=>[x.id,fullName(x)]))}/></Field><Field label="Status"><Select value={draft.status} set={v=>set('status',v as EmployeeStatus)} options={statuses}/></Field></div></>}
  {step===3&&<><Intro title="Business Lines" copy="Choose the work this employee will handle."/><div className="fe-field-grid"><Field label="Role"><Select value={draft.role} set={v=>set('role',v)} options={employeeRoles}/></Field><Field label="Department"><Select value={draft.department} set={v=>set('department',v)} options={employeeDepartments}/></Field><Field label="Reporting To"><Select value={draft.reportingManagerId} set={v=>set('reportingManagerId',v)} options={employees.filter(x=>x.id!==employee?.id).map(x=>x.id)} labels={Object.fromEntries(employees.map(x=>[x.id,fullName(x)]))}/></Field><Field label="Login / Access"><input disabled value="Not Enabled"/></Field></div><fieldset><legend>Business Lines</legend><Multi items={unique([...employeeProductOptions,...products])} selected={draft.assignedProducts} set={value=>set('assignedProducts',value)}/></fieldset><fieldset><legend>Customers <small>Optional</small></legend><Multi items={customers.map(x=>x.id)} labels={Object.fromEntries(customers.map(x=>[x.id,`${x.name} · ${x.id}`]))} selected={draft.assignedCustomerIds} set={value=>set('assignedCustomerIds',value)}/></fieldset></>}
  {step===4&&<KycDocuments draft={draft} set={set}/>} {step===5&&<Review draft={draft} employees={employees} customers={customers} edit={setStep}/>} {error&&<p className="fe-error"><AlertTriangle/>{error}</p>}
 </div><footer><button type="button" className="tf-secondary" onClick={()=>step?go(step-1):onClose()}><ArrowLeft/> {step?'Previous':'Cancel'}</button><span/>{step<5?<button type="button" className="tf-primary" onClick={()=>go(step+1)}>Continue <ArrowRight/></button>:<button className="tf-primary"><Save/> {employee?'Save Employee':'Create Employee'}</button>}</footer></form></aside></div>}

export function EmployeeCreatePage({employees,customers,products,subFranchiseeId,onClose,onSave,contextLabel}:{employees:FranchiseeEmployee[];customers:FranchiseeCustomer[];products:string[];subFranchiseeId?:string;onClose:()=>void;onSave:(draft:EmployeeDraft)=>void;contextLabel?:string}){
  const [draft,setDraft]=useState<EmployeeDraft>(()=>blankDraft(subFranchiseeId)),[activeSection,setActiveSection]=useState(0),[error,setError]=useState(''),[submitted,setSubmitted]=useState(false)
  const set=<K extends keyof EmployeeDraft>(key:K,value:EmployeeDraft[K])=>setDraft(current=>({...current,[key]:value}))
  const address=(key:keyof EmployeeAddress,value:string,permanent=false)=>set(permanent?'permanentAddress':'address',{...(permanent?(draft.permanentAddress||blankAddress()):draft.address),[key]:value})
  const submit=()=>{setSubmitted(true);const invalid=[0,1,2].filter(index=>Boolean(validate(index,draft)));if(invalid.length){setError(validate(invalid[0],draft));document.getElementById(invalid[0]===0?'fe-create-basic':'fe-create-essentials')?.scrollIntoView({behavior:'smooth',block:'start'});return}setError('');onSave({...draft,franchiseeId:currentFranchiseeId,subFranchiseeId})}
  const edit=(step:number)=>{if(step===0||step===2){document.getElementById(step===0?'fe-create-basic':'fe-create-essentials')?.scrollIntoView({behavior:'smooth',block:'start'});return}setActiveSection(step===1?0:step===3?1:2)}
  const sections=[['Address & Emergency',UsersRound],['Business Lines',WalletCards],['KYC & Documents',ShieldCheck],['Review',Check]] as const
  return <div className="fe-add-page"><button type="button" className="fe-add-back" onClick={onClose}><ArrowLeft/> Back to Employees</button><header className="fe-add-header"><div><span>FRANCHISE TEAM</span><h1>Add Employee</h1><p>Create a new employee and configure their work details and access.{contextLabel?` Adding employee for ${contextLabel}.`:''}</p></div><b>{draft.employeeId}</b></header><form className="fe-add-form" onSubmit={event=>{event.preventDefault();submit()}}>
    <section id="fe-create-basic" className={`fe-add-panel ${submitted&&validate(0,draft)?'error':''}`}><Intro title="Basic Information" copy="Enter the employee's basic information."/><div className="fe-field-grid"><Field label="Employee Photo"><FileInput onChange={photo=>set('photo',photo)}/></Field><Field label="Employee ID"><input value={draft.employeeId} onChange={event=>set('employeeId',event.target.value)}/></Field><Field label="Title"><Select value={draft.title} set={value=>set('title',value)} options={['Mr','Mrs','Ms','Dr']}/></Field><Field label="First Name" required><input value={draft.firstName} onChange={event=>set('firstName',event.target.value)}/></Field><Field label="Middle Name"><input value={draft.middleName} onChange={event=>set('middleName',event.target.value)}/></Field><Field label="Last Name" required><input value={draft.lastName} onChange={event=>set('lastName',event.target.value)}/></Field><Field label="Date of Birth"><input type="date" value={draft.dateOfBirth} onChange={event=>set('dateOfBirth',event.target.value)}/></Field><Field label="Gender"><Select value={draft.gender} set={value=>set('gender',value)} options={['Male','Female','Other','Prefer not to say']}/></Field><Field label="Marital Status"><Select value={draft.maritalStatus} set={value=>set('maritalStatus',value)} options={['Single','Married','Other']}/></Field><Field label="Blood Group"><Select value={draft.bloodGroup} set={value=>set('bloodGroup',value)} options={['A+','A-','B+','B-','AB+','AB-','O+','O-']}/></Field><Field label="Joining Date" required><input type="date" value={draft.joiningDate} onChange={event=>set('joiningDate',event.target.value)}/></Field><Field label="Status"><Select value={draft.status} set={value=>set('status',value as EmployeeStatus)} options={statuses}/></Field></div></section>
    <section id="fe-create-essentials" className={`fe-add-panel ${submitted&&(validate(1,draft)||validate(2,draft))?'error':''}`}><Intro title="Contact & Work Information" copy="Capture contact details and the employee's role in the franchise."/><div className="fe-field-grid"><Field label="Primary Mobile" required><input value={draft.mobile} onChange={event=>set('mobile',event.target.value)}/></Field><Field label="Alternate Mobile"><input value={draft.alternateMobile} onChange={event=>set('alternateMobile',event.target.value)}/></Field><Field label="Work Email" required><input type="email" value={draft.email} onChange={event=>set('email',event.target.value)}/></Field><Field label="Personal Email"><input type="email" value={draft.personalEmail} onChange={event=>set('personalEmail',event.target.value)}/></Field><Field label="Designation" required><input value={draft.designation} onChange={event=>set('designation',event.target.value)}/></Field><Field label="Department" required><Select value={draft.department} set={value=>set('department',value)} options={employeeDepartments}/></Field><Field label="Employment Type"><Select value={draft.employmentType} set={value=>set('employmentType',value)} options={['Full Time','Part Time','Contract','Intern','Consultant']}/></Field><Field label="Probation End Date"><input type="date" value={draft.probationEndDate} onChange={event=>set('probationEndDate',event.target.value)}/></Field><Field label="Work Location / Branch"><input value={draft.workLocation} onChange={event=>set('workLocation',event.target.value)}/></Field><Field label="Reporting To"><Select value={draft.reportingManagerId} set={value=>set('reportingManagerId',value)} options={employees.map(employee=>employee.id)} labels={Object.fromEntries(employees.map(employee=>[employee.id,fullName(employee)]))}/></Field></div></section>
    <div className="fe-additional-heading"><span>ADDITIONAL INFORMATION</span><h2>Select a section to continue</h2><p>Only one additional section opens at a time. Your entered information is retained when switching.</p></div><nav className="fe-section-selector" aria-label="Additional employee information">{sections.map(([name,Icon],index)=>{const status=employeeSectionStatus(index,draft,submitted);return <button type="button" key={name} className={`${activeSection===index?'active ':''}${status.tone}`} aria-pressed={activeSection===index} onClick={()=>{setActiveSection(index);setError('')}}><Icon/><b>{name}</b><small>{status.label}</small></button>})}</nav>
    <section className="fe-add-panel fe-add-active">{activeSection===0?<><Intro title="Address & Emergency Contact" copy="Capture address and emergency contact details."/><AddressForm title="Current Address" value={draft.address} set={(key,value)=>address(key,value)}/><label className="fe-check"><input type="checkbox" checked={draft.permanentSame} onChange={event=>set('permanentSame',event.target.checked)}/> Permanent address same as current</label>{!draft.permanentSame&&<AddressForm title="Permanent Address" value={draft.permanentAddress||blankAddress()} set={(key,value)=>address(key,value,true)}/>}<fieldset><legend>Emergency Contact</legend><div className="fe-field-grid"><Field label="Name"><input value={draft.emergencyContact.name} onChange={event=>set('emergencyContact',{...draft.emergencyContact,name:event.target.value})}/></Field><Field label="Relationship"><input value={draft.emergencyContact.relationship} onChange={event=>set('emergencyContact',{...draft.emergencyContact,relationship:event.target.value})}/></Field><Field label="Mobile"><input value={draft.emergencyContact.mobile} onChange={event=>set('emergencyContact',{...draft.emergencyContact,mobile:event.target.value})}/></Field></div></fieldset></>:activeSection===1?<><Intro title="Business Lines" copy="Choose the work this employee will handle."/><div className="fe-field-grid"><Field label="Role"><Select value={draft.role} set={value=>set('role',value)} options={employeeRoles}/></Field><Field label="Department"><Select value={draft.department} set={value=>set('department',value)} options={employeeDepartments}/></Field><Field label="Reporting To"><Select value={draft.reportingManagerId} set={value=>set('reportingManagerId',value)} options={employees.map(employee=>employee.id)} labels={Object.fromEntries(employees.map(employee=>[employee.id,fullName(employee)]))}/></Field><Field label="Login / Access"><input disabled value="Not Enabled"/></Field></div><fieldset><legend>Business Lines</legend><Multi items={unique([...employeeProductOptions,...products])} selected={draft.assignedProducts} set={value=>set('assignedProducts',value)}/></fieldset><fieldset><legend>Customers <small>Optional</small></legend><Multi items={customers.map(customer=>customer.id)} labels={Object.fromEntries(customers.map(customer=>[customer.id,`${customer.name} · ${customer.id}`]))} selected={draft.assignedCustomerIds} set={value=>set('assignedCustomerIds',value)}/></fieldset></>:activeSection===2?<KycDocuments draft={draft} set={set}/>:<Review draft={draft} employees={employees} customers={customers} edit={edit}/>}</section>
    {error&&<p className="fe-error" role="alert"><AlertTriangle/>{error}</p>}<footer className="fe-add-actions"><button type="button" className="tf-secondary" onClick={onClose}>Cancel</button><button className="tf-primary"><Save/> Create Employee</button></footer>
  </form></div>
}

function employeeSectionStatus(index:number,draft:EmployeeDraft,submitted:boolean):{label:string;tone:'neutral'|'progress'|'complete'|'error'}{if(index===0){const started=Boolean(draft.address.line1||draft.address.city||draft.address.pinCode||draft.emergencyContact.name||draft.emergencyContact.mobile);return started?{label:'Complete',tone:'complete'}:{label:'Not started',tone:'neutral'}}if(index===1){const count=draft.assignedProducts.length+draft.assignedCustomerIds.length;return count?{label:`${count} assigned`,tone:'complete'}:{label:'Not started',tone:'neutral'}}if(index===2){const uploaded=draft.documents.filter(document=>document.file).length,started=Boolean(draft.pan||draft.aadhaarNumber||draft.drivingLicence||draft.passport||draft.documents.length);return started?{label:uploaded?`${uploaded} uploaded`:'In progress',tone:uploaded?'complete':'progress'}:{label:'Not started',tone:'neutral'}}const ready=[0,1,2].every(step=>!validate(step,draft));return ready?{label:'Ready',tone:'complete'}:{label:'Needs attention',tone:submitted?'error':'progress'}}

function KycDocuments({draft,set}:{draft:EmployeeDraft;set:<K extends keyof EmployeeDraft>(key:K,value:EmployeeDraft[K])=>void}){const update=(doc:EmployeeDocument,key:keyof EmployeeDocument,value:unknown)=>set('documents',draft.documents.map(x=>x.id===doc.id?{...x,[key]:value}:x));return <><Intro title="KYC & Documents" copy="Only local file metadata is retained in this frontend prototype."/><div className="fe-field-grid"><Field label="PAN"><input value={draft.pan} onChange={e=>set('pan',e.target.value.toUpperCase())}/></Field><Field label="Aadhaar Available"><Select value={draft.aadhaarAvailable?'Yes':'No'} set={v=>set('aadhaarAvailable',v==='Yes')} options={['Yes','No']}/></Field>{draft.aadhaarAvailable&&<Field label="Aadhaar Number"><input value={draft.aadhaarNumber} onChange={e=>set('aadhaarNumber',e.target.value)} placeholder="Masked in Employee 360"/></Field>}<Field label="Driving Licence"><input value={draft.drivingLicence} onChange={e=>set('drivingLicence',e.target.value)}/></Field><Field label="Passport"><input value={draft.passport} onChange={e=>set('passport',e.target.value)}/></Field></div><div className="fe-repeat-head"><div><h4>Employee Documents</h4><small>File metadata only</small></div><button type="button" className="tf-secondary" onClick={()=>set('documents',[...draft.documents,{id:crypto.randomUUID(),documentType:'PAN Card',status:'Pending'}])}><Plus/> Add Document</button></div>{draft.documents.map(doc=><div className="fe-document-card" key={doc.id}><div className="fe-field-grid"><Field label="Document Type"><Select value={doc.documentType} set={v=>update(doc,'documentType',v)} options={employeeDocumentTypes}/></Field><Field label="Document Number"><input value={doc.documentNumber||''} onChange={e=>update(doc,'documentNumber',e.target.value)}/></Field><Field label="Issue Date"><input type="date" value={doc.issueDate||''} onChange={e=>update(doc,'issueDate',e.target.value)}/></Field><Field label="Expiry Date"><input type="date" value={doc.expiryDate||''} onChange={e=>update(doc,'expiryDate',e.target.value)}/></Field><Field label="File"><FileInput onChange={file=>{update(doc,'file',file);if(file)update(doc,'status','Uploaded')}}/></Field><Field label="Status"><Select value={doc.status} set={v=>update(doc,'status',v)} options={['Uploaded','Pending','Verified','Expired']}/></Field><Field label="Remarks" wide><input value={doc.remarks||''} onChange={e=>update(doc,'remarks',e.target.value)}/></Field></div><button type="button" onClick={()=>set('documents',draft.documents.filter(x=>x.id!==doc.id))}><Trash2/> Remove</button></div>)}</>}
function Review({draft,employees,customers,edit}:{draft:EmployeeDraft;employees:FranchiseeEmployee[];customers:FranchiseeCustomer[];edit:(step:number)=>void}){const manager=employees.find(x=>x.id===draft.reportingManagerId),sections:[string,number,string][]=[['Basic Details',0,`${draft.title} ${draft.firstName} ${draft.lastName} · ${draft.employeeId}`],['Contact',1,`${draft.mobile} · ${draft.email} · ${draft.address.city}`],['Employment',2,`${draft.designation} · ${draft.department} · ${draft.status}`],['Role & Assignments',3,`${draft.role} · ${draft.assignedProducts.length} products · ${draft.assignedCustomerIds.length} customers · ${manager?fullName(manager):'No manager'}`],['Documents',4,`${draft.documents.length} documents · PAN ${draft.pan?'available':'not recorded'}`]];return <><Intro title="Review Employee" copy="Confirm the employee master record before saving."/><div className="fe-review">{sections.map(([title,index,value])=><article key={title}><div><b>{title}</b><p>{value}</p></div><button type="button" onClick={()=>edit(index)}>Edit</button></article>)}</div><div className="fe-security"><ShieldCheck/><span><b>No login will be created</b> This is an employee master record only. Assigned customers: {customers.filter(x=>draft.assignedCustomerIds.includes(x.id)).map(x=>x.name).join(', ')||'None'}.</span></div></>}

function Intro({title,copy}:{title:string;copy:string}){return <div className="fe-intro"><h3>{title}</h3><p>{copy}</p></div>}
function Field({label,required,wide,children}:{label:string;required?:boolean;wide?:boolean;children:ReactNode}){return <label className={wide?'wide':''}>{label}{required&&<sup>*</sup>}{children}</label>}
function Select({value,set,options,labels}:{value:string|undefined;set:(value:string)=>void;options:string[];labels?:Record<string,string>}){return <select value={value||''} onChange={e=>set(e.target.value)}><option value="">Select</option>{options.map(item=><option key={item} value={item}>{labels?.[item]||item}</option>)}</select>}
function Multi({items,selected,set,labels}:{items:string[];selected:string[];set:(values:string[])=>void;labels?:Record<string,string>}){return <div className="fe-multi">{items.map(item=><label key={item}><input type="checkbox" checked={selected.includes(item)} onChange={()=>set(selected.includes(item)?selected.filter(x=>x!==item):[...selected,item])}/><span>{labels?.[item]||item}</span></label>)}</div>}
function FileInput({onChange}:{onChange:(file?:EmployeeFileMetadata)=>void}){return <input type="file" onChange={(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];onChange(file?{fileName:file.name,fileSize:file.size,fileType:file.type||'file',uploadedAt:new Date().toISOString()}:undefined)}}/>}
function AddressForm({title,value,set}:{title:string;value:EmployeeAddress;set:(key:keyof EmployeeAddress,value:string)=>void}){return <fieldset><legend>{title}</legend><div className="fe-field-grid"><Field label="Address Line 1" wide><input value={value.line1} onChange={e=>set('line1',e.target.value)}/></Field><Field label="Address Line 2"><input value={value.line2||''} onChange={e=>set('line2',e.target.value)}/></Field><Field label="City"><input value={value.city} onChange={e=>set('city',e.target.value)}/></Field><Field label="State"><input value={value.state} onChange={e=>set('state',e.target.value)}/></Field><Field label="PIN Code"><input value={value.pinCode} onChange={e=>set('pinCode',e.target.value)}/></Field><Field label="Country"><input value={value.country} onChange={e=>set('country',e.target.value)}/></Field></div></fieldset>}
function Stat({label,value}:{label:string;value:string}){return <article><span>{label}</span><b>{value}</b></article>}
function Info({rows}:{rows:[string,string][]}){return <div className="fe-info">{rows.map(([label,value])=><div key={label}><span>{label}</span><b>{value||'—'}</b></div>)}</div>}
function CompactList({values}:{values:string[]}){return <><b>{values.slice(0,2).join(', ')||'None'}</b>{values.length>2&&<small>+{values.length-2} more</small>}</>}
function groupBusiness(rows:RevenueRow[]){return Object.entries(rows.reduce<Record<string,number>>((map,row)=>({...map,[row.product]:(map[row.product]||0)+row.business}),{})).map(([product,value])=>({product,value})).sort((a,b)=>b.value-a.value)}
function validate(step:number,draft:EmployeeDraft){if(step===0&&(!draft.firstName.trim()||!draft.lastName.trim()||!draft.joiningDate||!draft.employeeId.trim()))return 'Enter first name, last name, employee ID and joining date.';if(step===1&&(!draft.mobile.trim()||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(draft.email)))return 'Enter a primary mobile number and valid work email.';if(step===2&&(!draft.designation.trim()||!draft.department||!draft.joiningDate))return 'Enter designation, department and joining date.';return ''}
function fullName(employee:Pick<FranchiseeEmployee,'firstName'|'middleName'|'lastName'>){return [employee.firstName,employee.middleName,employee.lastName].filter(Boolean).join(' ')}
function initials(employee:Pick<FranchiseeEmployee,'firstName'|'lastName'>){return `${employee.firstName[0]||''}${employee.lastName[0]||''}`.toUpperCase()}
function date(value?:string){return value?new Date(`${value}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—'}
function unique<T>(values:T[]){return [...new Set(values)]}
