import { Download, Eye, Megaphone, Plus } from 'lucide-react'
import { useMemo, useState } from 'react'
import type { MarketingAsset } from '../types'
import { FilterSelect, Filters, Modal, Panel, StatusBadge, PageHeader } from '../components/FranchiseeUI'

export function MarketingPage({assets,onRequest,onToast}:{assets:MarketingAsset[];onRequest:(campaign:string,description:string)=>void;onToast:(s:string)=>void}){
 const [search,setSearch]=useState(''),[format,setFormat]=useState('All formats'),[request,setRequest]=useState(false)
 const rows=useMemo(()=>assets.filter(a=>(format==='All formats'||a.format===format)&&`${a.title} ${a.product} ${a.campaign}`.toLowerCase().includes(search.toLowerCase())),[assets,format,search])
 return <><PageHeader eyebrow="HO MARKETING" title="Marketing Centre" description="Use ready-to-share collateral or request locally tailored and co-branded campaign material." actions={<button className="tf-primary" onClick={()=>setRequest(true)}><Plus/> Customisation request</button>}/>
 <Panel title="Marketing Material Library" subtitle="Ready material is self-service; custom work routes to HO Marketing"><Filters search={search} onSearch={setSearch}><FilterSelect label="Format" value={format} onChange={setFormat} options={['All formats','PDF','PNG','PPTX']}/></Filters><div className="tf-asset-grid">{rows.map(asset=><article key={asset.id}><div className="tf-asset-preview"><Megaphone/><span>{asset.format}</span></div><small>{asset.product} · {asset.category}</small><h3>{asset.title}</h3><p>Campaign: {asset.campaign}</p><div><button className="tf-secondary" onClick={()=>onToast(`${asset.title} opened in preview`)}><Eye/> Preview</button><button className="tf-primary" onClick={()=>onToast(`${asset.title} prepared for download`)}><Download/> Download</button></div></article>)}</div></Panel>
 <Panel title="Recent customisation requests" subtitle="Requests remain tracked as an HO Marketing thread"><div className="tf-handler-list"><div><i className="violet"/><span><b>Ahmedabad Home Festival co-branding</b><small>MR-208 · Routed to HO Marketing · In Progress</small></span><StatusBadge>In Progress</StatusBadge></div><div><i className="green"/><span><b>Health camp WhatsApp creative</b><small>MR-194 · Delivered 28 Aug 2026</small></span><StatusBadge>Completed</StatusBadge></div></div></Panel>
 {request&&<Modal title="Campaign / Customisation Request" subtitle="Submission creates a trackable thread owned by HO Marketing." onClose={()=>setRequest(false)}><form className="tf-form" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);onRequest(String(fd.get('campaign')),String(fd.get('description')));setRequest(false)}}><div className="tf-form-row"><label>Request type<select name="type"><option>Co-branded material</option><option>Local campaign material</option><option>Custom requirement</option></select></label><label>Campaign / product<input name="campaign" required/></label></div><label>Description<textarea name="description" required placeholder="Audience, message, channel, size, language, and brand requirements"/></label><div className="tf-form-row"><label>Needed by<input type="date" required/></label><label>Reference attachment<button type="button" className="tf-upload">Select reference</button></label></div><div className="tf-note">Status after submission: Routed to HO Marketing. Delivery will return through the same ticket thread.</div><div className="tf-form-actions"><button type="button" className="tf-secondary" onClick={()=>setRequest(false)}>Cancel</button><button className="tf-primary">Submit request</button></div></form></Modal>}</>
}
