import { Award, Download, FileText, GitCompareArrows, ShoppingBag } from 'lucide-react'
import { useMemo, useState } from 'react'
import type { ProductMapping, FranchiseeProduct } from '../types'
import { FilterSelect, Filters, Modal, Panel, StatusBadge, PageHeader } from '../components/FranchiseeUI'

export function ProductsPage({products,mappings,onApply,onToast}:{products:FranchiseeProduct[];mappings:ProductMapping[];onApply:(p:FranchiseeProduct)=>void;onToast:(s:string)=>void}){
  const [search,setSearch]=useState(''),[category,setCategory]=useState('All categories'),[selected,setSelected]=useState<FranchiseeProduct>(),[compare,setCompare]=useState<string[]>([])
  const rows=useMemo(()=>products.filter(p=>(category==='All categories'||p.category===category)&&`${p.name} ${p.description}`.toLowerCase().includes(search.toLowerCase())),[products,category,search])
  return <><PageHeader eyebrow="PRODUCT ENABLEMENT" title="Products & Services" description="Browse all 18 mapped products, eligibility, payout structures, documents, and certification gates." actions={compare.length?<button className="tf-primary" onClick={()=>onToast(`Comparing ${compare.length} products in the current workspace`)}><GitCompareArrows/> Compare ({compare.length})</button>:undefined}/>
    <Panel title="Product catalog" subtitle={`${rows.length} products available in this product catalog`}><Filters search={search} onSearch={setSearch}><FilterSelect label="Category" value={category} onChange={setCategory} options={['All categories','Insurance','Loans','Loan Protector','Investment & Wealth']}/></Filters><div className="tf-product-grid">{rows.map(product=>{const mapping=mappings.find(m=>m.productId===product.id);return <article key={product.id}><div className="tf-product-top"><span><FileText/></span><StatusBadge>{mapping?.enabled?'Enabled':'Disabled'}</StatusBadge></div><small>{product.category}</small><h3>{product.name}</h3><p>{product.description}</p><dl><div><dt>Eligibility</dt><dd>{product.eligibility}</dd></div><div><dt>Applicable payout</dt><dd>{product.commission}</dd></div></dl>{product.certification&&<div className="tf-cert-line"><Award/> Certification: <b>{mapping?.certified?'Passed':'Required'}</b></div>}<div className="tf-card-actions"><label><input type="checkbox" checked={compare.includes(product.id)} onChange={e=>setCompare(c=>e.target.checked?[...c,product.id]:c.filter(id=>id!==product.id))}/> Compare</label><button className="tf-text-btn" onClick={()=>setSelected(product)}>View detail</button><button className="tf-primary" disabled={!mapping?.enabled||!mapping.certified&&product.certification} onClick={()=>onApply(product)}><ShoppingBag/> Apply</button></div></article>})}</div></Panel>
    {selected&&<Modal title={selected.name} subtitle={selected.category} onClose={()=>setSelected(undefined)}><div className="tf-360-head"><div><span>Applicable commission / payout</span><strong>{selected.commission}</strong><small>Configured by HO; read-only for franchise</small></div><StatusBadge>{mappings.find(m=>m.productId===selected.id)?.empanelment||'Pending'}</StatusBadge><div className="tf-modal-actions"><button className="tf-secondary" onClick={()=>onToast(`${selected.name} brochure prepared for download`)}><Download/> Brochure</button><button className="tf-primary" onClick={()=>onApply(selected)}><ShoppingBag/> Buy / Apply</button></div></div><div className="tf-modal-grid"><Panel title="Terms & eligibility"><p>{selected.description}</p><ul className="tf-bullet-list"><li>{selected.eligibility}</li><li>Product suitability and partner underwriting apply.</li><li>Final terms are confirmed by the product provider.</li></ul></Panel><Panel title="Required documents"><ul className="tf-bullet-list">{selected.documents.map(d=><li key={d}>{d}</li>)}</ul>{selected.certification&&<div className="tf-note">Certification prerequisite: {mappings.find(m=>m.productId===selected.id)?.certified?'Completed':'Complete the assessment in Training & Knowledge before selling.'}</div>}</Panel><Panel title="Frequently asked questions" className="tf-span-2"><div className="tf-faq">{selected.faqs.map(q=><details key={q}><summary>{q}</summary><p>Refer to the current product note and provider terms available in the marketing collateral.</p></details>)}</div></Panel></div></Modal>}</>
}
