import { BadgeCheck, Building2, Download, Landmark, Plus, ShieldCheck, UserCog } from 'lucide-react'
import { useState } from 'react'
import type { ProductMapping, FranchiseeProduct } from '../types'
import { DataTable, Modal, Panel, StatusBadge, PageHeader } from '../components/FranchiseeUI'

export function ProfilePage({products,mappings,onToast}:{products:FranchiseeProduct[];mappings:ProductMapping[];onToast:(s:string)=>void}){
 const [userModal,setUserModal]=useState(false),[bankModal,setBankModal]=useState(false)
 const team=[['Nisha Patel','Franchise Principal','Full franchise ceiling','Active'],['Rahul Shah','Relationship Executive','Customers, CRM, Applications','Active'],['Aditi Rao','Service Coordinator','Customers, Support, Documents','Active']]
 return <><PageHeader eyebrow="FRANCHISE IDENTITY" title="My Franchise Profile" description="Registration, compliance, team permissions, bank details, and controlled update requests."/>
  <div className="tf-metrics tf-profile-summary"><div className="tf-profile-card"><span>TM</span><div><small>FRANCHISE ID · FR-GJ-0418</small><h2>Troth Meridian Financial Services</h2><p>Ahmedabad, Gujarat · Mapped RM: Rohan Mehta</p></div><StatusBadge tone="green">Active</StatusBadge></div><div><ShieldCheck/><span><b>KYC & Compliance</b><small>Verified · Next review 30 Apr 2027</small></span></div><div><BadgeCheck/><span><b>Empanelment</b><small>{mappings.filter(m=>m.empanelment==='Active').length} of {products.length} products active</small></span></div></div>
  <div className="tf-grid tf-grid-2"><Panel title="Profile & KYC" subtitle="Changes require HO Admin / Compliance approval"><dl className="tf-detail-list"><div><dt>Legal name</dt><dd>Troth Meridian Financial Services</dd></div><div><dt>Registration type</dt><dd>Individual Franchise · REG/GJ/4182</dd></div><div><dt>Primary contact</dt><dd>Nisha Patel · +91 98240 44018</dd></div><div><dt>Mapped RM</dt><dd>Rohan Mehta · West Region</dd></div><div><dt>Registered address</dt><dd>Prahlad Nagar, Ahmedabad, Gujarat 380015</dd></div></dl><button className="tf-secondary tf-full" onClick={()=>onToast('Profile update request created — Pending HO Admin / Compliance Approval')}><Building2/> Request profile update</button></Panel><Panel title="Compliance documents"><div className="tf-documents"><div><span className="tf-doc-icon">PDF</span><b>Franchise Agreement</b><StatusBadge>Verified</StatusBadge><button className="tf-text-btn">Download</button></div><div><span className="tf-doc-icon">PDF</span><b>PAN & GST registration</b><StatusBadge>Verified</StatusBadge><button className="tf-text-btn">View</button></div><div><span className="tf-doc-icon">PDF</span><b>Annual compliance declaration</b><StatusBadge>Received</StatusBadge><button className="tf-text-btn">View</button></div></div><div className="tf-note">Update requests are routed to HO Admin / Compliance. Existing approved data stays effective until review completes.</div></Panel></div>
  <Panel title="Team / User Management" subtitle="Franchise Principal may assign permissions only within the approved ceiling" action={<button className="tf-primary" onClick={()=>setUserModal(true)}><Plus/> Add team member</button>}><DataTable headers={['Team member','Role','Permissions','Status','']}><>{team.map(([name,role,permissions,status])=><tr key={name}><td><b>{name}</b><small>{name.toLowerCase().replace(' ','.')}@example.in</small></td><td>{role}</td><td>{permissions}</td><td><StatusBadge>{status}</StatusBadge></td><td><button className="tf-text-btn" onClick={()=>onToast(`Permission editor opened for ${name}`)}>Manage</button></td></tr>)}</></DataTable></Panel>
  <Panel title="Bank & Payout Details" subtitle="Current approved destination for brokerage and commission"><div className="tf-bank"><Landmark/><div><small>ACCOUNT HOLDER</small><b>Troth Meridian Financial Services</b><span>HDFC Bank · •••• 4821 · IFSC HDFC0000418</span></div><div><small>VERIFICATION</small><StatusBadge tone="green">Compliance verified</StatusBadge></div><button className="tf-secondary" onClick={()=>setBankModal(true)}>Request bank-detail change</button><button className="tf-text-btn" onClick={()=>onToast('Agreement prepared for download')}><Download/> Agreements</button></div></Panel>
  {userModal&&<Modal title="Add team member" subtitle="Permissions cannot exceed the Franchise Principal’s approved ceiling." onClose={()=>setUserModal(false)}><form className="tf-form" onSubmit={e=>{e.preventDefault();setUserModal(false);onToast('Team member invited within approved permission ceiling')}}><div className="tf-form-row"><label>Name<input required/></label><label>Email<input type="email" required/></label></div><label>Role<select><option>Relationship Executive</option><option>Service Coordinator</option><option>Sales Manager</option></select></label><fieldset><legend>Permissions</legend><label><input type="checkbox"/> Customers & CRM</label><label><input type="checkbox"/> Create applications</label><label><input type="checkbox"/> View revenue</label><label><input type="checkbox"/> Transaction approval <small>Requires HO Admin Approval</small></label></fieldset><div className="tf-form-actions"><button type="button" className="tf-secondary" onClick={()=>setUserModal(false)}>Cancel</button><button className="tf-primary"><UserCog/> Invite user</button></div></form></Modal>}
  {bankModal&&<Modal title="Request bank-detail change" subtitle="The current account remains active during verification." onClose={()=>setBankModal(false)}><form className="tf-form" onSubmit={e=>{e.preventDefault();setBankModal(false);onToast('Bank change request created — Pending Compliance Verification')}}><label>Account holder<input required/></label><div className="tf-form-row"><label>Account number<input required/></label><label>IFSC<input required/></label></div><label>Cancelled cheque<button type="button" className="tf-upload">Select document</button></label><div className="tf-note">Status after submission: Pending Compliance Verification.</div><div className="tf-form-actions"><button type="button" className="tf-secondary" onClick={()=>setBankModal(false)}>Cancel</button><button className="tf-primary">Submit request</button></div></form></Modal>}</>
}
