import { useMemo, useState, type ChangeEvent, type ReactNode } from 'react'
import { ArrowLeft, Ban, BriefcaseBusiness, Building2, CheckCircle2, ChevronLeft, ChevronRight, CircleAlert, Eye, FileText, Mail, MapPin, Pencil, Plus, ShieldCheck, Upload, UserCheck, UsersRound } from 'lucide-react'
import { DataTable, FilterSelect, Filters, Metric, Modal, PageHeader, Panel, Progress, StatusBadge } from '../components/FranchiseeUI'
import { authenticatedFranchisee, subFranchiseeService } from '../services/subFranchiseeService'
import { subFranchiseeRelationshipService } from '../services/subFranchiseeRelationshipService'
import { currentFranchiseeId, franchiseeEmployeeRepository, type FranchiseeEmployee } from '../employees'
import { assignmentEligibility, assignmentProgress, franchiseeAgentRepository, onboardingStatus, pendingRequirementCount, type FranchiseeAgent } from '../agentOnboarding'
import type { FranchiseeCustomer, FranchiseeProduct, RevenueRow } from '../types'
import { Employee360, type EmployeeTab } from './EmployeesPage'
import { AgentDetail, type DetailTab } from './AgentsPage'
import type { LegalEntityType, SubFranchisee, SubFranchiseeDocument, SubFranchiseeDocumentType, SubFranchiseeDraft } from '../subFranchiseeTypes'

type Screen={type:'list'}|{type:'add'}|{type:'edit';item:SubFranchisee}|{type:'detail';item:SubFranchisee}
const entityTypes:LegalEntityType[]=['Proprietorship','Partnership','LLP','Private Limited','Individual']
const documentTypes:SubFranchiseeDocumentType[]=['PAN Card','Identity Proof','GST Certificate','Business Registration','Cancelled Cheque','Photograph / Logo','Signed Agreement']
const blank=(products:string[]):SubFranchiseeDraft=>({firmName:'',contactPerson:'',mobile:'',email:'',businessType:'Financial Services',legalEntityType:'Proprietorship',pan:'',gstin:'',registrationNumber:'',yearsInBusiness:0,addressLine:'',area:'',city:'Ahmedabad',district:'Ahmedabad',state:'Gujarat',pinCode:'',territory:'Ahmedabad',products:products.slice(0,1),effectiveDate:new Date().toISOString().slice(0,10),documents:[]})
const date=(value:string)=>new Date(`${value}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})
const money=(value:number)=>value?`₹${value.toLocaleString('en-IN')}`:'—'

export function SubFranchiseesPage({availableProducts,products,customers,revenue,subFranchiseeId,onOpenDetail,onBack,onOpenCustomer,onToast}:{availableProducts:string[];products:FranchiseeProduct[];customers:FranchiseeCustomer[];revenue:RevenueRow[];subFranchiseeId?:string;onOpenDetail:(id:string)=>void;onBack:()=>void;onOpenCustomer:(id:string)=>void;onToast:(value:string)=>void}){
  const [rows,setRows]=useState(()=>subFranchiseeService.list()),[screen,setScreen]=useState<Screen>({type:'list'})
  const refresh=()=>setRows(subFranchiseeService.list())
  if(screen.type==='add')return <SubFranchiseeForm products={availableProducts} onBack={()=>setScreen({type:'list'})} onSave={draft=>{const created=subFranchiseeService.create(draft);refresh();setScreen({type:'list'});onOpenDetail(created.id);onToast(`${created.firmName} submitted for Head Office approval`)}}/>
  if(screen.type==='edit')return <SubFranchiseeForm item={screen.item} products={availableProducts} onBack={()=>setScreen({type:'list'})} onSave={draft=>{try{subFranchiseeService.update(screen.item.id,draft);refresh();setScreen({type:'list'});onToast('Sub-Franchisee details updated successfully')}catch(error){onToast(error instanceof Error?error.message:'Unable to update')}}}/>
  const routedItem=subFranchiseeId?rows.find(row=>row.id===subFranchiseeId):undefined
  if(subFranchiseeId)return routedItem?<SubFranchisee360 item={routedItem} products={products} customers={customers} revenue={revenue} onBack={onBack} onEdit={item=>setScreen({type:'edit',item})} onOpenCustomer={onOpenCustomer} onChanged={refresh} onToast={onToast}/>:<div className="sf-detail-empty"><CircleAlert/><b>Sub-Franchisee unavailable</b><span>This record does not exist or is outside your franchise access.</span><button className="tf-primary" onClick={onBack}>Back to Sub-Franchisees</button></div>
  return <Management rows={rows} onAdd={()=>setScreen({type:'add'})} onView={item=>onOpenDetail(item.id)} onEdit={item=>setScreen({type:'edit',item})} onChanged={refresh} onToast={onToast}/>
}

function Management({rows,onAdd,onView,onEdit,onChanged,onToast}:{rows:SubFranchisee[];onAdd:()=>void;onView:(item:SubFranchisee)=>void;onEdit:(item:SubFranchisee)=>void;onChanged:()=>void;onToast:(value:string)=>void}){
  const [search,setSearch]=useState(''),[status,setStatus]=useState('All statuses'),[location,setLocation]=useState('All locations'),[added,setAdded]=useState('Any time'),[page,setPage]=useState(1)
  const pageSize=5,locations=['All locations',...new Set(rows.map(row=>row.city))]
  const filtered=useMemo(()=>rows.filter(row=>{const query=search.trim().toLowerCase();const matches=!query||[row.firmName,row.code,row.mobile,row.email,row.contactPerson].some(value=>value.toLowerCase().includes(query));const days=(Date.now()-new Date(`${row.dateAdded}T00:00:00`).getTime())/86400000;return matches&&(status==='All statuses'||row.status===status)&&(location==='All locations'||row.city===location)&&(added==='Any time'||added==='Last 30 days'&&days<=30||added==='Last 90 days'&&days<=90)}),[rows,search,status,location,added])
  const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)),visible=filtered.slice((Math.min(page,totalPages)-1)*pageSize,Math.min(page,totalPages)*pageSize)
  const action=(fn:()=>void)=>{try{fn();onChanged()}catch(error){onToast(error instanceof Error?error.message:'Action could not be completed')}}
  return <div className="franchisee-sub-franchisees"><PageHeader eyebrow="PARTNER NETWORK" title="Sub-Franchisee Management" description="Create, review and manage Sub-Franchisees mapped exclusively to your franchise." actions={<button className="tf-primary" onClick={onAdd}><Plus/> Add Sub-Franchisee</button>}/>
    <div className="tf-metrics tf-metrics-4 sf-summary"><Metric label="Total Sub-Franchisees" value={rows.length} meta="Under your franchise" icon={<UsersRound/>}/><Metric label="Active" value={rows.filter(x=>x.status==='Active').length} meta="Approved and operating" icon={<UserCheck/>} tone="teal"/><Metric label="Pending Approval" value={rows.filter(x=>x.status==='Pending Approval').length} meta="Awaiting Head Office" icon={<CircleAlert/>} tone="orange"/><Metric label="Inactive" value={rows.filter(x=>x.status==='Inactive').length} meta="Currently disabled" icon={<Ban/>} tone="violet"/></div>
    <Panel title="Sub-Franchisee Directory" subtitle={`${filtered.length} records available to ${authenticatedFranchisee.code}`}><div className="sf-toolbar"><Filters search={search} onSearch={value=>{setSearch(value);setPage(1)}}/><FilterSelect label="Status" value={status} onChange={value=>{setStatus(value);setPage(1)}} options={['All statuses','Active','Pending Approval','Inactive','Rejected']}/><FilterSelect label="City / State" value={location} onChange={value=>{setLocation(value);setPage(1)}} options={locations}/><FilterSelect label="Added" value={added} onChange={value=>{setAdded(value);setPage(1)}} options={['Any time','Last 30 days','Last 90 days']}/></div>
      <DataTable headers={['Code / Name','Contact Person','Mobile & Email','City','Date Added','KYC Status','Status','Actions']} empty={!visible.length}>{visible.map(item=><tr key={item.id}><td><button className="tf-link-stack" onClick={()=>onView(item)}><b>{item.firmName}</b><small>{item.code}</small></button></td><td><b>{item.contactPerson}</b></td><td><span>{item.mobile}</span><small>{item.email}</small></td><td>{item.city}<small>{item.state}</small></td><td>{date(item.dateAdded)}</td><td><StatusBadge>{item.kycStatus}</StatusBadge></td><td><StatusBadge>{item.status}</StatusBadge></td><td><div className="sf-row-actions"><button title="View" onClick={()=>onView(item)}><Eye/></button><button title="Edit" onClick={()=>onEdit(item)}><Pencil/></button><button title="Documents" onClick={()=>onView(item)}><FileText/></button>{(item.status==='Active'||item.status==='Inactive')&&<button title={item.status==='Active'?'Deactivate':'Activate'} onClick={()=>action(()=>{subFranchiseeService.setStatus(item.id,item.status==='Active'?'Inactive':'Active');onToast(item.status==='Active'?'Sub-Franchisee deactivated':'Sub-Franchisee activated')})}>{item.status==='Active'?<Ban/>:<CheckCircle2/>}</button>}{item.invitationStatus!=='Accepted'&&<button title="Resend invitation" onClick={()=>action(()=>{subFranchiseeService.resendInvitation(item.id);onToast(`Invitation sent to ${item.email}`)})}><Mail/></button>}</div></td></tr>)}</DataTable>
      <div className="sf-pagination"><span>Showing {visible.length?((page-1)*pageSize)+1:0}–{Math.min(page*pageSize,filtered.length)} of {filtered.length}</span><div><button disabled={page<=1} onClick={()=>setPage(value=>value-1)}><ChevronLeft/></button><b>Page {Math.min(page,totalPages)} of {totalPages}</b><button disabled={page>=totalPages} onClick={()=>setPage(value=>value+1)}><ChevronRight/></button></div></div>
    </Panel></div>
}

function SubFranchiseeForm({item,products,onBack,onSave}:{item?:SubFranchisee;products:string[];onBack:()=>void;onSave:(draft:SubFranchiseeDraft)=>void}){
  const [draft,setDraft]=useState<SubFranchiseeDraft>(()=>item?{firmName:item.firmName,contactPerson:item.contactPerson,mobile:item.mobile,email:item.email,businessType:item.businessType,legalEntityType:item.legalEntityType,pan:item.pan,gstin:item.gstin,registrationNumber:item.registrationNumber,yearsInBusiness:item.yearsInBusiness,addressLine:item.addressLine,area:item.area,city:item.city,district:item.district,state:item.state,pinCode:item.pinCode,territory:item.territory,products:item.products,effectiveDate:item.effectiveDate,documents:item.documents}:blank(products)),[error,setError]=useState('')
  const set=<K extends keyof SubFranchiseeDraft>(key:K,value:SubFranchiseeDraft[K])=>setDraft(current=>({...current,[key]:value}))
  const submit=()=>{if(!draft.firmName.trim()||!draft.contactPerson.trim())return setError('Firm name and contact person are required.');if(!/^\+?[0-9 ]{10,16}$/.test(draft.mobile))return setError('Enter a valid 10-digit mobile number.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(draft.email))return setError('Enter a valid email address.');if(!/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(draft.pan))return setError('PAN must use the format ABCDE1234F.');if(!/^\d{6}$/.test(draft.pinCode))return setError('PIN code must contain 6 digits.');setError('');onSave(draft)}
  const addFiles=(event:ChangeEvent<HTMLInputElement>)=>{const files=[...(event.target.files||[])];const docs:SubFranchiseeDocument[]=files.map((file,index)=>({id:`DOC-${Date.now()}-${index}`,type:documentTypes[Math.min(draft.documents.length+index,documentTypes.length-1)],fileName:file.name,size:file.size,uploadedAt:new Date().toISOString().slice(0,10),status:'Uploaded'}));set('documents',[...draft.documents,...docs]);event.target.value=''}
  return <div className="franchisee-sub-franchisees sf-form-page"><button className="sf-back" onClick={onBack}><ArrowLeft/> Back to Sub-Franchisees</button><div className="sf-breadcrumb">Franchisee Dashboard <ChevronRight/> Sub-Franchisees <ChevronRight/> <b>{item?'Edit':'Add'} Sub-Franchisee</b></div><PageHeader eyebrow="PARTNER NETWORK" title={`${item?'Edit':'Add'} Sub-Franchisee`} description="The new account will remain pending until KYC and Head Office approval are complete."/>
    <section className="sf-parent"><ShieldCheck/><div><span>Authenticated Parent Franchisee</span><b>{authenticatedFranchisee.name}</b><small>{authenticatedFranchisee.code} · {authenticatedFranchisee.territory}</small></div><em>READ ONLY</em></section>
    <form className="sf-form" onSubmit={event=>{event.preventDefault();submit()}}><FormSection icon={<UsersRound/>} title="Basic Details" copy="Primary identity and communication details."><div className="sf-fields"><Field label="Sub-Franchisee / Firm Name" required><input value={draft.firmName} onChange={e=>set('firmName',e.target.value)} placeholder="Registered or trading name"/></Field><Field label="Contact Person Name" required><input value={draft.contactPerson} onChange={e=>set('contactPerson',e.target.value)} placeholder="Full name"/></Field><Field label="Mobile Number" required><input value={draft.mobile} onChange={e=>set('mobile',e.target.value)} placeholder="+91 98765 43210"/></Field><Field label="Email Address" required><input type="email" value={draft.email} onChange={e=>set('email',e.target.value)} placeholder="name@company.in"/></Field><Field label="Business Type"><input value={draft.businessType} onChange={e=>set('businessType',e.target.value)}/></Field></div></FormSection>
      <FormSection icon={<BriefcaseBusiness/>} title="Business Details" copy="Legal and statutory information used for verification."><div className="sf-fields"><Field label="Legal Entity Type" required><select value={draft.legalEntityType} onChange={e=>set('legalEntityType',e.target.value as LegalEntityType)}>{entityTypes.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="PAN" required><input maxLength={10} value={draft.pan} onChange={e=>set('pan',e.target.value.toUpperCase().replace(/\s/g,''))} placeholder="ABCDE1234F"/></Field><Field label="GSTIN"><input maxLength={15} value={draft.gstin} onChange={e=>set('gstin',e.target.value.toUpperCase())}/></Field><Field label="Registration Number"><input value={draft.registrationNumber} onChange={e=>set('registrationNumber',e.target.value)}/></Field><Field label="Years in Business"><input type="number" min="0" max="99" value={draft.yearsInBusiness} onChange={e=>set('yearsInBusiness',Number(e.target.value))}/></Field></div></FormSection>
      <FormSection icon={<MapPin/>} title="Address Details" copy="Registered office and operating territory."><div className="sf-fields"><Field label="Address Line" required wide><input value={draft.addressLine} onChange={e=>set('addressLine',e.target.value)}/></Field><Field label="Area"><input value={draft.area} onChange={e=>set('area',e.target.value)}/></Field><Field label="City" required><input value={draft.city} onChange={e=>set('city',e.target.value)}/></Field><Field label="District"><input value={draft.district} onChange={e=>set('district',e.target.value)}/></Field><Field label="State" required><input value={draft.state} onChange={e=>set('state',e.target.value)}/></Field><Field label="PIN Code" required><input maxLength={6} inputMode="numeric" value={draft.pinCode} onChange={e=>set('pinCode',e.target.value.replace(/\D/g,''))}/></Field><Field label="Territory"><input value={draft.territory} onChange={e=>set('territory',e.target.value)}/></Field></div></FormSection>
      <FormSection icon={<FileText/>} title="KYC & Documents" copy="Upload document metadata for Head Office verification."><label className="sf-upload"><Upload/><b>Choose documents to upload</b><span>PDF, JPG or PNG · maximum 10 MB each</span><input type="file" multiple accept=".pdf,.jpg,.jpeg,.png" onChange={addFiles}/></label>{draft.documents.length>0&&<div className="sf-document-list">{draft.documents.map((doc,index)=><article key={doc.id}><FileText/><div><input value={doc.fileName} readOnly/><small>{(doc.size/1024).toFixed(0)} KB · Uploaded {date(doc.uploadedAt)}</small></div><select value={doc.type} onChange={e=>set('documents',draft.documents.map((item,i)=>i===index?{...item,type:e.target.value as SubFranchiseeDocumentType}:item))}>{documentTypes.map(type=><option key={type}>{type}</option>)}</select><StatusBadge>{doc.status}</StatusBadge><button type="button" onClick={()=>set('documents',draft.documents.filter(x=>x.id!==doc.id))}>Remove</button></article>)}</div>}</FormSection>
      <FormSection icon={<Building2/>} title="Commercial, Product & Access" copy="Products are limited to those enabled for your franchise; payout controls remain with Head Office."><div className="sf-access"><div><span>Role</span><b>Sub-Franchisee</b><small>Assigned automatically</small></div><div><span>Approval</span><b>Head Office Review</b><small>Login sent only after approval</small></div><div><span>Commission / Payout</span><b>Derived from HO controls</b><small>Not editable by Franchisee</small></div></div><Field label="Product Access"><div className="sf-products">{products.map(product=><label key={product}><input type="checkbox" checked={draft.products.includes(product)} onChange={()=>set('products',draft.products.includes(product)?draft.products.filter(x=>x!==product):[...draft.products,product])}/><span>{product}</span></label>)}</div></Field><div className="sf-fields"><Field label="Effective Date"><input type="date" value={draft.effectiveDate} onChange={e=>set('effectiveDate',e.target.value)}/></Field></div></FormSection>
      {error&&<div className="sf-error"><CircleAlert/>{error}</div>}<footer><button type="button" className="tf-secondary" onClick={onBack}>Cancel</button><button className="tf-primary"><ShieldCheck/> {item?'Save Changes':'Submit for Approval'}</button></footer></form></div>
}

type SubDetailTab='Overview'|'Employees'|'Agents'

function SubFranchisee360({item,products,customers,revenue,onBack,onEdit,onOpenCustomer,onChanged,onToast}:{item:SubFranchisee;products:FranchiseeProduct[];customers:FranchiseeCustomer[];revenue:RevenueRow[];onBack:()=>void;onEdit:(item:SubFranchisee)=>void;onOpenCustomer:(id:string)=>void;onChanged:()=>void;onToast:(value:string)=>void}){
  const [tab,setTab]=useState<SubDetailTab>('Overview'),[employees,setEmployees]=useState(()=>franchiseeEmployeeRepository.load(currentFranchiseeId)),[agents,setAgents]=useState(()=>franchiseeAgentRepository.load(products)),[selectedEmployee,setSelectedEmployee]=useState<FranchiseeEmployee>(),[employeeTab,setEmployeeTab]=useState<EmployeeTab>('Overview'),[selectedAgent,setSelectedAgent]=useState<FranchiseeAgent>(),[agentTab,setAgentTab]=useState<DetailTab>('Profile')
  const relatedEmployees=useMemo(()=>subFranchiseeRelationshipService.employees(item.id,employees),[item.id,employees]),relatedAgents=useMemo(()=>subFranchiseeRelationshipService.agents(item.id,agents),[item.id,agents])
  const perform=(fn:()=>void)=>{try{fn();onChanged()}catch(error){onToast(error instanceof Error?error.message:'Action failed')}}
  const changeEmployeeStatus=(employee:FranchiseeEmployee,status:FranchiseeEmployee['status'])=>{const updated=franchiseeEmployeeRepository.changeStatus(employee,status);setEmployees(rows=>rows.map(row=>row.id===updated.id?updated:row));setSelectedEmployee(updated);onToast(`${employee.employeeId} marked ${status}`)}
  const removeEmployeeDocument=(employee:FranchiseeEmployee,documentId:string)=>{const {id:_,activity:__,createdAt:___,updatedAt:____,platformAccess:_____,...draft}=employee;draft.documents=draft.documents.filter(document=>document.id!==documentId);const updated=franchiseeEmployeeRepository.update(employee,draft);setEmployees(rows=>rows.map(row=>row.id===updated.id?updated:row));setSelectedEmployee(updated);onToast('Employee document metadata removed')}
  return <div className="franchisee-sub-franchisees sf-detail-page"><Modal title={item.firmName} subtitle={`${item.code} · Sub-Franchisee 360`} onClose={onBack}>
    <section className="sf-detail-hero"><div className="sf-avatar">{item.firmName.split(' ').slice(0,2).map(value=>value[0]).join('')}</div><div><span>{item.code}</span><h1>{item.firmName}</h1><p>{item.contactPerson} · {item.mobile} · {item.email} · {item.city}, {item.state}</p></div><div className="sf-hero-status"><StatusBadge>{item.status}</StatusBadge><small>Parent: {authenticatedFranchisee.name}</small></div><div className="tf-modal-actions"><button className="tf-secondary" onClick={onBack}><ArrowLeft/> Back to Sub-Franchisees</button><button className="tf-primary" onClick={()=>onEdit(item)}><Pencil/> Edit Details</button></div></section>
    <div className="tf-tabs sf-tabs">{(['Overview','Employees','Agents'] as SubDetailTab[]).map(value=><button key={value} className={tab===value?'active':''} onClick={()=>setTab(value)}>{value}{value==='Employees'&&<em>{relatedEmployees.length}</em>}{value==='Agents'&&<em>{relatedAgents.length}</em>}</button>)}</div>
    <div className="sf-360-content">
      {tab==='Overview'&&<><div className="sf-detail-metrics"><Metric label="Total Employees" value={relatedEmployees.length} meta="Directly assigned records" icon={<UsersRound/>}/><Metric label="Active Employees" value={relatedEmployees.filter(employee=>employee.status==='Active').length} meta="Currently active" icon={<UserCheck/>} tone="teal"/><Metric label="Total Agents" value={relatedAgents.length} meta="Directly assigned records" icon={<UsersRound/>} tone="violet"/><Metric label="Active Agents" value={relatedAgents.filter(agent=>onboardingStatus(agent)==='Eligible / Active').length} meta="Eligible across assigned lines" icon={<CheckCircle2/>} tone="orange"/></div><div className="sf-overview-grid"><InfoPanel title="Profile & contact" rows={[['Sub-Franchisee Code',item.code],['Contact Person',item.contactPerson],['Mobile',item.mobile],['Email',item.email],['Location',`${item.city}, ${item.state}`],['Joining Date',date(item.dateAdded)],['Status',item.status],['Parent Franchise',authenticatedFranchisee.name]]}/><InfoPanel title="Business & onboarding" rows={[['Business Type',item.businessType],['Legal Entity',item.legalEntityType],['Territory',item.territory],['Years in Business',String(item.yearsInBusiness)],['KYC Status',item.kycStatus],['Invitation Status',item.invitationStatus],['Effective Date',date(item.effectiveDate)],['Product Access',item.products.join(', ')||'No access configured']]}/></div><Panel title="KYC documents" subtitle={`${item.documents.length} document records · Head Office verification controls apply`}><div className="sf-detail-docs">{item.documents.length?item.documents.map(doc=><article key={doc.id}><FileText/><div><b>{doc.type}</b><small>{doc.fileName} · {(doc.size/1024).toFixed(0)} KB</small></div><StatusBadge>{doc.status}</StatusBadge><button className="tf-text-btn" onClick={()=>onToast('Document preview is available after storage integration')}>Preview</button></article>):<div className="sf-detail-empty"><FileText/><b>No documents uploaded</b><span>Edit this record to add KYC documents.</span></div>}</div></Panel><div className="sf-detail-actions">{item.invitationStatus!=='Accepted'&&<button className="tf-secondary" onClick={()=>perform(()=>{subFranchiseeService.resendInvitation(item.id);onToast(`Invitation sent to ${item.email}`)})}><Mail/> Resend Invitation</button>}{(item.status==='Active'||item.status==='Inactive')&&<button className={item.status==='Active'?'tf-secondary sf-danger':'tf-primary'} onClick={()=>perform(()=>{subFranchiseeService.setStatus(item.id,item.status==='Active'?'Inactive':'Active');onToast(item.status==='Active'?'Sub-Franchisee deactivated':'Sub-Franchisee activated')})}>{item.status==='Active'?<Ban/>:<CheckCircle2/>}{item.status==='Active'?'Deactivate':'Activate'} Account</button>}</div></>}
      {tab==='Employees'&&<Panel title="Sub-Franchisee Employees" subtitle="Only records explicitly assigned to this Sub-Franchisee"><DataTable headers={['Employee','Employee ID','Designation','Mobile','Email','Business Lines','Status','Joining Date','Action']} empty={!relatedEmployees.length}>{relatedEmployees.map(employee=><tr key={employee.id}><td><b>{[employee.firstName,employee.middleName,employee.lastName].filter(Boolean).join(' ')}</b></td><td>{employee.employeeId}</td><td>{employee.designation}</td><td>{employee.mobile}</td><td>{employee.email}</td><td>{employee.assignedProducts.join(', ')||'None assigned'}</td><td><StatusBadge>{employee.status}</StatusBadge></td><td>{date(employee.joiningDate)}</td><td><button className="tf-text-btn" onClick={()=>{setSelectedEmployee(employee);setEmployeeTab('Overview')}}>View</button></td></tr>)}</DataTable>{!relatedEmployees.length&&<RelationshipEmpty kind="employees"/>}</Panel>}
      {tab==='Agents'&&<Panel title="Sub-Franchisee Agents" subtitle="Only records explicitly assigned to this Sub-Franchisee"><DataTable headers={['Agent','Agent ID','Contact','Business Lines','Progress','Compliance','Eligibility','Last Updated','Action']} empty={!relatedAgents.length}>{relatedAgents.map(agent=>{const progress=Math.round(agent.assignments.reduce((sum,line)=>sum+assignmentProgress(line),0)/Math.max(1,agent.assignments.length)),eligible=agent.assignments.filter(line=>assignmentEligibility(line)==='Eligible').length;return <tr key={agent.id}><td><b>{agent.name}</b><small>{agent.designation}</small></td><td>{agent.agentCode}</td><td>{agent.mobile}<small>{agent.email}</small></td><td>{agent.assignments.map(line=>line.businessLine).join(', ')||'None assigned'}</td><td><b>{progress}%</b><Progress value={progress}/></td><td><StatusBadge>{onboardingStatus(agent)}</StatusBadge><small>{pendingRequirementCount(agent)} pending</small></td><td>{eligible} / {agent.assignments.length}</td><td>{dateTime(agent.updatedAt)}</td><td><button className="tf-text-btn" onClick={()=>{setSelectedAgent(agent);setAgentTab('Profile')}}>View</button></td></tr>})}</DataTable>{!relatedAgents.length&&<RelationshipEmpty kind="agents"/>}</Panel>}
    </div>
    {selectedEmployee&&<div className="franchisee-employees"><Employee360 employee={selectedEmployee} employees={employees} customers={customers} revenue={revenue} tab={employeeTab} setTab={setEmployeeTab} onClose={()=>setSelectedEmployee(undefined)} onStatus={status=>changeEmployeeStatus(selectedEmployee,status)} onRemoveDocument={documentId=>removeEmployeeDocument(selectedEmployee,documentId)} onOpenCustomer={onOpenCustomer} onToast={onToast}/></div>}
    {selectedAgent&&<div className="franchisee-agents"><AgentDetail agent={selectedAgent} tab={agentTab} setTab={setAgentTab} onClose={()=>setSelectedAgent(undefined)}/></div>}
  </Modal></div>
}

function RelationshipEmpty({kind}:{kind:'employees'|'agents'}){return <div className="sf-relationship-empty"><UsersRound/><b>No assigned {kind}</b><span>Records appear here only when their Sub-Franchisee relationship or assignment mapping matches this record.</span></div>}
function dateTime(value:string){const parsed=new Date(value);return Number.isNaN(parsed.getTime())?'—':parsed.toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}

function SubFranchiseeDetail({item,onBack,onEdit,onChanged,onToast}:{item:SubFranchisee;onBack:()=>void;onEdit:(item:SubFranchisee)=>void;onChanged:()=>void;onToast:(value:string)=>void}){
  const [tab,setTab]=useState('Overview'),tabs=['Overview','Business Details','Contact & Address','Documents / KYC','Commercial Details','Login / Account']
  const perform=(fn:()=>void)=>{try{fn();onChanged()}catch(error){onToast(error instanceof Error?error.message:'Action failed')}}
  return <div className="franchisee-sub-franchisees sf-detail-page"><button className="sf-back" onClick={onBack}><ArrowLeft/> Back to Sub-Franchisees</button><section className="sf-detail-hero"><div className="sf-avatar">{item.firmName.split(' ').slice(0,2).map(x=>x[0]).join('')}</div><div><span>{item.code}</span><h1>{item.firmName}</h1><p>{item.contactPerson} · {item.city}, {item.state}</p></div><div className="sf-hero-status"><StatusBadge>{item.status}</StatusBadge><small>Parent: {authenticatedFranchisee.name}</small></div><button className="tf-secondary" onClick={()=>onEdit(item)}><Pencil/> Edit Details</button></section><div className="tf-tabs sf-tabs">{tabs.map(value=><button key={value} className={tab===value?'active':''} onClick={()=>setTab(value)}>{value}{value==='Documents / KYC'&&<em>{item.documents.length}</em>}</button>)}</div>
    <div className="sf-detail-content">{tab==='Overview'&&<><div className="sf-detail-metrics"><Metric label="Business Generated" value={money(item.businessGenerated)} meta="Current financial year" icon={<BriefcaseBusiness/>}/><Metric label="KYC Status" value={item.kycStatus} meta={`${item.documents.length} documents uploaded`} icon={<ShieldCheck/>} tone="teal"/><Metric label="Product Access" value={item.products.length} meta="Products enabled" icon={<Building2/>} tone="violet"/></div><InfoPanel title="At a glance" rows={[['Sub-Franchisee Code',item.code],['Date Added',date(item.dateAdded)],['Legal Entity',item.legalEntityType],['Territory',item.territory],['Contact Person',item.contactPerson],['Mobile',item.mobile],['Email',item.email],['Approval Status',item.status]]}/></>}
      {tab==='Business Details'&&<InfoPanel title="Business & statutory information" rows={[['Firm Name',item.firmName],['Business Type',item.businessType],['Legal Entity Type',item.legalEntityType],['PAN',item.pan],['GSTIN',item.gstin||'Not provided'],['Registration Number',item.registrationNumber||'Not provided'],['Years in Business',String(item.yearsInBusiness)],['Effective Date',date(item.effectiveDate)]]}/>} 
      {tab==='Contact & Address'&&<InfoPanel title="Contact & registered address" rows={[['Contact Person',item.contactPerson],['Mobile',item.mobile],['Email',item.email],['Address',item.addressLine],['Area',item.area],['City / District',`${item.city} / ${item.district}`],['State',item.state],['PIN Code',item.pinCode]]}/>} 
      {tab==='Documents / KYC'&&<Panel title="KYC documents" subtitle="Documents remain subject to Head Office verification."><div className="sf-detail-docs">{item.documents.length?item.documents.map(doc=><article key={doc.id}><FileText/><div><b>{doc.type}</b><small>{doc.fileName} · {(doc.size/1024).toFixed(0)} KB</small></div><StatusBadge>{doc.status}</StatusBadge><button className="tf-text-btn" onClick={()=>onToast('Document preview is available after storage integration')}>Preview</button></article>):<div className="sf-detail-empty"><FileText/><b>No documents uploaded</b><span>Edit this record to add KYC documents.</span></div>}</div></Panel>}
      {tab==='Commercial Details'&&<><InfoPanel title="Product configuration" rows={[['Products',item.products.join(', ')||'No access configured'],['Territory',item.territory],['Effective Date',date(item.effectiveDate)],['Payout Structure','Inherited from parent franchise controls']]}/><div className="sf-policy"><ShieldCheck/><div><b>Commercial controls protected</b><p>Sub-Franchisee payout cannot exceed the parent Franchisee entitlement. Rates are derived from Head Office configuration and cannot be edited here.</p></div></div></>}
      {tab==='Login / Account'&&<><InfoPanel title="Login and activation" rows={[['Assigned Role','Sub-Franchisee'],['Invitation Status',item.invitationStatus],['Invitation Email',item.email],['Last Invitation',item.lastInvitationAt?date(item.lastInvitationAt):'Not sent'],['Account Status',item.status==='Active'?'Enabled':'Not active'],['Approval Owner','Head Office']]}/><div className="sf-detail-actions">{item.invitationStatus!=='Accepted'&&<button className="tf-secondary" onClick={()=>perform(()=>{subFranchiseeService.resendInvitation(item.id);onToast(`Invitation sent to ${item.email}`)})}><Mail/> Resend Invitation</button>}{(item.status==='Active'||item.status==='Inactive')&&<button className={item.status==='Active'?'tf-secondary sf-danger':'tf-primary'} onClick={()=>perform(()=>{subFranchiseeService.setStatus(item.id,item.status==='Active'?'Inactive':'Active');onToast(item.status==='Active'?'Sub-Franchisee deactivated':'Sub-Franchisee activated')})}>{item.status==='Active'?<Ban/>:<CheckCircle2/>}{item.status==='Active'?'Deactivate':'Activate'} Account</button>}</div></>}
    </div></div>
}

function FormSection({icon,title,copy,children}:{icon:ReactNode;title:string;copy:string;children:ReactNode}){return <section className="sf-form-section"><header><span>{icon}</span><div><h2>{title}</h2><p>{copy}</p></div></header><div className="sf-section-body">{children}</div></section>}
function Field({label,required,wide,children}:{label:string;required?:boolean;wide?:boolean;children:ReactNode}){return <label className={`sf-field ${wide?'wide':''}`}>{label}{required&&<sup>*</sup>}{children}</label>}
function InfoPanel({title,rows}:{title:string;rows:[string,string][]}){return <Panel title={title}><div className="sf-info-grid">{rows.map(([label,value])=><div key={label}><span>{label}</span><b>{value||'—'}</b></div>)}</div></Panel>}
