import { Edit3, FileText, Plus, UsersRound } from 'lucide-react'
import { useMemo, useState } from 'react'
import { buildAgentBusinessLines, franchiseeAgentRepository, onboardingStatus, type FranchiseeAgent } from '../agentOnboarding'
import { currentFranchiseeId, franchiseeEmployeeRepository, type EmployeeDraft, type FranchiseeEmployee } from '../employees'
import { DataTable, FilterSelect, Filters, Modal, PageHeader, Panel, StatusBadge } from '../components/FranchiseeUI'
import type { FranchiseeCase, FranchiseeCustomer, FranchiseeProduct } from '../types'
import { subFranchiseeRelationshipService } from '../services/subFranchiseeRelationshipService'
import { authenticatedFranchisee, subFranchiseeService } from '../services/subFranchiseeService'
import type { SubFranchisee, SubFranchiseeDraft } from '../subFranchiseeTypes'
import { AgentForm, SimpleAgentDetail, type SimpleAgentTab } from './AgentsPage'
import { EmployeeForm, SimpleEmployeeDetail, type SimpleEmployeeTab } from './EmployeesPage'

type SubTab='Overview'|'Employees'|'Agents'|'Customers'|'Business Lines'|'Documents'

export function SubFranchiseesPage({availableProducts,products,customers,cases,subFranchiseeId,onOpenDetail,onBack,onOpenCustomer,onToast}:{availableProducts:string[];products:FranchiseeProduct[];customers:FranchiseeCustomer[];cases:FranchiseeCase[];subFranchiseeId?:string;onOpenDetail:(id:string)=>void;onBack:()=>void;onOpenCustomer:(id:string)=>void;onToast:(value:string)=>void}){
  const [version,setVersion]=useState(0),[editing,setEditing]=useState<SubFranchisee>()
  const rows=useMemo(()=>subFranchiseeService.list(),[version])
  const selected=subFranchiseeId?rows.find(item=>item.id===subFranchiseeId):undefined
  if(editing)return <SubEditForm item={editing} products={availableProducts} onClose={()=>setEditing(undefined)} onSave={draft=>{subFranchiseeService.update(editing.id,draft);setEditing(undefined);setVersion(value=>value+1);onToast('Sub-Franchisee details updated successfully')}}/>
  if(subFranchiseeId)return selected?<SubFranchiseeDetail item={selected} products={products} customers={customers} cases={cases} onBack={onBack} onEdit={()=>setEditing(selected)} onOpenCustomer={onOpenCustomer} onToast={onToast}/>:<div className="sf-detail-empty"><UsersRound/><b>Sub-Franchisee not found.</b><button className="tf-text-btn" onClick={onBack}>Back to Sub-Franchisees</button></div>
  return <SubFranchiseeList rows={rows} products={products} customers={customers} onView={item=>onOpenDetail(item.id)}/>
}

function SubFranchiseeList({rows,products,customers,onView}:{rows:SubFranchisee[];products:FranchiseeProduct[];customers:FranchiseeCustomer[];onView:(item:SubFranchisee)=>void}){
  const [search,setSearch]=useState(''),[city,setCity]=useState('All Cities'),[status,setStatus]=useState('All Statuses')
  const employees=franchiseeEmployeeRepository.load(currentFranchiseeId),agents=franchiseeAgentRepository.load(products),cities=[...new Set(rows.map(item=>item.city))]
  const visible=rows.filter(item=>(city==='All Cities'||item.city===city)&&(status==='All Statuses'||item.status===status)&&`${item.firmName} ${item.code} ${item.contactPerson} ${item.mobile} ${item.email}`.toLowerCase().includes(search.toLowerCase()))
  return <div className="franchisee-sub-franchisees"><PageHeader eyebrow="PARTNER NETWORK" title="Sub-Franchisees" description="View Sub-Franchisees managed under your franchise."/>
    <Panel title="Sub-Franchisee List" subtitle={`${visible.length} Sub-Franchisees`}><div className="sf-toolbar"><Filters search={search} onSearch={setSearch}/><FilterSelect label="City" value={city} onChange={setCity} options={['All Cities',...cities]}/><FilterSelect label="Status" value={status} onChange={setStatus} options={['All Statuses','Active','Pending Approval','Inactive','Rejected']}/></div>
      <DataTable headers={['Sub-Franchisee Name','Contact','Location','Employees','Agents','Customers','Status','View']} empty={!visible.length}>{visible.map(item=>{const staff=subFranchiseeRelationshipService.employees(item.id,employees),partners=subFranchiseeRelationshipService.agents(item.id,agents),customerIds=mappedCustomerIds(staff,partners);return <tr key={item.id}><td><button className="tf-link-stack" onClick={()=>onView(item)}><b>{item.firmName}</b><small>{item.code}</small></button></td><td><b>{item.contactPerson}</b><small>{item.mobile} · {item.email}</small></td><td><b>{item.city}, {item.state}</b></td><td>{staff.length} Employee{staff.length===1?'':'s'}</td><td>{partners.length} Agent{partners.length===1?'':'s'}</td><td>{customers.filter(customer=>customerIds.has(customer.id)).length} Customer{customers.filter(customer=>customerIds.has(customer.id)).length===1?'':'s'}</td><td><StatusBadge>{item.status}</StatusBadge></td><td><button className="tf-text-btn" onClick={()=>onView(item)}>View</button></td></tr>})}</DataTable>
    </Panel>
  </div>
}

function SubFranchiseeDetail({item,products,customers,cases,onBack,onEdit,onOpenCustomer,onToast}:{item:SubFranchisee;products:FranchiseeProduct[];customers:FranchiseeCustomer[];cases:FranchiseeCase[];onBack:()=>void;onEdit:()=>void;onOpenCustomer:(id:string)=>void;onToast:(value:string)=>void}){
  const [tab,setTab]=useState<SubTab>('Overview'),[employees,setEmployees]=useState(()=>franchiseeEmployeeRepository.load(currentFranchiseeId)),[agents,setAgents]=useState(()=>franchiseeAgentRepository.load(products)),[employeeForm,setEmployeeForm]=useState(false),[agentForm,setAgentForm]=useState(false),[selectedEmployee,setSelectedEmployee]=useState<FranchiseeEmployee>(),[employeeTab,setEmployeeTab]=useState<SimpleEmployeeTab>('Overview'),[selectedAgent,setSelectedAgent]=useState<FranchiseeAgent>(),[agentTab,setAgentTab]=useState<SimpleAgentTab>('Overview')
  const lines=useMemo(()=>buildAgentBusinessLines(products),[products])
  const relatedEmployees=subFranchiseeRelationshipService.employees(item.id,employees),relatedAgents=subFranchiseeRelationshipService.agents(item.id,agents)
  const customerIds=mappedCustomerIds(relatedEmployees,relatedAgents),relatedCustomers=customers.filter(customer=>customerIds.has(customer.id))
  const tabs:SubTab[]=['Overview','Employees','Agents','Customers','Business Lines','Documents']
  const saveEmployee=(draft:EmployeeDraft)=>{const employee=franchiseeEmployeeRepository.saveNew({...draft,franchiseeId:currentFranchiseeId,subFranchiseeId:item.id});setEmployees(current=>[employee,...current]);setEmployeeForm(false);onToast(`${fullName(employee)} added to ${item.firmName}`)}
  return <div className="franchisee-sub-franchisees sf-detail-page"><Modal title={item.firmName} subtitle={`${item.code} · Sub-Franchisee Detail`} onClose={onBack}>
    <section className="sf-detail-hero"><div className="sf-avatar">{initials(item.firmName)}</div><div><span>{item.code}</span><h1>{item.firmName}</h1><p>{item.contactPerson} · {item.mobile} · {item.city}, {item.state}</p></div><div className="sf-hero-status"><StatusBadge>{item.status}</StatusBadge><small>Parent: {authenticatedFranchisee.name}</small></div><button className="tf-secondary" onClick={onEdit}><Edit3/> Edit</button></section>
    <div className="tf-tabs sf-tabs">{tabs.map(value=><button key={value} className={tab===value?'active':''} onClick={()=>setTab(value)}>{value}</button>)}</div>
    <div className="sf-360-content">
      {tab==='Overview'&&<div className="sf-overview-grid"><InfoPanel title="Overview" rows={[['Sub-Franchisee Name',item.firmName],['Sub-Franchisee ID',item.code],['Contact Person',item.contactPerson],['Mobile',item.mobile],['Email',item.email],['Address',[item.addressLine,item.area].filter(Boolean).join(', ')],['City',item.city],['State',item.state],['Start Date',date(item.dateAdded)],['Status',item.status]]}/><InfoPanel title="Team & Customers" rows={[['Employees',String(relatedEmployees.length)],['Agents',String(relatedAgents.length)],['Customers',String(relatedCustomers.length)],['Business Lines',item.products.join(', ')||'None assigned']]}/></div>}
      {tab==='Employees'&&<Panel title="Employees" subtitle="Only employees belonging to this Sub-Franchisee" action={<button className="tf-primary" onClick={()=>setEmployeeForm(true)}><Plus/> Add Employee</button>}><DataTable headers={['Employee Name','Contact','Role','Business Lines','Customers','Status','View']} empty={!relatedEmployees.length}>{relatedEmployees.map(employee=><tr key={employee.id}><td><b>{fullName(employee)}</b><small>{employee.employeeId}</small></td><td><b>{employee.mobile}</b><small>{employee.email}</small></td><td>{employee.role}</td><td><CompactList values={employee.assignedProducts}/></td><td>{employee.assignedCustomerIds.length} Customers</td><td><StatusBadge>{employee.status}</StatusBadge></td><td><button className="tf-text-btn" onClick={()=>{setSelectedEmployee(employee);setEmployeeTab('Overview')}}>View</button></td></tr>)}</DataTable>{!relatedEmployees.length&&<Empty text="No employees are assigned to this Sub-Franchisee."/>}</Panel>}
      {tab==='Agents'&&<Panel title="Agents" subtitle="Only agents belonging to this Sub-Franchisee" action={<button className="tf-primary" onClick={()=>setAgentForm(true)}><Plus/> Add Agent</button>}><DataTable headers={['Agent Name','Contact','Agent Type','Business Lines','Customers','Compliance','Status','View']} empty={!relatedAgents.length}>{relatedAgents.map(agent=><tr key={agent.id}><td><b>{agent.name}</b><small>{agent.agentCode}</small></td><td><b>{agent.mobile}</b><small>{agent.email}</small></td><td>{agent.designation}</td><td><CompactList values={agent.assignments.map(line=>line.businessLine)}/></td><td>{agent.assignedCustomerIds?.length||0} Customers</td><td><StatusBadge>{agentCompliance(agent)}</StatusBadge></td><td><StatusBadge>{onboardingStatus(agent)==='Eligible / Active'?'Active':'Onboarding'}</StatusBadge></td><td><button className="tf-text-btn" onClick={()=>{setSelectedAgent(agent);setAgentTab('Overview')}}>View</button></td></tr>)}</DataTable>{!relatedAgents.length&&<Empty text="No agents are assigned to this Sub-Franchisee."/>}</Panel>}
      {tab==='Customers'&&<Panel title="Customers" subtitle="Customers mapped through this Sub-Franchisee's employees and agents"><DataTable headers={['Customer Name','Contact','Customer Type','Products','Open Cases','Open 360']} empty={!relatedCustomers.length}>{relatedCustomers.map(customer=>{const openCases=cases.filter(record=>record.customerId===customer.id&&!['Completed','Rejected','Approved / Issued'].includes(record.status)).length;return <tr key={customer.id}><td><b>{customer.name}</b><small>{customer.id}</small></td><td><b>{customer.mobile}</b><small>{customer.email}</small></td><td>{customer.profile360?.customerType||'Individual'}</td><td><CompactList values={customer.products}/></td><td>{openCases}</td><td><button className="tf-text-btn" onClick={()=>onOpenCustomer(customer.id)}>Open 360</button></td></tr>})}</DataTable>{!relatedCustomers.length&&<Empty text="No customers are assigned to this Sub-Franchisee."/>}</Panel>}
      {tab==='Business Lines'&&<Panel title="Business Lines" subtitle="Business areas available to this Sub-Franchisee"><div className="agent-line-chips">{item.products.map(product=><span key={product}>{product}</span>)}</div>{!item.products.length&&<Empty text="No business lines are assigned."/>}</Panel>}
      {tab==='Documents'&&<Panel title="Documents" subtitle="Sub-Franchisee document records"><DataTable headers={['Document','File','Uploaded','Status']} empty={!item.documents.length}>{item.documents.map(document=><tr key={document.id}><td><b>{document.type}</b></td><td>{document.fileName}</td><td>{date(document.uploadedAt)}</td><td><StatusBadge>{document.status}</StatusBadge></td></tr>)}</DataTable>{!item.documents.length&&<Empty text="No documents are available."/>}</Panel>}
    </div>
    {employeeForm&&<div className="franchisee-employees"><EmployeeForm employee={null} employees={relatedEmployees} customers={relatedCustomers} products={item.products} subFranchiseeId={item.id} onClose={()=>setEmployeeForm(false)} onSave={saveEmployee}/></div>}
    {agentForm&&<div className="franchisee-agents"><AgentForm lines={lines.filter(line=>item.products.some(product=>line.name===product||line.productIds.some(id=>products.find(master=>master.id===id)?.name===product)))} products={products} customers={relatedCustomers} subFranchiseeId={item.id} onClose={()=>setAgentForm(false)} onSave={agent=>{setAgents(current=>[agent,...current]);setAgentForm(false);onToast(`${agent.name} added to ${item.firmName}`)}}/></div>}
    {selectedEmployee&&<div className="franchisee-employees"><SimpleEmployeeDetail employee={selectedEmployee} employees={relatedEmployees} customers={customers} cases={cases} tab={employeeTab} setTab={setEmployeeTab} onClose={()=>setSelectedEmployee(undefined)} onOpenCustomer={onOpenCustomer} onToast={onToast}/></div>}
    {selectedAgent&&<div className="franchisee-agents"><SimpleAgentDetail agent={selectedAgent} customers={customers} cases={cases} tab={agentTab} setTab={setAgentTab} onClose={()=>setSelectedAgent(undefined)} onOpenCustomer={onOpenCustomer}/></div>}
  </Modal></div>
}

function SubEditForm({item,products,onClose,onSave}:{item:SubFranchisee;products:string[];onClose:()=>void;onSave:(draft:SubFranchiseeDraft)=>void}){
  const {id:_,parentFranchiseeId:__,headOfficeId:___,code:____,dateAdded:_____,kycStatus:______,status:_______,invitationStatus:________,lastInvitationAt:_________,businessGenerated:__________,...initial}=item
  const [draft,setDraft]=useState<SubFranchiseeDraft>(initial),[error,setError]=useState('')
  const set=<K extends keyof SubFranchiseeDraft>(key:K,value:SubFranchiseeDraft[K])=>setDraft(current=>({...current,[key]:value}))
  const submit=()=>{if(!draft.firmName.trim()||!draft.contactPerson.trim()||!draft.mobile.trim()||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(draft.email)){setError('Enter the name, contact person, mobile number and a valid email address.');return}onSave(draft)}
  return <div className="franchisee-sub-franchisees"><Modal title="Edit Sub-Franchisee" subtitle={item.code} onClose={onClose}><form className="agent-form" onSubmit={event=>{event.preventDefault();submit()}}><section><h3>Contact Details</h3><div className="agent-fields"><label>Sub-Franchisee Name<input value={draft.firmName} onChange={event=>set('firmName',event.target.value)}/></label><label>Contact Person<input value={draft.contactPerson} onChange={event=>set('contactPerson',event.target.value)}/></label><label>Mobile Number<input value={draft.mobile} onChange={event=>set('mobile',event.target.value)}/></label><label>Email Address<input type="email" value={draft.email} onChange={event=>set('email',event.target.value)}/></label></div></section><section><h3>Address</h3><div className="agent-fields"><label className="wide">Address<input value={draft.addressLine} onChange={event=>set('addressLine',event.target.value)}/></label><label>City<input value={draft.city} onChange={event=>set('city',event.target.value)}/></label><label>State<input value={draft.state} onChange={event=>set('state',event.target.value)}/></label></div></section><section><h3>Business Lines</h3><div className="agent-line-picker">{products.map(product=><label key={product}><input type="checkbox" checked={draft.products.includes(product)} onChange={event=>set('products',event.target.checked?[...draft.products,product]:draft.products.filter(value=>value!==product))}/><span><b>{product}</b></span></label>)}</div></section>{error&&<div className="agent-error"><FileText/>{error}</div>}<footer><button type="button" className="tf-secondary" onClick={onClose}>Cancel</button><button className="tf-primary">Save Changes</button></footer></form></Modal></div>
}

function mappedCustomerIds(employees:FranchiseeEmployee[],agents:FranchiseeAgent[]){return new Set([...employees.flatMap(employee=>employee.assignedCustomerIds),...agents.flatMap(agent=>agent.assignedCustomerIds||[])])}
function InfoPanel({title,rows}:{title:string;rows:[string,string][]}){return <Panel title={title}><div className="sf-info-grid">{rows.map(([label,value])=><div key={label}><span>{label}</span><b>{value||'—'}</b></div>)}</div></Panel>}
function CompactList({values}:{values:string[]}){return <><b>{values.slice(0,2).join(', ')||'None'}</b>{values.length>2&&<small>+{values.length-2} more</small>}</>}
function Empty({text}:{text:string}){return <div className="sf-relationship-empty"><UsersRound/><b>{text}</b></div>}
function agentCompliance(agent:FranchiseeAgent){const status=onboardingStatus(agent);return status==='Eligible / Active'?'Complete':status==='Pending Verification'?'Verification Required':'Pending'}
function fullName(employee:FranchiseeEmployee){return [employee.firstName,employee.middleName,employee.lastName].filter(Boolean).join(' ')}
function initials(value:string){return value.split(/\s+/).slice(0,2).map(part=>part[0]||'').join('').toUpperCase()}
function date(value?:string){if(!value)return '—';const parsed=new Date(value);return Number.isNaN(parsed.getTime())?value:parsed.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}
