import { AlertTriangle, MessageSquarePlus, Paperclip, Plus } from 'lucide-react'
import { useMemo, useState } from 'react'
import type { FranchiseeTicket } from '../types'
import { DataTable, FilterSelect, Filters, Modal, Panel, StatusBadge, PageHeader, Timeline } from '../components/FranchiseeUI'

const desk:Record<string,string>={'Operational Query':'HO Operations','Technical / Portal Issue':'HO IT','Marketing Material Request':'HO Marketing','Customer Escalation':'HO Support','Payout Query':'HO Finance'}
export function SupportPage({tickets,prefill,onClearPrefill,onCreate,onUpdate,onToast}:{tickets:FranchiseeTicket[];prefill?:{category?:string;subject?:string};onClearPrefill:()=>void;onCreate:(category:string,subject:string,description:string,assigned:string)=>void;onUpdate:(id:string,patch:Partial<FranchiseeTicket>)=>void;onToast:(s:string)=>void}){
  const [search,setSearch]=useState(''),[status,setStatus]=useState('All statuses'),[selected,setSelected]=useState<FranchiseeTicket>(),[raising,setRaising]=useState(Boolean(prefill))
  const rows=useMemo(()=>tickets.filter(t=>(status==='All statuses'||t.status===status)&&`${t.id} ${t.subject} ${t.category}`.toLowerCase().includes(search.toLowerCase())),[tickets,status,search])
  return <><PageHeader eyebrow="HEAD OFFICE ASSISTANCE" title="Franchisee Support" description="Raise operational, portal, marketing, or customer escalations and track the owning HO desk and SLA." actions={<button className="tf-primary" onClick={()=>setRaising(true)}><Plus/> Raise ticket</button>}/>
    <Panel title="My tickets" subtitle="Conversation, ownership, and SLA remain in one thread"><Filters search={search} onSearch={setSearch}><FilterSelect label="Status" value={status} onChange={setStatus} options={['All statuses','New','In Progress','Waiting for Me','Resolved','Closed']}/></Filters><DataTable headers={['Ticket','Category','Status','Assigned desk','SLA','Created','Last response','']} empty={!rows.length}>{rows.map(ticket=><tr key={ticket.id}><td><button className="tf-link-stack" onClick={()=>setSelected(ticket)}><b>{ticket.subject}</b><small>{ticket.id}</small></button></td><td>{ticket.category}</td><td><StatusBadge>{ticket.status}</StatusBadge></td><td>{ticket.assignedDesk}</td><td><b>{ticket.sla}</b></td><td>{ticket.created}</td><td>{ticket.lastResponse}</td><td><button className="tf-text-btn" onClick={()=>setSelected(ticket)}>Open</button></td></tr>)}</DataTable></Panel>
    {raising&&<Modal title="Raise support ticket" subtitle="The category determines which Head Office desk owns the next step." onClose={()=>{setRaising(false);onClearPrefill()}}><form className="tf-form" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget),category=String(fd.get('category'));onCreate(category,String(fd.get('subject')),String(fd.get('description')),desk[category]||'HO Support');setRaising(false);onClearPrefill()}}><label>Category<select name="category" defaultValue={prefill?.category||'Operational Query'}>{Object.keys(desk).map(x=><option key={x}>{x}</option>)}</select></label><label>Subject<input name="subject" defaultValue={prefill?.subject||''} required/></label><label>Description<textarea name="description" required placeholder="Include record IDs, expected result, and what is blocking you."/></label><div className="tf-form-row"><label>Priority<select name="priority"><option>Normal</option><option>Urgent</option></select></label><label>Attachment<button type="button" className="tf-upload"><Paperclip/> Select file</button></label></div><div className="tf-routing"><MessageSquarePlus/><div><b>Routed by category</b><p>Operational → Operations · Portal → IT · Marketing → Marketing · Customer escalation → Support.</p></div></div><div className="tf-form-actions"><button type="button" className="tf-secondary" onClick={()=>setRaising(false)}>Cancel</button><button className="tf-primary">Submit to HO desk</button></div></form></Modal>}
    {selected&&<Modal title={selected.subject} subtitle={`${selected.id} · ${selected.assignedDesk}`} onClose={()=>setSelected(undefined)}><div className="tf-360-head"><div><span>SLA</span><strong>{selected.sla}</strong><small>Created {selected.created}</small></div><StatusBadge>{selected.status}</StatusBadge>{!['Closed','Resolved'].includes(selected.status)&&<button className="tf-secondary" onClick={()=>{onUpdate(selected.id,{priority:'Urgent'});onToast(`Escalation routed to mapped RM for ${selected.id}`)}}><AlertTriangle/> Escalate</button>}</div><Panel title="Ticket conversation"><Timeline items={selected.messages}/></Panel><div className="tf-reply"><label>Reply<textarea placeholder="Add a response to reopen the thread with HO..."/></label><div className="tf-form-actions"><button className="tf-secondary" onClick={()=>onToast('Attachment added to ticket draft')}><Paperclip/> Attachment</button><button className="tf-primary" onClick={()=>onToast('Reply added to ticket thread')}>Send reply</button>{selected.status==='Resolved'&&<button className="tf-secondary" onClick={()=>{onUpdate(selected.id,{status:'Closed'});setSelected(undefined);onToast('Ticket closed; satisfaction rating recorded')}}>Close & rate</button>}</div></div></Modal>}</>
}
