import { Award, BookOpen, Download, PlayCircle } from 'lucide-react'
import { useMemo, useState } from 'react'
import type { Certification, LearningItem } from '../types'
import { DataTable, FilterSelect, Filters, Panel, Progress, StatusBadge, PageHeader } from '../components/FranchiseeUI'

export function TrainingPage({learning,certifications,onPass,onToast}:{learning:LearningItem[];certifications:Certification[];onPass:(productId:string)=>void;onToast:(s:string)=>void}){
 const [search,setSearch]=useState(''),[type,setType]=useState('All types'),[tab,setTab]=useState('library')
 const rows=useMemo(()=>learning.filter(i=>(type==='All types'||i.type===type)&&`${i.title} ${i.product}`.toLowerCase().includes(search.toLowerCase())),[learning,type,search])
 return <><PageHeader eyebrow="ENABLEMENT" title="Troth Academy" description="Self-service learning plus product assessments that control certification-dependent mappings."/>
 <div className="tf-tabs tf-page-tabs"><button className={tab==='library'?'active':''} onClick={()=>setTab('library')}>Learning Library</button><button className={tab==='certification'?'active':''} onClick={()=>setTab('certification')}>Certification / Assessment</button></div>
 {tab==='library'?<Panel title="Learning Library" subtitle="Videos, SOPs, scripts, process guides, and FAQs"><Filters search={search} onSearch={setSearch}><FilterSelect label="Content type" value={type} onChange={setType} options={['All types','Video','SOP','Process guide','Sales script']}/></Filters><div className="tf-learning-grid">{rows.map(item=><article key={item.id}><span><BookOpen/></span><div><small>{item.product} · {item.type}</small><h3>{item.title}</h3><p>{item.duration} · <StatusBadge>{item.completed?'Completed':'Not started'}</StatusBadge></p></div><button className="tf-primary" onClick={()=>onToast(`${item.completed?'Resource':'Learning session'} opened`)}>{item.type==='Video'?<PlayCircle/>:<Download/>}{item.completed?'Review':'Start'}</button></article>)}</div></Panel>:<Panel title="Certification / Assessment" subtitle="Passing a required assessment updates Product Mapping automatically"><DataTable headers={['Product','Requirement','Assessment status','Score','Mapping impact','']}><>{certifications.map(cert=><tr key={cert.productId}><td><b>{cert.product}</b></td><td>{cert.required?'Required to sell':'Optional'}</td><td><StatusBadge>{cert.status}</StatusBadge></td><td>{cert.score?<><b>{cert.score}%</b><Progress value={cert.score}/></>:'—'}</td><td>{cert.status==='Passed'?'Product eligible for active mapping':'Mapping remains restricted until pass'}</td><td>{cert.status==='Passed'?<button className="tf-text-btn" onClick={()=>onToast(`${cert.product} certificate prepared for download`)}><Download/> Certificate</button>:<button className="tf-primary" onClick={()=>onPass(cert.productId)}><Award/> {cert.status==='In progress'?'Continue':'Start'} assessment</button>}</td></tr>)}</></DataTable></Panel>}</>
}
